UPDATE PROD_DNA_LOAD.META_RAW.PROCESS SET IS_ACTIVE='FALSE' WHERE PROCESS_ID =3037;


create or replace table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW_BKP_NOV AS (SELECT * FROM PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW);

TRUNCATE TABLE PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW;

INSERT INTO PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW
(select * from PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW_BKP_NOV
union all
select * from PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW_BKP_121024);

