create or replace TABLE PROD_DNA_CORE.PCFWKS_INTEGRATION.WKS_NATIONAL_ECOMM_DATA (
	PFC VARCHAR(20),
	SKUNAME VARCHAR(100),
	NEC1_DESC VARCHAR(100),
	NEC2_DESC VARCHAR(100),
	NEC3_DESC VARCHAR(100),
	BRAND VARCHAR(50),
	OWNER VARCHAR(50),
	MANUFACTURER VARCHAR(50),
	CATEGORY VARCHAR(50),
	MAT_YEAR VARCHAR(10),
	PERIODID VARCHAR(10),
	SALES_ONLINE VARCHAR(10),
	UNIT_ONLINE VARCHAR(10),
	WEEK_END VARCHAR(20),
	FILE_NAME VARCHAR(50)
);
