UPDATE META_RAW.HISTORICAL_OBJ_METADATA SET ISACTIVE = FALSE;
 
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (552,'RG_EDW','EDW_PERFECT_STORE_REBASE_WT','PROD_DNA_CORE','ASPEDW_INTEGRATION','EDW_PERFECT_STORE_REBASE_WT','UTILITY_RAW',TRUE,'Regional','FULL_REFRESH',8);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (553,'RG_EDW','EDW_RPT_REGIONAL_SELLOUT_OFFTAKE','PROD_DNA_CORE','ASPEDW_INTEGRATION','EDW_RPT_REGIONAL_SELLOUT_OFFTAKE','UTILITY_RAW',TRUE,'Regional','FULL_REFRESH',8);
