create or replace TABLE PROD_DNA_LOAD.PRPCFSDL_RAW.SDL_PERENSO_OVER_AND_ABOVE (
	OVER_AND_ABOVE_KEY NUMBER(10,0),
	ACCT_KEY NUMBER(10,0),
	TODO_OPTION_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	ACTIVATED VARCHAR(10),
	NOTES VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
