update meta_raw.process
set USECASE_ID = 72
where process_id = 178;

INSERT INTO meta_raw.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (5317,415,'j_pac_sls_evol_refresh_group','container','pac',FALSE,TRUE);
INSERT INTO meta_raw.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (5318,415,'j_pac_sls_evol_refresh_group','contentUrl','ADB',FALSE,TRUE);
INSERT INTO meta_raw.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (5319,415,'j_pac_sls_evol_refresh_group','refreshType','datasource',FALSE,TRUE);
INSERT INTO meta_raw.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (5320,415,'j_pac_sls_evol_refresh_group','tableauSourceName','Pacific Sales Evolution TDE',FALSE,TRUE);
INSERT INTO meta_raw.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (5321,415,'j_pac_sls_evol_refresh_group','waitTime','30',FALSE,TRUE);

update meta_raw.process
set is_active = TRUE
where PROCESS_ID = 517;
