COPY INTO PCFSDL_RAW.SDL_NATIONAL_ECOMM_DATA FROM '@META_RAW.PROD_CORE_STAGE_S3/AU_SDL_SDL_NATIONAL_ECOMM_DATA/' FILE_FORMAT = 'META_RAW.PROD_CORE_CSV_FILEFORMAT' ;

COPY INTO PCFSDL_RAW.SDL_CHW_ECOMM_DATA FROM '@META_RAW.PROD_CORE_STAGE_S3/AU_SDL_SDL_CHW_ECOMM_DATA/' FILE_FORMAT = 'META_RAW.PROD_CORE_CSV_FILEFORMAT' ;
