-- update META_RAW.HISTORICAL_OBJ_METADATA
-- set ISACTIVE = TRUE
--WHERE ID IN (552,553);

-- update meta_raw.process
-- set SNOWFLAKE_STAGE = 'THASDL_RAW.PROD_LOAD_STAGE_ADLS'
-- where PROCESS_ID in (171,172,173,174,177);

create or replace TABLE VNMSDL_RAW.SDL_VN_DMS_DATA_EXTRACT_SUMMARY (
	SOURCE_FILE_NAME VARCHAR(256),
	DATE_OF_EXTRACTION TIMESTAMP_NTZ(9),
	RECORD_COUNT NUMBER(18,0)
);

create or replace TABLE VNMSDL_RAW.SDL_VN_MT_SELLIN_DKSH_HISTORY (
	SUPPLIER_CODE VARCHAR(10),
	SUPPLIER_NAME VARCHAR(100),
	PLANT VARCHAR(10),
	PRODUCTID VARCHAR(20),
	PRODUCT VARCHAR(255),
	BRAND VARCHAR(100),
	SELLIN_CATEGORY VARCHAR(100),
	PRODUCT_GROUP VARCHAR(100),
	PRODUCT_SUB_GROUP VARCHAR(100),
	UNIT_OF_MEASUREMENT VARCHAR(10),
	CUSTCODE VARCHAR(20),
	CUSTOMER VARCHAR(100),
	ADDRESS VARCHAR(100),
	DISTRICT VARCHAR(100),
	PROVINCE VARCHAR(50),
	REGION VARCHAR(20),
	ZONE VARCHAR(20),
	CHANNEL VARCHAR(10),
	SELLIN_SUB_CHANNEL VARCHAR(50),
	CUST_GROUP VARCHAR(50),
	BILLING_NO VARCHAR(20),
	INVOICE_DATE VARCHAR(20),
	QTY_INCLUDE_FOC NUMBER(18,0),
	QTY_EXCLUDE_FOC NUMBER(18,0),
	FOC VARCHAR(100),
	NET_PRICE_WO_VAT NUMBER(20,5),
	TAX NUMBER(20,5),
	NET_AMOUNT_WO_VAT NUMBER(20,5),
	NET_AMOUNT_W_VAT NUMBER(20,5),
	GROSS_AMOUNT_WO_VAT NUMBER(20,5),
	GROSS_AMOUNT_W_VAT NUMBER(20,5),
	LIST_PRICE_WO_VAT NUMBER(20,5),
	VENDOR_LOT VARCHAR(100),
	ORDER_TYPE VARCHAR(20),
	RED_INVOICE_NO VARCHAR(20),
	EXPIRY_DATE VARCHAR(20),
	ORDER_NO VARCHAR(20),
	ORDER_DATE VARCHAR(20),
	PERIOD VARCHAR(20),
	SELLOUT_SUB_CHANNEL VARCHAR(50),
	GROUP_ACCOUNT VARCHAR(50),
	ACCOUNT VARCHAR(50),
	NAME_ST_OR_DDP VARCHAR(100),
	ZONE_OR_AREA VARCHAR(20),
	FRANCHISE VARCHAR(50),
	SELLOUT_CATEGORY VARCHAR(50),
	SUB_CAT VARCHAR(50),
	SUB_BRAND VARCHAR(50),
	BARCODE VARCHAR(20),
	BASE_OR_BUNDLE VARCHAR(20),
	SIZE VARCHAR(20),
	KEY_CHAIN VARCHAR(20),
	STATUS VARCHAR(20),
	PPG VARCHAR(20),
	SUB_CAT_MONTHLY_SALES VARCHAR(20),
	SALES_SUP VARCHAR(255),
	SP VARCHAR(255),
	FILENAME VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);



