-- update META_RAW.HISTORICAL_OBJ_METADATA
-- set ISACTIVE = TRUE
--WHERE ID IN (552,553);

update meta_raw.process
set SNOWFLAKE_STAGE = 'THASDL_RAW.PROD_LOAD_STAGE_ADLS'
where PROCESS_ID in (171,172,173,174,177)



