UPDATE PROD_DNA_LOAD.META_RAW.PROCESS
SET USECASE_ID = 174
WHERE PARAMETER_GROUP_ID IN (415,
416,
491,
492,
494,
495);


use schema meta_raw;
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (173,'TWSI_Target_Ingestion','TWSI_Target_Ingestion','TWSI_Target_Ingestion_desc','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (3,'J_REG_COPA_CIW_RPT_REFRESH','REGIONAL_COPA','rg sellin copa ciw refresh description','TRUE',3);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (6,'J_RG_SELL_IN_COPA_TAB_REFRESH','REGIONAL_COPA','j_rg_sell_in_copa_tab_refresh description','TRUE',2);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (29,'SAP_BW_COPA10','REGIONAL_COPA','SAP BW Opehub Copa10 tables Load','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (37,'j_reg_copa_sku_rpt_refresh_group','REGIONAL_COPA','REGIONAL REFRESH_Adhoc ','TRUE',4);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (32,'SAP_BW_INVOICE','PCF_BW_INVOICE','SAP BW Opehub Invoice tables Load','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (174,'PCF_REFRESH','PCF_BW_INVOICE','SAP BW Opehub Invoice tables Load','TRUE',2);
