---------------------CORE-----------------------------------
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_PS_TARGETS CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_PS_TARGETS;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_PS_WEIGHTS CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_PS_WEIGHTS;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_CUSTOMER_HIERARCHY CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_CUSTOMER_HIERARCHY;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_PRODUCT_HIERARCHY CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_PRODUCT_HIERARCHY;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_PRODUCT_MAPPING CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_PRODUCT_MAPPING;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_MDS_SG_STORE_MASTER CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_MDS_SG_STORE_MASTER;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_SG_TP_CLOSED_YEAR_BAL CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_SG_TP_CLOSED_YEAR_BAL;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_SG_CONSTANT_KEY_VALUE CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_SG_CONSTANT_KEY_VALUE;
CREATE TABLE IF NOT EXISTS PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_SG_POS_SALES_FACT CLONE PROD_DNA_CORE.SNAPOSEITG_INTEGRATION.ITG_SG_POS_SALES_FACT;

create or replace TABLE MYSITG_INTEGRATION.ITG_MY_SELLOUT_STOCK_FACT (
	CUST_ID VARCHAR(50),
	INV_DT DATE,
	DSTRBTR_WH_ID VARCHAR(50),
	ITEM_CD VARCHAR(50),
	DSTRBTR_PROD_CD VARCHAR(50),
	EAN_NUM VARCHAR(50),
	DSTRBTR_PROD_DESC VARCHAR(100),
	QTY NUMBER(20,4),
	UOM VARCHAR(20),
	QTY_ON_ORD NUMBER(20,4),
	UOM_ON_ORD VARCHAR(100),
	QTY_COMMITTED NUMBER(20,4),
	UOM_COMMITTED VARCHAR(100),
	AVAILABLE_QTY_PC NUMBER(20,4),
	QTY_ON_ORD_PC NUMBER(20,4),
	QTY_COMMITTED_PC NUMBER(20,4),
	UNIT_PRC NUMBER(20,4),
	TOTAL_VAL NUMBER(20,4),
	CUSTOM_FIELD1 VARCHAR(255),
	SAP_MATL_NUM VARCHAR(255),
	FILENAME VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

create or replace TABLE MYSITG_INTEGRATION.ITG_MY_SELLOUT_SALES_FACT (
	DSTRBTR_ID VARCHAR(50),
	SLS_ORD_NUM VARCHAR(50),
	SLS_ORD_DT DATE,
	TYPE VARCHAR(20),
	CUST_CD VARCHAR(50),
	DSTRBTR_WH_ID VARCHAR(50),
	ITEM_CD VARCHAR(50),
	DSTRBTR_PROD_CD VARCHAR(50),
	EAN_NUM VARCHAR(50),
	DSTRBTR_PROD_DESC VARCHAR(100),
	GRS_PRC NUMBER(20,4),
	QTY NUMBER(20,4),
	UOM VARCHAR(20),
	QTY_PC NUMBER(20,4),
	QTY_AFT_CONV NUMBER(20,4),
	SUBTOTAL_1 NUMBER(20,4),
	DISCOUNT NUMBER(20,4),
	SUBTOTAL_2 NUMBER(20,4),
	BOTTOM_LINE_DSCNT NUMBER(20,4),
	TOTAL_AMT_AFT_TAX NUMBER(20,4),
	TOTAL_AMT_BFR_TAX NUMBER(20,4),
	SLS_EMP VARCHAR(100),
	CUSTOM_FIELD1 VARCHAR(255),
	CUSTOM_FIELD2 VARCHAR(255),
	SAP_MATL_NUM VARCHAR(255),
	FILENAME VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

create or replace TABLE MYSITG_INTEGRATION.ITG_MY_SELLOUT_SALES_FACT (
	DSTRBTR_ID VARCHAR(50),
	SLS_ORD_NUM VARCHAR(50),
	SLS_ORD_DT DATE,
	TYPE VARCHAR(20),
	CUST_CD VARCHAR(50),
	DSTRBTR_WH_ID VARCHAR(50),
	ITEM_CD VARCHAR(50),
	DSTRBTR_PROD_CD VARCHAR(50),
	EAN_NUM VARCHAR(50),
	DSTRBTR_PROD_DESC VARCHAR(100),
	GRS_PRC NUMBER(20,4),
	QTY NUMBER(20,4),
	UOM VARCHAR(20),
	QTY_PC NUMBER(20,4),
	QTY_AFT_CONV NUMBER(20,4),
	SUBTOTAL_1 NUMBER(20,4),
	DISCOUNT NUMBER(20,4),
	SUBTOTAL_2 NUMBER(20,4),
	BOTTOM_LINE_DSCNT NUMBER(20,4),
	TOTAL_AMT_AFT_TAX NUMBER(20,4),
	TOTAL_AMT_BFR_TAX NUMBER(20,4),
	SLS_EMP VARCHAR(100),
	CUSTOM_FIELD1 VARCHAR(255),
	CUSTOM_FIELD2 VARCHAR(255),
	SAP_MATL_NUM VARCHAR(255),
	FILENAME VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

create or replace TABLE MYSWKS_INTEGRATION.WKS_MY_SELLOUT_STOCK_FACT (
	CUST_ID VARCHAR(255),
	INV_DT VARCHAR(255),
	DSTRBTR_WH_ID VARCHAR(255),
	ITEM_CD VARCHAR(255),
	DSTRBTR_PROD_CD VARCHAR(255),
	EAN_NUM VARCHAR(255),
	DSTRBTR_PROD_DESC VARCHAR(255),
	QTY VARCHAR(255),
	UOM VARCHAR(255),
	QTY_ON_ORD VARCHAR(255),
	UOM_ON_ORD VARCHAR(255),
	QTY_COMMITTED VARCHAR(255),
	UOM_COMMITTED VARCHAR(255),
	AVAILABLE_QTY_PC VARCHAR(255),
	QTY_ON_ORD_PC VARCHAR(255),
	QTY_COMMITTED_PC VARCHAR(255),
	UNIT_PRC VARCHAR(255),
	TOTAL_VAL VARCHAR(255),
	CUSTOM_FIELD1 VARCHAR(255),
	CUSTOM_FIELD2 VARCHAR(255),
	FILENAME VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9)
);
