truncate table ASPEDW_INTEGRATION.EDW_COPA_TRANS_FACT;COPY INTO ASPEDW_INTEGRATION.EDW_COPA_TRANS_FACT FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/RG_EDW_EDW_COPA_TRANS_FACT/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT' ;

truncate table ASPITG_INTEGRATION.ITG_SAP_BILLING_CONDITION;COPY INTO ASPITG_INTEGRATION.ITG_SAP_BILLING_CONDITION FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/RG_ITG_ITG_SAP_BILLING_CONDITION/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';

truncate table ASPITG_INTEGRATION.SDL_RAW_SAP_BILLING_CONDITION;COPY INTO ASPITG_INTEGRATION.SDL_RAW_SAP_BILLING_CONDITION FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/RG_SDL_ITG_SAP_BILLING_CONDITION/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';

truncate table ASPITG_INTEGRATION.ITG_COPA_TRANS;COPY INTO ASPITG_INTEGRATION.ITG_COPA_TRANS FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/RG_ITG_ITG_COPA_TRANS/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';
