create or replace view PROD_DNA_CORE.IDNEDW_ACCESS.EDW_INDONESIA_LPPB_ANALYSIS(
	"jj_year",
	"jj_qrtr",
	"jj_mnth_id",
	"jj_mnth",
	"jj_mnth_desc",
	"jj_mnth_no",
	"dstrbtr_grp_cd",
	"dstrbtr_grp_nm",
	"jj_sap_dstrbtr_id",
	"jj_sap_dstrbtr_nm",
	"dstrbtr_cd_nm",
	"area",
	"region",
	"bdm_nm",
	"rbm_nm",
	"dstrbtr_status",
	"jj_sap_prod_id",
	"jj_sap_prod_desc",
	"jj_sap_upgrd_prod_id",
	"jj_sap_upgrd_prod_desc",
	"jj_sap_cd_mp_prod_id",
	"jj_sap_cd_mp_prod_desc",
	"sap_prod_code_name",
	"franchise",
	"brand",
	"sku_grp_or_variant",
	"sku_grp1_or_variant1",
	"sku_grp2_or_variant2",
	"sku_grp3_or_variant3",
	"prod_status",
	"strt_inv_qty",
	"sellin_qty",
	"sellout_qty",
	"end_inv_qty",
	"strt_inv_val",
	"gross_strt_inv_val",
	"sellin_val",
	"gross_sellin_val",
	"sellout_val",
	"gross_sellout_val",
	"end_inv_val",
	"gross_end_inv_val",
	"sellout_last_two_mnths_qty",
	"sellout_last_two_mnths_val",
	"gross_sellout_last_two_mnths_val",
	"stock_on_hand_qty",
	"stock_on_hand_val",
	"variant",
	"jj_mnth_long",
	"bp_qtn",
	"bp_val",
	"s_op_qtn",
	"s_op_val",
	"trgt_hna",
	"trgt_niv",
	"trgt_bp_s_op_flag",
	"trgt_dist_brnd_chnl_flag",
	"saleable_stock_qty",
	"saleable_stock_value",
	"non_saleable_stock_qty",
	"non_saleable_stock_value",
	"intransit_qty",
	"intransit_hna",
	"intransit_niv",
	"stock_on_hand_niv",
	"p3m_sellout_val",
	"p3m_gross_sellout_val",
	"p6m_sellout_val",
	"p6m_gross_sellout_val"
) as
select jj_year as "jj_year",
    jj_qrtr as "jj_qrtr",
    jj_mnth_id as "jj_mnth_id",
    jj_mnth as "jj_mnth",
    jj_mnth_desc as "jj_mnth_desc",
    jj_mnth_no as "jj_mnth_no",
    dstrbtr_grp_cd as "dstrbtr_grp_cd",
    dstrbtr_grp_nm as "dstrbtr_grp_nm",
    jj_sap_dstrbtr_id as "jj_sap_dstrbtr_id",
    jj_sap_dstrbtr_nm as "jj_sap_dstrbtr_nm",
    dstrbtr_cd_nm as "dstrbtr_cd_nm",
    area as "area",
    region as "region",
    bdm_nm as "bdm_nm",
    rbm_nm as "rbm_nm",
    dstrbtr_status as "dstrbtr_status",
    jj_sap_prod_id as "jj_sap_prod_id",
    jj_sap_prod_desc as "jj_sap_prod_desc",
    jj_sap_upgrd_prod_id as "jj_sap_upgrd_prod_id",
    jj_sap_upgrd_prod_desc as "jj_sap_upgrd_prod_desc",
    jj_sap_cd_mp_prod_id as "jj_sap_cd_mp_prod_id",
    jj_sap_cd_mp_prod_desc as "jj_sap_cd_mp_prod_desc",
    sap_prod_code_name as "sap_prod_code_name",
    franchise as "franchise",
    brand as "brand",
    sku_grp_or_variant as "sku_grp_or_variant",
    sku_grp1_or_variant1 as "sku_grp1_or_variant1",
    sku_grp2_or_variant2 as "sku_grp2_or_variant2",
    sku_grp3_or_variant3 as "sku_grp3_or_variant3",
    prod_status as "prod_status",
    strt_inv_qty as "strt_inv_qty",
    sellin_qty as "sellin_qty",
    sellout_qty as "sellout_qty",
    end_inv_qty as "end_inv_qty",
    strt_inv_val as "strt_inv_val",
    gross_strt_inv_val as "gross_strt_inv_val",
    sellin_val as "sellin_val",
    gross_sellin_val as "gross_sellin_val",
    sellout_val as "sellout_val",
    gross_sellout_val as "gross_sellout_val",
    end_inv_val as "end_inv_val",
    gross_end_inv_val as "gross_end_inv_val",
    sellout_last_two_mnths_qty as "sellout_last_two_mnths_qty",
    sellout_last_two_mnths_val as "sellout_last_two_mnths_val",
    gross_sellout_last_two_mnths_val as "gross_sellout_last_two_mnths_val",
    stock_on_hand_qty as "stock_on_hand_qty",
    stock_on_hand_val as "stock_on_hand_val",
    variant as "variant",
    jj_mnth_long as "jj_mnth_long",
    bp_qtn as "bp_qtn",
    bp_val as "bp_val",
    s_op_qtn as "s_op_qtn",
    s_op_val as "s_op_val",
    trgt_hna as "trgt_hna",
    trgt_niv as "trgt_niv",
    trgt_bp_s_op_flag as "trgt_bp_s_op_flag",
    trgt_dist_brnd_chnl_flag as "trgt_dist_brnd_chnl_flag",
    saleable_stock_qty as "saleable_stock_qty",
    saleable_stock_value as "saleable_stock_value",
    non_saleable_stock_qty as "non_saleable_stock_qty",
    non_saleable_stock_value as "non_saleable_stock_value",
    intransit_qty as "intransit_qty",
    intransit_hna as "intransit_hna",
    intransit_niv as "intransit_niv",
    stock_on_hand_niv as "stock_on_hand_niv",
    p3m_sellout_val as "p3m_sellout_val",
    p3m_gross_sellout_val as "p3m_gross_sellout_val",
    p6m_sellout_val as "p6m_sellout_val",
    p6m_gross_sellout_val as "p6m_gross_sellout_val"
from PROD_DNA_CORE.idnedw_integration.edw_indonesia_lppb_analysis;

create or replace view PROD_DNA_CORE.IDNEDW_ACCESS.EDW_INDONESIA_NOO_ANALYSIS(
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_wk_no",
	"jj_mnth_no",
	"bill_doc",
	"bill_dt",
	"dstrbtr_grp_cd",
	"dstrbtr_grp_nm",
	"jj_sap_dstrbtr_id",
	"jj_sap_dstrbtr_nm",
	"dstrbtr_cd_nm",
	"area",
	"region",
	"bdm_nm",
	"rbm_nm",
	"dstrbtr_status",
	"cust_id_map",
	"cust_nm_map",
	"dstrbtr_cust_cd_nm",
	"cust_grp",
	"chnl",
	"outlet_type",
	"chnl_grp",
	"jjid",
	"chnl_grp2",
	"city",
	"cust_status",
	"jj_sap_prod_id",
	"jj_sap_prod_desc",
	"jj_sap_upgrd_prod_id",
	"jj_sap_upgrd_prod_desc",
	"jj_sap_cd_mp_prod_id",
	"jj_sap_cd_mp_prod_desc",
	"sap_prod_code_name",
	"franchise",
	"brand",
	"variant1",
	"variant2",
	"variant",
	"put_up",
	"prod_status",
	"slsmn_id",
	"slsmn_nm",
	"sls_qty",
	"hna",
	"niv",
	"trd_dscnt",
	"dstrbtr_niv",
	"rtrn_qty",
	"rtrn_val",
	"hsku_target_growth",
	"hsku_target_coverage",
	"jj_mnth_long",
	"trgt_hna",
	"trgt_niv",
	"npi_flag",
	"benchmark_sku_code",
	"sku_benchmark",
	"hero_sku_flag",
	"trgt_dist_brnd_chnl_flag",
	"tiering",
	"count_sku_code",
	"mcs_status",
	"local_variant",
	"count_local_variant",
	"salesman_key",
	"sfa_id",
	"latest_chnl",
	"latest_outlet_type",
	"latest_chnl_grp",
	"latest_cust_grp2",
	"latest_cust_grp",
	"latest_cust_nm_map",
	"latest_region",
	"latest_area",
	"latest_rbm",
	"latest_area_pic",
	"latest_jjid",
	"latest_put_up",
	"latest_franchise",
	"latest_brand",
	"latest_msl",
	"latest_count_local_variant",
	"latest_chnl_grp2",
	"latest_distributor_group",
	"latest_dstrbtr_grp_cd"
) as
select 
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_wk_no as "jj_mnth_wk_no",
	jj_mnth_no as "jj_mnth_no",
	bill_doc as "bill_doc",
	bill_dt as "bill_dt",
	dstrbtr_grp_cd as "dstrbtr_grp_cd",
	dstrbtr_grp_nm as "dstrbtr_grp_nm",
	jj_sap_dstrbtr_id as "jj_sap_dstrbtr_id",
	jj_sap_dstrbtr_nm as "jj_sap_dstrbtr_nm",
	dstrbtr_cd_nm as "dstrbtr_cd_nm",
	area as "area",
	region as "region",
	bdm_nm as "bdm_nm",
	rbm_nm as "rbm_nm",
	dstrbtr_status as "dstrbtr_status",
	cust_id_map as "cust_id_map",
	cust_nm_map as "cust_nm_map",
	dstrbtr_cust_cd_nm as "dstrbtr_cust_cd_nm",
	cust_grp as "cust_grp",
	chnl as "chnl",
	outlet_type as "outlet_type",
	chnl_grp as "chnl_grp",
	jjid as "jjid",
	chnl_grp2 as "chnl_grp2",
	city as "city",
	cust_status as "cust_status",
	jj_sap_prod_id as "jj_sap_prod_id",
	jj_sap_prod_desc as "jj_sap_prod_desc",
	jj_sap_upgrd_prod_id as "jj_sap_upgrd_prod_id",
	jj_sap_upgrd_prod_desc as "jj_sap_upgrd_prod_desc",
	jj_sap_cd_mp_prod_id as "jj_sap_cd_mp_prod_id",
	jj_sap_cd_mp_prod_desc as "jj_sap_cd_mp_prod_desc",
	sap_prod_code_name as "sap_prod_code_name",
	franchise as "franchise",
	brand as "brand",
	variant1 as "variant1",
	variant2 as "variant2",
	variant as "variant",
	put_up as "put_up",
	prod_status as "prod_status",
	slsmn_id as "slsmn_id",
	slsmn_nm as "slsmn_nm",
	sls_qty as "sls_qty",
	hna as "hna",
	niv as "niv",
	trd_dscnt as "trd_dscnt",
	dstrbtr_niv as "dstrbtr_niv",
	rtrn_qty as "rtrn_qty",
	rtrn_val as "rtrn_val",
	hsku_target_growth as "hsku_target_growth",
	hsku_target_coverage as "hsku_target_coverage",
	jj_mnth_long as "jj_mnth_long",
	trgt_hna as "trgt_hna",
	trgt_niv as "trgt_niv",
	npi_flag as "npi_flag",
	benchmark_sku_code as "benchmark_sku_code",
	sku_benchmark as "sku_benchmark",
	hero_sku_flag as "hero_sku_flag",
	trgt_dist_brnd_chnl_flag as "trgt_dist_brnd_chnl_flag",
	tiering as "tiering",
	count_sku_code as "count_sku_code",
	mcs_status as "mcs_status",
	local_variant as "local_variant",
	count_local_variant as "count_local_variant",
	salesman_key as "salesman_key",
	sfa_id as "sfa_id",
	latest_chnl as "latest_chnl",
	latest_outlet_type as "latest_outlet_type",
	latest_chnl_grp as "latest_chnl_grp",
	latest_cust_grp2 as "latest_cust_grp2",
	latest_cust_grp as "latest_cust_grp",
	latest_cust_nm_map as "latest_cust_nm_map",
	latest_region as "latest_region",
	latest_area as "latest_area",
	latest_rbm as "latest_rbm",
	latest_area_pic as "latest_area_pic",
	latest_jjid as "latest_jjid",
	latest_put_up as "latest_put_up",
	latest_franchise as "latest_franchise",
	latest_brand as "latest_brand",
	latest_msl as "latest_msl",
	latest_count_local_variant as "latest_count_local_variant",
	latest_chnl_grp2 as "latest_chnl_grp2",
	latest_distributor_group as "latest_distributor_group",
	latest_dstrbtr_grp_cd as "latest_dstrbtr_grp_cd"
from PROD_DNA_CORE.idnedw_integration.edw_indonesia_noo_analysis;


create or replace view PROD_DNA_CORE.IDNEDW_ACCESS.EDW_ORDER_SELL_IN_ANALYSIS(
	"datasrc",
	"invoice_dt",
	"bill_doc",
	"jj_year",
	"jj_qrtr",
	"jj_mnth_id",
	"jj_mnth",
	"jj_mnth_desc",
	"jj_mnth_no",
	"jj_mnth_long",
	"dstrbtr_grp_cd",
	"dstrbtr_grp_nm",
	"jj_sap_dstrbtr_id",
	"jj_sap_dstrbtr_nm",
	"dstrbtr_cd_nm",
	"area",
	"region",
	"bdm_nm",
	"rbm_nm",
	"dstrbtr_status",
	"jj_sap_prod_id",
	"jj_sap_prod_desc",
	"jj_sap_upgrd_prod_id",
	"jj_sap_upgrd_prod_desc",
	"jj_sap_cd_mp_prod_id",
	"jj_sap_cd_mp_prod_desc",
	"sap_prod_code_name",
	"franchise",
	"brand",
	"sku_grp_or_variant",
	"sku_grp1_or_variant1",
	"sku_grp2_or_variant2",
	"sku_grp3_or_variant3",
	"prod_status",
	"sellin_qty",
	"sellin_val",
	"gross_sellin_val",
	"order_net",
	"order_qty",
	"order_gross",
	"nts_order_val",
	"order_dt",
	"order_doc",
	"target_niv",
	"target_hna"
) as
select 
	datasrc as "datasrc",
	invoice_dt as "invoice_dt",
	bill_doc as "bill_doc",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth as "jj_mnth",
	jj_mnth_desc as "jj_mnth_desc",
	jj_mnth_no as "jj_mnth_no",
	jj_mnth_long as "jj_mnth_long",
	dstrbtr_grp_cd as "dstrbtr_grp_cd",
	dstrbtr_grp_nm as "dstrbtr_grp_nm",
	jj_sap_dstrbtr_id as "jj_sap_dstrbtr_id",
	jj_sap_dstrbtr_nm as "jj_sap_dstrbtr_nm",
	dstrbtr_cd_nm as "dstrbtr_cd_nm",
	area as "area",
	region as "region",
	bdm_nm as "bdm_nm",
	rbm_nm as "rbm_nm",
	dstrbtr_status as "dstrbtr_status",
	jj_sap_prod_id as "jj_sap_prod_id",
	jj_sap_prod_desc as "jj_sap_prod_desc",
	jj_sap_upgrd_prod_id as "jj_sap_upgrd_prod_id",
	jj_sap_upgrd_prod_desc as "jj_sap_upgrd_prod_desc",
	jj_sap_cd_mp_prod_id as "jj_sap_cd_mp_prod_id",
	jj_sap_cd_mp_prod_desc as "jj_sap_cd_mp_prod_desc",
	sap_prod_code_name as "sap_prod_code_name",
	franchise as "franchise",
	brand as "brand",
	sku_grp_or_variant as "sku_grp_or_variant",
	sku_grp1_or_variant1 as "sku_grp1_or_variant1",
	sku_grp2_or_variant2 as "sku_grp2_or_variant2",
	sku_grp3_or_variant3 as "sku_grp3_or_variant3",
	prod_status as "prod_status",
	sellin_qty as "sellin_qty",
	sellin_val as "sellin_val",
	gross_sellin_val as "gross_sellin_val",
	order_net as "order_net",
	order_qty as "order_qty",
	order_gross as "order_gross",
	nts_order_val as "nts_order_val",
	order_dt as "order_dt",
	order_doc as "order_doc",
	target_niv as "target_niv",
	target_hna as "target_hna",
from PROD_DNA_CORE.idnedw_integration.edw_order_sell_in_analysis;

create or replace view PROD_DNA_CORE.IDNEDW_ACCESS.EDW_RPT_ID_SELLIN_ANALYSIS(
	"bill_dt",
	"bill_doc",
	"jj_year",
	"jj_qrtr",
	"jj_mnth_id",
	"jj_mnth",
	"jj_mnth_desc",
	"jj_mnth_no",
	"jj_mnth_long",
	"dstrbtr_grp_cd",
	"dstrbtr_grp_nm",
	"jj_sap_dstrbtr_id",
	"jj_sap_dstrbtr_nm",
	"dstrbtr_cd_nm",
	"area",
	"region",
	"bdm_nm",
	"rbm_nm",
	"dstrbtr_status",
	"jj_sap_prod_id",
	"jj_sap_prod_desc",
	"jj_sap_upgrd_prod_id",
	"jj_sap_upgrd_prod_desc",
	"jj_sap_cd_mp_prod_id",
	"jj_sap_cd_mp_prod_desc",
	"sap_prod_code_name",
	"franchise",
	"brand",
	"sku_grp_or_variant",
	"sku_grp1_or_variant1",
	"sku_grp2_or_variant2",
	"sku_grp3_or_variant3",
	"prod_status",
	"sellin_qty",
	"sellin_val",
	"gross_sellin_val"
) as
select 
	bill_dt as "bill_dt",
	bill_doc as "bill_doc",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth as "jj_mnth",
	jj_mnth_desc as "jj_mnth_desc",
	jj_mnth_no as "jj_mnth_no",
	jj_mnth_long as "jj_mnth_long",
	dstrbtr_grp_cd as "dstrbtr_grp_cd",
	dstrbtr_grp_nm as "dstrbtr_grp_nm",
	jj_sap_dstrbtr_id as "jj_sap_dstrbtr_id",
	jj_sap_dstrbtr_nm as "jj_sap_dstrbtr_nm",
	dstrbtr_cd_nm as "dstrbtr_cd_nm",
	area as "area",
	region as "region",
	bdm_nm as "bdm_nm",
	rbm_nm as "rbm_nm",
	dstrbtr_status as "dstrbtr_status",
	jj_sap_prod_id as "jj_sap_prod_id",
	jj_sap_prod_desc as "jj_sap_prod_desc",
	jj_sap_upgrd_prod_id as "jj_sap_upgrd_prod_id",
	jj_sap_upgrd_prod_desc as "jj_sap_upgrd_prod_desc",
	jj_sap_cd_mp_prod_id as "jj_sap_cd_mp_prod_id",
	jj_sap_cd_mp_prod_desc as "jj_sap_cd_mp_prod_desc",
	sap_prod_code_name as "sap_prod_code_name",
	franchise as "franchise",
	brand as "brand",
	sku_grp_or_variant as "sku_grp_or_variant",
	sku_grp1_or_variant1 as "sku_grp1_or_variant1",
	sku_grp2_or_variant2 as "sku_grp2_or_variant2",
	sku_grp3_or_variant3 as "sku_grp3_or_variant3",
	prod_status as "prod_status",
	sellin_qty as "sellin_qty",
	sellin_val as "sellin_val",
	gross_sellin_val as "gross_sellin_val"
from PROD_DNA_CORE.idnedw_integration.edw_rpt_id_sellin_analysis;
