create or replace TABLE PHLITG_INTEGRATION.ITG_PH_711_PRODUCT_DIM (
	YEARMONTH VARCHAR(100),
	CUST_CD VARCHAR(100),
	ITEM_CD VARCHAR(100),
	ITEM_NM VARCHAR(255),
	SAP_ITEM_CD VARCHAR(100),
	SAP_ITEM_NM VARCHAR(255),
	CUST_CONV_FACTOR NUMBER(20,4),
	LST_PERIOD VARCHAR(100),
	EARLY_BK_PERIOD VARCHAR(100),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

create or replace TABLE PHLITG_INTEGRATION.ITG_PH_PRICELIST (
	JJ_MNTH_ID VARCHAR(10),
	ITEM_CD VARCHAR(20),
	ITEM_DESC VARCHAR(80),
	CONSUMER_BAR_CD VARCHAR(20),
	SHIPPERS_BAR_CD VARCHAR(20),
	DZ_PER_CASE NUMBER(15,4),
	LST_PRICE_CASE NUMBER(15,4),
	LST_PRICE_DZ NUMBER(15,4),
	LST_PRICE_UNIT NUMBER(15,4),
	SRP NUMBER(15,4),
	STATUS VARCHAR(15),
	SAP_ITEM_DESC VARCHAR(50),
	BRND_VRNT VARCHAR(100),
	FRNCHSE_CD VARCHAR(50),
	CDL_DTTM VARCHAR(20),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

create or replace TABLE PHLITG_INTEGRATION.ITG_PH_POS_PRODUCT_DIM (
	CUST_CD VARCHAR(255),
	ITEM_CD VARCHAR(255),
	ITEM_NM VARCHAR(255),
	SAP_ITEM_CD VARCHAR(255),
	CUST_SKU_GRP VARCHAR(255),
	CUST_CONV_FACTOR NUMBER(20,4),
	JNJ_PC_PER_CUST_UNIT NUMBER(20,4),
	CUST_ITEM_PRC NUMBER(20,4),
	LST_PERIOD VARCHAR(255),
	EARLY_BK_PERIOD VARCHAR(255),
	BARCODE VARCHAR(255),
	JNJ_MATL_SHIPPER_BARCODE VARCHAR(255),
	JNJ_MATL_CONSUMER_BARCODE VARCHAR(255),
	JNJ_MATL_CSE_BARCODE VARCHAR(255),
	JNJ_MATL_PC_BARCODE VARCHAR(255),
	UOM VARCHAR(255),
	JNJ_PC_PER_CSE NUMBER(20,4),
	CDL_DTTM VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);
