use schema NTAEDW_ACCESS;
create or replace view EDW_HK_SELLIN_BP_LE(
	"subsource_type",
	"fisc_yr_per",
	"mega_brnd_desc",
	"brnd_desc",
	"go to model",
	"banner format",
	"sub channel",
	"parent customer",
	"usd_rt",
	"lcl_rt",
	"tp_acc_start",
	"tp_perc",
	"time_gone",
	"preww7_act",
	"nts_act",
	"tp_act",
	"tp_act_calc",
	"nts_bp",
	"tp_bp",
	"nts_le",
	"tp_le"
) as
select subsource_type as "subsource_type",
    fisc_yr_per as "fisc_yr_per",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_desc as "brnd_desc",
    "go to model",
    "banner format",
    "sub channel",
    "parent customer",
    usd_rt as "usd_rt",
    lcl_rt as "lcl_rt",
    tp_acc_start as "tp_acc_start",
    tp_perc as "tp_perc",
    time_gone as "time_gone",
    preww7_act as "preww7_act",
    nts_act as "nts_act",
    tp_act as "tp_act",
    tp_act_calc as "tp_act_calc",
    nts_bp as "nts_bp",
    tp_bp as "tp_bp",
    nts_le as "nts_le",
    tp_le as "tp_le"
from ntaedw_integration.edw_hk_sellin_bp_le;
create or replace view EDW_IMS_FACT(
	"ims_txn_dt",
	"dstr_cd",
	"dstr_nm",
	"cust_cd",
	"cust_nm",
	"prod_cd",
	"prod_nm",
	"rpt_per_strt_dt",
	"rpt_per_end_dt",
	"ean_num",
	"uom",
	"unit_prc",
	"sls_amt",
	"sls_qty",
	"rtrn_qty",
	"rtrn_amt",
	"ship_cust_nm",
	"cust_cls_grp",
	"cust_sub_cls",
	"prod_spec",
	"itm_agn_nm",
	"ordr_co",
	"rtrn_rsn",
	"sls_ofc_cd",
	"sls_grp_cd",
	"sls_ofc_nm",
	"sls_grp_nm",
	"acc_type",
	"co_cd",
	"sls_rep_cd",
	"sls_rep_nm",
	"doc_dt",
	"doc_num",
	"invc_num",
	"remark_desc",
	"gift_qty",
	"sls_bfr_tax_amt",
	"sku_per_box",
	"ctry_cd",
	"crncy_cd",
	"crt_dttm",
	"updt_dttm",
	"prom_sls_amt",
	"prom_rtrn_amt",
	"prom_prc_amt",
	"sap_code",
	"sku_type",
	"sub_customer_code",
	"sub_customer_name",
	"sales_priority",
	"sales_stores",
	"sales_rate"
) as
select ims_txn_dt as "ims_txn_dt",
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    cust_cd as "cust_cd",
    cust_nm as "cust_nm",
    prod_cd as "prod_cd",
    prod_nm as "prod_nm",
    rpt_per_strt_dt as "rpt_per_strt_dt",
    rpt_per_end_dt as "rpt_per_end_dt",
    ean_num as "ean_num",
    uom as "uom",
    unit_prc as "unit_prc",
    sls_amt as "sls_amt",
    sls_qty as "sls_qty",
    rtrn_qty as "rtrn_qty",
    rtrn_amt as "rtrn_amt",
    ship_cust_nm as "ship_cust_nm",
    cust_cls_grp as "cust_cls_grp",
    cust_sub_cls as "cust_sub_cls",
    prod_spec as "prod_spec",
    itm_agn_nm as "itm_agn_nm",
    ordr_co as "ordr_co",
    rtrn_rsn as "rtrn_rsn",
    sls_ofc_cd as "sls_ofc_cd",
    sls_grp_cd as "sls_grp_cd",
    sls_ofc_nm as "sls_ofc_nm",
    sls_grp_nm as "sls_grp_nm",
    acc_type as "acc_type",
    co_cd as "co_cd",
    sls_rep_cd as "sls_rep_cd",
    sls_rep_nm as "sls_rep_nm",
    doc_dt as "doc_dt",
    doc_num as "doc_num",
    invc_num as "invc_num",
    remark_desc as "remark_desc",
    gift_qty as "gift_qty",
    sls_bfr_tax_amt as "sls_bfr_tax_amt",
    sku_per_box as "sku_per_box",
    ctry_cd as "ctry_cd",
    crncy_cd as "crncy_cd",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm",
    prom_sls_amt as "prom_sls_amt",
    prom_rtrn_amt as "prom_rtrn_amt",
    prom_prc_amt as "prom_prc_amt",
    sap_code as "sap_code",
    sku_type as "sku_type",
    sub_customer_code as "sub_customer_code",
    sub_customer_name as "sub_customer_name",
    sales_priority as "sales_priority",
    sales_stores as "sales_stores",
    sales_rate as "sales_rate"
from ntaedw_integration.edw_ims_fact;
create or replace view EDW_IMS_INVENTORY_FACT(
	"invnt_dt",
	"dstr_cd",
	"dstr_nm",
	"prod_cd",
	"prod_nm",
	"ean_num",
	"cust_nm",
	"invnt_qty",
	"invnt_amt",
	"avg_prc_amt",
	"safety_stock",
	"bad_invnt_qty",
	"book_invnt_qty",
	"convs_amt",
	"prch_disc_amt",
	"end_invnt_qty",
	"batch_no",
	"uom",
	"sls_rep_cd",
	"sls_rep_nm",
	"ctry_cd",
	"crncy_cd",
	"crt_dttm",
	"updt_dttm",
	"chn_uom",
	"storage_name",
	"area"
) as
select invnt_dt as "invnt_dt",
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    prod_cd as "prod_cd",
    prod_nm as "prod_nm",
    ean_num as "ean_num",
    cust_nm as "cust_nm",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    avg_prc_amt as "avg_prc_amt",
    safety_stock as "safety_stock",
    bad_invnt_qty as "bad_invnt_qty",
    book_invnt_qty as "book_invnt_qty",
    convs_amt as "convs_amt",
    prch_disc_amt as "prch_disc_amt",
    end_invnt_qty as "end_invnt_qty",
    batch_no as "batch_no",
    uom as "uom",
    sls_rep_cd as "sls_rep_cd",
    sls_rep_nm as "sls_rep_nm",
    ctry_cd as "ctry_cd",
    crncy_cd as "crncy_cd",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm",
    chn_uom as "chn_uom",
    storage_name as "storage_name",
    area as "area"
from ntaedw_integration.edw_ims_inventory_fact;
create or replace view EDW_KR_DADS_ANALYSIS(
	"brand",
	"keyword",
	"search_area",
	"ad_types",
	"retailer",
	"sub_retailer",
	"product_name",
	"barcode",
	"keyword_group",
	"fisc_wk_num",
	"fisc_mnth",
	"fisc_per",
	"fisc_day",
	"category_1",
	"category_2",
	"category_3",
	"ranking",
	"click",
	"impression",
	"ad_cost",
	"total_order",
	"total_order_sku",
	"total_conversion_sales",
	"total_conversion_sales_sku",
	"sales_gmv",
	"sales_gmv_sku",
	"pa_cost",
	"bpa_cost",
	"sa_cost",
	"observed_price",
	"rocket_wow_price",
	"total_monthly_search_volume",
	"payment_amount"
) as
select brand as "brand",
    keyword as "keyword",
    search_area as "search_area",
    ad_types as "ad_types",
    retailer as "retailer",
    sub_retailer as "sub_retailer",
    product_name as "product_name",
    barcode as "barcode",
    keyword_group as "keyword_group",
    fisc_wk_num as "fisc_wk_num",
    fisc_mnth as "fisc_mnth",
    fisc_per as "fisc_per",
    fisc_day as "fisc_day",
    category_1 as "category_1",
    category_2 as "category_2",
    category_3 as "category_3",
    ranking as "ranking",
    click as "click",
    impression as "impression",
    ad_cost as "ad_cost",
    total_order as "total_order",
    total_order_sku as "total_order_sku",
    total_conversion_sales as "total_conversion_sales",
    total_conversion_sales_sku as "total_conversion_sales_sku",
    sales_gmv as "sales_gmv",
    sales_gmv_sku as "sales_gmv_sku",
    pa_cost as "pa_cost",
    bpa_cost as "bpa_cost",
    sa_cost as "sa_cost",
    observed_price as "observed_price",
    rocket_wow_price as "rocket_wow_price",
    total_monthly_search_volume as "total_monthly_search_volume",
    payment_amount as "payment_amount"
from ntaedw_integration.edw_kr_dads_analysis;
create or replace view EDW_RPT_HK_POS(
	"subsource_type",
	"customer",
	"vendor_desc",
	"customer_product_code",
	"jnj_sku_code",
	"pka_product_key",
	"pka_product_key_description",
	"stronghold",
	"gcph_needstate",
	"category_name",
	"age_group_name",
	"gcph_brand",
	"mega_brnd_desc",
	"package",
	"size",
	"greenlight_sku_flag",
	"usd_rt",
	"lcl_rt",
	"year",
	"fisc_per",
	"qrtr_no",
	"qrtr",
	"mnth_id",
	"mnth_desc",
	"mnth_no",
	"mnth_shrt",
	"mnth_long",
	"wk",
	"mnth_wk_no",
	"fisc_week_day_num",
	"mnth_day",
	"cal_year",
	"cal_qrtr_no",
	"cal_mnth_id",
	"cal_mnth_no",
	"cal_mnth_nm",
	"cal_mnth_day",
	"cal_mnth_wk_num",
	"cal_yr_wk_num",
	"cal_week_day_num",
	"promo_week",
	"promo_month_week_num",
	"promo_week_day_num",
	"promo_month_shrt",
	"promo_year",
	"cal_day",
	"cal_date_id",
	"pos_qty",
	"pos_sales",
	"sellin_qty",
	"sellin_preww",
	"sellin_nts",
	"customer_description",
	"ciw_gts_lcy",
	"ciw_gts_usd",
	"ciw_lcy",
	"ciw_usd",
	"ciw_gts_prev_yr_mnth",
	"ciw_prev_yr_mnth",
	"ciw_gts_lcy_prev_yr_mnth",
	"ciw_lcy_prev_yr_mnth",
	"numerator",
	"denominator",
	"numerator_prev_yr",
	"denominator_prev_yr",
	"msl_complaince_numerator",
	"msl_complaince_denominator",
	"msl_complaince_denominator_wt",
	"osa_complaince_numerator",
	"osa_complaince_denominator",
	"osa_complaince_denominator_wt",
	"promo_complaince_numerator",
	"promo_complaince_denominator",
	"promo_complaince_denominator_wt",
	"display_complaince_numerator",
	"display_complaince_denominator",
	"display_complaince_denominator_wt",
	"planogram_complaince_numerator",
	"planogram_complaince_denominator",
	"planogram_complaince_denominator_wt",
	"sos_complaince_numerator",
	"sos_complaince_denominator",
	"sos_complaince_denominator_wt",
	"soa_complaince_numerator",
	"soa_complaince_denominator",
	"soa_complaince_denominator_wt"
) as SELECT
	subsource_type as "subsource_type",
customer as "customer",
vendor_desc as "vendor_desc",
customer_product_code as "customer_product_code",
jnj_sku_code as "jnj_sku_code",
pka_product_key as "pka_product_key",
pka_product_key_description as "pka_product_key_description",
stronghold as "stronghold",
gcph_needstate as "gcph_needstate",
category_name as "category_name",
age_group_name as "age_group_name",
gcph_brand as "gcph_brand",
mega_brnd_desc as "mega_brnd_desc",
package as "package",
size as "size",
greenlight_sku_flag as "greenlight_sku_flag",
usd_rt as "usd_rt",
lcl_rt as "lcl_rt",
year as "year",
fisc_per as "fisc_per",
qrtr_no as "qrtr_no",
qrtr as "qrtr",
mnth_id as "mnth_id",
mnth_desc as "mnth_desc",
mnth_no as "mnth_no",
mnth_shrt as "mnth_shrt",
mnth_long as "mnth_long",
wk as "wk",
mnth_wk_no as "mnth_wk_no",
fisc_week_day_num as "fisc_week_day_num",
mnth_day as "mnth_day",
cal_year as "cal_year",
cal_qrtr_no as "cal_qrtr_no",
cal_mnth_id as "cal_mnth_id",
cal_mnth_no as "cal_mnth_no",
cal_mnth_nm as "cal_mnth_nm",
cal_mnth_day as "cal_mnth_day",
cal_mnth_wk_num as "cal_mnth_wk_num",
cal_yr_wk_num as "cal_yr_wk_num",
cal_week_day_num as "cal_week_day_num",
promo_week as "promo_week",
promo_month_week_num as "promo_month_week_num",
promo_week_day_num as "promo_week_day_num",
promo_month_shrt as "promo_month_shrt",
promo_year as "promo_year",
cal_day as "cal_day",
cal_date_id as "cal_date_id",
pos_qty as "pos_qty",
pos_sales as "pos_sales",
sellin_qty as "sellin_qty",
sellin_preww as "sellin_preww",
sellin_nts as "sellin_nts",
customer_description as "customer_description",
ciw_gts_lcy as "ciw_gts_lcy",
ciw_gts_usd as "ciw_gts_usd",
ciw_lcy as "ciw_lcy",
ciw_usd as "ciw_usd",
ciw_gts_prev_yr_mnth as "ciw_gts_prev_yr_mnth",
ciw_prev_yr_mnth as "ciw_prev_yr_mnth",
ciw_gts_lcy_prev_yr_mnth as "ciw_gts_lcy_prev_yr_mnth",
ciw_lcy_prev_yr_mnth as "ciw_lcy_prev_yr_mnth",
numerator as "numerator",
denominator as "denominator",
numerator_prev_yr as "numerator_prev_yr",
denominator_prev_yr as "denominator_prev_yr",
msl_complaince_numerator as "msl_complaince_numerator",
msl_complaince_denominator as "msl_complaince_denominator",
msl_complaince_denominator_wt as "msl_complaince_denominator_wt",
osa_complaince_numerator as "osa_complaince_numerator",
osa_complaince_denominator as "osa_complaince_denominator",
osa_complaince_denominator_wt as "osa_complaince_denominator_wt",
promo_complaince_numerator as "promo_complaince_numerator",
promo_complaince_denominator as "promo_complaince_denominator",
promo_complaince_denominator_wt as "promo_complaince_denominator_wt",
display_complaince_numerator as "display_complaince_numerator",
display_complaince_denominator as "display_complaince_denominator",
display_complaince_denominator_wt as "display_complaince_denominator_wt",
planogram_complaince_numerator as "planogram_complaince_numerator",
planogram_complaince_denominator as "planogram_complaince_denominator",
planogram_complaince_denominator_wt as "planogram_complaince_denominator_wt",
sos_complaince_numerator as "sos_complaince_numerator",
sos_complaince_denominator as "sos_complaince_denominator",
sos_complaince_denominator_wt as "sos_complaince_denominator_wt",
soa_complaince_numerator as "soa_complaince_numerator",
soa_complaince_denominator as "soa_complaince_denominator",
soa_complaince_denominator_wt as "soa_complaince_denominator_wt"
from ntaedw_integration.edw_rpt_hk_pos;
create or replace view EDW_RPT_TW_SALES_INCENTIVE(
	"source_type",
	"cntry_cd",
	"crncy_cd",
	"to_crncy",
	"psr_code",
	"psr_name",
	"year",
	"qrtr",
	"mnth_id",
	"report_to",
	"reportto_name",
	"reverse",
	"monthly_actual",
	"monthly_target",
	"monthly_achievement",
	"monthly_incentive_amount",
	"quarterly_actual",
	"quarterly_target",
	"quarterly_achievement",
	"quarterly_incentive_amount",
	"crt_dttm"
) as
select source_type as "source_type",
    cntry_cd as "cntry_cd",
    crncy_cd as "crncy_cd",
    to_crncy as "to_crncy",
    psr_code as "psr_code",
    psr_name as "psr_name",
    year as "year",
    qrtr as "qrtr",
    mnth_id as "mnth_id",
    report_to as "report_to",
    reportto_name as "reportto_name",
    reverse as "reverse",
    monthly_actual as "monthly_actual",
    monthly_target as "monthly_target",
    monthly_achievement as "monthly_achievement",
    monthly_incentive_amount as "monthly_incentive_amount",
    quarterly_actual as "quarterly_actual",
    quarterly_target as "quarterly_target",
    quarterly_achievement as "quarterly_achievement",
    quarterly_incentive_amount as "quarterly_incentive_amount",
    crt_dttm as "crt_dttm"
from ntaedw_integration.edw_rpt_tw_sales_incentive;
create or replace view EDW_SFMC_NAVER_DM(
	"cntry_cd",
	"naver_id",
	"birth_year",
	"gender",
	"total_purchase_amount",
	"total_number_of_purchases",
	"membership_grade_level",
	"marketing_message_viewing_receiving",
	"coupon_usage_issuance",
	"number_of_reviews",
	"number_of_comments",
	"number_of_attendances",
	"opt_in_for_jnj_communication",
	"notification_subscription",
	"acquisition_channel",
	"reason_for_joining",
	"skin_type_body",
	"baby_skin_concerns",
	"oral_health_concerns",
	"skin_concerns_face",
	"updated_date",
	"membership_registration_date",
	"file_date",
	"file_name",
	"crtd_dttm",
	"age",
	"age_group",
	"no_of_purchase_group",
	"no_of_reviews_group",
	"no_of_comments_group",
	"no_of_attendances_group",
	"msg_read",
	"coupon_usage",
	"new_update_date"
) as SELECT
	cntry_cd as "cntry_cd",
naver_id as "naver_id",
birth_year as "birth_year",
gender as "gender",
total_purchase_amount as "total_purchase_amount",
total_number_of_purchases as "total_number_of_purchases",
membership_grade_level as "membership_grade_level",
marketing_message_viewing_receiving as "marketing_message_viewing_receiving",
coupon_usage_issuance as "coupon_usage_issuance",
number_of_reviews as "number_of_reviews",
number_of_comments as "number_of_comments",
number_of_attendances as "number_of_attendances",
opt_in_for_jnj_communication as "opt_in_for_jnj_communication",
notification_subscription as "notification_subscription",
acquisition_channel as "acquisition_channel",
reason_for_joining as "reason_for_joining",
skin_type_body as "skin_type_body",
baby_skin_concerns as "baby_skin_concerns",
oral_health_concerns as "oral_health_concerns",
skin_concerns_face as "skin_concerns_face",
updated_date as "updated_date",
membership_registration_date as "membership_registration_date",
file_date as "file_date",
file_name as "file_name",
crtd_dttm as "crtd_dttm",
age as "age",
age_group as "age_group",
no_of_purchase_group as "no_of_purchase_group",
no_of_reviews_group as "no_of_reviews_group",
no_of_comments_group as "no_of_comments_group",
no_of_attendances_group as "no_of_attendances_group",
msg_read as "msg_read",
coupon_usage as "coupon_usage",
new_update_date as "new_update_date"
from NTAEDW_INTEGRATION.EDW_SFMC_NAVER_DM;
create or replace view EDW_VW_KR_TP_TRACKER(
	"identifier",
	"sls_org",
	"matl_num",
	"cust_num",
	"acct_num",
	"sls_ofc",
	"ctry_nm",
	"ctry_key",
	"sls_grp",
	"caln_day",
	"caln_yr_mo",
	"fisc_yr",
	"fisc_yr_per",
	"b3_base_prod",
	"b4_var",
	"b5_put_up",
	"b1_mega_brnd",
	"b2_brnd",
	"prod_minor",
	"prod_maj",
	"prod_fran",
	"fran",
	"matl_sls",
	"prod_hier",
	"amt_obj_crncy",
	"nts_actuals",
	"tp_actuals",
	"nts_qty",
	"tp_qty",
	"sls_grp_desc",
	"sls_ofc_desc",
	"matl_desc",
	"mega_brnd_desc",
	"brnd_desc",
	"varnt_desc",
	"base_prod_desc",
	"put_up_desc",
	"channel",
	"med_desc",
	"edw_cust_nm",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"acct_hier_desc",
	"acct_hier_shrt_desc",
	"company_nm",
	"ean_num",
	"prod_hier_lvl1",
	"prod_hier_lvl2",
	"prod_hier_lvl3",
	"prod_hier_lvl4",
	"prod_hier_lvl5",
	"prod_hier_lvl6",
	"prod_hier_lvl7",
	"prod_hier_lvl8",
	"prod_hier_lvl9",
	"store_type",
	"account_classification",
	"target_type",
	"tgt_value_per",
	"tgt_value"
) as
    select
    identifier as "identifier",
    sls_org as "sls_org",
    matl_num as "matl_num",
    cust_num as "cust_num",
    acct_num as "acct_num",
    sls_ofc as "sls_ofc",
    ctry_nm as "ctry_nm",
    ctry_key as "ctry_key",
    sls_grp as "sls_grp",
    caln_day as "caln_day",
    caln_yr_mo as "caln_yr_mo",
    fisc_yr as "fisc_yr",
    fisc_yr_per as "fisc_yr_per",
    b3_base_prod as "b3_base_prod",
    b4_var as "b4_var",
    b5_put_up as "b5_put_up",
    b1_mega_brnd as "b1_mega_brnd",
    b2_brnd as "b2_brnd",
    prod_minor as "prod_minor",
    prod_maj as "prod_maj",
    prod_fran as "prod_fran",
    fran as "fran",
    matl_sls as "matl_sls",
    prod_hier as "prod_hier",
    amt_obj_crncy as "amt_obj_crncy",
    nts_actuals as "nts_actuals",
    tp_actuals as "tp_actuals",
    nts_qty as "nts_qty",
    tp_qty as "tp_qty",
    sls_grp_desc as "sls_grp_desc",
    sls_ofc_desc as "sls_ofc_desc",
    matl_desc as "matl_desc",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_desc as "brnd_desc",
    varnt_desc as "varnt_desc",
    base_prod_desc as "base_prod_desc",
    put_up_desc as "put_up_desc",
    channel as "channel",
    med_desc as "med_desc",
    edw_cust_nm as "edw_cust_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    acct_hier_desc as "acct_hier_desc",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    company_nm as "company_nm",
    ean_num as "ean_num",
    prod_hier_lvl1 as "prod_hier_lvl1",
    prod_hier_lvl2 as "prod_hier_lvl2",
    prod_hier_lvl3 as "prod_hier_lvl3",
    prod_hier_lvl4 as "prod_hier_lvl4",
    prod_hier_lvl5 as "prod_hier_lvl5",
    prod_hier_lvl6 as "prod_hier_lvl6",
    prod_hier_lvl7 as "prod_hier_lvl7",
    prod_hier_lvl8 as "prod_hier_lvl8",
    prod_hier_lvl9 as "prod_hier_lvl9",
    store_type as "store_type",
    account_classification as "account_classification",
    target_type as "target_type",
    tgt_value_per as "tgt_value_per",
    tgt_value as "tgt_value"
    from ntaedw_integration.edw_vw_kr_tp_tracker
;
create or replace view EDW_VW_POP6_ANALYSIS_ACTIVE_DATA(
	"data_type",
	"cntry_cd",
	"visit_id",
	"task_group",
	"task_id",
	"task_name",
	"audit_form_id",
	"audit_form",
	"section_id",
	"section",
	"subsection_id",
	"subsection",
	"field_id",
	"field_code",
	"field_label",
	"field_type",
	"dependent_on_field_id",
	"sku_id",
	"sku",
	"response",
	"visit_date",
	"check_in_datetime",
	"check_out_datetime",
	"popdb_id",
	"pop_code",
	"pop_name",
	"address",
	"check_in_longitude",
	"check_in_latitude",
	"check_out_longitude",
	"check_out_latitude",
	"check_in_photo",
	"check_out_photo",
	"username",
	"user_full_name",
	"superior_username",
	"superior_name",
	"planned_visit",
	"cancelled_visit",
	"cancellation_reason",
	"cancellation_note",
	"promotion_plan_id",
	"promotion_code",
	"promotion_name",
	"promotion_mechanics",
	"promotion_type",
	"promotion_price",
	"promotion_compliance",
	"actual_price",
	"non_compliance_reason",
	"photo",
	"product_attribute_id",
	"product_attribute",
	"product_attribute_value_id",
	"product_attribute_value",
	"pop_status",
	"pop_longitude",
	"pop_latitude",
	"country",
	"channel",
	"retail_environment_ps",
	"customer",
	"sales_group_code",
	"sales_group_name",
	"customer_grade",
	"external_pop_code",
	"business_unit_name",
	"territory_or_region",
	"prod_status",
	"productdb_id",
	"barcode",
	"unit_price",
	"display_order",
	"launch_date",
	"largest_uom_quantity",
	"middle_uom_quantity",
	"smallest_uom_quantity",
	"company",
	"sku_english",
	"sku_code",
	"ps_category",
	"ps_segment",
	"ps_category_segment",
	"country_l1",
	"regional_franchise_l2",
	"franchise_l3",
	"brand_l4",
	"sub_category_l5",
	"platform_l6",
	"variance_l7",
	"pack_size_l8",
	"sap_matl_num",
	"msl_rank",
	"user_status",
	"userdb_id",
	"first_name",
	"last_name",
	"team",
	"authorisation_group",
	"email_address",
	"user_longitude",
	"user_latitude",
	"display_plan_id",
	"display_type",
	"display_code",
	"display_name",
	"display_start_date",
	"display_end_date",
	"checklist_method",
	"display_number",
	"display_comments",
	"y/n_flag",
	"mkt_share",
	"planned_visit_date",
	"visited_flag",
	"facing",
	"is_eyelevel"
) as
    select
    data_type as "data_type",
    cntry_cd as "cntry_cd",
    visit_id as "visit_id",
    task_group as "task_group",
    task_id as "task_id",
    task_name as "task_name",
    audit_form_id as "audit_form_id",
    audit_form as "audit_form",
    section_id as "section_id",
    section as "section",
    subsection_id as "subsection_id",
    subsection as "subsection",
    field_id as "field_id",
    field_code as "field_code",
    field_label as "field_label",
    field_type as "field_type",
    dependent_on_field_id as "dependent_on_field_id",
    sku_id as "sku_id",
    sku as "sku",
    response as "response",
    visit_date as "visit_date",
    check_in_datetime as "check_in_datetime",
    check_out_datetime as "check_out_datetime",
    popdb_id as "popdb_id",
    pop_code as "pop_code",
    pop_name as "pop_name",
    address as "address",
    check_in_longitude as "check_in_longitude",
    check_in_latitude as "check_in_latitude",
    check_out_longitude as "check_out_longitude",
    check_out_latitude as "check_out_latitude",
    check_in_photo as "check_in_photo",
    check_out_photo as "check_out_photo",
    username as "username",
    user_full_name as "user_full_name",
    superior_username as "superior_username",
    superior_name as "superior_name",
    planned_visit as "planned_visit",
    cancelled_visit as "cancelled_visit",
    cancellation_reason as "cancellation_reason",
    cancellation_note as "cancellation_note",
    promotion_plan_id as "promotion_plan_id",
    promotion_code as "promotion_code",
    promotion_name as "promotion_name",
    promotion_mechanics as "promotion_mechanics",
    promotion_type as "promotion_type",
    promotion_price as "promotion_price",
    promotion_compliance as "promotion_compliance",
    actual_price as "actual_price",
    non_compliance_reason as "non_compliance_reason",
    photo as "photo",
    product_attribute_id as "product_attribute_id",
    product_attribute as "product_attribute",
    product_attribute_value_id as "product_attribute_value_id",
    product_attribute_value as "product_attribute_value",
    pop_status as "pop_status",
    pop_longitude as "pop_longitude",
    pop_latitude as "pop_latitude",
    country as "country",
    channel as "channel",
    retail_environment_ps as "retail_environment_ps",
    customer as "customer",
    sales_group_code as "sales_group_code",
    sales_group_name as "sales_group_name",
    customer_grade as "customer_grade",
    external_pop_code as "external_pop_code",
    business_unit_name as "business_unit_name",
    territory_or_region as "territory_or_region",
    prod_status as "prod_status",
    productdb_id as "productdb_id",
    barcode as "barcode",
    unit_price as "unit_price",
    display_order as "display_order",
    launch_date as "launch_date",
    largest_uom_quantity as "largest_uom_quantity",
    middle_uom_quantity as "middle_uom_quantity",
    smallest_uom_quantity as "smallest_uom_quantity",
    company as "company",
    sku_english as "sku_english",
    sku_code as "sku_code",
    ps_category as "ps_category",
    ps_segment as "ps_segment",
    ps_category_segment as "ps_category_segment",
    country_l1 as "country_l1",
    regional_franchise_l2 as "regional_franchise_l2",
    franchise_l3 as "franchise_l3",
    brand_l4 as "brand_l4",
    sub_category_l5 as "sub_category_l5",
    platform_l6 as "platform_l6",
    variance_l7 as "variance_l7",
    pack_size_l8 as "pack_size_l8",
    sap_matl_num as "sap_matl_num",
    msl_rank as "msl_rank",
    user_status as "user_status",
    userdb_id as "userdb_id",
    first_name as "first_name",
    last_name as "last_name",
    team as "team",
    authorisation_group as "authorisation_group",
    email_address as "email_address",
    user_longitude as "user_longitude",
    user_latitude as "user_latitude",
    display_plan_id as "display_plan_id",
    display_type as "display_type",
    display_code as "display_code",
    display_name as "display_name",
    display_start_date as "display_start_date",
    display_end_date as "display_end_date",
    checklist_method as "checklist_method",
    display_number as "display_number",
    display_comments as "display_comments",
    "y/n_flag" as "y/n_flag",
    mkt_share as "mkt_share",
    planned_visit_date as "planned_visit_date",
    visited_flag as "visited_flag",
    facing as "facing",
    is_eyelevel as "is_eyelevel"
    from ntaedw_integration.edw_vw_pop6_analysis_active_data
;
create or replace view ITG_TW_IMS_DSTR_CUSTOMER_MAPPING(
	"distributor_code",
	"distributor_name",
	"distributors_customer_code",
	"distributors_customer_name",
	"store_type",
	"hq",
	"crt_dttm",
	"updt_dttm"
) as
select distributor_code as "distributor_code",
    distributor_name as "distributor_name",
    distributors_customer_code as "distributors_customer_code",
    distributors_customer_name as "distributors_customer_name",
    store_type as "store_type",
    hq as "hq",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm"
from ntaitg_integration.itg_tw_ims_dstr_customer_mapping;
create or replace view ITG_TW_IMS_DSTR_PROD_MAP(
	"dstr_cd",
	"dstr_nm",
	"dstr_prod_cd",
	"dstr_prod_nm",
	"ean_cd",
	"crt_dttm",
	"updt_dttm"
) as
select dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    dstr_prod_cd as "dstr_prod_cd",
    dstr_prod_nm as "dstr_prod_nm",
    ean_cd as "ean_cd",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm"
from ntaitg_integration.itg_tw_ims_dstr_prod_map;
create or replace view ITG_TW_IMS_DSTR_PROD_PRICE_MAP(
	"dstr_cd",
	"dstr_nm",
	"ean_cd",
	"dstr_prod_cd",
	"dstr_prod_nm",
	"sell_out_price_manual",
	"promotion_start_date",
	"promotion_end_date",
	"crt_dttm",
	"updt_dttm"
) as
select dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    ean_cd as "ean_cd",
    dstr_prod_cd as "dstr_prod_cd",
    dstr_prod_nm as "dstr_prod_nm",
    sell_out_price_manual as "sell_out_price_manual",
    promotion_start_date as "promotion_start_date",
    promotion_end_date as "promotion_end_date",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm"
from ntaitg_integration.itg_tw_ims_dstr_prod_price_map;
create or replace view VW_EDW_COUPANG_PREMIUM(
	"ctry_cd",
	"ctry_nm",
	"data_source",
	"reference_date",
	"data_granularity",
	"category_depth1",
	"category_depth2",
	"category_depth3",
	"ranking",
	"prev_day_ranking",
	"prev_week_ranking",
	"prev_mon_ranking",
	"sku_id",
	"sku_name",
	"jnj_brand",
	"rank_change",
	"vendoritemid",
	"ean",
	"all_brand",
	"jnj_product_flag",
	"coupang_product_name",
	"review_score_star",
	"review_contents",
	"coupang_id",
	"new_user_count",
	"curr_user_count",
	"tot_user_count",
	"new_user_sales_amt",
	"curr_user_sales_amt",
	"new_user_avg_product_sales_price",
	"curr_user_avg_product_sales_price",
	"tot_user_avg_product_sales_price",
	"search_keyword",
	"product_name",
	"by_search_keyword",
	"by_product_ranking",
	"product_ranking",
	"click_rate",
	"cart_transition_rate",
	"purchase_conversion_rate",
	"fisc_year",
	"fisc_qrtr",
	"fisc_month",
	"fisc_month_num",
	"fisc_month_name",
	"fisc_wk_num",
	"fisc_month_wk_num",
	"fisc_month_day",
	"cal_year",
	"cal_qrtr",
	"cal_month",
	"cal_month_num",
	"cal_month_name",
	"cal_wk_num",
	"cal_mnth_wk_num",
	"cal_mnth_day",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"lcl_prod_nm"
) as
    select
    ctry_cd as "ctry_cd",
    ctry_nm as "ctry_nm",
    data_source as "data_source",
    reference_date as "reference_date",
    data_granularity as "data_granularity",
    category_depth1 as "category_depth1",
    category_depth2 as "category_depth2",
    category_depth3 as "category_depth3",
    ranking as "ranking",
    prev_day_ranking as "prev_day_ranking",
    prev_week_ranking as "prev_week_ranking",
    prev_mon_ranking as "prev_mon_ranking",
    sku_id as "sku_id",
    sku_name as "sku_name",
    jnj_brand as "jnj_brand",
    rank_change as "rank_change",
    vendoritemid as "vendoritemid",
    ean as "ean",
    all_brand as "all_brand",
    jnj_product_flag as "jnj_product_flag",
    coupang_product_name as "coupang_product_name",
    review_score_star as "review_score_star",
    review_contents as "review_contents",
    coupang_id as "coupang_id",
    new_user_count as "new_user_count",
    curr_user_count as "curr_user_count",
    tot_user_count as "tot_user_count",
    new_user_sales_amt as "new_user_sales_amt",
    curr_user_sales_amt as "curr_user_sales_amt",
    new_user_avg_product_sales_price as "new_user_avg_product_sales_price",
    curr_user_avg_product_sales_price as "curr_user_avg_product_sales_price",
    tot_user_avg_product_sales_price as "tot_user_avg_product_sales_price",
    search_keyword as "search_keyword",
    product_name as "product_name",
    by_search_keyword as "by_search_keyword",
    by_product_ranking as "by_product_ranking",
    product_ranking as "product_ranking",
    click_rate as "click_rate",
    cart_transition_rate as "cart_transition_rate",
    purchase_conversion_rate as "purchase_conversion_rate",
    fisc_year as "fisc_year",
    fisc_qrtr as "fisc_qrtr",
    fisc_month as "fisc_month",
    fisc_month_num as "fisc_month_num",
    fisc_month_name as "fisc_month_name",
    fisc_wk_num as "fisc_wk_num",
    fisc_month_wk_num as "fisc_month_wk_num",
    fisc_month_day as "fisc_month_day",
    cal_year as "cal_year",
    cal_qrtr as "cal_qrtr",
    cal_month as "cal_month",
    cal_month_num as "cal_month_num",
    cal_month_name as "cal_month_name",
    cal_wk_num as "cal_wk_num",
    cal_mnth_wk_num as "cal_mnth_wk_num",
    cal_mnth_day as "cal_mnth_day",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.vw_edw_coupang_premium
;
create or replace view VW_KR_GT_SELLOUT(
	"ims_txn_dt",
	"dstr_cd",
	"dstr_nm",
	"cust_cd",
	"cust_nm",
	"prod_nm",
	"ean_num",
	"ctry_cd",
	"crncy_cd",
	"sap_code",
	"sku_type",
	"unit_prc",
	"sls_amt",
	"sls_qty",
	"cal_day",
	"fisc_yr",
	"fisc_wk_num",
	"fisc_per",
	"ex_rt_typ",
	"from_crncy",
	"to_crncy",
	"vld_from",
	"ex_rt",
	"sap_matl_num",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"store_typ",
	"channel",
	"sls_grp",
	"lcl_prod_nm",
	"sub_customer_code",
	"sub_customer_name",
	"sales_priority",
	"sales_stores",
	"sales_rate"
) as
    select
    ims_txn_dt as "ims_txn_dt",
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    cust_cd as "cust_cd",
    cust_nm as "cust_nm",
    prod_nm as "prod_nm",
    ean_num as "ean_num",
    ctry_cd as "ctry_cd",
    crncy_cd as "crncy_cd",
    sap_code as "sap_code",
    sku_type as "sku_type",
    unit_prc as "unit_prc",
    sls_amt as "sls_amt",
    sls_qty as "sls_qty",
    cal_day as "cal_day",
    fisc_yr as "fisc_yr",
    fisc_wk_num as "fisc_wk_num",
    fisc_per as "fisc_per",
    ex_rt_typ as "ex_rt_typ",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    vld_from as "vld_from",
    ex_rt as "ex_rt",
    sap_matl_num as "sap_matl_num",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    store_typ as "store_typ",
    channel as "channel",
    sls_grp as "sls_grp",
    lcl_prod_nm as "lcl_prod_nm",
    sub_customer_code as "sub_customer_code",
    sub_customer_name as "sub_customer_name",
    sales_priority as "sales_priority",
    sales_stores as "sales_stores",
    sales_rate as "sales_rate"
    from ntaedw_integration.vw_kr_gt_sellout
;
create or replace view VW_TW_ACTUAL_FORECAST_TP_ELEMENTS(
	"subsource_type",
	"cntry_cd",
	"crncy_cd",
	"bu_version",
	"forecast_on_year",
	"forecast_on_month",
	"forecast_for_year",
	"forecast_for_mnth",
	"caln_day",
	"sls_grp",
	"channel",
	"sls_ofc",
	"sls_ofc_desc",
	"strategy_customer_hierachy_name",
	"lph_level_6",
	"brand",
	"tp_element",
	"gts_bp_tgt",
	"gts_bu_forecast",
	"gts",
	"trading_term_act",
	"hidden_discnt_act",
	"rtn_act",
	"gts_act",
	"nts_bp_tgt",
	"nts_bu_forecast",
	"nts_act",
	"tp_bp_tgt",
	"tp_bu_forecast",
	"tp_act",
	"to_crncy",
	"ex_rt"
) as
    select
    subsource_type as "subsource_type",
    cntry_cd as "cntry_cd",
    crncy_cd as "crncy_cd",
    bu_version as "bu_version",
    forecast_on_year as "forecast_on_year",
    forecast_on_month as "forecast_on_month",
    forecast_for_year as "forecast_for_year",
    forecast_for_mnth as "forecast_for_mnth",
    caln_day as "caln_day",
    sls_grp as "sls_grp",
    channel as "channel",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    strategy_customer_hierachy_name as "strategy_customer_hierachy_name",
    lph_level_6 as "lph_level_6",
    brand as "brand",
    tp_element as "tp_element",
    gts_bp_tgt as "gts_bp_tgt",
    gts_bu_forecast as "gts_bu_forecast",
    gts as "gts",
    trading_term_act as "trading_term_act",
    hidden_discnt_act as "hidden_discnt_act",
    rtn_act as "rtn_act",
    gts_act as "gts_act",
    nts_bp_tgt as "nts_bp_tgt",
    nts_bu_forecast as "nts_bu_forecast",
    nts_act as "nts_act",
    tp_bp_tgt as "tp_bp_tgt",
    tp_bu_forecast as "tp_bu_forecast",
    tp_act as "tp_act",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt"
    from ntaedw_integration.vw_tw_actual_forecast_tp_elements
;
create or replace view VW_TW_FORECAST(
	"subsource_type",
	"cntry_cd",
	"crncy_cd",
	"bu_version",
	"forecast_on_year",
	"forecast_on_month",
	"forecast_for_year",
	"forecast_for_mnth",
	"caln_day",
	"latest_date",
	"latest_fisc_yrmnth",
	"sls_grp",
	"channel",
	"sls_ofc",
	"sls_ofc_desc",
	"strategy_customer_hierachy_name",
	"lph_level_6",
	"gts_bp_tgt",
	"gts_bu_forecast",
	"gts",
	"trading_term_act",
	"hidden_discnt_act",
	"rtn_act",
	"gts_act",
	"nts_bp_tgt",
	"nts_bu_forecast",
	"nts_act",
	"tp_bp_tgt",
	"tp_bu_forecast",
	"tp_act",
	"price_off_bu_forecast",
	"display_bu_forecast",
	"dm_bu_forecast",
	"other_support_bu_forecast",
	"sr_bu_forecast",
	"brand",
	"to_crncy",
	"ex_rt"
) as
    select
    subsource_type as "subsource_type",
    cntry_cd as "cntry_cd",
    crncy_cd as "crncy_cd",
    bu_version as "bu_version",
    forecast_on_year as "forecast_on_year",
    forecast_on_month as "forecast_on_month",
    forecast_for_year as "forecast_for_year",
    forecast_for_mnth as "forecast_for_mnth",
    caln_day as "caln_day",
    latest_date as "latest_date",
    latest_fisc_yrmnth as "latest_fisc_yrmnth",
    sls_grp as "sls_grp",
    channel as "channel",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    strategy_customer_hierachy_name as "strategy_customer_hierachy_name",
    lph_level_6 as "lph_level_6",
    gts_bp_tgt as "gts_bp_tgt",
    gts_bu_forecast as "gts_bu_forecast",
    gts as "gts",
    trading_term_act as "trading_term_act",
    hidden_discnt_act as "hidden_discnt_act",
    rtn_act as "rtn_act",
    gts_act as "gts_act",
    nts_bp_tgt as "nts_bp_tgt",
    nts_bu_forecast as "nts_bu_forecast",
    nts_act as "nts_act",
    tp_bp_tgt as "tp_bp_tgt",
    tp_bu_forecast as "tp_bu_forecast",
    tp_act as "tp_act",
    price_off_bu_forecast as "price_off_bu_forecast",
    display_bu_forecast as "display_bu_forecast",
    dm_bu_forecast as "dm_bu_forecast",
    other_support_bu_forecast as "other_support_bu_forecast",
    sr_bu_forecast as "sr_bu_forecast",
    brand as "brand",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt"
    from ntaedw_integration.vw_tw_forecast
;
create or replace view V_BI_SLSCYC_VST_TGTG_CUST_MRCH_PROD_HIER_SLSP(
	"customerid",
	"customername",
	"remotekey",
	"country",
	"storetype",
	"channel",
	"salesgroup",
	"visitid",
	"scheduleddate",
	"scheduledtime",
	"status",
	"merchandisingresponseid",
	"salespersonid",
	"salesperson_remotekey",
	"salesperson_firstname",
	"salesperson_lastname",
	"salesperson_jobrole",
	"salesperson_language",
	"salescampaignid",
	"presence",
	"pricepresence",
	"pricedetails",
	"outofstock_cause",
	"stockcount",
	"mustcarryitem",
	"facings",
	"verticalposition",
	"storeposition",
	"promodetails",
	"productid",
	"prod_remotekey",
	"eannumber",
	"productname",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9"
) as
    select
    customerid as "customerid",
    customername as "customername",
    remotekey as "remotekey",
    country as "country",
    storetype as "storetype",
    channel as "channel",
    salesgroup as "salesgroup",
    visitid as "visitid",
    scheduleddate as "scheduleddate",
    scheduledtime as "scheduledtime",
    status as "status",
    merchandisingresponseid as "merchandisingresponseid",
    salespersonid as "salespersonid",
    salesperson_remotekey as "salesperson_remotekey",
    salesperson_firstname as "salesperson_firstname",
    salesperson_lastname as "salesperson_lastname",
    salesperson_jobrole as "salesperson_jobrole",
    salesperson_language as "salesperson_language",
    salescampaignid as "salescampaignid",
    presence as "presence",
    pricepresence as "pricepresence",
    pricedetails as "pricedetails",
    outofstock_cause as "outofstock_cause",
    stockcount as "stockcount",
    mustcarryitem as "mustcarryitem",
    facings as "facings",
    verticalposition as "verticalposition",
    storeposition as "storeposition",
    promodetails as "promodetails",
    productid as "productid",
    prod_remotekey as "prod_remotekey",
    eannumber as "eannumber",
    productname as "productname",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9"
    from ntaedw_integration.v_bi_slscyc_vst_tgtg_cust_mrch_prod_hier_slsp
;
create or replace view V_KR_ECOMMERCE_SELLOUT(
	"country",
	"product_name",
	"distributor_code",
	"distributor_name",
	"subcustomer_name",
	"ean",
	"ex_rt",
	"sales_qty",
	"sales_value_lcy",
	"from_crncy",
	"to_crncy",
	"fisc_year",
	"fisc_month",
	"fisc_day",
	"cal_year",
	"cal_month",
	"cal_day",
	"fisc_wk",
	"ims_txn_dt",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"put_up_description",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment",
	"jnj_sku_code",
	"sku_type",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"store_type",
	"sls_grp",
	"sls_grp_cd"
) as
    select
    country as "country",
    product_name as "product_name",
    distributor_code as "distributor_code",
    distributor_name as "distributor_name",
    subcustomer_name as "subcustomer_name",
    ean as "ean",
    ex_rt as "ex_rt",
    sales_qty as "sales_qty",
    sales_value_lcy as "sales_value_lcy",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    fisc_year as "fisc_year",
    fisc_month as "fisc_month",
    fisc_day as "fisc_day",
    cal_year as "cal_year",
    cal_month as "cal_month",
    cal_day as "cal_day",
    fisc_wk as "fisc_wk",
    ims_txn_dt as "ims_txn_dt",
    gcph_franchise as "gcph_franchise",
    gcph_brand as "gcph_brand",
    gcph_subbrand as "gcph_subbrand",
    gcph_variant as "gcph_variant",
    put_up_description as "put_up_description",
    gcph_needstate as "gcph_needstate",
    gcph_category as "gcph_category",
    gcph_subcategory as "gcph_subcategory",
    gcph_segment as "gcph_segment",
    gcph_subsegment as "gcph_subsegment",
    jnj_sku_code as "jnj_sku_code",
    sku_type as "sku_type",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    store_type as "store_type",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd"
    from ntaedw_integration.v_kr_ecommerce_sellout
;
create or replace view V_RPT_COPA(
	"cntry_key",
	"acct_num",
	"cust_num",
	"channel",
	"prft_ctr",
	"matl",
	"matl_desc",
	"ean_num",
	"prod_hier_lvl1",
	"prod_hier_lvl2",
	"prod_hier_lvl3",
	"mega_brnd_desc",
	"brnd_desc",
	"prod_minor",
	"sls_grp",
	"sls_grp_desc",
	"sls_ofc",
	"sls_ofc_desc",
	"category_1",
	"categroy_2",
	"platform_ca",
	"prod_hier_lvl8",
	"prod_hier_lvl9",
	"amt_obj_crncy",
	"obj_crncy_co_obj",
	"edw_cust_nm",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"brand_group",
	"fisc_day",
	"fisc_yr_per",
	"caln_day",
	"caln_yr_mo",
	"qty",
	"uom",
	"acct_hier_desc",
	"acct_hier_shrt_desc",
	"cntry_cd",
	"company_nm",
	"store_type",
	"plnt"
) as
    select
    cntry_key as "cntry_key",
    acct_num as "acct_num",
    cust_num as "cust_num",
    channel as "channel",
    prft_ctr as "prft_ctr",
    matl as "matl",
    matl_desc as "matl_desc",
    ean_num as "ean_num",
    prod_hier_lvl1 as "prod_hier_lvl1",
    prod_hier_lvl2 as "prod_hier_lvl2",
    prod_hier_lvl3 as "prod_hier_lvl3",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_desc as "brnd_desc",
    prod_minor as "prod_minor",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    category_1 as "category_1",
    categroy_2 as "categroy_2",
    platform_ca as "platform_ca",
    prod_hier_lvl8 as "prod_hier_lvl8",
    prod_hier_lvl9 as "prod_hier_lvl9",
    amt_obj_crncy as "amt_obj_crncy",
    obj_crncy_co_obj as "obj_crncy_co_obj",
    edw_cust_nm as "edw_cust_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    brand_group as "brand_group",
    fisc_day as "fisc_day",
    fisc_yr_per as "fisc_yr_per",
    caln_day as "caln_day",
    caln_yr_mo as "caln_yr_mo",
    qty as "qty",
    uom as "uom",
    acct_hier_desc as "acct_hier_desc",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    cntry_cd as "cntry_cd",
    company_nm as "company_nm",
    store_type as "store_type",
    plnt as "plnt"
    from ntaedw_integration.v_rpt_copa
;
create or replace view V_RPT_COPA_TREND(
	"cntry_key",
	"channel",
	"amt_obj_crncy",
	"obj_crncy_co_obj",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"fisc_day",
	"acct_hier_desc",
	"acct_hier_shrt_desc",
	"catg",
	"brnd_nm",
	"sls_grp",
	"sls_grp_desc",
	"sls_ofc",
	"sls_ofc_desc",
	"store_type",
	"cust_num",
	"edw_cust_nm",
	"cntry_cd",
	"current_fisc_per"
) as
    select
    cntry_key as "cntry_key",
    channel as "channel",
    amt_obj_crncy as "amt_obj_crncy",
    obj_crncy_co_obj as "obj_crncy_co_obj",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    fisc_day as "fisc_day",
    acct_hier_desc as "acct_hier_desc",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    catg as "catg",
    brnd_nm as "brnd_nm",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    store_type as "store_type",
    cust_num as "cust_num",
    edw_cust_nm as "edw_cust_nm",
    cntry_cd as "cntry_cd",
    current_fisc_per as "current_fisc_per"
    from ntaedw_integration.v_rpt_copa_trend
;
create or replace view V_RPT_DLY_PLAN_IMS_ENRICH(
	"ims_txn_dt",
	"fisc_per",
	"fisc_wk",
	"no_of_wks",
	"fisc_wk_num",
	"visit_dt",
	"visit_jj_mnth_id",
	"visit_jj_wk_no",
	"visit_jj_wkdy_no",
	"visit_end_dt",
	"actl_ims_txn_dt",
	"ctry_cd",
	"dstr_cd",
	"dstr_nm",
	"sls_rep_cd",
	"sls_rep_typ",
	"sls_rep_nm",
	"store_cd",
	"store_nm",
	"store_class",
	"from_crncy_cd",
	"dly_store_tgt",
	"dly_plan_flg",
	"prod_cd",
	"non_sellable_product",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"prnt_prod_hier_l9",
	"sap_matl_num",
	"lcl_prod_nm",
	"msl_flg",
	"period_sls_amt",
	"dly_prod_cnt",
	"store_sls_amt",
	"ean_num",
	"prnt_ean_num",
	"to_crncy",
	"ex_rt",
	"sls_amt",
	"sls_qty",
	"rtrn_qty",
	"rtrn_amt",
	"hq",
	"store_type",
	"sell_in_price_manual",
	"sell_out_unit_price"
) as
    select
    ims_txn_dt as "ims_txn_dt",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    no_of_wks as "no_of_wks",
    fisc_wk_num as "fisc_wk_num",
    visit_dt as "visit_dt",
    visit_jj_mnth_id as "visit_jj_mnth_id",
    visit_jj_wk_no as "visit_jj_wk_no",
    visit_jj_wkdy_no as "visit_jj_wkdy_no",
    visit_end_dt as "visit_end_dt",
    actl_ims_txn_dt as "actl_ims_txn_dt",
    ctry_cd as "ctry_cd",
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    sls_rep_cd as "sls_rep_cd",
    sls_rep_typ as "sls_rep_typ",
    sls_rep_nm as "sls_rep_nm",
    store_cd as "store_cd",
    store_nm as "store_nm",
    store_class as "store_class",
    from_crncy_cd as "from_crncy_cd",
    dly_store_tgt as "dly_store_tgt",
    dly_plan_flg as "dly_plan_flg",
    prod_cd as "prod_cd",
    non_sellable_product as "non_sellable_product",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    prnt_prod_hier_l9 as "prnt_prod_hier_l9",
    sap_matl_num as "sap_matl_num",
    lcl_prod_nm as "lcl_prod_nm",
    msl_flg as "msl_flg",
    period_sls_amt as "period_sls_amt",
    dly_prod_cnt as "dly_prod_cnt",
    store_sls_amt as "store_sls_amt",
    ean_num as "ean_num",
    prnt_ean_num as "prnt_ean_num",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt",
    sls_amt as "sls_amt",
    sls_qty as "sls_qty",
    rtrn_qty as "rtrn_qty",
    rtrn_amt as "rtrn_amt",
    hq as "hq",
    store_type as "store_type",
    sell_in_price_manual as "sell_in_price_manual",
    sell_out_unit_price as "sell_out_unit_price"
    from ntaedw_integration.v_rpt_dly_plan_ims_enrich
;
create or replace view V_RPT_IMS(
	"dstr_cd",
	"dstr_nm",
	"cust_cd",
	"cust_nm",
	"channel1",
	"channel2",
	"ims_txn_dt",
	"fisc_per",
	"fisc_wk",
	"no_of_wks",
	"fisc_wk_num",
	"prod_cd",
	"prod_nm",
	"ean_num",
	"sls_amt",
	"sls_qty",
	"rtrn_qty",
	"rtrn_amt",
	"sls_rep_nm",
	"sls_rep_cd",
	"ctry_nm",
	"from_crncy",
	"to_crncy",
	"ex_rt",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"sap_matl_num",
	"lcl_prod_nm",
	"sls_grp",
	"store_typ",
	"non_sellable_product"
) as
    select
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    cust_cd as "cust_cd",
    cust_nm as "cust_nm",
    channel1 as "channel1",
    channel2 as "channel2",
    ims_txn_dt as "ims_txn_dt",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    no_of_wks as "no_of_wks",
    fisc_wk_num as "fisc_wk_num",
    prod_cd as "prod_cd",
    prod_nm as "prod_nm",
    ean_num as "ean_num",
    sls_amt as "sls_amt",
    sls_qty as "sls_qty",
    rtrn_qty as "rtrn_qty",
    rtrn_amt as "rtrn_amt",
    sls_rep_nm as "sls_rep_nm",
    sls_rep_cd as "sls_rep_cd",
    ctry_nm as "ctry_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    sap_matl_num as "sap_matl_num",
    lcl_prod_nm as "lcl_prod_nm",
    sls_grp as "sls_grp",
    store_typ as "store_typ",
    non_sellable_product as "non_sellable_product"
    from ntaedw_integration.v_rpt_ims
;
create or replace view V_RPT_IMS_INVENTORY(
	"invnt_dt",
	"dstr_cd",
	"dstr_nm",
	"cust_name",
	"channel1",
	"channel2",
	"fisc_per",
	"fisc_wk",
	"no_of_wks",
	"fisc_wk_num",
	"prod_cd",
	"prod_nm",
	"ean_num",
	"invnt_qty",
	"invnt_amt",
	"sls_rep_nm",
	"sls_rep_cd",
	"ctry_nm",
	"from_crncy",
	"to_crncy",
	"chn_uom",
	"ex_rt",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"sap_matl_num",
	"lcl_prod_nm",
	"sls_grp",
	"store_typ",
	"non_sellable_product",
	"sell_in_price_manual",
	"storage_name",
	"area"
) as
    select
    invnt_dt as "invnt_dt",
    dstr_cd as "dstr_cd",
    dstr_nm as "dstr_nm",
    cust_name as "cust_name",
    channel1 as "channel1",
    channel2 as "channel2",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    no_of_wks as "no_of_wks",
    fisc_wk_num as "fisc_wk_num",
    prod_cd as "prod_cd",
    prod_nm as "prod_nm",
    ean_num as "ean_num",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_rep_nm as "sls_rep_nm",
    sls_rep_cd as "sls_rep_cd",
    ctry_nm as "ctry_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    chn_uom as "chn_uom",
    ex_rt as "ex_rt",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    sap_matl_num as "sap_matl_num",
    lcl_prod_nm as "lcl_prod_nm",
    sls_grp as "sls_grp",
    store_typ as "store_typ",
    non_sellable_product as "non_sellable_product",
    sell_in_price_manual as "sell_in_price_manual",
    storage_name as "storage_name",
    area as "area"
    from ntaedw_integration.v_rpt_ims_inventory
;
create or replace view V_RPT_INVC(
	"sls_doc_typ",
	"billing_type",
	"cust_no",
	"fisc_yr",
	"fisc_mo",
	"cal_day",
	"fisc_wk_num",
	"sls_ofc_cv_cd",
	"sls_ofc_cv",
	"sls_grp_cv_cd",
	"sls_grp_cv",
	"sls_ofc_cy",
	"mega_brnd_cd",
	"brnd_desc",
	"mother_sku",
	"prod_hier_l2",
	"prod_hier_l3",
	"category_1",
	"categroy_2",
	"platform_ca",
	"core_plat",
	"prod_hier_l9",
	"key_acct_nm",
	"channel",
	"store_cd",
	"store_nm",
	"store_typ",
	"mat",
	"matl_desc",
	"ean_num",
	"tot_invc_val",
	"tot_invc_qty",
	"country",
	"edw_cust_nm",
	"currency",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"country_cd",
	"company_nm",
	"current_fisc_per"
) as
    select
    sls_doc_typ as "sls_doc_typ",
    billing_type as "billing_type",
    cust_no as "cust_no",
    fisc_yr as "fisc_yr",
    fisc_mo as "fisc_mo",
    cal_day as "cal_day",
    fisc_wk_num as "fisc_wk_num",
    sls_ofc_cv_cd as "sls_ofc_cv_cd",
    sls_ofc_cv as "sls_ofc_cv",
    sls_grp_cv_cd as "sls_grp_cv_cd",
    sls_grp_cv as "sls_grp_cv",
    sls_ofc_cy as "sls_ofc_cy",
    mega_brnd_cd as "mega_brnd_cd",
    brnd_desc as "brnd_desc",
    mother_sku as "mother_sku",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    category_1 as "category_1",
    categroy_2 as "categroy_2",
    platform_ca as "platform_ca",
    core_plat as "core_plat",
    prod_hier_l9 as "prod_hier_l9",
    key_acct_nm as "key_acct_nm",
    channel as "channel",
    store_cd as "store_cd",
    store_nm as "store_nm",
    store_typ as "store_typ",
    mat as "mat",
    matl_desc as "matl_desc",
    ean_num as "ean_num",
    tot_invc_val as "tot_invc_val",
    tot_invc_qty as "tot_invc_qty",
    country as "country",
    edw_cust_nm as "edw_cust_nm",
    currency as "currency",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    country_cd as "country_cd",
    company_nm as "company_nm",
    current_fisc_per as "current_fisc_per"
    from ntaedw_integration.v_rpt_invc
;
create or replace view V_RPT_INVC_TO_NTS(
	"fisc_yr_per",
	"fisc_day",
	"sls_ofc",
	"sls_ofc_desc",
	"channel",
	"sls_grp",
	"sls_grp_desc",
	"mega_brnd_desc",
	"matl_num",
	"brnd_desc",
	"category",
	"matl_desc",
	"cust_num",
	"ctry_key",
	"ctry_nm",
	"store_type",
	"prod_hier_lvl1",
	"prod_hier_lvl2",
	"prod_hier_lvl3",
	"prod_hier_lvl4",
	"prod_hier_lvl5",
	"prod_hier_lvl6",
	"prod_hier_lvl7",
	"prod_hier_lvl8",
	"prod_hier_lvl9",
	"ean_num",
	"ciw_desc",
	"ciw_code",
	"ciw_bucket",
	"acct_num",
	"acct_nm",
	"from_crncy",
	"to_crncy",
	"amt_obj_crncy",
	"ex_rt",
	"edw_cust_nm"
) as
    select
    fisc_yr_per as "fisc_yr_per",
    fisc_day as "fisc_day",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    channel as "channel",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    mega_brnd_desc as "mega_brnd_desc",
    matl_num as "matl_num",
    brnd_desc as "brnd_desc",
    category as "category",
    matl_desc as "matl_desc",
    cust_num as "cust_num",
    ctry_key as "ctry_key",
    ctry_nm as "ctry_nm",
    store_type as "store_type",
    prod_hier_lvl1 as "prod_hier_lvl1",
    prod_hier_lvl2 as "prod_hier_lvl2",
    prod_hier_lvl3 as "prod_hier_lvl3",
    prod_hier_lvl4 as "prod_hier_lvl4",
    prod_hier_lvl5 as "prod_hier_lvl5",
    prod_hier_lvl6 as "prod_hier_lvl6",
    prod_hier_lvl7 as "prod_hier_lvl7",
    prod_hier_lvl8 as "prod_hier_lvl8",
    prod_hier_lvl9 as "prod_hier_lvl9",
    ean_num as "ean_num",
    ciw_desc as "ciw_desc",
    ciw_code as "ciw_code",
    ciw_bucket as "ciw_bucket",
    acct_num as "acct_num",
    acct_nm as "acct_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    amt_obj_crncy as "amt_obj_crncy",
    ex_rt as "ex_rt",
    edw_cust_nm as "edw_cust_nm"
    from ntaedw_integration.v_rpt_invc_to_nts
;
create or replace view V_RPT_INVC_TREND(
	"fisc_yr",
	"fisc_mo",
	"channel",
	"tot_invc_val",
	"tot_invc_qty",
	"country",
	"currency",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"catg",
	"brnd_nm",
	"sls_grp",
	"sls_grp_desc",
	"sls_ofc",
	"sls_ofc_desc",
	"store_typ",
	"cust_num",
	"edw_cust_nm",
	"country_cd",
	"current_fisc_per"
) as
    select
    fisc_yr as "fisc_yr",
    fisc_mo as "fisc_mo",
    channel as "channel",
    tot_invc_val as "tot_invc_val",
    tot_invc_qty as "tot_invc_qty",
    country as "country",
    currency as "currency",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    catg as "catg",
    brnd_nm as "brnd_nm",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    store_typ as "store_typ",
    cust_num as "cust_num",
    edw_cust_nm as "edw_cust_nm",
    country_cd as "country_cd",
    current_fisc_per as "current_fisc_per"
    from ntaedw_integration.v_rpt_invc_trend
;
create or replace view V_RPT_KR_COUPANG_PPM(
	"ctry_cd",
	"ctry_nm",
	"crncy_cd",
	"transaction_date",
	"sku_id",
	"barcode",
	"brand",
	"sku_people",
	"product_id",
	"ppp",
	"sales_gmv",
	"revenue",
	"ppm_percent",
	"cost_of_purchase",
	"units_sold",
	"price",
	"fisc_year",
	"fisc_qrtr",
	"fisc_month",
	"fisc_month_num",
	"fisc_month_name",
	"fisc_wk_num",
	"fisc_month_wk_num",
	"fisc_month_day",
	"cal_year",
	"cal_qrtr",
	"cal_month",
	"cal_month_num",
	"cal_month_name",
	"cal_wk_num",
	"cal_mnth_wk_num",
	"cal_mnth_day",
	"cal_day",
	"ex_rt_typ",
	"to_crncy",
	"ex_rt",
	"sap_matl_num",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"lcl_prod_nm"
) as
    select
    ctry_cd as "ctry_cd",
    ctry_nm as "ctry_nm",
    crncy_cd as "crncy_cd",
    transaction_date as "transaction_date",
    sku_id as "sku_id",
    barcode as "barcode",
    brand as "brand",
    sku_people as "sku_people",
    product_id as "product_id",
    ppp as "ppp",
    sales_gmv as "sales_gmv",
    revenue as "revenue",
    ppm_percent as "ppm_percent",
    cost_of_purchase as "cost_of_purchase",
    units_sold as "units_sold",
    price as "price",
    fisc_year as "fisc_year",
    fisc_qrtr as "fisc_qrtr",
    fisc_month as "fisc_month",
    fisc_month_num as "fisc_month_num",
    fisc_month_name as "fisc_month_name",
    fisc_wk_num as "fisc_wk_num",
    fisc_month_wk_num as "fisc_month_wk_num",
    fisc_month_day as "fisc_month_day",
    cal_year as "cal_year",
    cal_qrtr as "cal_qrtr",
    cal_month as "cal_month",
    cal_month_num as "cal_month_num",
    cal_month_name as "cal_month_name",
    cal_wk_num as "cal_wk_num",
    cal_mnth_wk_num as "cal_mnth_wk_num",
    cal_mnth_day as "cal_mnth_day",
    cal_day as "cal_day",
    ex_rt_typ as "ex_rt_typ",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt",
    sap_matl_num as "sap_matl_num",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_kr_coupang_ppm
;
create or replace view V_RPT_KR_PRICE_TRACKER(
	"id__by_product_page",
	"id_by_option_on_page",
	"data_collection_date",
	"data_collection_day",
	"product_description_on_the_website",
	"option_description",
	"product_url",
	"bundle_or_not",
	"bundle_type",
	"total_volume",
	"gift",
	"price",
	"option_price",
	"final_selling_price__including_shipping_fee",
	"shipping_fee",
	"shipping_fee_included_or_not",
	"sell_out_qty",
	"total_sales_price",
	"promotional_site",
	"customer_rating",
	"count_of_product_review",
	"type_of_ecom__open_market__social_commerce",
	"ecom_mall_name",
	"name_of_seller",
	"name_of_seller_s_company",
	"seller_type__black_seller___official_seller",
	"option",
	"sku_id",
	"product_category",
	"manufacturer__including_competitors",
	"brand_name",
	"product_description",
	"qty_of_bundle",
	"volume_per_unit_qty",
	"total_volume_static",
	"price_per_ml",
	"price_per_qty",
	"recommended_consumer_price",
	"selling_price_relative_to_the_regular_price",
	"total_sales_qty",
	"month",
	"coupang_non_coupang",
	"coupang_matching",
	"jnj_price_guide"
) as
    select
    id__by_product_page as "id__by_product_page",
    id_by_option_on_page as "id_by_option_on_page",
    data_collection_date as "data_collection_date",
    data_collection_day as "data_collection_day",
    product_description_on_the_website as "product_description_on_the_website",
    option_description as "option_description",
    product_url as "product_url",
    bundle_or_not as "bundle_or_not",
    bundle_type as "bundle_type",
    total_volume as "total_volume",
    gift as "gift",
    price as "price",
    option_price as "option_price",
    final_selling_price__including_shipping_fee as "final_selling_price__including_shipping_fee",
    shipping_fee as "shipping_fee",
    shipping_fee_included_or_not as "shipping_fee_included_or_not",
    sell_out_qty as "sell_out_qty",
    total_sales_price as "total_sales_price",
    promotional_site as "promotional_site",
    customer_rating as "customer_rating",
    count_of_product_review as "count_of_product_review",
    type_of_ecom__open_market__social_commerce as "type_of_ecom__open_market__social_commerce",
    ecom_mall_name as "ecom_mall_name",
    name_of_seller as "name_of_seller",
    name_of_seller_s_company as "name_of_seller_s_company",
    seller_type__black_seller___official_seller as "seller_type__black_seller___official_seller",
    option as "option",
    sku_id as "sku_id",
    product_category as "product_category",
    manufacturer__including_competitors as "manufacturer__including_competitors",
    brand_name as "brand_name",
    product_description as "product_description",
    qty_of_bundle as "qty_of_bundle",
    volume_per_unit_qty as "volume_per_unit_qty",
    total_volume_static as "total_volume_static",
    price_per_ml as "price_per_ml",
    price_per_qty as "price_per_qty",
    recommended_consumer_price as "recommended_consumer_price",
    selling_price_relative_to_the_regular_price as "selling_price_relative_to_the_regular_price",
    total_sales_qty as "total_sales_qty",
    month as "month",
    coupang_non_coupang as "coupang_non_coupang",
    coupang_matching as "coupang_matching",
    jnj_price_guide as "jnj_price_guide"
    from ntaedw_integration.v_rpt_kr_price_tracker
;
create or replace view V_RPT_KR_TRADE_PROMOTION(
	"promo_begin_date",
	"promo_end_date",
	"ctry_cd",
	"crncy_cd",
	"fisc_wk",
	"fisc_yr",
	"fisc_mon",
	"year",
	"week",
	"month",
	"customer_code",
	"customer_name",
	"store_typ",
	"customer_channel",
	"sls_grp",
	"sls_ofc",
	"sls_ofc_desc",
	"sls_grp_cd",
	"activity_name",
	"material_code",
	"ean",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"unit_tpr_price",
	"estimated_quantity",
	"estimated_unit_price",
	"estimated_amount_lcy",
	"estimated_amount_usd",
	"actual_quantity",
	"actual_quantity_pc",
	"actual_unit_price",
	"actual_amount_lcy",
	"actual_amount_usd",
	"application_code",
	"remark"
) as
select
promo_begin_date as "promo_begin_date",
promo_end_date as "promo_end_date",
ctry_cd as "ctry_cd",
crncy_cd as "crncy_cd",
fisc_wk as "fisc_wk",
fisc_yr as "fisc_yr",
fisc_mon as "fisc_mon",
year as "year",
week as "week",
month as "month",
customer_code as "customer_code",
customer_name as "customer_name",
store_typ as "store_typ",
customer_channel as "customer_channel",
sls_grp as "sls_grp",
sls_ofc as "sls_ofc",
sls_ofc_desc as "sls_ofc_desc",
sls_grp_cd as "sls_grp_cd",
activity_name as "activity_name",
material_code as "material_code",
ean as "ean",
prod_hier_l1 as "prod_hier_l1",
prod_hier_l2 as "prod_hier_l2",
prod_hier_l3 as "prod_hier_l3",
prod_hier_l4 as "prod_hier_l4",
prod_hier_l5 as "prod_hier_l5",
prod_hier_l6 as "prod_hier_l6",
prod_hier_l7 as "prod_hier_l7",
prod_hier_l8 as "prod_hier_l8",
prod_hier_l9 as "prod_hier_l9",
unit_tpr_price as "unit_tpr_price",
estimated_quantity as "estimated_quantity",
estimated_unit_price as "estimated_unit_price",
estimated_amount_lcy as "estimated_amount_lcy",
estimated_amount_usd as "estimated_amount_usd",
actual_quantity as "actual_quantity",
actual_quantity_pc as "actual_quantity_pc",
actual_unit_price as "actual_unit_price",
actual_amount_lcy as "actual_amount_lcy",
actual_amount_usd as "actual_amount_usd",
application_code as "application_code",
remark as "remark"
from ntaedw_integration.v_rpt_kr_trade_promotion;
create or replace view V_RPT_NTS_VS_TGT(
	"fisc_yr_per",
	"fisc_day",
	"sls_ofc",
	"sls_ofc_desc",
	"channel",
	"sls_grp",
	"sls_grp_desc",
	"ctry_key",
	"ctry_nm",
	"store_type",
	"prod_hier_lvl2",
	"prod_hier_lvl4",
	"target_type",
	"from_crncy",
	"to_crncy",
	"ex_rt",
	"amt_obj_crncy",
	"target_amt",
	"total_working_days",
	"working_days_elapsed"
) as
    select
    fisc_yr_per as "fisc_yr_per",
    fisc_day as "fisc_day",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    channel as "channel",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    ctry_key as "ctry_key",
    ctry_nm as "ctry_nm",
    store_type as "store_type",
    prod_hier_lvl2 as "prod_hier_lvl2",
    prod_hier_lvl4 as "prod_hier_lvl4",
    target_type as "target_type",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt",
    amt_obj_crncy as "amt_obj_crncy",
    target_amt as "target_amt",
    total_working_days as "total_working_days",
    working_days_elapsed as "working_days_elapsed"
    from ntaedw_integration.v_rpt_nts_vs_tgt
;
create or replace view V_RPT_ONPACK(
	"fisc_yr",
	"fisc_mo",
	"ctry_cd",
	"ctry_nm",
	"matl_num",
	"matl_desc",
	"mega_brnd_desc",
	"sls_grp",
	"sls_grp_desc",
	"channel",
	"store_type",
	"sales_office",
	"invoice_qty",
	"target_qty",
	"curr_inventory_qty",
	"bonus_desc"
) as
    select
    fisc_yr as "fisc_yr",
    fisc_mo as "fisc_mo",
    ctry_cd as "ctry_cd",
    ctry_nm as "ctry_nm",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    mega_brnd_desc as "mega_brnd_desc",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    channel as "channel",
    store_type as "store_type",
    sales_office as "sales_office",
    invoice_qty as "invoice_qty",
    target_qty as "target_qty",
    curr_inventory_qty as "curr_inventory_qty",
    bonus_desc as "bonus_desc"
    from ntaedw_integration.v_rpt_onpack
;
create or replace view V_RPT_POS_COSTCO_INVENTORY(
	"pos_dt",
	"fisc_per",
	"fisc_wk",
	"fisc_wk_strt_dt",
	"fisc_wk_end_dt",
	"univ_per",
	"univ_wk",
	"univ_wk_strt_dt",
	"univ_wk_end_dt",
	"invnt_qty",
	"invnt_amt",
	"str_cd",
	"str_nm",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"my_sls_brand_nm",
	"mysls_catg",
	"vend_prod_cd",
	"matl_num",
	"matl_desc",
	"ean_num",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"channel",
	"store_typ",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"price",
	"lcl_prod_nm"
) as
    select
    pos_dt as "pos_dt",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_strt_dt as "fisc_wk_strt_dt",
    fisc_wk_end_dt as "fisc_wk_end_dt",
    univ_per as "univ_per",
    univ_wk as "univ_wk",
    univ_wk_strt_dt as "univ_wk_strt_dt",
    univ_wk_end_dt as "univ_wk_end_dt",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    str_cd as "str_cd",
    str_nm as "str_nm",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    my_sls_brand_nm as "my_sls_brand_nm",
    mysls_catg as "mysls_catg",
    vend_prod_cd as "vend_prod_cd",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    ean_num as "ean_num",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    channel as "channel",
    store_typ as "store_typ",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    price as "price",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_costco_inventory
;
create or replace view V_RPT_POS_NONKOREA(
	"fisc_per",
	"fisc_wk",
	"fisc_wk_num",
	"max_wk_flg",
	"curr_month_ind",
	"sls_qty",
	"sls_amt_customer",
	"invnt_qty",
	"invnt_amt",
	"sls_amt",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"store_typ",
	"my_sls_brand_nm",
	"channel",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"ean_num",
	"str_cd",
	"str_nm",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"lcl_prod_nm"
) as
    select
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_num as "fisc_wk_num",
    max_wk_flg as "max_wk_flg",
    curr_month_ind as "curr_month_ind",
    sls_qty as "sls_qty",
    sls_amt_customer as "sls_amt_customer",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_amt as "sls_amt",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    store_typ as "store_typ",
    my_sls_brand_nm as "my_sls_brand_nm",
    channel as "channel",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    ean_num as "ean_num",
    str_cd as "str_cd",
    str_nm as "str_nm",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_nonkorea
;
create or replace view V_RPT_POS_OFFTAKE_DAILY_KOREA(
	"pos_dt",
	"fisc_per",
	"fisc_wk",
	"fisc_wk_strt_dt",
	"fisc_wk_end_dt",
	"univ_per",
	"univ_wk",
	"univ_wk_strt_dt",
	"univ_wk_end_dt",
	"univ_week_month",
	"univ_wk_month_strt_dt",
	"univ_wk_month_end_dt",
	"sls_qty",
	"sls_amt_customer",
	"invnt_qty",
	"invnt_amt",
	"sls_amt",
	"str_cd",
	"str_nm",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"my_sls_brand_nm",
	"mysls_catg",
	"vend_prod_cd",
	"matl_num",
	"matl_desc",
	"ean_num",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"channel",
	"store_typ",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"price",
	"lcl_prod_nm"
) as
    select
    pos_dt as "pos_dt",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_strt_dt as "fisc_wk_strt_dt",
    fisc_wk_end_dt as "fisc_wk_end_dt",
    univ_per as "univ_per",
    univ_wk as "univ_wk",
    univ_wk_strt_dt as "univ_wk_strt_dt",
    univ_wk_end_dt as "univ_wk_end_dt",
    univ_week_month as "univ_week_month",
    univ_wk_month_strt_dt as "univ_wk_month_strt_dt",
    univ_wk_month_end_dt as "univ_wk_month_end_dt",
    sls_qty as "sls_qty",
    sls_amt_customer as "sls_amt_customer",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_amt as "sls_amt",
    str_cd as "str_cd",
    str_nm as "str_nm",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    my_sls_brand_nm as "my_sls_brand_nm",
    mysls_catg as "mysls_catg",
    vend_prod_cd as "vend_prod_cd",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    ean_num as "ean_num",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    channel as "channel",
    store_typ as "store_typ",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    price as "price",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_offtake_daily_korea
;
create or replace view V_RPT_POS_OFFTAKE_DAILY_NONKOREA(
	"pos_dt",
	"fisc_per",
	"fisc_wk",
	"fisc_wk_strt_dt",
	"fisc_wk_end_dt",
	"promo_per",
	"promo_wk",
	"promo_wk_strt_dt",
	"promo_wk_end_dt",
	"univ_per",
	"univ_wk",
	"univ_wk_strt_dt",
	"univ_wk_end_dt",
	"sls_qty",
	"sls_amt_customer",
	"invnt_qty",
	"invnt_amt",
	"sls_amt",
	"str_cd",
	"str_nm",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"my_sls_brand_nm",
	"mysls_catg",
	"vend_prod_cd",
	"matl_num",
	"matl_desc",
	"ean_num",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"channel",
	"store_typ",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"price",
	"lcl_prod_nm"
) as
    select
    pos_dt as "pos_dt",
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_strt_dt as "fisc_wk_strt_dt",
    fisc_wk_end_dt as "fisc_wk_end_dt",
    promo_per as "promo_per",
    promo_wk as "promo_wk",
    promo_wk_strt_dt as "promo_wk_strt_dt",
    promo_wk_end_dt as "promo_wk_end_dt",
    univ_per as "univ_per",
    univ_wk as "univ_wk",
    univ_wk_strt_dt as "univ_wk_strt_dt",
    univ_wk_end_dt as "univ_wk_end_dt",
    sls_qty as "sls_qty",
    sls_amt_customer as "sls_amt_customer",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_amt as "sls_amt",
    str_cd as "str_cd",
    str_nm as "str_nm",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    my_sls_brand_nm as "my_sls_brand_nm",
    mysls_catg as "mysls_catg",
    vend_prod_cd as "vend_prod_cd",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    ean_num as "ean_num",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    channel as "channel",
    store_typ as "store_typ",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    price as "price",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_offtake_daily_nonkorea
;
create or replace view V_RPT_POS_OFFTAKE_WKLY_KOREA(
	"fisc_per",
	"fisc_wk",
	"fisc_wk_strt_dt",
	"fisc_wk_end_dt",
	"univ_per",
	"univ_wk",
	"univ_wk_strt_dt",
	"univ_wk_end_dt",
	"univ_week_month",
	"univ_wk_month_strt_dt",
	"univ_wk_month_end_dt",
	"sls_qty",
	"sls_amt_customer",
	"invnt_qty",
	"invnt_amt",
	"sls_amt",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"ean_num",
	"str_cd",
	"str_nm",
	"store_typ",
	"my_sls_brand_nm",
	"mysls_catg",
	"vend_prod_cd",
	"matl_num",
	"matl_desc",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"channel",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"price",
	"lcl_prod_nm"
) as
    select
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_strt_dt as "fisc_wk_strt_dt",
    fisc_wk_end_dt as "fisc_wk_end_dt",
    univ_per as "univ_per",
    univ_wk as "univ_wk",
    univ_wk_strt_dt as "univ_wk_strt_dt",
    univ_wk_end_dt as "univ_wk_end_dt",
    univ_week_month as "univ_week_month",
    univ_wk_month_strt_dt as "univ_wk_month_strt_dt",
    univ_wk_month_end_dt as "univ_wk_month_end_dt",
    sls_qty as "sls_qty",
    sls_amt_customer as "sls_amt_customer",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_amt as "sls_amt",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    ean_num as "ean_num",
    str_cd as "str_cd",
    str_nm as "str_nm",
    store_typ as "store_typ",
    my_sls_brand_nm as "my_sls_brand_nm",
    mysls_catg as "mysls_catg",
    vend_prod_cd as "vend_prod_cd",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    channel as "channel",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    price as "price",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_offtake_wkly_korea
;
create or replace view V_RPT_POS_OFFTAKE_WKLY_NONKOREA(
	"fisc_per",
	"fisc_wk",
	"fisc_wk_strt_dt",
	"fisc_wk_end_dt",
	"promo_per",
	"promo_wk",
	"promo_wk_strt_dt",
	"promo_wk_end_dt",
	"univ_per",
	"univ_wk",
	"univ_wk_strt_dt",
	"univ_wk_end_dt",
	"sls_qty",
	"sls_amt_customer",
	"invnt_qty",
	"invnt_amt",
	"sls_amt",
	"crncy_cd",
	"src_sys_cd",
	"ctry_nm",
	"sls_grp",
	"sls_grp_cd",
	"sold_to_party",
	"ean_num",
	"str_cd",
	"str_nm",
	"store_typ",
	"my_sls_brand_nm",
	"mysls_catg",
	"vend_prod_cd",
	"matl_num",
	"matl_desc",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"channel",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"price",
	"lcl_prod_nm"
) as
    select
    fisc_per as "fisc_per",
    fisc_wk as "fisc_wk",
    fisc_wk_strt_dt as "fisc_wk_strt_dt",
    fisc_wk_end_dt as "fisc_wk_end_dt",
    promo_per as "promo_per",
    promo_wk as "promo_wk",
    promo_wk_strt_dt as "promo_wk_strt_dt",
    promo_wk_end_dt as "promo_wk_end_dt",
    univ_per as "univ_per",
    univ_wk as "univ_wk",
    univ_wk_strt_dt as "univ_wk_strt_dt",
    univ_wk_end_dt as "univ_wk_end_dt",
    sls_qty as "sls_qty",
    sls_amt_customer as "sls_amt_customer",
    invnt_qty as "invnt_qty",
    invnt_amt as "invnt_amt",
    sls_amt as "sls_amt",
    crncy_cd as "crncy_cd",
    src_sys_cd as "src_sys_cd",
    ctry_nm as "ctry_nm",
    sls_grp as "sls_grp",
    sls_grp_cd as "sls_grp_cd",
    sold_to_party as "sold_to_party",
    ean_num as "ean_num",
    str_cd as "str_cd",
    str_nm as "str_nm",
    store_typ as "store_typ",
    my_sls_brand_nm as "my_sls_brand_nm",
    mysls_catg as "mysls_catg",
    vend_prod_cd as "vend_prod_cd",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    channel as "channel",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    price as "price",
    lcl_prod_nm as "lcl_prod_nm"
    from ntaedw_integration.v_rpt_pos_offtake_wkly_nonkorea
;
create or replace view V_RPT_SLS_COPA_TGT(
	"co_cd",
	"cust_num",
	"ctry_nm",
	"ctry_key",
	"sls_grp",
	"rgn",
	"fisc_yr_per",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"amt_obj_crncy",
	"obj_crncy_co_obj",
	"sls_trgt",
	"cust_sls_grp",
	"sls_grp_desc",
	"cust_sls_ofc",
	"sls_ofc_desc",
	"channel",
	"edw_cust_nm",
	"acct_hier_desc",
	"acct_hier_shrt_desc",
	"company_nm"
) as
    select
    co_cd as "co_cd",
    cust_num as "cust_num",
    ctry_nm as "ctry_nm",
    ctry_key as "ctry_key",
    sls_grp as "sls_grp",
    rgn as "rgn",
    fisc_yr_per as "fisc_yr_per",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    amt_obj_crncy as "amt_obj_crncy",
    obj_crncy_co_obj as "obj_crncy_co_obj",
    sls_trgt as "sls_trgt",
    cust_sls_grp as "cust_sls_grp",
    sls_grp_desc as "sls_grp_desc",
    cust_sls_ofc as "cust_sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    channel as "channel",
    edw_cust_nm as "edw_cust_nm",
    acct_hier_desc as "acct_hier_desc",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    company_nm as "company_nm"
    from ntaedw_integration.v_rpt_sls_copa_tgt
;
create or replace view V_RPT_SLS_PLN_ACTL(
	"ctry_nm",
	"cust_num",
	"cust_nm",
	"matl_num",
	"matl_desc",
	"mega_brnd_desc",
	"brnd_desc",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"cust_hier_l1",
	"cust_hier_l2",
	"cust_hier_l3",
	"cust_hier_l4",
	"cust_hier_l5",
	"sls_grp",
	"sls_ofc_desc",
	"channel",
	"store_type",
	"fisc_yr_per",
	"acct_hier_shrt_desc",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"copa_val",
	"net_bill_val",
	"ord_qty_pc",
	"rf_total",
	"bp_total",
	"le_total",
	"timegone"
) as
    select
    ctry_nm as "ctry_nm",
    cust_num as "cust_num",
    cust_nm as "cust_nm",
    matl_num as "matl_num",
    matl_desc as "matl_desc",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_desc as "brnd_desc",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    cust_hier_l1 as "cust_hier_l1",
    cust_hier_l2 as "cust_hier_l2",
    cust_hier_l3 as "cust_hier_l3",
    cust_hier_l4 as "cust_hier_l4",
    cust_hier_l5 as "cust_hier_l5",
    sls_grp as "sls_grp",
    sls_ofc_desc as "sls_ofc_desc",
    channel as "channel",
    store_type as "store_type",
    fisc_yr_per as "fisc_yr_per",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    copa_val as "copa_val",
    net_bill_val as "net_bill_val",
    ord_qty_pc as "ord_qty_pc",
    rf_total as "rf_total",
    bp_total as "bp_total",
    le_total as "le_total",
    timegone as "timegone"
    from ntaedw_integration.v_rpt_sls_pln_actl
;
create or replace view V_RPT_SLS_PLN_ACTL_LST_TXN_DT(
	"country",
	"last_txn_dt"
) as
    select
    country as "country",
    last_txn_dt as "last_txn_dt"
    from ntaedw_integration.v_rpt_sls_pln_actl_lst_txn_dt
;
create or replace view V_RPT_TPFGSUMMARY(
	"identifier",
	"cntry_key",
	"cust_num",
	"channel",
	"prft_ctr",
	"matl",
	"matl_desc",
	"mega_brnd_desc",
	"brnd_desc",
	"franchise",
	"prod_minor",
	"sls_grp",
	"sls_grp_desc",
	"sls_ofc",
	"sls_ofc_desc",
	"category_1",
	"categroy_2",
	"platform_ca",
	"amt_obj_crncy",
	"obj_crncy_co_obj",
	"edw_cust_nm",
	"from_crncy",
	"to_crncy",
	"ex_rt_typ",
	"ex_rt",
	"brand_group",
	"fisc_day",
	"fisc_yr_per",
	"qty",
	"units_sold",
	"uom",
	"acct_hier_desc",
	"acct_hier_shrt_desc",
	"cntry_cd",
	"company_nm",
	"fert_flag",
	"store_type",
	"free_good_value",
	"pre_apsc_cogs",
	"package_cost",
	"labour_cost",
	"valuation_class",
	"target_type",
	"target_value",
	"target_amount"
) as
    select
    identifier as "identifier",
    cntry_key as "cntry_key",
    cust_num as "cust_num",
    channel as "channel",
    prft_ctr as "prft_ctr",
    matl as "matl",
    matl_desc as "matl_desc",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_desc as "brnd_desc",
    franchise as "franchise",
    prod_minor as "prod_minor",
    sls_grp as "sls_grp",
    sls_grp_desc as "sls_grp_desc",
    sls_ofc as "sls_ofc",
    sls_ofc_desc as "sls_ofc_desc",
    category_1 as "category_1",
    categroy_2 as "categroy_2",
    platform_ca as "platform_ca",
    amt_obj_crncy as "amt_obj_crncy",
    obj_crncy_co_obj as "obj_crncy_co_obj",
    edw_cust_nm as "edw_cust_nm",
    from_crncy as "from_crncy",
    to_crncy as "to_crncy",
    ex_rt_typ as "ex_rt_typ",
    ex_rt as "ex_rt",
    brand_group as "brand_group",
    fisc_day as "fisc_day",
    fisc_yr_per as "fisc_yr_per",
    qty as "qty",
    units_sold as "units_sold",
    uom as "uom",
    acct_hier_desc as "acct_hier_desc",
    acct_hier_shrt_desc as "acct_hier_shrt_desc",
    cntry_cd as "cntry_cd",
    company_nm as "company_nm",
    fert_flag as "fert_flag",
    store_type as "store_type",
    free_good_value as "free_good_value",
    pre_apsc_cogs as "pre_apsc_cogs",
    package_cost as "package_cost",
    labour_cost as "labour_cost",
    valuation_class as "valuation_class",
    target_type as "target_type",
    target_value as "target_value",
    target_amount as "target_amount"
    from ntaedw_integration.v_rpt_tpfgsummary
;
create or replace view V_RPT_TW_SI_SO_POS_SLS(
	"data_set",
	"fisc_per",
	"fisc_yr",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"sap_matl_num",
	"channel",
	"sls_grp",
	"strategy_customer_hierachy_name",
	"to_crncy",
	"ex_rt",
	"ean_num",
	"sls_amt",
	"sls_return_amt",
	"sls_qty",
	"sls_amt_l3m",
	"sls_return_amt_13m",
	"sls_qty_l3m",
	"sls_amt_l6m",
	"sls_return_amt_l6m",
	"sls_qty_l6m",
	"rf_amount_si",
	"rf_qty_si",
	"rf_amount_so",
	"rf_qty_so",
	"rf_amount_si_l2m",
	"rf_qty_si_l2m",
	"rf_amount_so_l2m",
	"rf_qty_so_l2m"
) as
    select
    data_set as "data_set",
    fisc_per as "fisc_per",
    fisc_yr as "fisc_yr",
    prod_hier_l1 as "prod_hier_l1",
    prod_hier_l2 as "prod_hier_l2",
    prod_hier_l3 as "prod_hier_l3",
    prod_hier_l4 as "prod_hier_l4",
    prod_hier_l5 as "prod_hier_l5",
    prod_hier_l6 as "prod_hier_l6",
    prod_hier_l7 as "prod_hier_l7",
    prod_hier_l8 as "prod_hier_l8",
    prod_hier_l9 as "prod_hier_l9",
    sap_matl_num as "sap_matl_num",
    channel as "channel",
    sls_grp as "sls_grp",
    strategy_customer_hierachy_name as "strategy_customer_hierachy_name",
    to_crncy as "to_crncy",
    ex_rt as "ex_rt",
    ean_num as "ean_num",
    sls_amt as "sls_amt",
    sls_return_amt as "sls_return_amt",
    sls_qty as "sls_qty",
    sls_amt_l3m as "sls_amt_l3m",
    sls_return_amt_13m as "sls_return_amt_13m",
    sls_qty_l3m as "sls_qty_l3m",
    sls_amt_l6m as "sls_amt_l6m",
    sls_return_amt_l6m as "sls_return_amt_l6m",
    sls_qty_l6m as "sls_qty_l6m",
    rf_amount_si as "rf_amount_si",
    rf_qty_si as "rf_qty_si",
    rf_amount_so as "rf_amount_so",
    rf_qty_so as "rf_qty_so",
    rf_amount_si_l2m as "rf_amount_si_l2m",
    rf_qty_si_l2m as "rf_qty_si_l2m",
    rf_amount_so_l2m as "rf_amount_so_l2m",
    rf_qty_so_l2m as "rf_qty_so_l2m"
    from ntaedw_integration.v_rpt_tw_si_so_pos_sls
;
create or replace view V_SLSC_TGTG_ITEMS_CUST_TASK_SRRESP_CUSTOMER(
	"salescampaignid",
	"salescampaignname",
	"salescampaigndescription",
	"salescampaignstartdt",
	"salescampaignenddt",
	"targetgroupid",
	"target",
	"customerid",
	"cust_remotekey",
	"customername",
	"country",
	"storetype",
	"channel",
	"salesgroup",
	"soldtoparty",
	"mastertaskid",
	"text",
	"type",
	"validfrom",
	"validto",
	"mastertaskstartdt",
	"mastertaskenddt",
	"taskid",
	"salespersonid",
	"surveyresponseid",
	"taskstartdt",
	"taskenddt",
	"status",
	"visitid",
	"businessunitid",
	"mastersurveyid",
	"enddate",
	"endtime",
	"questionkey",
	"questiontext",
	"valuekey",
	"value",
	"mastersurveyname",
	"mastersurveydescription",
	"remotekey",
	"title",
	"salespersonname",
	"flag"
) as
    select
    salescampaignid as "salescampaignid",
    salescampaignname as "salescampaignname",
    salescampaigndescription as "salescampaigndescription",
    salescampaignstartdt as "salescampaignstartdt",
    salescampaignenddt as "salescampaignenddt",
    targetgroupid as "targetgroupid",
    target as "target",
    customerid as "customerid",
    cust_remotekey as "cust_remotekey",
    customername as "customername",
    country as "country",
    storetype as "storetype",
    channel as "channel",
    salesgroup as "salesgroup",
    soldtoparty as "soldtoparty",
    mastertaskid as "mastertaskid",
    text as "text",
    type as "type",
    validfrom as "validfrom",
    validto as "validto",
    mastertaskstartdt as "mastertaskstartdt",
    mastertaskenddt as "mastertaskenddt",
    taskid as "taskid",
    salespersonid as "salespersonid",
    surveyresponseid as "surveyresponseid",
    taskstartdt as "taskstartdt",
    taskenddt as "taskenddt",
    status as "status",
    visitid as "visitid",
    businessunitid as "businessunitid",
    mastersurveyid as "mastersurveyid",
    enddate as "enddate",
    endtime as "endtime",
    questionkey as "questionkey",
    questiontext as "questiontext",
    valuekey as "valuekey",
    value as "value",
    mastersurveyname as "mastersurveyname",
    mastersurveydescription as "mastersurveydescription",
    remotekey as "remotekey",
    title as "title",
    salespersonname as "salespersonname",
    flag as "flag"
    from ntaedw_integration.v_slsc_tgtg_items_cust_task_srresp_customer
;
