insert into PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS 
(COUNTRY_CODE ,PARAMETER_NAME,PARAMETER_VALUE) values 
(
'AU','NON_PRIORITY_STORES','SEDENIOJAY'
);

insert into PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS 
(COUNTRY_CODE ,PARAMETER_NAME,PARAMETER_VALUE) values 
(
'AU','NON_PRIORITY_STORES','EBRAHIMYOSRA'
)
