create or replace TABLE PROD_DNA_CORE.CHNITG_INTEGRATION.ITG_MDS_CN_OTC_PRODUCT_MAPPING (
	NAME VARCHAR(500),
	CODE VARCHAR(500),
	XJP_CODE VARCHAR(200),
	JNTL_CODE VARCHAR(200),
	BRAND_CODE VARCHAR(200),
	BRAND_CN VARCHAR(200),
	BRAND_EN VARCHAR(200),
	STATUS VARCHAR(200),
	PRODUCT_NAME_CN VARCHAR(200),
	PRODUCT_NAME_EN VARCHAR(200)
);

create or replace TABLE PROD_DNA_CORE.CHNITG_INTEGRATION.ITG_CS_RE_STORE (
	STORE_CODE VARCHAR(50),
	STORE_NAME VARCHAR(250),
	REGION VARCHAR(50),
	STORE_TYPE VARCHAR(50),
	CHANNEL VARCHAR(50),
	DISTRIBUTOR_CODE VARCHAR(50),
	DISTRIBUTOR_NAME VARCHAR(50),
	PRODUCT_CODE VARCHAR(100),
	PRODUCT_DESC VARCHAR(500),
	ZONE VARCHAR(50)
);
