create or replace TABLE PROD_DNA_CORE.ASPEDW_INTEGRATION.EDW_OTIF_CONSUMER_ATTR (
	REGION VARCHAR(765),
	RGN_MKT_CD VARCHAR(765),
	FISCAL_YR_MO VARCHAR(500),
	SEGMENT_INFORMATION VARCHAR(500),
	NUMERATOR NUMBER(38,2),
	DENOMINATOR NUMBER(38,2),
	OTIF NUMBER(38,8)
);
