create or replace TABLE PROD_DNA_CORE.JPNEDW_INTEGRATION.JP_INV_COVERAGE_AREA_REGION_MAPPING (
	JIS_CD VARCHAR(20),
	PREFECTURE_NAME VARCHAR(50),
	PREFECTURE_NAME_KANA VARCHAR(50),
	PREFECTURE_NAME_ENG VARCHAR(100),
	REGION VARCHAR(100)
);
