create or replace TABLE PROD_DNA_CORE.CHNEDW_INTEGRATION.EDW_PERFECT_STORE_PRODUCT_MASTER (
	PRODUCT_CODE VARCHAR(50),
	PRODUCT_NAME_CN VARCHAR(500),
	PRODUCT_NAME_EN VARCHAR(100),
	CATEGORY_CN VARCHAR(50),
	CATEGORY_EN VARCHAR(50),
	CATEGORY VARCHAR(20),
	BRAND VARCHAR(20),
	PACKING VARCHAR(10),
	SALES_CATEGORY_CODE VARCHAR(20),
	SALES_CATEGORY_LEVEL2 VARCHAR(100),
	SALES_CATEGORY_LEVEL3 VARCHAR(100),
	UPC VARCHAR(20),
	STATUS VARCHAR(10),
	LAYER2 VARCHAR(200),
	LAYER3 VARCHAR(200),
	INSERT_DATE TIMESTAMP_NTZ(9),
	UPDATE_DATE TIMESTAMP_NTZ(9)
);
