DELETE FROM PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_SLS_EVOLUTION WHERE (SNAPSHOT_DATE)='2024-08-02'

DELETE  FROM PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_SLS_EVOLUTION_HISTORY WHERE (SNAPSHOT_DATE)='2024-08-02'
