USE Schema VNMEDW_INTEGRATION;
create or replace TABLE EDW_VN_MT_OFFTAKE_EXCEPTION_REPORT (
	ACCOUNT VARCHAR(13),
	MONTH_ID VARCHAR(23),
	PRODUCT_CD VARCHAR(100),
	CUSTOMER_CD VARCHAR(200),
	STORE_NAME VARCHAR(255),
	BARCODE VARCHAR(200),
	PRODUCT_NAME VARCHAR(1125),
	FRANCHISE VARCHAR(1687),
	CATEGORY VARCHAR(1687),
	SUB_BRAND VARCHAR(1350),
	SUB_CATEGORY VARCHAR(1687),
	AMOUNT NUMBER(38,9),
	AMOUNT_USD NUMBER(38,14)
);
create or replace TABLE EDW_VN_MT_SELLIN_EXCEPTION (
	DATA_SOURCE VARCHAR(6),
	DATA_TYPE VARCHAR(7),
	MNTH_ID VARCHAR(23),
	PRODUCTID VARCHAR(50),
	PRODUCT_NAME VARCHAR(500),
	BARCODE VARCHAR(40),
	CUSTCODE VARCHAR(200),
	NAME VARCHAR(500),
	SUB_CHANNEL VARCHAR(1125),
	REGION VARCHAR(1125),
	PROVINCE VARCHAR(1125),
	KAM VARCHAR(450),
	RETAIL_ENVIRONMENT VARCHAR(450),
	GROUP_ACCOUNT VARCHAR(1125),
	ACCOUNT VARCHAR(1125),
	FRANCHISE VARCHAR(1125),
	CATEGORY VARCHAR(1125),
	SUB_CATEGORY VARCHAR(1125),
	SUB_BRAND VARCHAR(900),
	SALES_AMT_LCY NUMBER(38,5),
	SALES_AMT_USD NUMBER(38,10),
	TARGET_LCY NUMBER(28,10),
	TARGET_USD NUMBER(28,10)
);
create or replace TABLE EDW_VN_MT_SELLIN_SELLOUT_ANALYSIS (
	DATA_SOURCE VARCHAR(6),
	DATA_TYPE VARCHAR(7),
	INVOICE_DATE VARCHAR(20),
	YEAR NUMBER(18,0),
	QRTR_NO NUMBER(18,0),
	QRTR VARCHAR(14),
	MNTH_ID VARCHAR(23),
	MNTH_DESC VARCHAR(15),
	MNTH_NO NUMBER(18,0),
	MNTH_SHRT VARCHAR(3),
	MNTH_LONG VARCHAR(9),
	WK NUMBER(38,0),
	MNTH_WK_NO NUMBER(38,0),
	CAL_YEAR NUMBER(18,0),
	CAL_QRTR_NO NUMBER(18,0),
	CAL_MNTH_ID NUMBER(18,0),
	CAL_MNTH_NO NUMBER(18,0),
	CAL_MNTH_NM VARCHAR(9),
	CAL_DATE DATE,
	CAL_DATE_ID VARCHAR(52),
	SUPPLIER_CODE VARCHAR(10),
	SUPPLIER_NAME VARCHAR(100),
	PLANT VARCHAR(10),
	PRODUCTID VARCHAR(100),
	PRODUCT_NAME VARCHAR(1125),
	BARCODE VARCHAR(200),
	JNJ_SAP_CODE VARCHAR(40),
	FRANCHISE VARCHAR(1687),
	CATEGORY VARCHAR(1687),
	SUB_CATEGORY VARCHAR(1350),
	SUB_BRAND VARCHAR(1687),
	SIZE VARCHAR(400),
	CHANNEL VARCHAR(10),
	CUSTCODE VARCHAR(200),
	NAME VARCHAR(500),
	ADDRESS VARCHAR(300),
	SUB_CHANNEL VARCHAR(1125),
	GROUP_ACCOUNT VARCHAR(1125),
	ACCOUNT VARCHAR(1125),
	REGION VARCHAR(1125),
	PROVINCE VARCHAR(1125),
	RETAIL_ENVIRONMENT VARCHAR(450),
	DISTRICT VARCHAR(1),
	ZONE VARCHAR(20),
	PERIOD VARCHAR(20),
	SALES_SUPERVISOR VARCHAR(450),
	KAM VARCHAR(450),
	SALES_QTY NUMBER(38,4),
	SALES_AMT_LCY NUMBER(38,9),
	SALES_AMT_USD NUMBER(38,14),
	TARGET_LCY NUMBER(28,10),
	TARGET_USD NUMBER(28,10)
);
create or replace TABLE EDW_VN_ONEVIEW_RPT (
	DATA_TYPE VARCHAR(15),
	CHANNEL VARCHAR(20),
	SUB_CHANNEL VARCHAR(300),
	JJ_YEAR NUMBER(18,0),
	JJ_QRTR VARCHAR(14),
	JJ_MNTH_ID VARCHAR(23),
	JJ_MNTH_NO NUMBER(18,0),
	JJ_MNTH_WK_NO NUMBER(38,0),
	JJ_MNTH_DAY NUMBER(38,0),
	MAPPED_SPK VARCHAR(100),
	DSTRBTR_GRP_CD VARCHAR(100),
	DSTRBTR_NAME VARCHAR(100),
	SAP_SOLD_TO_CODE VARCHAR(50),
	SAP_MATL_NUM VARCHAR(100),
	SAP_MATL_NAME VARCHAR(100),
	DSTRBTR_MATL_NUM VARCHAR(100),
	DSTRBTR_MATL_NAME VARCHAR(500),
	BAR_CODE VARCHAR(40),
	CUSTOMER_CODE VARCHAR(100),
	CUSTOMER_NAME VARCHAR(500),
	INVOICE_DATE DATE,
	SALESMAN VARCHAR(50),
	SALESMAN_NAME VARCHAR(100),
	SI_GTS_VAL NUMBER(38,10),
	SI_GTS_EXCL_DM_VAL NUMBER(38,10),
	SI_NTS_VAL NUMBER(38,10),
	SI_MNTH_TGT_BY_SKU FLOAT,
	SO_NET_TRD_SLS_LOC NUMBER(38,5),
	SO_NET_TRD_SLS_USD NUMBER(38,10),
	SO_MNTH_TGT NUMBER(38,10),
	SO_AVG_WK_TGT NUMBER(28,6),
	SO_MNTH_TGT_BY_SKU FLOAT,
	ZONE_MANAGER_ID VARCHAR(100),
	ZONE_MANAGER_NAME VARCHAR(450),
	ZONE VARCHAR(20),
	PROVINCE VARCHAR(1125),
	REGION VARCHAR(1125),
	SHOP_TYPE VARCHAR(100),
	MT_SUB_CHANNEL VARCHAR(1125),
	RETAIL_ENVIRONMENT VARCHAR(450),
	GROUP_ACCOUNT VARCHAR(1125),
	ACCOUNT VARCHAR(1125),
	FRANCHISE VARCHAR(30),
	BRAND VARCHAR(83),
	VARIANT VARCHAR(100),
	PRODUCT_GROUP VARCHAR(255),
	GROUP_JB VARCHAR(6)
);
create or replace TABLE EDW_VN_SI_ST_SO_DETAILS (
	JJ_YEAR NUMBER(18,0),
	JJ_QRTR VARCHAR(14),
	JJ_MNTH_ID VARCHAR(23),
	JJ_MNTH_NO NUMBER(18,0),
	JJ_MNTH_WK_NO NUMBER(38,0),
	WKS_IN_QRTR NUMBER(38,0),
	MNTH_START_DATE DATE,
	MNTH_END_DATE DATE,
	TERRITORY_DIST VARCHAR(100),
	DISTRIBUTOR_ID_REPORT VARCHAR(100),
	DSTRBTR_GRP_CD VARCHAR(100),
	DSTRBTR_NAME VARCHAR(100),
	SAP_SOLD_TO_CODE VARCHAR(50),
	SAP_MATL_NUM VARCHAR(50),
	SAP_MATL_NAME VARCHAR(100),
	DSTRBTR_MATL_NUM VARCHAR(100),
	DSTRBTR_MATL_NAME VARCHAR(100),
	CUST_CD VARCHAR(100),
	TRADE_TYPE VARCHAR(13),
	BILL_DOC VARCHAR(30),
	BILL_DATE DATE,
	EXCHG_RATE NUMBER(9,5),
	SLSMN_CD VARCHAR(50),
	SLSMN_NM VARCHAR(100),
	SLSMN_STATUS VARCHAR(1),
	SO_SLS_QTY NUMBER(22,4),
	SO_RET_QTY NUMBER(22,4),
	SO_GRS_TRD_SLS NUMBER(22,4),
	SO_NET_TRD_SLS NUMBER(22,4),
	SO_AVG_WK_TGT NUMBER(28,6),
	SO_MNTH_TGT NUMBER(24,6),
	SUPERVISOR_CODE VARCHAR(50),
	SUPERVISOR_NAME VARCHAR(100),
	ASM_ID VARCHAR(100),
	ASM_NAME VARCHAR(200),
	DSTRB_REGION VARCHAR(20),
	OUTLET_NAME VARCHAR(100),
	SHOP_TYPE VARCHAR(100),
	GROUP_HIERARCHY VARCHAR(100),
	TOP_DOOR_GROUP VARCHAR(100),
	TOP_DOOR_FLAG VARCHAR(1),
	TOP_DOOR_TARGET NUMBER(20,2),
	SI_SLS_QTY NUMBER(38,4),
	SI_RET_QTY NUMBER(38,4),
	SI_GTS_VAL NUMBER(38,4),
	SI_NTS_VAL NUMBER(38,4),
	SI_MNTH_TGT NUMBER(22,4),
	SI_AVG_WK_TGT NUMBER(25,4),
	ST_SLS_QTY NUMBER(20,2),
	ST_RET_QTY NUMBER(20,2),
	ST_GRS_TRD_SLS NUMBER(22,4),
	ST_NET_TRD_SLS NUMBER(22,4),
	ST_MNTH_TGT NUMBER(22,4),
	ST_AVG_WK_TGT NUMBER(25,4),
	PC_TARGET NUMBER(22,4),
	PC_TARGET_BY_WEEK NUMBER(22,4),
	CE_TARGET NUMBER(22,4),
	CE_TARGET_BY_WEEK NUMBER(22,4),
	UB_WEEKLY_TARGET NUMBER(38,24),
	VISIT_CALL_DATE DATE,
	PRODUCT_VISIT_CALL_DATE DATE,
	FORECASTSO_MIL NUMBER(23,4),
	CNTRY_NM VARCHAR(40),
	SAP_STATE_CD VARCHAR(150),
	SAP_SLS_ORG VARCHAR(4),
	SAP_CMP_ID VARCHAR(6),
	SAP_CNTRY_CD VARCHAR(3),
	SAP_CNTRY_NM VARCHAR(40),
	SAP_ADDR VARCHAR(150),
	SAP_REGION VARCHAR(150),
	SAP_CITY VARCHAR(150),
	SAP_POST_CD VARCHAR(150),
	SAP_CHNL_CD VARCHAR(2),
	SAP_CHNL_DESC VARCHAR(20),
	SAP_SLS_OFFICE_CD VARCHAR(4),
	SAP_SLS_OFFICE_DESC VARCHAR(40),
	SAP_SLS_GRP_CD VARCHAR(3),
	SAP_SLS_GRP_DESC VARCHAR(40),
	SAP_CURR_CD VARCHAR(5),
	GCH_REGION VARCHAR(50),
	GCH_CLUSTER VARCHAR(50),
	GCH_SUBCLUSTER VARCHAR(50),
	GCH_MARKET VARCHAR(50),
	GCH_RETAIL_BANNER VARCHAR(50),
	SKU VARCHAR(40),
	SKU_DESC VARCHAR(100),
	SAP_MAT_TYPE_CD VARCHAR(10),
	SAP_MAT_TYPE_DESC VARCHAR(40),
	SAP_BASE_UOM_CD VARCHAR(10),
	SAP_PRCHSE_UOM_CD VARCHAR(10),
	SAP_PROD_SGMT_CD VARCHAR(18),
	SAP_PROD_SGMT_DESC VARCHAR(100),
	SAP_BASE_PROD_CD VARCHAR(10),
	SAP_BASE_PROD_DESC VARCHAR(100),
	SAP_MEGA_BRND_CD VARCHAR(10),
	SAP_MEGA_BRND_DESC VARCHAR(100),
	SAP_BRND_CD VARCHAR(10),
	SAP_BRND_DESC VARCHAR(100),
	SAP_VRNT_CD VARCHAR(10),
	SAP_VRNT_DESC VARCHAR(100),
	SAP_PUT_UP_CD VARCHAR(10),
	SAP_PUT_UP_DESC VARCHAR(100),
	SAP_GRP_FRNCHSE_CD VARCHAR(18),
	SAP_GRP_FRNCHSE_DESC VARCHAR(100),
	SAP_FRNCHSE_CD VARCHAR(18),
	SAP_FRNCHSE_DESC VARCHAR(100),
	SAP_PROD_FRNCHSE_CD VARCHAR(18),
	SAP_PROD_FRNCHSE_DESC VARCHAR(100),
	SAP_PROD_MJR_CD VARCHAR(18),
	SAP_PROD_MJR_DESC VARCHAR(100),
	SAP_PROD_MNR_CD VARCHAR(18),
	SAP_PROD_MNR_DESC VARCHAR(100),
	SAP_PROD_HIER_CD VARCHAR(18),
	SAP_PROD_HIER_DESC VARCHAR(100),
	GLOBAL_MAT_REGION VARCHAR(50),
	GLOBAL_PROD_FRANCHISE VARCHAR(30),
	GLOBAL_PROD_BRAND VARCHAR(30),
	GLOBAL_PROD_VARIANT VARCHAR(100),
	GLOBAL_PROD_PUT_UP_CD VARCHAR(10),
	GLOBAL_PUT_UP_DESC VARCHAR(100),
	GLOBAL_PROD_SUB_BRAND VARCHAR(100),
	GLOBAL_PROD_NEED_STATE VARCHAR(50),
	GLOBAL_PROD_CATEGORY VARCHAR(50),
	GLOBAL_PROD_SUBCATEGORY VARCHAR(50),
	GLOBAL_PROD_SEGMENT VARCHAR(50),
	GLOBAL_PROD_SUBSEGMENT VARCHAR(100),
	GLOBAL_PROD_SIZE VARCHAR(20),
	GLOBAL_PROD_SIZE_UOM VARCHAR(20),
	LOCAL_PROD_FRANCHISE VARCHAR(100),
	LOCAL_PROD_BRAND VARCHAR(100),
	LOCAL_PROD_VARIANT VARCHAR(100),
	LOCAL_PROD_GRP VARCHAR(200),
	LOCAL_GROUP_JB VARCHAR(50),
	GROUPMSL VARCHAR(100),
	CURR_MNTH_INDC VARCHAR(1),
	CURR_YEAR_INDC VARCHAR(1)
);


use schema VNMEDW_ACCESS;
create or replace view EDW_VN_MT_OFFTAKE_EXCEPTION_REPORT(
	"sub_brand",
	"month_id",
	"category",
	"barcode",
	"amount_usd",
	"amount",
	"customer_cd",
	"franchise",
	"product_cd",
	"store_name",
	"product_name",
	"account"
) as
    SELECT 
    sub_brand AS "sub_brand",
    month_id AS "month_id",
    category AS "category",
    barcode AS "barcode",
    amount_usd AS "amount_usd",
    amount AS "amount",
    customer_cd AS "customer_cd",
    franchise AS "franchise",
    product_cd AS "product_cd",
    store_name AS "store_name",
    product_name AS "product_name",
    account AS "account"
FROM VNMEDW_INTEGRATION.EDW_VN_MT_OFFTAKE_EXCEPTION_REPORT;
create or replace view EDW_VN_MT_SELLIN_EXCEPTION(
	"data_type",
	"region",
	"sub_channel",
	"name",
	"sub_category",
	"sales_amt_lcy",
	"account",
	"barcode",
	"data_source",
	"sales_amt_usd",
	"target_lcy",
	"product_name",
	"custcode",
	"productid",
	"sub_brand",
	"group_account",
	"retail_environment",
	"province",
	"franchise",
	"target_usd",
	"kam",
	"mnth_id",
	"category"
) as
    SELECT 
    data_type AS "data_type",
    region AS "region",
    sub_channel AS "sub_channel",
    name AS "name",
    sub_category AS "sub_category",
    sales_amt_lcy AS "sales_amt_lcy",
    account AS "account",
    barcode AS "barcode",
    data_source AS "data_source",
    sales_amt_usd AS "sales_amt_usd",
    target_lcy AS "target_lcy",
    product_name AS "product_name",
    custcode AS "custcode",
    productid AS "productid",
    sub_brand AS "sub_brand",
    group_account AS "group_account",
    retail_environment AS "retail_environment",
    province AS "province",
    franchise AS "franchise",
    target_usd AS "target_usd",
    kam AS "kam",
    mnth_id AS "mnth_id",
    category AS "category"
FROM VNMEDW_INTEGRATION.EDW_VN_MT_SELLIN_EXCEPTION;
create or replace view EDW_VN_MT_SELLIN_SELLOUT_ANALYSIS(
	"custcode",
	"name",
	"data_type",
	"cal_year",
	"district",
	"franchise",
	"wk",
	"mnth_id",
	"mnth_desc",
	"target_usd",
	"cal_qrtr_no",
	"supplier_code",
	"jnj_sap_code",
	"channel",
	"size",
	"mnth_no",
	"productid",
	"kam",
	"sales_amt_usd",
	"qrtr_no",
	"year",
	"region",
	"address",
	"account",
	"mnth_wk_no",
	"cal_mnth_id",
	"qrtr",
	"sales_qty",
	"group_account",
	"sales_supervisor",
	"cal_date_id",
	"target_lcy",
	"mnth_long",
	"plant",
	"period",
	"sub_channel",
	"sub_category",
	"supplier_name",
	"cal_mnth_no",
	"mnth_shrt",
	"category",
	"retail_environment",
	"sales_amt_lcy",
	"invoice_date",
	"zone",
	"product_name",
	"cal_mnth_nm",
	"cal_date",
	"sub_brand",
	"province",
	"barcode",
	"data_source"
) as
    SELECT 
    custcode AS "custcode",
    name AS "name",
    data_type AS "data_type",
    cal_year AS "cal_year",
    district AS "district",
    franchise AS "franchise",
    wk AS "wk",
    mnth_id AS "mnth_id",
    mnth_desc AS "mnth_desc",
    target_usd AS "target_usd",
    cal_qrtr_no AS "cal_qrtr_no",
    supplier_code AS "supplier_code",
    jnj_sap_code AS "jnj_sap_code",
    channel AS "channel",
    size AS "size",
    mnth_no AS "mnth_no",
    productid AS "productid",
    kam AS "kam",
    sales_amt_usd AS "sales_amt_usd",
    qrtr_no AS "qrtr_no",
    year AS "year",
    region AS "region",
    address AS "address",
    account AS "account",
    mnth_wk_no AS "mnth_wk_no",
    cal_mnth_id AS "cal_mnth_id",
    qrtr AS "qrtr",
    sales_qty AS "sales_qty",
    group_account AS "group_account",
    sales_supervisor AS "sales_supervisor",
    cal_date_id AS "cal_date_id",
    target_lcy AS "target_lcy",
    mnth_long AS "mnth_long",
    plant AS "plant",
    period AS "period",
    sub_channel AS "sub_channel",
    sub_category AS "sub_category",
    supplier_name AS "supplier_name",
    cal_mnth_no AS "cal_mnth_no",
    mnth_shrt AS "mnth_shrt",
    category AS "category",
    retail_environment AS "retail_environment",
    sales_amt_lcy AS "sales_amt_lcy",
    invoice_date AS "invoice_date",
    zone AS "zone",
    product_name AS "product_name",
    cal_mnth_nm AS "cal_mnth_nm",
    cal_date AS "cal_date",
    sub_brand AS "sub_brand",
    province AS "province",
    barcode AS "barcode",
    data_source AS "data_source"
FROM VNMEDW_INTEGRATION.EDW_VN_MT_SELLIN_SELLOUT_ANALYSIS;
create or replace view EDW_VN_ONEVIEW_RPT(
	"sap_matl_name",
	"customer_code",
	"account",
	"customer_name",
	"jj_year",
	"dstrbtr_matl_num",
	"dstrbtr_matl_name",
	"zone_manager_name",
	"dstrbtr_name",
	"data_type",
	"sap_matl_num",
	"province",
	"mapped_spk",
	"si_gts_val",
	"bar_code",
	"so_mnth_tgt",
	"sap_sold_to_code",
	"retail_environment",
	"si_nts_val",
	"franchise",
	"group_account",
	"so_net_trd_sls_usd",
	"jj_mnth_id",
	"jj_qrtr",
	"so_avg_wk_tgt",
	"brand",
	"si_mnth_tgt_by_sku",
	"zone_manager_id",
	"shop_type",
	"channel",
	"si_gts_excl_dm_val",
	"invoice_date",
	"jj_mnth_no",
	"variant",
	"dstrbtr_grp_cd",
	"jj_mnth_wk_no",
	"sub_channel",
	"jj_mnth_day",
	"region",
	"product_group",
	"so_mnth_tgt_by_sku",
	"salesman",
	"zone",
	"so_net_trd_sls_loc",
	"salesman_name",
	"group_jb",
	"mt_sub_channel"
) as
    SELECT
    sap_matl_name AS "sap_matl_name",
    customer_code AS "customer_code",
    account AS "account",
    customer_name AS "customer_name",
    jj_year AS "jj_year",
    dstrbtr_matl_num AS "dstrbtr_matl_num",
    dstrbtr_matl_name AS "dstrbtr_matl_name",
    zone_manager_name AS "zone_manager_name",
    dstrbtr_name AS "dstrbtr_name",
    data_type AS "data_type",
    sap_matl_num AS "sap_matl_num",
    province AS "province",
    mapped_spk AS "mapped_spk",
    si_gts_val AS "si_gts_val",
    bar_code AS "bar_code",
    so_mnth_tgt AS "so_mnth_tgt",
    sap_sold_to_code AS "sap_sold_to_code",
    retail_environment AS "retail_environment",
    si_nts_val AS "si_nts_val",
    franchise AS "franchise",
    group_account AS "group_account",
    so_net_trd_sls_usd AS "so_net_trd_sls_usd",
    jj_mnth_id AS "jj_mnth_id",
    jj_qrtr AS "jj_qrtr",
    so_avg_wk_tgt AS "so_avg_wk_tgt",
    brand AS "brand",
    si_mnth_tgt_by_sku AS "si_mnth_tgt_by_sku",
    zone_manager_id AS "zone_manager_id",
    shop_type AS "shop_type",
    channel AS "channel",
    si_gts_excl_dm_val AS "si_gts_excl_dm_val",
    invoice_date AS "invoice_date",
    jj_mnth_no AS "jj_mnth_no",
    variant AS "variant",
    dstrbtr_grp_cd AS "dstrbtr_grp_cd",
    jj_mnth_wk_no AS "jj_mnth_wk_no",
    sub_channel AS "sub_channel",
    jj_mnth_day AS "jj_mnth_day",
    region AS "region",
    product_group AS "product_group",
    so_mnth_tgt_by_sku AS "so_mnth_tgt_by_sku",
    salesman AS "salesman",
    zone AS "zone",
    so_net_trd_sls_loc AS "so_net_trd_sls_loc",
    salesman_name AS "salesman_name",
    group_jb AS "group_jb",
    mt_sub_channel AS "mt_sub_channel"
FROM VNMEDW_INTEGRATION.EDW_VN_ONEVIEW_RPT;
create or replace view EDW_VN_SI_ST_SO_DETAILS(
	"sku_desc",
	"global_prod_franchise",
	"si_sls_qty",
	"curr_year_indc",
	"so_avg_wk_tgt",
	"supervisor_name",
	"sap_put_up_cd",
	"sap_put_up_desc",
	"sap_matl_num",
	"pc_target_by_week",
	"sap_cntry_cd",
	"sap_post_cd",
	"territory_dist",
	"si_mnth_tgt",
	"sap_chnl_cd",
	"global_prod_size",
	"sap_matl_name",
	"sap_mega_brnd_cd",
	"dstrbtr_matl_num",
	"sap_cntry_nm",
	"st_ret_qty",
	"global_prod_size_uom",
	"global_prod_need_state",
	"global_prod_subsegment",
	"sap_prod_mjr_cd",
	"st_grs_trd_sls",
	"so_net_trd_sls",
	"so_sls_qty",
	"global_prod_subcategory",
	"slsmn_cd",
	"global_put_up_desc",
	"jj_mnth_no",
	"dstrbtr_grp_cd",
	"local_prod_grp",
	"curr_mnth_indc",
	"sap_city",
	"slsmn_status",
	"si_ret_qty",
	"sap_prchse_uom_cd",
	"global_prod_category",
	"mnth_end_date",
	"sap_sls_office_cd",
	"so_grs_trd_sls",
	"jj_year",
	"global_mat_region",
	"so_mnth_tgt",
	"group_hierarchy",
	"sap_grp_frnchse_cd",
	"bill_date",
	"sap_mega_brnd_desc",
	"sap_prod_mnr_desc",
	"sap_addr",
	"global_prod_segment",
	"sap_brnd_cd",
	"sap_prod_sgmt_desc",
	"bill_doc",
	"gch_subcluster",
	"sap_base_uom_cd",
	"sap_prod_hier_cd",
	"sap_grp_frnchse_desc",
	"shop_type",
	"local_prod_brand",
	"sap_sls_grp_cd",
	"sap_prod_sgmt_cd",
	"asm_id",
	"sap_mat_type_desc",
	"sap_brnd_desc",
	"sap_vrnt_desc",
	"dstrb_region",
	"sap_frnchse_desc",
	"sap_chnl_desc",
	"sap_region",
	"product_visit_call_date",
	"top_door_target",
	"outlet_name",
	"sap_prod_hier_desc",
	"global_prod_brand",
	"sap_curr_cd",
	"wks_in_qrtr",
	"sap_state_cd",
	"gch_market",
	"trade_type",
	"global_prod_variant",
	"sap_vrnt_cd",
	"gch_retail_banner",
	"sap_frnchse_cd",
	"exchg_rate",
	"top_door_group",
	"sap_prod_frnchse_cd",
	"sap_sls_org",
	"sku",
	"cntry_nm",
	"global_prod_put_up_cd",
	"distributor_id_report",
	"sap_mat_type_cd",
	"global_prod_sub_brand",
	"sap_prod_mnr_cd",
	"groupmsl",
	"cust_cd",
	"forecastso_mil",
	"jj_mnth_id",
	"top_door_flag",
	"mnth_start_date",
	"sap_base_prod_cd",
	"jj_qrtr",
	"si_nts_val",
	"st_avg_wk_tgt",
	"si_avg_wk_tgt",
	"ce_target",
	"gch_cluster",
	"sap_base_prod_desc",
	"pc_target",
	"sap_prod_mjr_desc",
	"local_prod_variant",
	"dstrbtr_matl_name",
	"slsmn_nm",
	"visit_call_date",
	"st_sls_qty",
	"dstrbtr_name",
	"sap_sls_office_desc",
	"si_gts_val",
	"asm_name",
	"ub_weekly_target",
	"jj_mnth_wk_no",
	"sap_cmp_id",
	"gch_region",
	"sap_prod_frnchse_desc",
	"sap_sls_grp_desc",
	"supervisor_code",
	"st_mnth_tgt",
	"so_ret_qty",
	"sap_sold_to_code",
	"st_net_trd_sls",
	"local_group_jb",
	"local_prod_franchise",
	"ce_target_by_week"
) as
    SELECT
    sku_desc AS "sku_desc",
    global_prod_franchise AS "global_prod_franchise",
    si_sls_qty AS "si_sls_qty",
    curr_year_indc AS "curr_year_indc",
    so_avg_wk_tgt AS "so_avg_wk_tgt",
    supervisor_name AS "supervisor_name",
    sap_put_up_cd AS "sap_put_up_cd",
    sap_put_up_desc AS "sap_put_up_desc",
    sap_matl_num AS "sap_matl_num",
    pc_target_by_week AS "pc_target_by_week",
    sap_cntry_cd AS "sap_cntry_cd",
    sap_post_cd AS "sap_post_cd",
    territory_dist AS "territory_dist",
    si_mnth_tgt AS "si_mnth_tgt",
    sap_chnl_cd AS "sap_chnl_cd",
    global_prod_size AS "global_prod_size",
    sap_matl_name AS "sap_matl_name",
    sap_mega_brnd_cd AS "sap_mega_brnd_cd",
    dstrbtr_matl_num AS "dstrbtr_matl_num",
    sap_cntry_nm AS "sap_cntry_nm",
    st_ret_qty AS "st_ret_qty",
    global_prod_size_uom AS "global_prod_size_uom",
    global_prod_need_state AS "global_prod_need_state",
    global_prod_subsegment AS "global_prod_subsegment",
    sap_prod_mjr_cd AS "sap_prod_mjr_cd",
    st_grs_trd_sls AS "st_grs_trd_sls",
    so_net_trd_sls AS "so_net_trd_sls",
    so_sls_qty AS "so_sls_qty",
    global_prod_subcategory AS "global_prod_subcategory",
    slsmn_cd AS "slsmn_cd",
    global_put_up_desc AS "global_put_up_desc",
    jj_mnth_no AS "jj_mnth_no",
    dstrbtr_grp_cd AS "dstrbtr_grp_cd",
    local_prod_grp AS "local_prod_grp",
    curr_mnth_indc AS "curr_mnth_indc",
    sap_city AS "sap_city",
    slsmn_status AS "slsmn_status",
    si_ret_qty AS "si_ret_qty",
    sap_prchse_uom_cd AS "sap_prchse_uom_cd",
    global_prod_category AS "global_prod_category",
    mnth_end_date AS "mnth_end_date",
    sap_sls_office_cd AS "sap_sls_office_cd",
    so_grs_trd_sls AS "so_grs_trd_sls",
    jj_year AS "jj_year",
    global_mat_region AS "global_mat_region",
    so_mnth_tgt AS "so_mnth_tgt",
    group_hierarchy AS "group_hierarchy",
    sap_grp_frnchse_cd AS "sap_grp_frnchse_cd",
    bill_date AS "bill_date",
    sap_mega_brnd_desc AS "sap_mega_brnd_desc",
    sap_prod_mnr_desc AS "sap_prod_mnr_desc",
    sap_addr AS "sap_addr",
    global_prod_segment AS "global_prod_segment",
    sap_brnd_cd AS "sap_brnd_cd",
    sap_prod_sgmt_desc AS "sap_prod_sgmt_desc",
    bill_doc AS "bill_doc",
    gch_subcluster AS "gch_subcluster",
    sap_base_uom_cd AS "sap_base_uom_cd",
    sap_prod_hier_cd AS "sap_prod_hier_cd",
    sap_grp_frnchse_desc AS "sap_grp_frnchse_desc",
    shop_type AS "shop_type",
    local_prod_brand AS "local_prod_brand",
    sap_sls_grp_cd AS "sap_sls_grp_cd",
    sap_prod_sgmt_cd AS "sap_prod_sgmt_cd",
    asm_id AS "asm_id",
    sap_mat_type_desc AS "sap_mat_type_desc",
    sap_brnd_desc AS "sap_brnd_desc",
    sap_vrnt_desc AS "sap_vrnt_desc",
    dstrb_region AS "dstrb_region",
    sap_frnchse_desc AS "sap_frnchse_desc",
    sap_chnl_desc AS "sap_chnl_desc",
    sap_region AS "sap_region",
    product_visit_call_date AS "product_visit_call_date",
    top_door_target AS "top_door_target",
    outlet_name AS "outlet_name",
    sap_prod_hier_desc AS "sap_prod_hier_desc",
    global_prod_brand AS "global_prod_brand",
    sap_curr_cd AS "sap_curr_cd",
    wks_in_qrtr AS "wks_in_qrtr",
    sap_state_cd AS "sap_state_cd",
    gch_market AS "gch_market",
    trade_type AS "trade_type",
    global_prod_variant AS "global_prod_variant",
    sap_vrnt_cd AS "sap_vrnt_cd",
    gch_retail_banner AS "gch_retail_banner",
    sap_frnchse_cd AS "sap_frnchse_cd",
    exchg_rate AS "exchg_rate",
    top_door_group AS "top_door_group",
    sap_prod_frnchse_cd AS "sap_prod_frnchse_cd",
    sap_sls_org AS "sap_sls_org",
    sku AS "sku",
    cntry_nm AS "cntry_nm",
    global_prod_put_up_cd AS "global_prod_put_up_cd",
    distributor_id_report AS "distributor_id_report",
    sap_mat_type_cd AS "sap_mat_type_cd",
    global_prod_sub_brand AS "global_prod_sub_brand",
    sap_prod_mnr_cd AS "sap_prod_mnr_cd",
    groupmsl AS "groupmsl",
    cust_cd AS "cust_cd",
    forecastso_mil AS "forecastso_mil",
    jj_mnth_id AS "jj_mnth_id",
    top_door_flag AS "top_door_flag",
    mnth_start_date AS "mnth_start_date",
    sap_base_prod_cd AS "sap_base_prod_cd",
    jj_qrtr AS "jj_qrtr",
    si_nts_val AS "si_nts_val",
    st_avg_wk_tgt AS "st_avg_wk_tgt",
    si_avg_wk_tgt AS "si_avg_wk_tgt",
    ce_target AS "ce_target",
    gch_cluster AS "gch_cluster",
    sap_base_prod_desc AS "sap_base_prod_desc",
    pc_target AS "pc_target",
    sap_prod_mjr_desc AS "sap_prod_mjr_desc",
    local_prod_variant AS "local_prod_variant",
    dstrbtr_matl_name AS "dstrbtr_matl_name",
    slsmn_nm AS "slsmn_nm",
    visit_call_date AS "visit_call_date",
    st_sls_qty AS "st_sls_qty",
    dstrbtr_name AS "dstrbtr_name",
    sap_sls_office_desc AS "sap_sls_office_desc",
    si_gts_val AS "si_gts_val",
    asm_name AS "asm_name",
    ub_weekly_target AS "ub_weekly_target",
    jj_mnth_wk_no AS "jj_mnth_wk_no",
    sap_cmp_id AS "sap_cmp_id",
    gch_region AS "gch_region",
    sap_prod_frnchse_desc AS "sap_prod_frnchse_desc",
    sap_sls_grp_desc AS "sap_sls_grp_desc",
    supervisor_code AS "supervisor_code",
    st_mnth_tgt AS "st_mnth_tgt",
    so_ret_qty AS "so_ret_qty",
    sap_sold_to_code AS "sap_sold_to_code",
    st_net_trd_sls AS "st_net_trd_sls",
    local_group_jb AS "local_group_jb",
    local_prod_franchise AS "local_prod_franchise",
    ce_target_by_week AS "ce_target_by_week" 
FROM VNMEDW_INTEGRATION.EDW_VN_SI_ST_SO_DETAILS;


USE SCHEMA THAEDW_ACCESS;

create or replace view EDW_RPT_LCM_GT_SCORECARD(
	"otif_count",
	"distributor_id",
	"msl_target_count",
	"month",
	"active_store_count",
	"net_sell_out_actual",
	"msl_actual_count",
	"effective_call_count",
	"cntry_cd",
	"sales_area",
	"year_month",
	"sales_order_count",
	"on_time_count",
	"gross_sell_out_actual",
	"visited_call_count",
	"exch_rate",
	"sellout_target",
	"year",
	"inactive_stores_count",
	"identifier",
	"crncy_cd",
	"in_full_count",
	"coverage_stores_count",
	"store_type",
	"reactivate_stores_count",
	"cntry_nm",
	"planned_call_count",
	"sell_out_actual"
) as 
select
otif_count AS "otif_count",
distributor_id AS "distributor_id",
msl_target_count AS "msl_target_count",
month AS "month",
active_store_count AS "active_store_count",
net_sell_out_actual AS "net_sell_out_actual",
msl_actual_count AS "msl_actual_count",
effective_call_count AS "effective_call_count",
cntry_cd AS "cntry_cd",
sales_area AS "sales_area",
year_month AS "year_month",
sales_order_count AS "sales_order_count",
on_time_count AS "on_time_count",
gross_sell_out_actual AS "gross_sell_out_actual",
visited_call_count AS "visited_call_count",
exch_rate AS "exch_rate",
sellout_target AS "sellout_target",
year AS "year",
inactive_stores_count AS "inactive_stores_count",
identifier AS "identifier",
crncy_cd AS "crncy_cd",
in_full_count AS "in_full_count",
coverage_stores_count AS "coverage_stores_count",
store_type AS "store_type",
reactivate_stores_count AS "reactivate_stores_count",
cntry_nm AS "cntry_nm",
planned_call_count AS "planned_call_count",
sell_out_actual AS "sell_out_actual"
from thaedw_integration.edw_rpt_lcm_gt_scorecard;
create or replace view EDW_RPT_TH_GT_SCORECARD(
	"on_time_count",
	"cntry_cd",
	"msl_target_count",
	"net_sell_out_actual",
	"sales_order_count",
	"sales_area",
	"identifier",
	"store_type",
	"effective_call_count",
	"planned_store",
	"planned_call_count",
	"year",
	"total_skus",
	"sell_out_target",
	"visited_call_count",
	"year_month",
	"active_stores_count",
	"effective_store_all",
	"month",
	"reactivate_stores_count",
	"total_stores",
	"effective_call_all",
	"otif_count",
	"msl_actual_count",
	"route_com_all",
	"gross_sell_out_actual",
	"in_time_count",
	"sell_out_actual",
	"crncy_cd",
	"distributor_id",
	"inactive_stores_count",
	"coverage_stores_count",
	"effective_store_in_plan",
	"cntry_nm"
) as 
select
on_time_count AS "on_time_count",
cntry_cd AS "cntry_cd",
msl_target_count AS "msl_target_count",
net_sell_out_actual AS "net_sell_out_actual",
sales_order_count AS "sales_order_count",
sales_area AS "sales_area",
identifier AS "identifier",
store_type AS "store_type",
effective_call_count AS "effective_call_count",
planned_store AS "planned_store",
planned_call_count AS "planned_call_count",
year AS "year",
total_skus AS "total_skus",
sell_out_target AS "sell_out_target",
visited_call_count AS "visited_call_count",
year_month AS "year_month",
active_stores_count AS "active_stores_count",
effective_store_all AS "effective_store_all",
month AS "month",
reactivate_stores_count AS "reactivate_stores_count",
total_stores AS "total_stores",
effective_call_all AS "effective_call_all",
otif_count AS "otif_count",
msl_actual_count AS "msl_actual_count",
route_com_all AS "route_com_all",
gross_sell_out_actual AS "gross_sell_out_actual",
in_time_count AS "in_time_count",
sell_out_actual AS "sell_out_actual",
crncy_cd AS "crncy_cd",
distributor_id AS "distributor_id",
inactive_stores_count AS "inactive_stores_count",
coverage_stores_count AS "coverage_stores_count",
effective_store_in_plan AS "effective_store_in_plan",
cntry_nm AS "cntry_nm"
from THAedw_integration.edw_rpt_th_gt_scorecard;
create or replace view EDW_TH_INVENTORY_ANALYSIS(
	"sap_sls_office_cd",
	"si_tp_value",
	"sap_cust_id",
	"sap_cust_sub_chnl_key",
	"sap_cust_chnl_desc",
	"prod_category",
	"country_name",
	"month_year",
	"retail_env",
	"sap_state_cd",
	"sku_description",
	"sap_bnr_frmt_key",
	"sap_city",
	"prod_subsegment",
	"sap_sls_org",
	"sap_cust_nm",
	"sap_addr",
	"year_week_number",
	"sap_chnl_desc",
	"sap_bnr_desc",
	"sap_sls_grp_cd",
	"sap_chnl_cd",
	"sap_bnr_frmt_desc",
	"franchise",
	"sap_go_to_mdl_desc",
	"segment",
	"sap_sub_chnl_desc",
	"return_quantity",
	"data_type",
	"sap_cntry_nm",
	"sap_cntry_cd",
	"sku_code",
	"year_quarter",
	"sap_bnr_key",
	"inventory",
	"distributor_id",
	"sap_cust_chnl_key",
	"sap_region",
	"brand",
	"variant",
	"sap_cmp_id",
	"amount_before_discount",
	"whcode",
	"gross_trade_sales",
	"month_week_number",
	"year",
	"si_gross_trade_sales_value",
	"put_up_description",
	"inventory_quantity",
	"prod_subcategory",
	"sap_prnt_cust_key",
	"order_date",
	"month_number",
	"sap_go_to_mdl_key",
	"prod_sub_brand",
	"sap_sls_office_desc",
	"country_code",
	"sales_quantity",
	"sap_prnt_cust_desc",
	"si_net_trade_sales_value",
	"sap_sls_grp_desc",
	"sap_post_cd",
	"whgroup"
) as 
select
sap_sls_office_cd AS "sap_sls_office_cd",
si_tp_value AS "si_tp_value",
sap_cust_id AS "sap_cust_id",
sap_cust_sub_chnl_key AS "sap_cust_sub_chnl_key",
sap_cust_chnl_desc AS "sap_cust_chnl_desc",
prod_category AS "prod_category",
country_name AS "country_name",
month_year AS "month_year",
retail_env AS "retail_env",
sap_state_cd AS "sap_state_cd",
sku_description AS "sku_description",
sap_bnr_frmt_key AS "sap_bnr_frmt_key",
sap_city AS "sap_city",
prod_subsegment AS "prod_subsegment",
sap_sls_org AS "sap_sls_org",
sap_cust_nm AS "sap_cust_nm",
sap_addr AS "sap_addr",
year_week_number AS "year_week_number",
sap_chnl_desc AS "sap_chnl_desc",
sap_bnr_desc AS "sap_bnr_desc",
sap_sls_grp_cd AS "sap_sls_grp_cd",
sap_chnl_cd AS "sap_chnl_cd",
sap_bnr_frmt_desc AS "sap_bnr_frmt_desc",
franchise AS "franchise",
sap_go_to_mdl_desc AS "sap_go_to_mdl_desc",
segment AS "segment",
sap_sub_chnl_desc AS "sap_sub_chnl_desc",
return_quantity AS "return_quantity",
data_type AS "data_type",
sap_cntry_nm AS "sap_cntry_nm",
sap_cntry_cd AS "sap_cntry_cd",
sku_code AS "sku_code",
year_quarter AS "year_quarter",
sap_bnr_key AS "sap_bnr_key",
inventory AS "inventory",
distributor_id AS "distributor_id",
sap_cust_chnl_key AS "sap_cust_chnl_key",
sap_region AS "sap_region",
brand AS "brand",
variant AS "variant",
sap_cmp_id AS "sap_cmp_id",
amount_before_discount AS "amount_before_discount",
whcode AS "whcode",
gross_trade_sales AS "gross_trade_sales",
month_week_number AS "month_week_number",
year AS "year",
si_gross_trade_sales_value AS "si_gross_trade_sales_value",
put_up_description AS "put_up_description",
inventory_quantity AS "inventory_quantity",
prod_subcategory AS "prod_subcategory",
sap_prnt_cust_key AS "sap_prnt_cust_key",
order_date AS "order_date",
month_number AS "month_number",
sap_go_to_mdl_key AS "sap_go_to_mdl_key",
prod_sub_brand AS "prod_sub_brand",
sap_sls_office_desc AS "sap_sls_office_desc",
country_code AS "country_code",
sales_quantity AS "sales_quantity",
sap_prnt_cust_desc AS "sap_prnt_cust_desc",
si_net_trade_sales_value AS "si_net_trade_sales_value",
sap_sls_grp_desc AS "sap_sls_grp_desc",
sap_post_cd AS "sap_post_cd",
whgroup AS "whgroup"

from THAedw_integration.edw_th_inventory_analysis;
create or replace view EDW_TH_JBP_ANALYSIS(
	"bar_code",
	"region_desc",
	"bottom_line_discount",
	"ar_code",
	"cn_reason_code",
	"district",
	"sales_quantity",
	"year",
	"credit_note_amount",
	"whgroup",
	"ar_type_code",
	"month_year",
	"month_number",
	"distributor_name",
	"distributor_id",
	"target_calls",
	"sap_cust_id",
	"mcl_barcd",
	"segment",
	"ar_type_name",
	"str_count",
	"sales_office_code",
	"gross_trade_sales",
	"ar_name",
	"inventory_quantity",
	"salesman_code",
	"whcode",
	"quantity_dz",
	"salesman_name",
	"variant",
	"brand",
	"channel_code",
	"si_gross_trade_sales_value",
	"put_up_description",
	"sku_description",
	"line_discount",
	"channel",
	"sku_code",
	"net_invoice",
	"target_sales",
	"data_type",
	"order_date",
	"si_sellin_target",
	"cluster",
	"cn_damaged_goods",
	"city",
	"year_quarter",
	"inventory",
	"sales_group",
	"sales_office_name",
	"cn_reason_description",
	"franchise",
	"return_quantity"
) as 
select
bar_code AS "bar_code",
region_desc AS "region_desc",
bottom_line_discount AS "bottom_line_discount",
ar_code AS "ar_code",
cn_reason_code AS "cn_reason_code",
district AS "district",
sales_quantity AS "sales_quantity",
year AS "year",
credit_note_amount AS "credit_note_amount",
whgroup AS "whgroup",
ar_type_code AS "ar_type_code",
month_year AS "month_year",
month_number AS "month_number",
distributor_name AS "distributor_name",
distributor_id AS "distributor_id",
target_calls AS "target_calls",
sap_cust_id AS "sap_cust_id",
mcl_barcd AS "mcl_barcd",
segment AS "segment",
ar_type_name AS "ar_type_name",
str_count AS "str_count",
sales_office_code AS "sales_office_code",
gross_trade_sales AS "gross_trade_sales",
ar_name AS "ar_name",
inventory_quantity AS "inventory_quantity",
salesman_code AS "salesman_code",
whcode AS "whcode",
quantity_dz AS "quantity_dz",
salesman_name AS "salesman_name",
variant AS "variant",
brand AS "brand",
channel_code AS "channel_code",
si_gross_trade_sales_value AS "si_gross_trade_sales_value",
put_up_description AS "put_up_description",
sku_description AS "sku_description",
line_discount AS "line_discount",
channel AS "channel",
sku_code AS "sku_code",
net_invoice AS "net_invoice",
target_sales AS "target_sales",
data_type AS "data_type",
order_date AS "order_date",
si_sellin_target AS "si_sellin_target",
cluster AS "cluster",
cn_damaged_goods AS "cn_damaged_goods",
city AS "city",
year_quarter AS "year_quarter",
inventory AS "inventory",
sales_group AS "sales_group",
sales_office_name AS "sales_office_name",
cn_reason_description AS "cn_reason_description",
franchise AS "franchise",
return_quantity AS "return_quantity"


from THAedw_integration.edw_th_jbp_analysis;
create or replace view EDW_TH_MARKET_SHARE_DISTRIBUTION_ANALYSIS(
	"category",
	"cntry_cd",
	"mnfctrer",
	"cntry_nm",
	"yr_mnth",
	"chnl",
	"measure",
	"value"
) as 
select
category AS "category",
cntry_cd AS "cntry_cd",
mnfctrer AS "mnfctrer",
cntry_nm AS "cntry_nm",
yr_mnth AS "yr_mnth",
chnl AS "chnl",
measure AS "measure",
value AS "value"



from THAedw_integration.edw_th_market_share_distribution_analysis;
create or replace view EDW_TH_POS_ANALYSIS(
	"province_code",
	"month_number",
	"province_name",
	"retailer_unit_conversion",
	"inventory_baht",
	"customer_branch_code",
	"franchise",
	"inventory_quantity_piece",
	"bar_code",
	"quarter",
	"salesbaht",
	"inventory_quantity_dozen",
	"branch_name",
	"sales_gts",
	"inventory_gts",
	"region_name",
	"customer_rsp",
	"month_week_number",
	"month_year",
	"variant",
	"put_up",
	"week",
	"brand",
	"invoice_date",
	"customer_code",
	"sale_quantity",
	"segment",
	"year",
	"material_description",
	"branch_type",
	"item_code",
	"list_price"
) as 
select
province_code AS "province_code",
month_number AS "month_number",
province_name AS "province_name",
retailer_unit_conversion AS "retailer_unit_conversion",
inventory_baht AS "inventory_baht",
customer_branch_code AS "customer_branch_code",
franchise AS "franchise",
inventory_quantity_piece AS "inventory_quantity_piece",
bar_code AS "bar_code",
quarter AS "quarter",
salesbaht AS "salesbaht",
inventory_quantity_dozen AS "inventory_quantity_dozen",
branch_name AS "branch_name",
sales_gts AS "sales_gts",
inventory_gts AS "inventory_gts",
region_name AS "region_name",
customer_rsp AS "customer_rsp",
month_week_number AS "month_week_number",
month_year AS "month_year",
variant AS "variant",
put_up AS "put_up",
week AS "week",
brand AS "brand",
invoice_date AS "invoice_date",
customer_code AS "customer_code",
sale_quantity AS "sale_quantity",
segment AS "segment",
year AS "year",
material_description AS "material_description",
branch_type AS "branch_type",
item_code AS "item_code",
list_price AS "list_price"



from thaedw_integration.edw_th_pos_analysis;
create or replace view EDW_TH_SELLIN_ANALYSIS(
	"sap_addr",
	"sap_cust_chnl_desc",
	"net_trade_sales_value",
	"sap_sls_org",
	"hero_indicator",
	"year_jnj",
	"sales_less_return_quantity",
	"npi_start_date",
	"variant",
	"sap_cust_sub_chnl_key",
	"max_pstng_dt",
	"sap_channel_description",
	"return_quantity",
	"sap_company_id",
	"sap_state_cd",
	"sap_bnr_key",
	"return_value",
	"customer_sales",
	"npi_end_date",
	"sap_bnr_frmt_key",
	"npi_indicator",
	"prod_sub_brand",
	"ciw_account_value",
	"sap_prnt_cust_desc",
	"sap_cntry_nm",
	"sap_chnl_desc",
	"sales_quantity",
	"sap_cust_id",
	"banner_description",
	"prod_category",
	"sap_cust_nm",
	"posting_per",
	"gross_trade_sales_less_return_value",
	"sap_company_name",
	"put_up",
	"category",
	"tp_value",
	"account_name",
	"brand",
	"sap_city",
	"go_to_model_description",
	"sap_sales_office_description",
	"net_trade_sales_quantity",
	"prod_subsegment",
	"sap_sub_chnl_desc",
	"year_month_jnj",
	"area",
	"account_number",
	"sap_sales_group_description",
	"base_value",
	"sap_prnt_cust_key",
	"sap_go_to_mdl_key",
	"plant",
	"sap_bnr_frmt_desc",
	"sap_region",
	"sap_address",
	"sap_post_code",
	"item_code",
	"distributor_channel",
	"sap_sales_org",
	"franchise",
	"segment",
	"reg_indicator",
	"year_quarter_jnj",
	"month_number_jnj",
	"retail_env",
	"item_description",
	"sap_sales_office_code",
	"customer_id",
	"sap_cntry_cd",
	"customer_group",
	"sap_sales_group_code",
	"prod_subcategory",
	"sap_customer_name",
	"gross_trade_sales_value",
	"sap_cust_chnl_key"
) as 
select
sap_addr AS "sap_addr",
sap_cust_chnl_desc AS "sap_cust_chnl_desc",
net_trade_sales_value AS "net_trade_sales_value",
sap_sls_org AS "sap_sls_org",
hero_indicator AS "hero_indicator",
year_jnj AS "year_jnj",
sales_less_return_quantity AS "sales_less_return_quantity",
npi_start_date AS "npi_start_date",
variant AS "variant",
sap_cust_sub_chnl_key AS "sap_cust_sub_chnl_key",
max_pstng_dt AS "max_pstng_dt",
sap_channel_description AS "sap_channel_description",
return_quantity AS "return_quantity",
sap_company_id AS "sap_company_id",
sap_state_cd AS "sap_state_cd",
sap_bnr_key AS "sap_bnr_key",
return_value AS "return_value",
customer_sales AS "customer_sales",
npi_end_date AS "npi_end_date",
sap_bnr_frmt_key AS "sap_bnr_frmt_key",
npi_indicator AS "npi_indicator",
prod_sub_brand AS "prod_sub_brand",
ciw_account_value AS "ciw_account_value",
sap_prnt_cust_desc AS "sap_prnt_cust_desc",
sap_cntry_nm AS "sap_cntry_nm",
sap_chnl_desc AS "sap_chnl_desc",
sales_quantity AS "sales_quantity",
sap_cust_id AS "sap_cust_id",
banner_description AS "banner_description",
prod_category AS "prod_category",
sap_cust_nm AS "sap_cust_nm",
posting_per AS "posting_per",
gross_trade_sales_less_return_value AS "gross_trade_sales_less_return_value",
sap_company_name AS "sap_company_name",
put_up AS "put_up",
category AS "category",
tp_value AS "tp_value",
account_name AS "account_name",
brand AS "brand",
sap_city AS "sap_city",
go_to_model_description AS "go_to_model_description",
sap_sales_office_description AS "sap_sales_office_description",
net_trade_sales_quantity AS "net_trade_sales_quantity",
prod_subsegment AS "prod_subsegment",
sap_sub_chnl_desc AS "sap_sub_chnl_desc",
year_month_jnj AS "year_month_jnj",
area AS "area",
account_number AS "account_number",
sap_sales_group_description AS "sap_sales_group_description",
base_value AS "base_value",
sap_prnt_cust_key AS "sap_prnt_cust_key",
sap_go_to_mdl_key AS "sap_go_to_mdl_key",
plant AS "plant",
sap_bnr_frmt_desc AS "sap_bnr_frmt_desc",
sap_region AS "sap_region",
sap_address AS "sap_address",
sap_post_code AS "sap_post_code",
item_code AS "item_code",
distributor_channel AS "distributor_channel",
sap_sales_org AS "sap_sales_org",
franchise AS "franchise",
segment AS "segment",
reg_indicator AS "reg_indicator",
year_quarter_jnj AS "year_quarter_jnj",
month_number_jnj AS "month_number_jnj",
retail_env AS "retail_env",
item_description AS "item_description",
sap_sales_office_code AS "sap_sales_office_code",
customer_id AS "customer_id",
sap_cntry_cd AS "sap_cntry_cd",
customer_group AS "customer_group",
sap_sales_group_code AS "sap_sales_group_code",
prod_subcategory AS "prod_subcategory",
sap_customer_name AS "sap_customer_name",
gross_trade_sales_value AS "gross_trade_sales_value",
sap_cust_chnl_key AS "sap_cust_chnl_key"




from THAedw_integration.edw_th_sellin_analysis;
create or replace view EDW_TH_SELLOUT_ANALYSIS(
	"net_invoice",
	"sap_cust_id",
	"foc_trd_discnt_item_lvl",
	"sap_chnl_cd",
	"sap_bnr_frmt_desc",
	"cn_damaged_goods",
	"year",
	"store",
	"sap_sls_grp_cd",
	"target_calls",
	"gross_trade_sales",
	"distributor_id",
	"ar_type_code",
	"channel_code",
	"sap_sls_org",
	"city",
	"region_desc",
	"year_quarter",
	"salesman_code",
	"sap_sub_chnl_desc",
	"sap_addr",
	"cluster",
	"channel",
	"sap_chnl_desc",
	"put_up_description",
	"franchise",
	"distributor_name",
	"credit_note_amount",
	"district",
	"ar_type_name",
	"foc_trd_discnt_bill_lvl",
	"re_nm",
	"tot_bf_discount",
	"prod_subsegment",
	"sap_bnr_key",
	"country_name",
	"prod_sub_brand",
	"sap_prnt_cust_desc",
	"sap_cust_nm",
	"sap_cntry_cd",
	"prod_subcategory",
	"line_discount",
	"sap_bnr_desc",
	"gross_sales",
	"foc_net_invc",
	"sap_sls_grp_desc",
	"return_quantity",
	"brand",
	"country_code",
	"prod_category",
	"sap_go_to_mdl_desc",
	"sap_region",
	"sku_code",
	"target_sales",
	"sap_city",
	"month_number",
	"salesman_name",
	"retail_env",
	"sap_cust_chnl_key",
	"sales_group",
	"bar_code",
	"sap_sls_office_cd",
	"sap_prnt_cust_key",
	"sap_sls_office_desc",
	"ar_code",
	"year_week_number",
	"sales_office_name",
	"cn_reason_code",
	"sales_office_code",
	"sap_state_cd",
	"sap_cust_chnl_desc",
	"quantity_dz",
	"sales_quantity",
	"sap_bnr_frmt_key",
	"sap_post_cd",
	"month_week_number",
	"bottom_line_discount",
	"sap_go_to_mdl_key",
	"sap_cntry_nm",
	"month_year",
	"variant",
	"cn_reason_description",
	"sap_cmp_id",
	"sap_cust_sub_chnl_key",
	"segment",
	"order_date",
	"ar_name",
	"sku_description"
) as 
select
net_invoice AS "net_invoice",
sap_cust_id AS "sap_cust_id",
foc_trd_discnt_item_lvl AS "foc_trd_discnt_item_lvl",
sap_chnl_cd AS "sap_chnl_cd",
sap_bnr_frmt_desc AS "sap_bnr_frmt_desc",
cn_damaged_goods AS "cn_damaged_goods",
year AS "year",
store AS "store",
sap_sls_grp_cd AS "sap_sls_grp_cd",
target_calls AS "target_calls",
gross_trade_sales AS "gross_trade_sales",
distributor_id AS "distributor_id",
ar_type_code AS "ar_type_code",
channel_code AS "channel_code",
sap_sls_org AS "sap_sls_org",
city AS "city",
region_desc AS "region_desc",
year_quarter AS "year_quarter",
salesman_code AS "salesman_code",
sap_sub_chnl_desc AS "sap_sub_chnl_desc",
sap_addr AS "sap_addr",
cluster AS "cluster",
channel AS "channel",
sap_chnl_desc AS "sap_chnl_desc",
put_up_description AS "put_up_description",
franchise AS "franchise",
distributor_name AS "distributor_name",
credit_note_amount AS "credit_note_amount",
district AS "district",
ar_type_name AS "ar_type_name",
foc_trd_discnt_bill_lvl AS "foc_trd_discnt_bill_lvl",
re_nm AS "re_nm",
tot_bf_discount AS "tot_bf_discount",
prod_subsegment AS "prod_subsegment",
sap_bnr_key AS "sap_bnr_key",
country_name AS "country_name",
prod_sub_brand AS "prod_sub_brand",
sap_prnt_cust_desc AS "sap_prnt_cust_desc",
sap_cust_nm AS "sap_cust_nm",
sap_cntry_cd AS "sap_cntry_cd",
prod_subcategory AS "prod_subcategory",
line_discount AS "line_discount",
sap_bnr_desc AS "sap_bnr_desc",
gross_sales AS "gross_sales",
foc_net_invc AS "foc_net_invc",
sap_sls_grp_desc AS "sap_sls_grp_desc",
return_quantity AS "return_quantity",
brand AS "brand",
country_code AS "country_code",
prod_category AS "prod_category",
sap_go_to_mdl_desc AS "sap_go_to_mdl_desc",
sap_region AS "sap_region",
sku_code AS "sku_code",
target_sales AS "target_sales",
sap_city AS "sap_city",
month_number AS "month_number",
salesman_name AS "salesman_name",
retail_env AS "retail_env",
sap_cust_chnl_key AS "sap_cust_chnl_key",
sales_group AS "sales_group",
bar_code AS "bar_code",
sap_sls_office_cd AS "sap_sls_office_cd",
sap_prnt_cust_key AS "sap_prnt_cust_key",
sap_sls_office_desc AS "sap_sls_office_desc",
ar_code AS "ar_code",
year_week_number AS "year_week_number",
sales_office_name AS "sales_office_name",
cn_reason_code AS "cn_reason_code",
sales_office_code AS "sales_office_code",
sap_state_cd AS "sap_state_cd",
sap_cust_chnl_desc AS "sap_cust_chnl_desc",
quantity_dz AS "quantity_dz",
sales_quantity AS "sales_quantity",
sap_bnr_frmt_key AS "sap_bnr_frmt_key",
sap_post_cd AS "sap_post_cd",
month_week_number AS "month_week_number",
bottom_line_discount AS "bottom_line_discount",
sap_go_to_mdl_key AS "sap_go_to_mdl_key",
sap_cntry_nm AS "sap_cntry_nm",
month_year AS "month_year",
variant AS "variant",
cn_reason_description AS "cn_reason_description",
sap_cmp_id AS "sap_cmp_id",
sap_cust_sub_chnl_key AS "sap_cust_sub_chnl_key",
segment AS "segment",
order_date AS "order_date",
ar_name AS "ar_name",
sku_description AS "sku_description"

from THAedw_integration.edw_th_sellout_analysis;
create or replace view EDW_TH_SELLOUT_FOC_ANALYSIS(
	"segment",
	"distributor_id",
	"ar_type_code",
	"sap_sls_office_cd",
	"prom_cd3",
	"retail_env",
	"salesman_name",
	"sap_prnt_cust_desc",
	"sap_bnr_frmt_desc",
	"sku_code",
	"bar_code",
	"sap_state_cd",
	"sap_cust_id",
	"sap_cust_sub_chnl_key",
	"credit_note_amount",
	"cn_reason_description",
	"line_discount",
	"sap_city",
	"quantity_dz",
	"distributor_name",
	"year",
	"order_date",
	"return_quantity",
	"sap_go_to_mdl_key",
	"iscancel",
	"sap_sls_grp_cd",
	"tot_bf_discount",
	"sales_group",
	"sku_description",
	"country_name",
	"grp_cd",
	"city",
	"sap_bnr_frmt_key",
	"year_quarter",
	"region_desc",
	"net_invoice",
	"brand",
	"sap_chnl_cd",
	"sap_region",
	"year_week_number",
	"prod_category",
	"prod_subcategory",
	"sales_office_name",
	"sap_bnr_key",
	"target_sales",
	"sap_go_to_mdl_desc",
	"sap_cust_chnl_key",
	"prod_subsegment",
	"sap_post_cd",
	"cn_damaged_goods",
	"prod_sub_brand",
	"variant",
	"channel",
	"channel_code",
	"cluster",
	"sap_sls_office_desc",
	"salesman_code",
	"ar_type_name",
	"cn_reason_code",
	"franchise",
	"sap_sub_chnl_desc",
	"country_code",
	"sap_chnl_desc",
	"put_up_description",
	"bottom_line_discount",
	"sap_cust_nm",
	"sap_cmp_id",
	"sap_cust_chnl_desc",
	"prom_cd2",
	"ar_name",
	"prom_cd1",
	"sap_sls_grp_desc",
	"sales_office_code",
	"order_no",
	"month_week_number",
	"sap_prnt_cust_key",
	"gross_trade_sales",
	"sales_quantity",
	"ar_code",
	"sap_cntry_nm",
	"sap_addr",
	"month_number",
	"sap_sls_org",
	"sap_cntry_cd",
	"sap_bnr_desc",
	"price",
	"district",
	"target_calls",
	"month_year"
) as 
select
segment AS "segment",
distributor_id AS "distributor_id",
ar_type_code AS "ar_type_code",
sap_sls_office_cd AS "sap_sls_office_cd",
prom_cd3 AS "prom_cd3",
retail_env AS "retail_env",
salesman_name AS "salesman_name",
sap_prnt_cust_desc AS "sap_prnt_cust_desc",
sap_bnr_frmt_desc AS "sap_bnr_frmt_desc",
sku_code AS "sku_code",
bar_code AS "bar_code",
sap_state_cd AS "sap_state_cd",
sap_cust_id AS "sap_cust_id",
sap_cust_sub_chnl_key AS "sap_cust_sub_chnl_key",
credit_note_amount AS "credit_note_amount",
cn_reason_description AS "cn_reason_description",
line_discount AS "line_discount",
sap_city AS "sap_city",
quantity_dz AS "quantity_dz",
distributor_name AS "distributor_name",
year AS "year",
order_date AS "order_date",
return_quantity AS "return_quantity",
sap_go_to_mdl_key AS "sap_go_to_mdl_key",
iscancel AS "iscancel",
sap_sls_grp_cd AS "sap_sls_grp_cd",
tot_bf_discount AS "tot_bf_discount",
sales_group AS "sales_group",
sku_description AS "sku_description",
country_name AS "country_name",
grp_cd AS "grp_cd",
city AS "city",
sap_bnr_frmt_key AS "sap_bnr_frmt_key",
year_quarter AS "year_quarter",
region_desc AS "region_desc",
net_invoice AS "net_invoice",
brand AS "brand",
sap_chnl_cd AS "sap_chnl_cd",
sap_region AS "sap_region",
year_week_number AS "year_week_number",
prod_category AS "prod_category",
prod_subcategory AS "prod_subcategory",
sales_office_name AS "sales_office_name",
sap_bnr_key AS "sap_bnr_key",
target_sales AS "target_sales",
sap_go_to_mdl_desc AS "sap_go_to_mdl_desc",
sap_cust_chnl_key AS "sap_cust_chnl_key",
prod_subsegment AS "prod_subsegment",
sap_post_cd AS "sap_post_cd",
cn_damaged_goods AS "cn_damaged_goods",
prod_sub_brand AS "prod_sub_brand",
variant AS "variant",
channel AS "channel",
channel_code AS "channel_code",
cluster AS "cluster",
sap_sls_office_desc AS "sap_sls_office_desc",
salesman_code AS "salesman_code",
ar_type_name AS "ar_type_name",
cn_reason_code AS "cn_reason_code",
franchise AS "franchise",
sap_sub_chnl_desc AS "sap_sub_chnl_desc",
country_code AS "country_code",
sap_chnl_desc AS "sap_chnl_desc",
put_up_description AS "put_up_description",
bottom_line_discount AS "bottom_line_discount",
sap_cust_nm AS "sap_cust_nm",
sap_cmp_id AS "sap_cmp_id",
sap_cust_chnl_desc AS "sap_cust_chnl_desc",
prom_cd2 AS "prom_cd2",
ar_name AS "ar_name",
prom_cd1 AS "prom_cd1",
sap_sls_grp_desc AS "sap_sls_grp_desc",
sales_office_code AS "sales_office_code",
order_no AS "order_no",
month_week_number AS "month_week_number",
sap_prnt_cust_key AS "sap_prnt_cust_key",
gross_trade_sales AS "gross_trade_sales",
sales_quantity AS "sales_quantity",
ar_code AS "ar_code",
sap_cntry_nm AS "sap_cntry_nm",
sap_addr AS "sap_addr",
month_number AS "month_number",
sap_sls_org AS "sap_sls_org",
sap_cntry_cd AS "sap_cntry_cd",
sap_bnr_desc AS "sap_bnr_desc",
price AS "price",
district AS "district",
target_calls AS "target_calls",
month_year AS "month_year"

from THAedw_integration.edw_th_sellout_foc_analysis;
create or replace view EDW_TH_SFMC_ANALYSIS(
	"data_src",
	"country_code",
	"country_name",
	"created_date",
	"invoicec_created_date",
	"invoice_completed_date",
	"last_logon_time",
	"purchase_date",
	"redeemed_date",
	"redeemption_completed_date",
	"first_name",
	"last_name",
	"consumer_name",
	"mobile_number",
	"subscriber_key",
	"mobile_country_code",
	"address_country",
	"address_region",
	"address_1",
	"address_2",
	"line_id",
	"address",
	"birth_month",
	"birth_year",
	"consumer_age",
	"consumer_age_group",
	"email",
	"gender",
	"channel_name",
	"brand",
	"product_name",
	"product_category",
	"tier",
	"remaining_points",
	"customer_redeemed_points",
	"total_points",
	"invoive_number",
	"invoice_qty",
	"invoice_type",
	"invoice_seller_name",
	"invoice_points",
	"invoice_status",
	"child_name",
	"child_birth_month",
	"child_birth_year",
	"child_gender",
	"child_number",
	"child_age",
	"child_group",
	"child_flag",
	"redeemed_order_number",
	"redeemed_prod_name",
	"redemption_status",
	"redeemed_points",
	"redeemed_qty",
	"activity_date",
	"local_activity_date",
	"sent_activity_date",
	"email_name",
	"email_subject",
	"sent_email_name",
	"sent_email_subject",
	"email_delivered_flag",
	"is_unique",
	"url",
	"link_name",
	"link_content",
	"bounce_reason",
	"bounce_type",
	"bounce_description",
	"data_refresh_time",
	"smoker",
	"expectant_mother",
	"category_they_are_using",
	"category_they_are_using_eng",
	"skin_condition",
	"skin_condition_eng",
	"skin_problem",
	"skin_problem_eng",
	"use_mouthwash",
	"mouthwash_time",
	"mouthwash_time_eng",
	"why_not_use_mouthwash",
	"why_not_use_mouthwash_eng",
	"oral_problem",
	"oral_problem_eng"
) as
select
	data_src as "data_src",
	country_code as "country_code",
	country_name as "country_name",
	created_date as "created_date",
	invoicec_created_date as "invoicec_created_date",
	invoice_completed_date as "invoice_completed_date",
	last_logon_time as "last_logon_time",
	purchase_date as "purchase_date",
	redeemed_date as "redeemed_date",
	redeemption_completed_date as "redeemption_completed_date",
	first_name as "first_name",
	last_name as "last_name",
	consumer_name as "consumer_name",
	mobile_number as "mobile_number",
	subscriber_key as "subscriber_key",
	mobile_country_code as "mobile_country_code",
	address_country as "address_country",
	address_region as "address_region",
	address_1 as "address_1",
	address_2 as "address_2",
	line_id as "line_id",
	address as "address",
	birth_month as "birth_month",
	birth_year as "birth_year",
	consumer_age as "consumer_age",
	consumer_age_group as "consumer_age_group",
	email as "email",
	gender as "gender",
	channel_name as "channel_name",
	brand as "brand",
	product_name as "product_name",
	product_category as "product_category",
	tier as "tier",
	remaining_points as "remaining_points",
	customer_redeemed_points as "customer_redeemed_points",
	total_points as "total_points",
	invoive_number as "invoive_number",
	invoice_qty as "invoice_qty",
	invoice_type as "invoice_type",
	invoice_seller_name as "invoice_seller_name",
	invoice_points as "invoice_points",
	invoice_status as "invoice_status",
	child_name as "child_name",
	child_birth_month as "child_birth_month",
	child_birth_year as "child_birth_year",
	child_gender as "child_gender",
	child_number as "child_number",
	child_age as "child_age",
	child_group as "child_group",
	child_flag as "child_flag",
	redeemed_order_number as "redeemed_order_number",
	redeemed_prod_name as "redeemed_prod_name",
	redemption_status as "redemption_status",
	redeemed_points as "redeemed_points",
	redeemed_qty as "redeemed_qty",
	activity_date as "activity_date",
	local_activity_date as "local_activity_date",
	sent_activity_date as "sent_activity_date",
	email_name as "email_name",
	email_subject as "email_subject",
	sent_email_name as "sent_email_name",
	sent_email_subject as "sent_email_subject",
	email_delivered_flag as "email_delivered_flag",
	is_unique as "is_unique",
	url as "url",
	link_name as "link_name",
	link_content as "link_content",
	bounce_reason as "bounce_reason",
	bounce_type as "bounce_type",
	bounce_description as "bounce_description",
	data_refresh_time as "data_refresh_time",
	smoker as "smoker",
	expectant_mother as "expectant_mother",
	category_they_are_using as "category_they_are_using",
	category_they_are_using_eng as "category_they_are_using_eng",
	skin_condition as "skin_condition",
	skin_condition_eng as "skin_condition_eng",
	skin_problem as "skin_problem",
	skin_problem_eng as "skin_problem_eng",
	use_mouthwash as "use_mouthwash",
	mouthwash_time as "mouthwash_time",
	mouthwash_time_eng as "mouthwash_time_eng",
	why_not_use_mouthwash as "why_not_use_mouthwash",
	why_not_use_mouthwash_eng as "why_not_use_mouthwash_eng",
	oral_problem as "oral_problem",
	oral_problem_eng as "oral_problem_eng"
from thaedw_integration.edw_th_sfmc_analysis;
create or replace view EDW_TH_SISO_ANALYSIS(
	"franchise",
	"so_net_invoice",
	"data_type",
	"si_gross_trade_sales_value",
	"retail_env",
	"sap_customer_name",
	"so_quantity_dz",
	"sap_sales_group_code",
	"go_to_model_description",
	"sap_sales_office_description",
	"sap_sub_chnl_desc",
	"si_sales_quantity",
	"so_sales_quantity",
	"year_month_jnj",
	"item_code",
	"si_base_value",
	"sap_prnt_cust_desc",
	"sap_bnr_frmt_key",
	"banner_description",
	"sap_bnr_frmt_desc",
	"sap_bnr_key",
	"si_return_value",
	"si_net_trade_sales_quantity",
	"sap_sls_org",
	"so_cn_damaged_goods",
	"so_credit_note_amount",
	"prod_subsegment",
	"si_return_quantity",
	"item_description",
	"sap_cust_chnl_desc",
	"si_sales_less_return_quantity",
	"sap_go_to_mdl_key",
	"so_gross_trade_sales",
	"so_return_quantity",
	"so_target_sales",
	"brand",
	"prod_subcategory",
	"sap_sales_office_code",
	"variant",
	"prod_sub_brand",
	"month_number_jnj",
	"sap_sales_group_description",
	"so_target_calls",
	"sap_prnt_cust_key",
	"year_quarter_jnj",
	"si_gross_trade_sales_less_return_value",
	"sap_cust_sub_chnl_key",
	"si_tp_value",
	"prod_category",
	"year_jnj",
	"so_line_discount",
	"so_bottom_line_discount",
	"customer_id",
	"sap_cust_chnl_key",
	"put_up",
	"si_net_trade_sales_value",
	"segment"
) as
    SELECT 
    franchise AS "franchise",
    so_net_invoice AS "so_net_invoice",
    data_type AS "data_type",
    si_gross_trade_sales_value AS "si_gross_trade_sales_value",
    retail_env AS "retail_env",
    sap_customer_name AS "sap_customer_name",
    so_quantity_dz AS "so_quantity_dz",
    sap_sales_group_code AS "sap_sales_group_code",
    go_to_model_description AS "go_to_model_description",
    sap_sales_office_description AS "sap_sales_office_description",
    sap_sub_chnl_desc AS "sap_sub_chnl_desc",
    si_sales_quantity AS "si_sales_quantity",
    so_sales_quantity AS "so_sales_quantity",
    year_month_jnj AS "year_month_jnj",
    item_code AS "item_code",
    si_base_value AS "si_base_value",
    sap_prnt_cust_desc AS "sap_prnt_cust_desc",
    sap_bnr_frmt_key AS "sap_bnr_frmt_key",
    banner_description AS "banner_description",
    sap_bnr_frmt_desc AS "sap_bnr_frmt_desc",
    sap_bnr_key AS "sap_bnr_key",
    si_return_value AS "si_return_value",
    si_net_trade_sales_quantity AS "si_net_trade_sales_quantity",
    sap_sls_org AS "sap_sls_org",
    so_cn_damaged_goods AS "so_cn_damaged_goods",
    so_credit_note_amount AS "so_credit_note_amount",
    prod_subsegment AS "prod_subsegment",
    si_return_quantity AS "si_return_quantity",
    item_description AS "item_description",
    sap_cust_chnl_desc AS "sap_cust_chnl_desc",
    si_sales_less_return_quantity AS "si_sales_less_return_quantity",
    sap_go_to_mdl_key AS "sap_go_to_mdl_key",
    so_gross_trade_sales AS "so_gross_trade_sales",
    so_return_quantity AS "so_return_quantity",
    so_target_sales AS "so_target_sales",
    brand AS "brand",
    prod_subcategory AS "prod_subcategory",
    sap_sales_office_code AS "sap_sales_office_code",
    variant AS "variant",
    prod_sub_brand AS "prod_sub_brand",
    month_number_jnj AS "month_number_jnj",
    sap_sales_group_description AS "sap_sales_group_description",
    so_target_calls AS "so_target_calls",
    sap_prnt_cust_key AS "sap_prnt_cust_key",
    year_quarter_jnj AS "year_quarter_jnj",
    si_gross_trade_sales_less_return_value AS "si_gross_trade_sales_less_return_value",
    sap_cust_sub_chnl_key AS "sap_cust_sub_chnl_key",
    si_tp_value AS "si_tp_value",
    prod_category AS "prod_category",
    year_jnj AS "year_jnj",
    so_line_discount AS "so_line_discount",
    so_bottom_line_discount AS "so_bottom_line_discount",
    customer_id AS "customer_id",
    sap_cust_chnl_key AS "sap_cust_chnl_key",
    put_up AS "put_up",
    si_net_trade_sales_value AS "si_net_trade_sales_value",
    segment AS "segment"
FROM THAEDW_INTEGRATION.EDW_TH_SISO_ANALYSIS;

create or replace view EDW_VW_RPT_TH_ONE_VIEW_DASHBOARD(
	"name",
	"code",
	"changetrackingmask",
	"date_level",
	"date_value",
	"sector_function",
	"functional_area",
	"subject",
	"kpi",
	"level_1_def",
	"level_1",
	"level_2_def",
	"level_2",
	"ref_value",
	"actual_value",
	"add_info",
	"default_view_flag",
	"compliance_definition",
	"crtd_dttm",
	"updt_dttm"
) as
SELECT
itg_th_one_jnj_data.name "name",
itg_th_one_jnj_data.code as "code",
itg_th_one_jnj_data.changetrackingmask as "changetrackingmask",
itg_th_one_jnj_data.date_level as "date_level",
itg_th_one_jnj_data.date_value as "date_value",
itg_th_one_jnj_data.sector_function as "sector_function",
itg_th_one_jnj_data.functional_area as "functional_area",
itg_th_one_jnj_data.subject as "subject",
itg_th_one_jnj_data.kpi as "kpi",
itg_th_one_jnj_data.level_1_def as "level_1_def",
itg_th_one_jnj_data.level_1 as "level_1",
itg_th_one_jnj_data.level_2_def as "level_2_def",
itg_th_one_jnj_data.level_2 as "level_2",
itg_th_one_jnj_data.ref_value as "ref_value",
itg_th_one_jnj_data.actual_value as "actual_value",
itg_th_one_jnj_data.add_info as "add_info",
itg_th_one_jnj_data.default_view_flag as "default_view_flag",
itg_th_one_jnj_data.compliance_definition as "compliance_definition",
itg_th_one_jnj_data.crtd_dttm as "crtd_dttm",
itg_th_one_jnj_data.updt_dttm as "updt_dttm"
FROM itg_th_one_jnj_data;
create or replace view EDW_VW_TH_INVENTORY_AGEING_ANALYSIS(
	TYP,
	CNTRY_CD,
	CNTRY_NM,
	BILL_DATE,
	DSTRBTR_GRP_CD,
	DSTRBTR_NM,
	DSTRBTR_MATL_NUM,
	WAREHSE_CD,
	WAREHSE_GRP,
	BATCH_EXPIRY_DATE,
	ROOT_CODE,
	INV_QTY,
	INV_AMT,
	SLS_PRC2,
	UNIT_PER_CASE,
	CASES,
	EACHES,
	SLS_AMT,
	TOTAL_BHT,
	"year",
	QRTR,
	MNTH_ID,
	MNTH_NO,
	WK,
	MNTH_WK_NO,
	CAL_DATE,
	SKU_DESCRIPTION,
	FRANCHISE,
	BRAND,
	VARIANT,
	SEGMENT,
	PUT_UP_DESCRIPTION,
	PROD_SUB_BRAND,
	PROD_SUBSEGMENT,
	PROD_CATEGORY,
	PROD_SUBCATEGORY,
	SAP_CUST_ID,
	SAP_CUST_NM,
	SAP_SLS_ORG,
	SAP_CMP_ID,
	SAP_CNTRY_CD,
	SAP_CNTRY_NM,
	SAP_ADDR,
	SAP_REGION,
	SAP_STATE_CD,
	SAP_CITY,
	SAP_POST_CD,
	SAP_CHNL_CD,
	SAP_CHNL_DESC,
	SAP_SLS_OFFICE_CD,
	SAP_SLS_OFFICE_DESC,
	SAP_SLS_GRP_CD,
	SAP_SLS_GRP_DESC,
	SAP_PRNT_CUST_KEY,
	SAP_PRNT_CUST_DESC,
	SAP_CUST_CHNL_KEY,
	SAP_CUST_CHNL_DESC,
	SAP_CUST_SUB_CHNL_KEY,
	SAP_SUB_CHNL_DESC,
	SAP_GO_TO_MDL_KEY,
	SAP_GO_TO_MDL_DESC,
	SAP_BNR_KEY,
	SAP_BNR_DESC,
	SAP_BNR_FRMT_KEY,
	SAP_BNR_FRMT_DESC,
	RETAIL_ENV
) as 
SELECT inventory.typ,
    inventory.cntry_cd,
    inventory.cntry_nm,
    inventory.bill_date,
    inventory.dstrbtr_grp_cd,
    inventory.dstrbtr_nm,
    inventory.dstrbtr_matl_num,
    inventory.warehse_cd,
    inventory.warehse_grp,
    inventory.batch_expiry_date,
    inventory.pka_root_code AS root_code,
    inventory.inv_qty,
    inventory.inv_amt,
    inventory.sls_prc2,
    inventory.unit_per_case,
    inventory.cases,
    inventory.eaches,
    inventory.sls_amt,
    inventory.total_bht,
    "time"."year",
    "time".qrtr,
    "time".mnth_id,
    "time".mnth_no,
    "time".wk,
    "time".mnth_wk_no,
    "time".cal_date,
    matl.sap_mat_desc AS sku_description,
    matl.gph_prod_frnchse AS franchise,
    CASE
        WHEN (
            "left"((inventory.dstrbtr_matl_num)::text, 1) = ((9)::character varying)::text
        ) THEN 'FOC'::character varying
        WHEN (
            "left"((inventory.dstrbtr_matl_num)::text, 2) = ((99)::character varying)::text
        ) THEN 'FOC'::character varying
        WHEN (
            "left"((inventory.dstrbtr_matl_num)::text, 2) = ((89)::character varying)::text
        ) THEN 'PREMIUM'::character varying
        ELSE matl.gph_prod_brnd
    END AS brand,
    matl.gph_prod_vrnt AS variant,
    matl.gph_prod_sgmnt AS segment,
    matl.gph_prod_put_up_desc AS put_up_description,
    matl.prod_sub_brand,
    matl.prod_subsegment,
    matl.prod_category,
    matl.prod_subcategory,
    cust.sap_cust_id,
    cust.sap_cust_nm,
    cust.sap_sls_org,
    cust.sap_cmp_id,
    cust.sap_cntry_cd,
    cust.sap_cntry_nm,
    cust.sap_addr,
    cust.sap_region,
    cust.sap_state_cd,
    cust.sap_city,
    cust.sap_post_cd,
    cust.sap_chnl_cd,
    cust.sap_chnl_desc,
    cust.sap_sls_office_cd,
    cust.sap_sls_office_desc,
    cust.sap_sls_grp_cd,
    cust.sap_sls_grp_desc,
    cust.sap_prnt_cust_key,
    cust.sap_prnt_cust_desc,
    cust.sap_cust_chnl_key,
    cust.sap_cust_chnl_desc,
    cust.sap_cust_sub_chnl_key,
    cust.sap_sub_chnl_desc,
    cust.sap_go_to_mdl_key,
    cust.sap_go_to_mdl_desc,
    cust.sap_bnr_key,
    cust.sap_bnr_desc,
    cust.sap_bnr_frmt_key,
    cust.sap_bnr_frmt_desc,
    cust.retail_env
FROM (
        (
            (
                (
                    SELECT inv_f.typ,
                        inv_f.cntry_cd,
                        inv_f.cntry_nm,
                        inv_f.bill_date,
                        inv_f.dstrbtr_grp_cd,
                        inv_f.dstrbtr_nm,
                        inv_f.dstrbtr_matl_num,
                        inv_f.warehse_cd,
                        inv_f.pka_root_code,
                        inv_f.warehse_grp,
                        inv_f.batch_expiry_date,
                        inv_f.inv_qty,
                        inv_f.inv_amt,
                        inv_f.sls_prc2,
                        inv_f.unit_per_case,
                        inv_f.cases,
                        inv_f.eaches,
                        inv_f.sls_amt,
                        round(
                            (
                                (
                                    (
                                        ((inv_f.cases)::numeric)::numeric(18, 0) * inv_f.sls_amt
                                    ) * ((inv_f.unit_per_case)::numeric)::numeric(18, 0)
                                ) + (inv_f.eaches * inv_f.sls_amt)
                            ),
                            2
                        ) AS total_bht
                    FROM (
                            SELECT inv.typ,
                                inv.cntry_cd,
                                inv.cntry_nm,
                                inv.bill_date,
                                inv.dstrbtr_grp_cd,
                                inv.dstrbtr_nm,
                                inv.dstrbtr_matl_num,
                                inv.warehse_cd,
                                inv.pka_root_code,
                                inv.warehse_grp,
                                inv.batch_expiry_date,
                                inv.inv_qty,
                                inv.inv_amt,
                                inv.sls_prc2,
                                inv.unit_per_case,
                                CASE
                                    WHEN (
                                        ((inv.unit_per_case)::numeric)::numeric(18, 0) < inv.inv_qty
                                    ) THEN (
                                        "substring"(
                                            (
                                                (
                                                    (
                                                        round(
                                                            (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                            2
                                                        ) / ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                                    )
                                                )::character varying
                                            )::text,
                                            0,
                                            charindex(
                                                ('.'::character varying)::text,
                                                (
                                                    (
                                                        (
                                                            round(
                                                                (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                                2
                                                            ) / ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                                        )
                                                    )::character varying
                                                )::text
                                            )
                                        )
                                    )::integer
                                    WHEN (
                                        ((inv.unit_per_case)::numeric)::numeric(18, 0) >= inv.inv_qty
                                    ) THEN CASE
                                        WHEN (
                                            ((inv.unit_per_case)::numeric)::numeric(18, 0) > round(
                                                (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                2
                                            )
                                        ) THEN 0
                                        ELSE (
                                            "substring"(
                                                (
                                                    (
                                                        (
                                                            round(
                                                                (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                                2
                                                            ) / ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                                        )
                                                    )::character varying
                                                )::text,
                                                0,
                                                charindex(
                                                    ('.'::character varying)::text,
                                                    (
                                                        (
                                                            (
                                                                round(
                                                                    (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                                    2
                                                                ) / ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                                            )
                                                        )::character varying
                                                    )::text
                                                )
                                            )
                                        )::integer
                                    END
                                    ELSE NULL::integer
                                END AS cases,
                                CASE
                                    WHEN (
                                        ((inv.unit_per_case)::numeric)::numeric(18, 0) < inv.inv_qty
                                    ) THEN (
                                        round(
                                            (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                            2
                                        ) % ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                    )
                                    WHEN (
                                        ((inv.unit_per_case)::numeric)::numeric(18, 0) >= inv.inv_qty
                                    ) THEN CASE
                                        WHEN (
                                            ((inv.unit_per_case)::numeric)::numeric(18, 0) > round(
                                                (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                2
                                            )
                                        ) THEN round(
                                            (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                            2
                                        )
                                        ELSE (
                                            round(
                                                (inv.inv_qty * ((12)::numeric)::numeric(18, 0)),
                                                2
                                            ) % ((inv.unit_per_case)::numeric)::numeric(18, 0)
                                        )
                                    END
                                    ELSE (NULL::numeric)::numeric(18, 0)
                                END AS eaches,
                                (inv.sls_prc2 / ((12)::numeric)::numeric(18, 0)) AS sls_amt
                            FROM (
                                    SELECT 'Inventory'::character varying AS typ,
                                        'TH'::character varying AS cntry_cd,
                                        'Thailand'::character varying AS cntry_nm,
                                        inventory.inv_dt AS bill_date,
                                        inventory.dstrbtr_grp_cd,
                                        inventory.dstrbtr_matl_num,
                                        inventory.warehse_cd,
                                        mtldim.pka_root_code,
                                        cdim.dstrbtr_nm,
                                        CASE
                                            WHEN (
                                                "substring"((inventory.warehse_cd)::text, 2, 1) = ('7'::character varying)::text
                                            ) THEN 'Damage Goods'::character varying
                                            WHEN (
                                                (inventory.warehse_cd)::text = ('V902'::character varying)::text
                                            ) THEN 'Damage Goods'::character varying
                                            WHEN (
                                                (
                                                    "substring"((inventory.warehse_cd)::text, 2, 1) <> ('7'::character varying)::text
                                                )
                                                OR (
                                                    (inventory.warehse_cd)::text <> ('V902'::character varying)::text
                                                )
                                            ) THEN 'Normal Goods'::character varying
                                            ELSE NULL::character varying
                                        END AS warehse_grp,
                                        inventory.batch_expiry_date,
                                        inventory.inv_qty,
                                        inventory.inv_amt,
                                        itg_material.sls_prc2,
                                        itg_material.unit_per_case
                                    FROM (
                                            (
                                                (
                                                    (
                                                        SELECT itg_th_dms_inventory_fact.whcode AS warehse_cd,
                                                            itg_th_dms_inventory_fact.distributorid AS dstrbtr_grp_cd,
                                                            itg_th_dms_inventory_fact.productcode AS dstrbtr_matl_num,
                                                            itg_th_dms_inventory_fact.recdate AS inv_dt,
                                                            itg_th_dms_inventory_fact.expirydate AS batch_expiry_date,
                                                            sum(itg_th_dms_inventory_fact.qty) AS inv_qty,
                                                            sum(itg_th_dms_inventory_fact.amount) AS inv_amt
                                                        FROM itg_th_dms_inventory_fact
                                                        WHERE (
                                                                (
                                                                    itg_th_dms_inventory_fact.qty > (((0)::numeric)::numeric(18, 0))::numeric(19, 6)
                                                                )
                                                                AND (
                                                                    itg_th_dms_inventory_fact.distributorid IN (
                                                                        SELECT DISTINCT itg_th_dms_inventory_fact.distributorid
                                                                        FROM itg_th_dms_inventory_fact
                                                                        WHERE (itg_th_dms_inventory_fact.expirydate IS NOT NULL)
                                                                    )
                                                                )
                                                            )
                                                        GROUP BY itg_th_dms_inventory_fact.whcode,
                                                            itg_th_dms_inventory_fact.distributorid,
                                                            itg_th_dms_inventory_fact.productcode,
                                                            itg_th_dms_inventory_fact.recdate,
                                                            itg_th_dms_inventory_fact.expirydate
                                                    ) inventory
                                                    LEFT JOIN aspedw_integration.edw_material_dim mtldim ON (
                                                        (
                                                            (inventory.dstrbtr_matl_num)::text = (
                                                                (
                                                                    ltrim(
                                                                        (mtldim.matl_num)::text,
                                                                        ((0)::character varying)::text
                                                                    )
                                                                )::character varying
                                                            )::text
                                                        )
                                                    )
                                                )
                                                LEFT JOIN (
                                                    SELECT derived_table1.dstrbtr_id,
                                                        derived_table1.dstrbtr_nm,
                                                        derived_table1.rn
                                                    FROM (
                                                            SELECT itg_th_dstrbtr_customer_dim.dstrbtr_id,
                                                                itg_th_dstrbtr_customer_dim.dstrbtr_nm,
                                                                row_number() OVER(
                                                                    PARTITION BY itg_th_dstrbtr_customer_dim.dstrbtr_id
                                                                    ORDER BY itg_th_dstrbtr_customer_dim.dstrbtr_nm
                                                                ) AS rn
                                                            FROM itg_th_dstrbtr_customer_dim
                                                        ) derived_table1
                                                    WHERE (derived_table1.rn = 1)
                                                ) cdim ON (
                                                    (
                                                        (inventory.dstrbtr_grp_cd)::text = (cdim.dstrbtr_id)::text
                                                    )
                                                )
                                            )
                                            LEFT JOIN (
                                                SELECT DISTINCT itg_th_dtsitemmaster.item_cd,
                                                    itg_th_dtsitemmaster.sls_prc2,
                                                    itg_th_dtsitemmaster.unit_per_case
                                                FROM itg_th_dtsitemmaster
                                            ) itg_material ON (
                                                (
                                                    (inventory.dstrbtr_matl_num)::text = (itg_material.item_cd)::text
                                                )
                                            )
                                        )
                                ) inv
                        ) inv_f
                ) inventory
                RIGHT JOIN (
                    SELECT DISTINCT edw_vw_os_time_dim."year",
                        edw_vw_os_time_dim.qrtr,
                        edw_vw_os_time_dim.mnth_id,
                        edw_vw_os_time_dim.mnth_no,
                        edw_vw_os_time_dim.wk,
                        edw_vw_os_time_dim.mnth_wk_no,
                        edw_vw_os_time_dim.cal_date
                    FROM oseedw_access.edw_vw_os_time_dim edw_vw_os_time_dim
                    WHERE (
                            (
                                edw_vw_os_time_dim."year" > (
                                    "date_part"(
                                        year,
                                        (current_timestamp::character varying)::timestamp without time zone
                                    ) - 3
                                )
                            )
                            OR (
                                edw_vw_os_time_dim."year" > (
                                    "date_part"(
                                        year,
                                        (current_timestamp::character varying)::timestamp without time zone
                                    ) - 3
                                )
                            )
                        )
                ) "time" ON (
                    (
                        inventory.bill_date = ("time".cal_date)::timestamp without time zone
                    )
                )
            )
            LEFT JOIN (
                SELECT DISTINCT edw_vw_th_material_dim.cntry_key,
                    edw_vw_th_material_dim.sap_matl_num,
                    edw_vw_th_material_dim.sap_mat_desc,
                    edw_vw_th_material_dim.gph_region,
                    edw_vw_th_material_dim.gph_prod_frnchse,
                    edw_vw_th_material_dim.gph_prod_brnd,
                    edw_vw_th_material_dim.gph_prod_vrnt,
                    edw_vw_th_material_dim.gph_prod_sgmnt,
                    edw_vw_th_material_dim.gph_prod_put_up_desc,
                    edw_vw_th_material_dim.gph_prod_sub_brnd AS prod_sub_brand,
                    edw_vw_th_material_dim.gph_prod_subsgmnt AS prod_subsegment,
                    edw_vw_th_material_dim.gph_prod_ctgry AS prod_category,
                    edw_vw_th_material_dim.gph_prod_subctgry AS prod_subcategory
                FROM thaedw_integration.edw_vw_th_material_dim
                WHERE (
                        (edw_vw_th_material_dim.cntry_key)::text = ('TH'::character varying)::text
                    )
            ) matl ON (
                (
                    upper((inventory.dstrbtr_matl_num)::text) = upper(
                        ltrim(
                            (matl.sap_matl_num)::text,
                            ('0'::character varying)::text
                        )
                    )
                )
            )
        )
        LEFT JOIN (
            SELECT sellout_cust.dstrbtr_grp_cd,
                sellin_cust.sap_cust_id,
                sellin_cust.sap_cust_nm,
                sellin_cust.sap_sls_org,
                sellin_cust.sap_cmp_id,
                sellin_cust.sap_cntry_cd,
                sellin_cust.sap_cntry_nm,
                sellin_cust.sap_addr,
                sellin_cust.sap_region,
                sellin_cust.sap_state_cd,
                sellin_cust.sap_city,
                sellin_cust.sap_post_cd,
                sellin_cust.sap_chnl_cd,
                sellin_cust.sap_chnl_desc,
                sellin_cust.sap_sls_office_cd,
                sellin_cust.sap_sls_office_desc,
                sellin_cust.sap_sls_grp_cd,
                sellin_cust.sap_sls_grp_desc,
                sellin_cust.sap_prnt_cust_key,
                sellin_cust.sap_prnt_cust_desc,
                sellin_cust.sap_cust_chnl_key,
                sellin_cust.sap_cust_chnl_desc,
                sellin_cust.sap_cust_sub_chnl_key,
                sellin_cust.sap_sub_chnl_desc,
                sellin_cust.sap_go_to_mdl_key,
                sellin_cust.sap_go_to_mdl_desc,
                sellin_cust.sap_bnr_key,
                sellin_cust.sap_bnr_desc,
                sellin_cust.sap_bnr_frmt_key,
                sellin_cust.sap_bnr_frmt_desc,
                sellin_cust.retail_env
            FROM (
                    (
                        SELECT DISTINCT edw_vw_th_dstrbtr_customer_dim.dstrbtr_grp_cd,
                            edw_vw_th_dstrbtr_customer_dim.sap_soldto_code
                        FROM thaedw_integration.edw_vw_th_dstrbtr_customer_dim
                        WHERE (
                                (edw_vw_th_dstrbtr_customer_dim.cntry_cd)::text = ('TH'::character varying)::text
                            )
                    ) sellout_cust
                    JOIN thaedw_integration.edw_vw_th_customer_dim sellin_cust ON (
                        (
                            (sellout_cust.sap_soldto_code)::text = (sellin_cust.sap_cust_id)::text
                        )
                    )
                )
        ) cust ON (
            (
                (cust.dstrbtr_grp_cd)::text = (inventory.dstrbtr_grp_cd)::text
            )
        )
    );
