insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_my_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_ph_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_kr_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_sg_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_th_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_in_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_anz_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_jp_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_cnsc_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_cnpc_rpt_retail_excellence_summary;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.aspedw_integration__edw_rpt_retail_excellence_summary 
select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_528.ASPEDW_INTEGRATION__edw_id_rpt_retail_excellence_summary;
