insert into PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS
values
('CNSC','EXCLUDE_RE_BASE_RET_ENV','t1-'),
('CNSC','EXCLUDE_RE_BASE_RET_ENV','t2-'),
('CNSC','EXCLUDE_RE_BASE_RET_ENV','other-'),
('CNSC','EXCLUDE_RE_BASE_RET_ENV','c-pool-audit-'),
('CNSC','EXCLUDE_RE_BASE_RET_ENV','cbd-批发');
