create or replace view PROD_DNA_CORE.DBT_CLOUD_PR_5458_963.ASPEDW_ACCESS__EDW_PERFECT_STORE_REBASE_WT(
	"hashkey",
	"hash_row",
	"dataset",
	"customerid",
	"salespersonid",
	"visitid",
	"questiontext",
	"productid",
	"kpi",
	"scheduleddate",
	"latestdate",
	"fisc_yr",
	"fisc_per",
	"merchandiser_name",
	"customername",
	"country",
	"state",
	"parent_customer",
	"retail_environment",
	"channel",
	"retailer",
	"business_unit",
	"eannumber",
	"matl_num",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"ques_type",
	"y/n_flag",
	"priority_store_flag",
	"add_info",
	"response",
	"response_score",
	"kpi_chnl_wt",
	"channel_weightage",
	"weight_msl",
	"weight_oos",
	"weight_soa",
	"weight_sos",
	"weight_promo",
	"weight_planogram",
	"weight_display",
	"mkt_share",
	"salience_val",
	"actual_value",
	"ref_value",
	"kpi_actual_wt_val",
	"kpi_ref_val",
	"kpi_ref_wt_val",
	"photo_url",
	"compliance",
	"gap_to_target",
	"compliance_propogated",
	"gap_propagated",
	"full_opportunity_lcy",
	"weighted_opportunity_lcy",
	"full_opportunity_usd",
	"weighted_opportunity_usd",
	"sotp_lcy",
	"sotp_usd",
	"store_grade"
) as
SELECT
    hashkey AS "hashkey",
    hash_row AS "hash_row",
    dataset AS "dataset",
    customerid AS "customerid",
    salespersonid AS "salespersonid",
    visitid AS "visitid",
    questiontext AS "questiontext",
    productid AS "productid",
    kpi AS "kpi",
    scheduleddate AS "scheduleddate",
    latestdate AS "latestdate",
    fisc_yr AS "fisc_yr",
    fisc_per AS "fisc_per",
    merchandiser_name AS "merchandiser_name",
    customername AS "customername",
    country AS "country",
    state AS "state",
    parent_customer AS "parent_customer",
    retail_environment AS "retail_environment",
    channel AS "channel",
    retailer AS "retailer",
    business_unit AS "business_unit",
    eannumber AS "eannumber",
    matl_num AS "matl_num",
    prod_hier_l1 AS "prod_hier_l1",
    prod_hier_l2 AS "prod_hier_l2",
    prod_hier_l3 AS "prod_hier_l3",
    prod_hier_l4 AS "prod_hier_l4",
    prod_hier_l5 AS "prod_hier_l5",
    prod_hier_l6 AS "prod_hier_l6",
    prod_hier_l7 AS "prod_hier_l7",
    prod_hier_l8 AS "prod_hier_l8",
    prod_hier_l9 AS "prod_hier_l9",
    ques_type AS "ques_type",
    "y/n_flag" AS "y/n_flag",
    priority_store_flag AS "priority_store_flag",
    add_info AS "add_info",
    response AS "response",
    response_score AS "response_score",
    kpi_chnl_wt AS "kpi_chnl_wt",
    channel_weightage AS "channel_weightage",
    weight_msl AS "weight_msl",
    weight_oos AS "weight_oos",
    weight_soa AS "weight_soa",
    weight_sos AS "weight_sos",
    weight_promo AS "weight_promo",
    weight_planogram AS "weight_planogram",
    weight_display AS "weight_display",
    mkt_share AS "mkt_share",
    salience_val AS "salience_val",
    actual_value AS "actual_value",
    ref_value AS "ref_value",
    kpi_actual_wt_val AS "kpi_actual_wt_val",
    kpi_ref_val AS "kpi_ref_val",
    kpi_ref_wt_val AS "kpi_ref_wt_val",
    photo_url AS "photo_url",
    compliance AS "compliance",
    gap_to_target AS "gap_to_target",
    compliance_propogated AS "compliance_propogated",
    gap_propagated AS "gap_propagated",
    full_opportunity_lcy AS "full_opportunity_lcy",
    weighted_opportunity_lcy AS "weighted_opportunity_lcy",
    full_opportunity_usd AS "full_opportunity_usd",
    weighted_opportunity_usd AS "weighted_opportunity_usd",
    sotp_lcy AS "sotp_lcy",
    sotp_usd AS "sotp_usd",
    store_grade AS "store_grade"
FROM PROD_DNA_CORE.DBT_CLOUD_PR_5458_963.ASPEDW_INTEGRATION__EDW_PERFECT_STORE_REBASE_WT;
