insert into core_integration.dbtjobs_test_cdc_metadata values('my_sellin','15','(\'sdl_my_dstrbtrr_dim\',\'sdl_my_dstrbtr_doc_type\',\'sdl_my_in_transit\')','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('my_sellout','14','(\'sdl_my_customer_dim\')','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('my_pos','13','(\'sdl_my_pos_cust_mstr\')','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('my_joint_monthly','19','(\'sdl_my_monthly_sellout_stock_fact\',\'sdl_my_monthly_sellout_sales_fact\')','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('my_sellout_sales_morning','16','(\'sdl_so_sales_133986\', \'sdl_so_sales_133980\', \'sdl_so_sales_133981\', \'sdl_so_sales_133982\', \'sdl_so_sales_133983\', \'sdl_so_sales_133984\', \'sdl_so_sales_133985\', \'sdl_so_sales_131164\', \'sdl_so_sales_131165\', \'sdl_so_sales_131166\', \'sdl_so_sales_131167\', \'sdl_so_sales_130516\', \'sdl_so_sales_130517\', \'sdl_so_sales_130518\', \'sdl_so_sales_130519\', \'sdl_so_sales_130520\', \'sdl_so_sales_130521\', \'sdl_so_sales_119024\', \'sdl_so_sales_119025\', \'sdl_so_sales_108129\', \'sdl_so_sales_108273\', \'sdl_so_sales_108565\', \'sdl_so_sales_118477\', \'sdl_so_sales_109772\', \'sdl_so_sales_135976\', \'sdl_so_sales_137021\')','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('my_sellout_inv','18','(\'sdl_so_inv_133986\' ,\'sdl_so_inv_133980\' ,\'sdl_so_inv_133981\' ,\'sdl_so_inv_133982\' ,\'sdl_so_inv_133983\' ,\'sdl_so_inv_133984\' ,\'sdl_so_inv_133985\' ,\'sdl_so_inv_131164\' ,\'sdl_so_inv_131165\' ,\'sdl_so_inv_131166\' ,\'sdl_so_inv_131167\' ,\'sdl_so_inv_130516\' ,\'sdl_so_inv_130517\' ,\'sdl_so_inv_130518\' ,\'sdl_so_inv_130519\' ,\'sdl_so_inv_130520\' ,\'sdl_so_inv_130521\' ,\'sdl_so_inv_119024\',\'sdl_so_inv_119025\' ,\'sdl_so_inv_108129\' ,\'sdl_so_inv_108273\' ,\'sdl_so_inv_108565\' ,\'sdl_so_inv_118477\' ,\'sdl_so_inv_109772\' ,\'sdl_so_inv_135976\',\'sdl_so_inv_137021\' )','0');
insert into core_integration.dbtjobs_test_cdc_metadata values('j_rg_watsons_inv_ingestion','17','(\'sdl_my_as_watsons_inventory\')','0');

--------------------------------------

insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_customer_dim','select * from myswks_integration.TRATBL_sdl_my_customer_dim__duplicate_test union all select * from myswks_integration.TRATBL_sdl_my_customer_dim__null_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_pos_cust_mstr','select * from myswks_integration.TRATBL_sdl_my_pos_cust_mstr__duplicate_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133986','select * from myswks_integration.TRATBL_sdl_so_inv_133986__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133980','select * from myswks_integration.TRATBL_sdl_so_inv_133980__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133981','select * from myswks_integration.TRATBL_sdl_so_inv_133981__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133982','select * from myswks_integration.TRATBL_sdl_so_inv_133982__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133983','select * from myswks_integration.TRATBL_sdl_so_inv_133983__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133984','select * from myswks_integration.TRATBL_sdl_so_inv_133984__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_133985','select * from myswks_integration.TRATBL_sdl_so_inv_133985__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_131164','select * from myswks_integration.TRATBL_sdl_so_inv_131164__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_131165','select * from myswks_integration.TRATBL_sdl_so_inv_131165__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_131166','select * from myswks_integration.TRATBL_sdl_so_inv_131166__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_131167','select * from myswks_integration.TRATBL_sdl_so_inv_131167__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130516','select * from myswks_integration.TRATBL_sdl_so_inv_130516__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130517','select * from myswks_integration.TRATBL_sdl_so_inv_130517__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130518','select * from myswks_integration.TRATBL_sdl_so_inv_130518__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130519','select * from myswks_integration.TRATBL_sdl_so_inv_130519__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130520','select * from myswks_integration.TRATBL_sdl_so_inv_130520__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_130521','select * from myswks_integration.TRATBL_sdl_so_inv_130521__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_119024','select * from myswks_integration.TRATBL_sdl_so_inv_119024__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_119025','select * from myswks_integration.TRATBL_sdl_so_inv_119025__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_108129','select * from myswks_integration.TRATBL_sdl_so_inv_108129__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_108273','select * from myswks_integration.TRATBL_sdl_so_inv_108273__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_108565','select * from myswks_integration.TRATBL_sdl_so_inv_108565__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_118477','select * from myswks_integration.TRATBL_sdl_so_inv_118477__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_109772','select * from myswks_integration.TRATBL_sdl_so_inv_109772__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_135976','select * from myswks_integration.TRATBL_sdl_so_inv_135976__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_inv_137021','select * from myswks_integration.TRATBL_sdl_so_inv_137021__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_monthly_sellout_stock_fact','select * from myswks_integration.TRATBL_sdl_my_monthly_sellout_stock_fact__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_monthly_sellout_sales_fact','select * from myswks_integration.TRATBL_sdl_my_monthly_sellout_sales_fact__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133986','select * from myswks_integration.TRATBL_sdl_so_sales_133986__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133980','select * from myswks_integration.TRATBL_sdl_so_sales_133980__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133981','select * from myswks_integration.TRATBL_sdl_so_sales_133981__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133982','select * from myswks_integration.TRATBL_sdl_so_sales_133982__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133983','select * from myswks_integration.TRATBL_sdl_so_sales_133983__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133984','select * from myswks_integration.TRATBL_sdl_so_sales_133984__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_133985','select * from myswks_integration.TRATBL_sdl_so_sales_133985__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_131164','select * from myswks_integration.TRATBL_sdl_so_sales_131164__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_131165','select * from myswks_integration.TRATBL_sdl_so_sales_131165__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_131166','select * from myswks_integration.TRATBL_sdl_so_sales_131166__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_131167','select * from myswks_integration.TRATBL_sdl_so_sales_131167__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130516','select * from myswks_integration.TRATBL_sdl_so_sales_130516__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130517','select * from myswks_integration.TRATBL_sdl_so_sales_130517__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130518','select * from myswks_integration.TRATBL_sdl_so_sales_130518__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130519','select * from myswks_integration.TRATBL_sdl_so_sales_130519__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130520','select * from myswks_integration.TRATBL_sdl_so_sales_130520__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_130521','select * from myswks_integration.TRATBL_sdl_so_sales_130521__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_119024','select * from myswks_integration.TRATBL_sdl_so_sales_119024__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_119025','select * from myswks_integration.TRATBL_sdl_so_sales_119025__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_108129','select * from myswks_integration.TRATBL_sdl_so_sales_108129__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_108273','select * from myswks_integration.TRATBL_sdl_so_sales_108273__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_108565','select * from myswks_integration.TRATBL_sdl_so_sales_108565__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_118477','select * from myswks_integration.TRATBL_sdl_so_sales_118477__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_109772','select * from myswks_integration.TRATBL_sdl_so_sales_109772__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_135976','select * from myswks_integration.TRATBL_sdl_so_sales_135976__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_so_sales_137021','select * from myswks_integration.TRATBL_sdl_so_sales_137021__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_dstrbtrr_dim','select * from myswks_integration.TRATBL_sdl_my_dstrbtrr_dim__duplicate_test union all select * from myswks_integration.TRATBL_sdl_my_dstrbtrr_dim__null_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_dstrbtr_doc_type','select * from myswks_integration.TRATBL_sdl_my_dstrbtr_doc_type__duplicate_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_in_transit','select * from myswks_integration.TRATBL_sdl_my_in_transit__duplicate_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_as_watsons_inventory','select * from myswks_integration.TRATBL_sdl_my_as_watsons_inventory__duplicate_test union all select * from myswks_integration.TRATBL_sdl_my_as_watsons_inventory__null_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_accruals','select * from myswks_integration.TRATBL_sdl_my_accruals__null_test union all select * from myswks_integration.TRATBL_sdl_my_accruals__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_afgr','select * from myswks_integration.TRATBL_sdl_my_afgr__null_test union all select * from myswks_integration.TRATBL_sdl_my_afgr__duplicate_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_trgts','select * from myswks_integration.TRATBL_sdl_my_trgts__null_test union all select * from myswks_integration.TRATBL_sdl_my_trgts__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_le_trgt','select * from myswks_integration.TRATBL_sdl_my_le_trgt__lookup_test;');
insert into CORE_INTEGRATION.DBTTEST_TABLES_METADATA values('sdl_my_ciw_map','select * from myswks_integration.TRATBL_sdl_my_ciw_map__null_test union all select * from myswks_integration.TRATBL_sdl_my_ciw_map__duplicate_test;');
