delete  from  PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT
where to_char(snap_shot_dt, 'YYYYMM') in (202409);

delete  from  PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP
where to_char(snap_shot_dt, 'YYYYMM') in (202409);

insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_SYNC 
where to_char(snap_shot_dt, 'YYYYMM') in (202409);

insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_SYNC 
where to_char(snap_shot_dt, 'YYYYMM') in (202409);
