alter table prod_dna_core.idnitg_integration.itg_distributor_ivy_inventory add column file_name varchar(255);
alter table prod_dna_core.idnitg_integration.itg_distributor_ivy_user_master add column file_name varchar(255);
alter table prod_dna_core.idnitg_integration.itg_all_ivy_distributor_sellout_sales_fact add column file_name varchar(255);
alter table prod_dna_core.idnitg_integration.itg_distributor_ivy_order add column file_name varchar(255);
alter table prod_dna_core.idnitg_integration.itg_distributor_ivy_outlet_master add column file_name varchar(255);
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_RAW_DISTRIBUTOR_IVY_INVENTORY rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_RAW_DISTRIBUTOR_IVY_USER_MASTER  rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_RAW_DISTRIBUTOR_IVY_MERCHANDISING rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.ITG_DISTRIBUTOR_IVY_MERCHANDISING rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_RAW_DISTRIBUTOR_IVY_INVOICE rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_RAW_DISTRIBUTOR_IVY_ORDER rename column source_file_name to file_name;
alter table PROD_DNA_CORE.IDNITG_INTEGRATION.SDL_DISTRIBUTOR_CUSTOMER_DIM_RAW rename column filename to file_name;
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_in_iqvia_sales add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_in_iqvia_speciality add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_in_iqvia_brand add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_in_iqvia_brandtemp1 add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_in_iqvia_indication add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_click_data add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_forward_data add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_open_data add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_sent_data add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_hcp_details add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_unsubscribe_data add column file_name varchar(255);
alter table PROD_DNA_CORE.HCPITG_INTEGRATION.itg_hcp360_sfmc_bounce_data add column file_name varchar(255);
