create table PROD_DNA_CORE.pcfedw_integration.EDW_PACIFIC_PERENSO_IMS_ANALYSIS_19042024 clone PROD_DNA_CORE.pcfedw_integration.EDW_PACIFIC_PERENSO_IMS_ANALYSIS;
create table PROD_DNA_CORE.pcfedw_integration.edw_promax_analysis_snapshot_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_promax_analysis_snapshot;
create table PROD_DNA_CORE.pcfedw_integration.edw_px_master_fact_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_px_master_fact;
create table PROD_DNA_CORE.pcfedw_integration.edw_px_term_plan_ext_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_px_term_plan_ext;
create table PROD_DNA_CORE.pcfedw_integration.px_combined_ciw_fact_19042024 clone PROD_DNA_CORE.pcfedw_integration.px_combined_ciw_fact;
create table PROD_DNA_CORE.pcfedw_integration.edw_invoice_fact_snapshot_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_invoice_fact_snapshot;
create table PROD_DNA_CORE.pcfedw_integration.dly_sls_cust_attrb_lkp_19042024 clone PROD_DNA_CORE.pcfedw_integration.dly_sls_cust_attrb_lkp;
create table PROD_DNA_CORE.pcfedw_integration.edw_gts_visibility_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_gts_visibility;
create table PROD_DNA_CORE.PCFITG_INTEGRATION.ITG_IRI_SCAN_SALES_19042024 clone PROD_DNA_CORE.PCFITG_INTEGRATION.ITG_IRI_SCAN_SALES;
create table PROD_DNA_CORE.pcfedw_integration.edw_demand_forecast_snapshot_19042024 clone PROD_DNA_CORE.pcfedw_integration.edw_demand_forecast_snapshot;
create table PROD_DNA_CORE.pcfedw_integration.EDW_PACIFIC_PERENSO_IMS_PHARMACY_SNPSHOT_ANALYSIS_19042024 clone PROD_DNA_CORE.pcfedw_integration.EDW_PACIFIC_PERENSO_IMS_PHARMACY_SNPSHOT_ANALYSIS;
create table PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_SALES_REPORTING_19042024 clone PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_SALES_REPORTING;
create table PROD_DNA_CORE.pcfedw_integration.rpt_promo_analysis_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.v_rpt_promo_analysis;
create table PROD_DNA_CORE.pcfedw_integration.rpt_invoice_analysis_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_invoice_analysis;
create table PROD_DNA_CORE.pcfedw_integration.px_master_analysis_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_px_master_analysis;
create table PROD_DNA_CORE.pcfedw_integration.demand_forecast_analysis_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_demand_forecast_analysis;
create table PROD_DNA_CORE.pcfedw_integration.customer_dim_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_customer_dim;
create table PROD_DNA_CORE.pcfedw_integration.apo_parent_child_dim_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_apo_parent_child_dim;
create table PROD_DNA_CORE.pcfedw_integration.sapbw_futures_fact_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_sapbw_futures_fact;
create table PROD_DNA_CORE.pcfedw_integration.sapbw_fact_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_sapbw_fact;
create table PROD_DNA_CORE.pcfedw_integration.sapbw_ciw_fact_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_sapbw_ciw_fact;
create table PROD_DNA_CORE.pcfedw_integration.customer_dim_v2_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_customer_dim_v2;
create table PROD_DNA_CORE.pcfedw_integration.customer_dim_adj_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_customer_dim_adj;
create table PROD_DNA_CORE.pcfedw_integration.invoice_analysis_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.vw_invoice_analysis;
create table PROD_DNA_CORE.pcfedw_integration.IRI_SCAN_SALES_ANALYSIS_19042024 AS SELECT * FROM  PROD_DNA_CORE.pcfedw_integration.VW_IRI_SCAN_SALES_ANALYSIS;



