create or replace TABLE PROD_DNA_CORE.PCFEDW_INTEGRATION.DLY_SLS_CUST_ATTRB_LKP (
	SLS_ORG_CODE VARCHAR(500),
	SLS_ORG_NAME VARCHAR(500),
	SLS_ORG_ID NUMBER(20,4),
	CMP_ID_CODE VARCHAR(500),
	CMP_ID_NAME VARCHAR(500),
	CMP_ID_ID NUMBER(20,4),
	DSTR_CHNL_CODE VARCHAR(500),
	DSTR_CHNL_NAME VARCHAR(500),
	DSTR_CHNL_ID NUMBER(20,4),
	SLS_OFC_CODE VARCHAR(500),
	SLS_OFC_NAME VARCHAR(500),
	SLS_OFC_ID NUMBER(20,4),
	SLS_GRP_CODE VARCHAR(500),
	SLS_GRP_NAME VARCHAR(500),
	SLS_GRP_ID NUMBER(20,4),
	FCST_CHNL_CODE VARCHAR(500),
	FCST_CHNL_NAME VARCHAR(500),
	FCST_CHNL_ID NUMBER(20,4),
	CUSTOMER_SEGMENTATION_LEVEL_1_CODE VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_1_NAME VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_1_ID NUMBER(20,4),
	CUSTOMER_SEGMENTATION_LEVEL_2_CODE VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_2_NAME VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_2_ID NUMBER(20,4),
	ACTIVE_STATUS_CODE VARCHAR(500),
	ACTIVE_STATUS_NAME VARCHAR(500),
	ACTIVE_STATUS_ID NUMBER(20,4),
	CRT_DTTM TIMESTAMP_NTZ(9)
);
ALTER TABLE PROD_DNA_CORE.pcfedw_integration.edw_invoice_fact_snapshot 
ADD COLUMN CNFRM_QTY_PC number(38,7);
ALTER TABLE PROD_DNA_CORE.pcfedw_integration.edw_invoice_fact_snapshot 
ADD COLUMN ord_qty_pc number(38,7);
