alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_rt_mart  rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_ims_dstr_std_sel_out  rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_7eleven  rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_cosmed rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_ec rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_carrefour rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_px_civila rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_tw_pos_poya rename column filename to file_name;
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_ju_hj_life_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_nu_ri_zon_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_nacf_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_lotte_logistics_yang_ju_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_du_bae_ro_yu_tong_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_il_dong_hu_di_s_deok_seong_sang_sa_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_lotte_ak_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_daiso_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_dongbu_lsd_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_bo_young_jong_hap_logistics_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_hyundai_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_da_in_sang_sa_gt_sellout add column file_name varchar(255);
alter table prod_dna_core.ntaitg_integration.sdl_raw_kr_jungseok_gt_sellout add column file_name varchar(255);
