COPY INTO PCFITG_INTEGRATION.ITG_CHW_ECOMM_DATA FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/AU_ITG_ITG_CHW_ECOMM_DATA/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';

COPY INTO THAITG_INTEGRATION.ITG_TH_DMS_INVENTORY_FACT FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/OS_ITG_ITG_TH_DMS_INVENTORY_FACT/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';

COPY INTO PCFEDW_INTEGRATION.EDW_AU_PHARM_ECOMM_FACT FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/AU_EDW_EDW_AU_PHARM_ECOMM_FACT/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT';

COPY INTO PCFEDW_INTEGRATION.EDW_PHARMACY_ECOMMERCE_ANALYSIS FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/AU_EDW_EDW_PHARMACY_ECOMMERCE_ANALYSIS/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT' ;

COPY INTO PCFWKS_INTEGRATION.WKS_CHW_ECOMM_DATA FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/AU_WKS_WKS_CHW_ECOMM_DATA/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT' ;

COPY INTO PCFITG_INTEGRATION.ITG_NATIONAL_ECOMM_DATA FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/AU_ITG_ITG_NATIONAL_ECOMM_DATA/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT' ;

create or replace view PCFEDW_INTEGRATION.VW_CURR_EXCH_DIM(
	RATE_TYPE,
	FROM_CCY,
	TO_CCY,
	VALID_DATE,
	EXCH_RATE
) as

SELECT edw_crncy_exch.ex_rt_typ AS rate_type,
    edw_crncy_exch.from_crncy AS from_ccy,
    edw_crncy_exch.to_crncy AS to_ccy,
    (
        ((99999999)::numeric)::numeric(18, 0) - ((edw_crncy_exch.vld_from)::numeric)::numeric(18, 0)
    ) AS valid_date,
    edw_crncy_exch.ex_rt AS exch_rate
FROM aspedw_integration.edw_crncy_exch;
