use warehouse PROD_DNA_CORE_APP2_WH;

insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  in ('SAPBW_ACTUAL')
and to_char(snap_shot_dt, 'YYYYMM') = 202403;
