use warehouse PROD_DNA_CORE_APP2_WH;

create table PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp2
as select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  in ('SAPBW_ACTUAL');
