

ALTER TABLE PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1 CLUSTER BY (snap_shot_dt, PAC_SUBSOURCE_TYPE,jj_period);

insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'PX_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') =202408
and jj_period >= 202408 ;
