insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202408
and jj_period >= 202408 ;


insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202407
and jj_period >= 202407 ;


insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202406
and jj_period >= 202406 ;


insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202405
and jj_period >= 202405 ;


insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202404
and jj_period >= 202404 ;


insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp
WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST'
and to_char(snap_shot_dt, 'YYYYMM') = 202403
and jj_period >= 202403 ;
