create or replace view DEV_DNA_CORE.ASPEDW_ACCESS.EDW_REG_INVENTORY_HEALTH_ANALYSIS_PROPAGATION(
	"year",
	"year_quarter",
	"month_year",
	"month_number",
	"country_name",
	"distributor_id",
	"distributor_id_name",
	"franchise",
	"brand",
	"prod_sub_brand",
	"variant",
	"segment",
	"prod_subsegment",
	"prod_category",
	"prod_subcategory",
	"put_up_description",
	"sku_cd",
	"sku_description",
	"pka_product_key",
	"pka_product_key_description",
	"product_key",
	"product_key_description",
	"from_ccy",
	"to_ccy",
	"exch_rate",
	"sap_prnt_cust_key",
	"sap_prnt_cust_desc",
	"sap_cust_chnl_key",
	"sap_cust_chnl_desc",
	"sap_cust_sub_chnl_key",
	"sap_sub_chnl_desc",
	"sap_go_to_mdl_key",
	"sap_go_to_mdl_desc",
	"sap_bnr_key",
	"sap_bnr_desc",
	"sap_bnr_frmt_key",
	"sap_bnr_frmt_desc",
	"retail_env",
	"region",
	"zone_or_area",
	"si_sls_qty",
	"si_gts_val",
	"si_gts_val_usd",
	"inventory_quantity",
	"inventory_val",
	"inventory_val_usd",
	"so_sls_qty",
	"so_grs_trd_sls",
	"so_grs_trd_sls_usd",
	"si_all_db_val",
	"si_all_db_val_usd",
	"si_inv_db_val",
	"si_inv_db_val_usd",
	"last_3months_so_qty",
	"last_6months_so_qty",
	"last_12months_so_qty",
	"last_3months_so_val",
	"last_3months_so_val_usd",
	"last_6months_so_val",
	"last_6months_so_val_usd",
	"last_12months_so_val",
	"last_12months_so_val_usd",
	"propagate_flag",
	"propagate_from",
	"reason",
	"last_36months_so_val",
	"healthy_inventory",
	"min_date",
	"diff_weeks",
	"l12m_weeks",
	"l6m_weeks",
	"l3m_weeks",
	"l12m_weeks_avg_sales",
	"l6m_weeks_avg_sales",
	"l3m_weeks_avg_sales",
	"l12m_weeks_avg_sales_usd",
	"l6m_weeks_avg_sales_usd",
	"l3m_weeks_avg_sales_usd",
	"l12m_weeks_avg_sales_qty",
	"l6m_weeks_avg_sales_qty",
	"l3m_weeks_avg_sales_qty"
) as
with source as (
    select * from aspedw_integration.edw_reg_inventory_health_analysis_propagation
),
final as (
    select
        year as "year",
        year_quarter as "year_quarter",
        month_year as "month_year",
        month_number as "month_number",
        country_name as "country_name",
        distributor_id as "distributor_id",
        distributor_id_name as "distributor_id_name",
        franchise as "franchise",
        brand as "brand",
        prod_sub_brand as "prod_sub_brand",
        variant as "variant",
        segment as "segment",
        prod_subsegment as "prod_subsegment",
        prod_category as "prod_category",
        prod_subcategory as "prod_subcategory",
        put_up_description as "put_up_description",
        sku_cd as "sku_cd",
        sku_description as "sku_description",
        pka_product_key as "pka_product_key",
        pka_product_key_description as "pka_product_key_description",
        product_key as "product_key",
        product_key_description as "product_key_description",
        from_ccy as "from_ccy",
        to_ccy as "to_ccy",
        exch_rate as "exch_rate",
        sap_prnt_cust_key as "sap_prnt_cust_key",
        sap_prnt_cust_desc as "sap_prnt_cust_desc",
        sap_cust_chnl_key as "sap_cust_chnl_key",
        sap_cust_chnl_desc as "sap_cust_chnl_desc",
        sap_cust_sub_chnl_key as "sap_cust_sub_chnl_key",
        sap_sub_chnl_desc as "sap_sub_chnl_desc",
        sap_go_to_mdl_key as "sap_go_to_mdl_key",
        sap_go_to_mdl_desc as "sap_go_to_mdl_desc",
        sap_bnr_key as "sap_bnr_key",
        sap_bnr_desc as "sap_bnr_desc",
        sap_bnr_frmt_key as "sap_bnr_frmt_key",
        sap_bnr_frmt_desc as "sap_bnr_frmt_desc",
        retail_env as "retail_env",
        region as "region",
        zone_or_area as "zone_or_area",
        si_sls_qty as "si_sls_qty",
        si_gts_val as "si_gts_val",
        si_gts_val_usd as "si_gts_val_usd",
        inventory_quantity as "inventory_quantity",
        inventory_val as "inventory_val",
        inventory_val_usd as "inventory_val_usd",
        so_sls_qty as "so_sls_qty",
        so_grs_trd_sls as "so_grs_trd_sls",
        so_grs_trd_sls_usd as "so_grs_trd_sls_usd",
        si_all_db_val as "si_all_db_val",
        si_all_db_val_usd as "si_all_db_val_usd",
        si_inv_db_val as "si_inv_db_val",
        si_inv_db_val_usd as "si_inv_db_val_usd",
        last_3months_so_qty as "last_3months_so_qty",
        last_6months_so_qty as "last_6months_so_qty",
        last_12months_so_qty as "last_12months_so_qty",
        last_3months_so_val as "last_3months_so_val",
        last_3months_so_val_usd as "last_3months_so_val_usd",
        last_6months_so_val as "last_6months_so_val",
        last_6months_so_val_usd as "last_6months_so_val_usd",
        last_12months_so_val as "last_12months_so_val",
        last_12months_so_val_usd as "last_12months_so_val_usd",
        propagate_flag as "propagate_flag",
        propagate_from as "propagate_from",
        reason as "reason",
        last_36months_so_val as "last_36months_so_val",
        healthy_inventory as "healthy_inventory",
        min_date as "min_date",
        diff_weeks as "diff_weeks",
        l12m_weeks as "l12m_weeks",
        l6m_weeks as "l6m_weeks",
        l3m_weeks as "l3m_weeks",
        l12m_weeks_avg_sales as "l12m_weeks_avg_sales",
        l6m_weeks_avg_sales as "l6m_weeks_avg_sales",
        l3m_weeks_avg_sales as "l3m_weeks_avg_sales",
        l12m_weeks_avg_sales_usd as "l12m_weeks_avg_sales_usd",
        l6m_weeks_avg_sales_usd as "l6m_weeks_avg_sales_usd",
        l3m_weeks_avg_sales_usd as "l3m_weeks_avg_sales_usd",
        l12m_weeks_avg_sales_qty as "l12m_weeks_avg_sales_qty",
        l6m_weeks_avg_sales_qty as "l6m_weeks_avg_sales_qty",
        l3m_weeks_avg_sales_qty as "l3m_weeks_avg_sales_qty"
    from source
)
select * from final;


insert into THAITG_INTEGRATION.ITG_TH_DMS_INVENTORY_FACT VALUES('2022-09-30 00:00:00.0','WEL','JJ900','79620830',120.000000,13440.000000,'16082022B2','0001-01-01 00:00:00.0','2022-10-11','20221010114649');
insert into THAITG_INTEGRATION.ITG_TH_DMS_INVENTORY_FACT VALUES('2022-09-30 00:00:00.0','WEL','JJ900','79620567',40.000000,7600.000000,'18072022B2','0001-01-01 00:00:00.0','2022-10-11','20221010114649');
