 insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp2
select * from PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_temp1
 WHERE PAC_SUBSOURCE_TYPE  = 'SAPBW_APO_FORECAST' ;
