insert into PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP 
select * from
PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP_20240708 where pac_subsource_type='SAPBW_ACTUAL'
and to_char(snap_shot_dt, 'YYYYMM') = 202403; 
