create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_BOUNCES (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	BOUNCECATEGORY VARCHAR(60),
	SMTPCODE NUMBER(18,0),
	BOUNCEREASON VARCHAR(65535),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_CLICKS (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	SENDURLID NUMBER(38,0),
	URLID NUMBER(38,0),
	URL VARCHAR(65535),
	ALIAS VARCHAR(65535),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_NOTSENT (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	REASON VARCHAR(256),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_OPENS (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_SENDJOBS (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	FROMNAME VARCHAR(150),
	FROMEMAIL VARCHAR(100),
	SCHEDTIME TIMESTAMP_NTZ(9),
	SENTTIME TIMESTAMP_NTZ(9),
	SUBJECT VARCHAR(300),
	EMAILNAME VARCHAR(100),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SENDDEFINITIONEXTERNALKEY VARCHAR(100),
	JOBSTATUS VARCHAR(30),
	PREVIEWURL VARCHAR(65535),
	ISMULTIPART VARCHAR(65535),
	ADDITIONAL VARCHAR(50),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(100)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_SENT (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(9)
	--FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_UNSUBS (
	CLIENTID NUMBER(38,0),
	SENDID NUMBER(38,0),
	SUBSCRIBERKEY VARCHAR(300),
	EMAILADDRESS VARCHAR(300),
	SUBSCRIBERID NUMBER(38,0),
	LISTID NUMBER(38,0),
	EVENTDATE TIMESTAMP_NTZ(9),
	EVENTTYPE VARCHAR(20),
	BATCHID NUMBER(38,0),
	TRIGGEREDSENDEXTERNALKEY VARCHAR(100),
	SOURCE_FILE_DATE VARCHAR(30),
	INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
	INSERTED_BY VARCHAR(100),
	UPDATED_DATE TIMESTAMP_NTZ(9),
	UPDATED_BY VARCHAR(9)
	--FILE_NAME VARCHAR(255)
);
