ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_BOUNCES ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_CLICKS ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_NOTSENT ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_OPENS ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_SENDJOBS ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_SENT ADD FILE_NAME VARCHAR(255);
ALTER TABLE PROD_DNA_CORE.JPDCLITG_INTEGRATION.SFMC_UNSUBS ADD FILE_NAME VARCHAR(255);
