
create table PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP_20240926
clone PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP ;

    
delete from  
FROM  PROD_DNA_CORE.PCFEDW_INTEGRATION.EDW_DEMAND_FORECAST_SNAPSHOT_TEMP
WHERE PAC_SUBSOURCE_TYPE = 'SAPBW_ACTUAL'
and to_char(snap_shot_dt, 'YYYYMM') =202406
and   (ACTUAL_SALES_QTY = 0  and APO_TOT_FRCST = 0 and 
APO_BASE_FRCST = 0 and APO_PROMO_FRCST = 0 and
PX_TOT_FRCST = 0 and PX_BASE_FRCST = 0 and PX_PROMO_FRCST =0 );
