insert into PROD_DNA_core.PHLITG_INTEGRATION.ITG_QUERY_PARAMETERS values 
('PH','ROSE_PHARMACY','Philippines','GCH_MARKET');

 
insert into PROD_DNA_core.PHLITG_INTEGRATION.ITG_QUERY_PARAMETERS values 
('PH','ROSE_PHARMACY','APAC','GCH_REGION');
 
