create table ASPITG_INTEGRATION.ITG_POP6_RIR_DATA_bkp_before_chng as select * from ASPITG_INTEGRATION.ITG_POP6_RIR_DATA;

drop table ASPITG_INTEGRATION.ITG_POP6_RIR_DATA;

create or replace TABLE ASPITG_INTEGRATION.ITG_POP6_RIR_DATA (
	cntry_cd varchar(10),
    VISIT_ID VARCHAR(255),
	PHOTO VARCHAR(500),
	RELATED_ATTRIBUTE VARCHAR(255),
	SKU_ID VARCHAR(255),
	SKU VARCHAR(255),
	LAYER NUMBER(18,0),
	TOTAL_LAYER NUMBER(18,0),
	FACING_OF_THIS_LAYER NUMBER(18,0),
	FILE_NAME VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);


create table THAITG_INTEGRATION.SDL_RAW_POP6_TH_RIR_DATA_bkp_before_chng as select * from THAITG_INTEGRATION.SDL_RAW_POP6_TH_RIR_DATA;

drop table THAITG_INTEGRATION.SDL_RAW_POP6_TH_RIR_DATA;

create or replace TABLE THAITG_INTEGRATION.SDL_RAW_POP6_TH_RIR_DATA (
	VISIT_ID VARCHAR(255),
	PHOTO VARCHAR(500),
	RELATED_ATTRIBUTE VARCHAR(255),
	SKU_ID VARCHAR(255),
	SKU VARCHAR(255),
	LAYER NUMBER(18,0),
	TOTAL_LAYER NUMBER(18,0),
	FACING_OF_THIS_LAYER NUMBER(18,0),
	FILE_NAME VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);
