CREATE TABLE PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_KR_ECOMMERCE_SELLOUT_BKP_08102024
AS
SELECT * FROM PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_KR_ECOMMERCE_SELLOUT
where customer_name = 'TCAKOREA' and source_file_name = 'Weekly_Summary_TCA_raw_data_20240930.xlsx';

DELETE FROM PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_KR_ECOMMERCE_SELLOUT
where customer_name = 'TCAKOREA' and source_file_name = 'Weekly_Summary_TCA_raw_data_20240930.xlsx';
