use schema PCFEDW_ACCESS ;

create or replace view EDW_DEMAND_FORECAST_SNAPSHOT(
	"pac_source_type",
	"pac_subsource_type",
	"snap_shot_dt",
	"snapshot_week_no",
	"snapshot_mnth_week_no",
	"snapshot_mnth_shrt",
	"snapshot_year",
	"final_version_indicator",
	"jj_period",
	"jj_week_no",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"jj_mnth_tot",
	"matl_no",
	"matl_desc",
	"master_code",
	"parent_id",
	"parent_matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"cust_no",
	"cmp_id",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"fcst_chnl",
	"fcst_chnl_desc",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"curr_cd",
	"actual_sales_qty",
	"apo_tot_frcst",
	"apo_base_frcst",
	"apo_promo_frcst",
	"px_tot_frcst",
	"px_base_frcst",
	"px_promo_frcst",
	"count"
) as
select 
	pac_source_type as "pac_source_type",
    pac_subsource_type as "pac_subsource_type",
    snap_shot_dt as "snap_shot_dt",
    snapshot_week_no as "snapshot_week_no",
    snapshot_mnth_week_no as "snapshot_mnth_week_no",
    snapshot_mnth_shrt as "snapshot_mnth_shrt",
    snapshot_year as "snapshot_year",
    final_version_indicator as "final_version_indicator",
    jj_period as "jj_period",
    jj_week_no as "jj_week_no",
    jj_wk as "jj_wk",
    jj_mnth as "jj_mnth",
    jj_mnth_shrt as "jj_mnth_shrt",
    jj_mnth_long as "jj_mnth_long",
    jj_qrtr as "jj_qrtr",
    jj_year as "jj_year",
    jj_mnth_tot as "jj_mnth_tot",
    matl_no as "matl_no",
    matl_desc as "matl_desc",
    master_code as "master_code",
    parent_id as "parent_id",
    parent_matl_desc as "parent_matl_desc",
    mega_brnd_cd as "mega_brnd_cd",
    mega_brnd_desc as "mega_brnd_desc",
    brnd_cd as "brnd_cd",
    brnd_desc as "brnd_desc",
    base_prod_cd as "base_prod_cd",
    base_prod_desc as "base_prod_desc",
    variant_cd as "variant_cd",
    variant_desc as "variant_desc",
    fran_cd as "fran_cd",
    fran_desc as "fran_desc",
    grp_fran_cd as "grp_fran_cd",
    grp_fran_desc as "grp_fran_desc",
    matl_type_cd as "matl_type_cd",
    matl_type_desc as "matl_type_desc",
    prod_fran_cd as "prod_fran_cd",
    prod_fran_desc as "prod_fran_desc",
    prod_hier_cd as "prod_hier_cd",
    prod_hier_desc as "prod_hier_desc",
    prod_mjr_cd as "prod_mjr_cd",
    prod_mjr_desc as "prod_mjr_desc",
    prod_mnr_cd as "prod_mnr_cd",
    prod_mnr_desc as "prod_mnr_desc",
    mercia_plan as "mercia_plan",
    putup_cd as "putup_cd",
    putup_desc as "putup_desc",
    bar_cd as "bar_cd",
    cust_no as "cust_no",
    cmp_id as "cmp_id",
    ctry_key as "ctry_key",
    country as "country",
    state_cd as "state_cd",
    post_cd as "post_cd",
    cust_suburb as "cust_suburb",
    cust_nm as "cust_nm",
    fcst_chnl as "fcst_chnl",
    fcst_chnl_desc as "fcst_chnl_desc",
    sales_office_cd as "sales_office_cd",
    sales_office_desc as "sales_office_desc",
    sales_grp_cd as "sales_grp_cd",
    sales_grp_desc as "sales_grp_desc",
    curr_cd as "curr_cd",
    actual_sales_qty as "actual_sales_qty",
    apo_tot_frcst as "apo_tot_frcst",
    apo_base_frcst as "apo_base_frcst",
    apo_promo_frcst as "apo_promo_frcst",
    px_tot_frcst as "px_tot_frcst",
    px_base_frcst as "px_base_frcst",
    px_promo_frcst as "px_promo_frcst",
    count as "count" 
from pcfedw_integration.edw_demand_forecast_snapshot;
create or replace view EDW_GTS_VISIBILITY(
	"subsource_type",
	"country",
	"snapshot_date",
	"snapshot_date_jnj_month",
	"jj_mnth_id",
	"jj_mnth",
	"jj_mnth_nm",
	"jj_year",
	"jj_qrtr",
	"cust_num",
	"matl_num",
	"sls_doc",
	"rqst_delv_dt",
	"rqst_delv_dt_jnj_month",
	"bill_num",
	"bill_dt",
	"bill_dt_yyyy_mm",
	"created_on",
	"grp_fran_desc",
	"prod_fran_desc",
	"prod_mjr_desc",
	"prod_mnr_desc",
	"matl_desc",
	"brnd_desc",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment",
	"master_code",
	"channel_desc",
	"sales_office_desc",
	"cust_nm",
	"sales_grp_desc",
	"local_ccy",
	"to_ccy",
	"exch_rate",
	"open_orders_val",
	"gts_landing_val"
) as
select 
	subsource_type as "subsource_type",
	country as "country",
	snapshot_date as "snapshot_date",
	snapshot_date_jnj_month as "snapshot_date_jnj_month",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth as "jj_mnth",
	jj_mnth_nm as "jj_mnth_nm",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	cust_num as "cust_num",
	matl_num as "matl_num",
	sls_doc as "sls_doc",
	rqst_delv_dt as "rqst_delv_dt",
	rqst_delv_dt_jnj_month as "rqst_delv_dt_jnj_month",
	bill_num as "bill_num",
	bill_dt as "bill_dt",
	bill_dt_yyyy_mm as "bill_dt_yyyy_mm",
	created_on as "created_on",
	grp_fran_desc as "grp_fran_desc",
	prod_fran_desc as "prod_fran_desc",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_desc as "prod_mnr_desc",
	matl_desc as "matl_desc",
	brnd_desc as "brnd_desc",
	gcph_franchise as "gcph_franchise",
	gcph_brand as "gcph_brand",
	gcph_subbrand as "gcph_subbrand",
	gcph_variant as "gcph_variant",
	gcph_needstate as "gcph_needstate",
	gcph_category as "gcph_category",
	gcph_subcategory as "gcph_subcategory",
	gcph_segment as "gcph_segment",
	gcph_subsegment as "gcph_subsegment",
	master_code as "master_code",
	channel_desc as "channel_desc",
	sales_office_desc as "sales_office_desc",
	cust_nm as "cust_nm",
	sales_grp_desc as "sales_grp_desc",
	local_ccy as "local_ccy",
	to_ccy as "to_ccy",
	exch_rate as "exch_rate",
	open_orders_val as "open_orders_val",
	gts_landing_val as "gts_landing_val"
from pcfedw_integration.edw_gts_visibility;
create or replace view EDW_INVOICE_ANALYSIS(
	"matl_id",
	"matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"updt_dt",
	"cust_no",
	"cmp_id",
	"channel_cd",
	"channel_desc",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"sls_org",
	"cust_del_flag",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"mercia_ref",
	"curr_cd",
	"cal_date",
	"time_id",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"cal_mnth_id",
	"jj_mnth_id",
	"cal_mnth",
	"cal_qrtr",
	"cal_year",
	"jj_mnth_tot",
	"jj_mnth_day",
	"cal_mnth_nm",
	"act_delv_dt",
	"act_good_iss_dt",
	"base_uom",
	"bill_doc",
	"bill_dt",
	"bill_qty_cse",
	"bill_qty_difot",
	"bill_qty_otif",
	"bill_qty_pc",
	"bill_qty_sls_uom",
	"bill_to_prty",
	"bill_typ",
	"cal_day",
	"cnfrm_qty_difot",
	"cnfrm_qty_pc",
	"co_cd",
	"crt_dttm",
	"curr_key",
	"cust_num",
	"delv_doc_crt_dt",
	"delv_qty_cse",
	"delv_qty_pc",
	"delv_qty_sls_uom",
	"div",
	"doc_crt_dt",
	"doc_curr",
	"doc_dt",
	"dstr_chnl",
	"est_nts",
	"fisc_yr",
	"fisc_yr_src",
	"fut_sls_qty",
	"good_iss_dt",
	"future_gts_val",
	"mat_avail_dt",
	"matl_num",
	"net_amt",
	"net_bill_val",
	"net_invc_sls",
	"net_ord_val",
	"net_prc",
	"nts_val",
	"ord_pc_qty",
	"ord_qty_cse",
	"ord_qty_pc",
	"ord_rsn",
	"ord_sls_qty",
	"ovrl_rej_sts",
	"ovrl_sts_crd_chk",
	"payer",
	"plnt",
	"prec_doc_itm",
	"prec_doc_num",
	"proof_delv_dt",
	"rlse_dt_cr_mgmt",
	"route",
	"rqst_delv_dt",
	"rsn_cd_key",
	"rsn_rej",
	"ship_to_prty",
	"ship_name",
	"sls_doc",
	"sls_doc_cat",
	"sls_doc_itm",
	"sls_doc_itm_cat",
	"sls_doc_typ",
	"sls_emp_hist",
	"sls_unit",
	"sold_to_prty",
	"tran_ldtm",
	"unspp_qty",
	"unspp_val",
	"updt_dttm",
	"vol_delv",
	"vol_ord",
	"to_ccy",
	"exch_rate"
) as
select
    matl_id as "matl_id",
matl_desc as "matl_desc",
mega_brnd_cd as "mega_brnd_cd",
mega_brnd_desc as "mega_brnd_desc",
brnd_cd as "brnd_cd",
brnd_desc as "brnd_desc",
base_prod_cd as "base_prod_cd",
base_prod_desc as "base_prod_desc",
variant_cd as "variant_cd",
variant_desc as "variant_desc",
fran_cd as "fran_cd",
fran_desc as "fran_desc",
grp_fran_cd as "grp_fran_cd",
grp_fran_desc as "grp_fran_desc",
matl_type_cd as "matl_type_cd",
matl_type_desc as "matl_type_desc",
prod_fran_cd as "prod_fran_cd",
prod_fran_desc as "prod_fran_desc",
prod_hier_cd as "prod_hier_cd",
prod_hier_desc as "prod_hier_desc",
prod_mjr_cd as "prod_mjr_cd",
prod_mjr_desc as "prod_mjr_desc",
prod_mnr_cd as "prod_mnr_cd",
prod_mnr_desc as "prod_mnr_desc",
mercia_plan as "mercia_plan",
putup_cd as "putup_cd",
putup_desc as "putup_desc",
bar_cd as "bar_cd",
updt_dt as "updt_dt",
cust_no as "cust_no",
cmp_id as "cmp_id",
channel_cd as "channel_cd",
channel_desc as "channel_desc",
ctry_key as "ctry_key",
country as "country",
state_cd as "state_cd",
post_cd as "post_cd",
cust_suburb as "cust_suburb",
cust_nm as "cust_nm",
sls_org as "sls_org",
cust_del_flag as "cust_del_flag",
sales_office_cd as "sales_office_cd",
sales_office_desc as "sales_office_desc",
sales_grp_cd as "sales_grp_cd",
sales_grp_desc as "sales_grp_desc",
mercia_ref as "mercia_ref",
curr_cd as "curr_cd",
cal_date as "cal_date",
time_id as "time_id",
jj_wk as "jj_wk",
jj_mnth as "jj_mnth",
jj_mnth_shrt as "jj_mnth_shrt",
jj_mnth_long as "jj_mnth_long",
jj_qrtr as "jj_qrtr",
jj_year as "jj_year",
cal_mnth_id as "cal_mnth_id",
jj_mnth_id as "jj_mnth_id",
cal_mnth as "cal_mnth",
cal_qrtr as "cal_qrtr",
cal_year as "cal_year",
jj_mnth_tot as "jj_mnth_tot",
jj_mnth_day as "jj_mnth_day",
cal_mnth_nm as "cal_mnth_nm",
act_delv_dt as "act_delv_dt",
act_good_iss_dt as "act_good_iss_dt",
base_uom as "base_uom",
bill_doc as "bill_doc",
bill_dt as "bill_dt",
bill_qty_cse as "bill_qty_cse",
bill_qty_difot as "bill_qty_difot",
bill_qty_otif as "bill_qty_otif",
bill_qty_pc as "bill_qty_pc",
bill_qty_sls_uom as "bill_qty_sls_uom",
bill_to_prty as "bill_to_prty",
bill_typ as "bill_typ",
cal_day as "cal_day",
cnfrm_qty_difot as "cnfrm_qty_difot",
cnfrm_qty_pc as "cnfrm_qty_pc",
co_cd as "co_cd",
crt_dttm as "crt_dttm",
curr_key as "curr_key",
cust_num as "cust_num",
delv_doc_crt_dt as "delv_doc_crt_dt",
delv_qty_cse as "delv_qty_cse",
delv_qty_pc as "delv_qty_pc",
delv_qty_sls_uom as "delv_qty_sls_uom",
div as "div",
doc_crt_dt as "doc_crt_dt",
doc_curr as "doc_curr",
doc_dt as "doc_dt",
dstr_chnl as "dstr_chnl",
est_nts as "est_nts",
fisc_yr as "fisc_yr",
fisc_yr_src as "fisc_yr_src",
fut_sls_qty as "fut_sls_qty",
good_iss_dt as "good_iss_dt",
future_gts_val as "future_gts_val",
mat_avail_dt as "mat_avail_dt",
matl_num as "matl_num",
net_amt as "net_amt",
net_bill_val as "net_bill_val",
net_invc_sls as "net_invc_sls",
net_ord_val as "net_ord_val",
net_prc as "net_prc",
nts_val as "nts_val",
ord_pc_qty as "ord_pc_qty",
ord_qty_cse as "ord_qty_cse",
ord_qty_pc as "ord_qty_pc",
ord_rsn as "ord_rsn",
ord_sls_qty as "ord_sls_qty",
ovrl_rej_sts as "ovrl_rej_sts",
ovrl_sts_crd_chk as "ovrl_sts_crd_chk",
payer as "payer",
plnt as "plnt",
prec_doc_itm as "prec_doc_itm",
prec_doc_num as "prec_doc_num",
proof_delv_dt as "proof_delv_dt",
rlse_dt_cr_mgmt as "rlse_dt_cr_mgmt",
route as "route",
rqst_delv_dt as "rqst_delv_dt",
rsn_cd_key as "rsn_cd_key",
rsn_rej as "rsn_rej",
ship_to_prty as "ship_to_prty",
ship_name as "ship_name",
sls_doc as "sls_doc",
sls_doc_cat as "sls_doc_cat",
sls_doc_itm as "sls_doc_itm",
sls_doc_itm_cat as "sls_doc_itm_cat",
sls_doc_typ as "sls_doc_typ",
sls_emp_hist as "sls_emp_hist",
sls_unit as "sls_unit",
sold_to_prty as "sold_to_prty",
tran_ldtm as "tran_ldtm",
unspp_qty as "unspp_qty",
unspp_val as "unspp_val",
updt_dttm as "updt_dttm",
vol_delv as "vol_delv",
vol_ord as "vol_ord",
to_ccy as "to_ccy",
exch_rate as "exch_rate"
from pcfedw_integration.edw_invoice_analysis;
create or replace view EDW_PACIFIC_FIELD_SALES_ANALYSIS(
	"perenso_source",
	"time_id",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_wk",
	"cal_mnth_wk",
	"cal_mnth_id",
	"cal_mnth_nm",
	"diary_item_type_desc",
	"diary_item_category",
	"diary_start_date",
	"diary_start_time",
	"diary_end_date",
	"diary_end_time",
	"diary_complete",
	"count_in_call_rate",
	"todo_type",
	"to_do_option_desc",
	"acct_key",
	"acct_display_name",
	"acct_type_desc",
	"acct_street_1",
	"acct_street_2",
	"acct_street_3",
	"acct_suburb",
	"acct_postcode",
	"acct_phone_number",
	"acct_fax_number",
	"acct_email",
	"acct_country",
	"acct_region",
	"acct_state",
	"acct_banner_country",
	"acct_banner_division",
	"acct_banner_type",
	"acct_banner",
	"acct_type",
	"acct_sub_type",
	"acct_grade",
	"acct_nz_pharma_country",
	"acct_nz_pharma_state",
	"acct_nz_pharma_territory",
	"acct_nz_groc_country",
	"acct_nz_groc_state",
	"acct_nz_groc_territory",
	"acct_ssr_country",
	"acct_ssr_state",
	"acct_ssr_team_leader",
	"acct_ssr_territory",
	"acct_ssr_sub_territory",
	"acct_ind_groc_country",
	"acct_ind_groc_state",
	"acct_ind_groc_territory",
	"acct_ind_groc_sub_territory",
	"acct_au_pharma_country",
	"acct_au_pharma_state",
	"acct_au_pharma_territory",
	"acct_au_pharma_ssr_country",
	"acct_au_pharma_ssr_state",
	"acct_au_pharma_ssr_territory",
	"acct_tsm",
	"acct_terriroty",
	"acct_store_code",
	"acct_fax_opt_out",
	"acct_email_opt_out",
	"acct_contact_method",
	"ssr_grade",
	"create_user_key",
	"create_user_name",
	"create_user_desc",
	"create_user_email_address",
	"store_chk_date",
	"prod_grp_key",
	"prod_grp_desc",
	"todo_desc",
	"to_do_start_date",
	"to_do_end_date",
	"work_item_desc",
	"work_item_type",
	"work_item_start_date",
	"work_item_end_date",
	"survery_notes",
	"fail_reason_desc",
	"req_start_date",
	"req_end_date",
	"oa_acct_key",
	"oa_start_date",
	"oa_end_date",
	"oa_points",
	"batch_count",
	"activated",
	"over_and_above_notes",
	"load_date",
	"question_response",
	"dash_start_time",
	"dash_end_time",
	"cycle_start_date",
	"cycle_end_date",
	"cycle_number",
	"parent_question",
	"question_order",
	"survey_target_type",
	"survey_target",
	"survey_category",
	"call_weekly_targets",
	"call_monthly_targets",
	"call_yearly_targets",
	"calls_per_week",
	"call_description",
	"assigned_user_key",
	"assigned_user_name",
	"due_dt",
	"completed_dt",
	"status",
	"diary_session_start_time",
	"diary_session_end_time",
	"duration",
	"latitude",
	"longitude"
) as
select 
	perenso_source as "perenso_source",
	time_id as "time_id",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_wk as "jj_mnth_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_wk as "cal_wk",
	cal_mnth_wk as "cal_mnth_wk",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	diary_item_type_desc as "diary_item_type_desc",
	diary_item_category as "diary_item_category",
	diary_start_date as "diary_start_date",
	diary_start_time as "diary_start_time",
	diary_end_date as "diary_end_date",
	diary_end_time as "diary_end_time",
	diary_complete as "diary_complete",
	count_in_call_rate as "count_in_call_rate",
	todo_type as "todo_type",
	to_do_option_desc as "to_do_option_desc",
	acct_key as "acct_key",
	acct_display_name as "acct_display_name",
	acct_type_desc as "acct_type_desc",
	acct_street_1 as "acct_street_1",
	acct_street_2 as "acct_street_2",
	acct_street_3 as "acct_street_3",
	acct_suburb as "acct_suburb",
	acct_postcode as "acct_postcode",
	acct_phone_number as "acct_phone_number",
	acct_fax_number as "acct_fax_number",
	acct_email as "acct_email",
	acct_country as "acct_country",
	acct_region as "acct_region",
	acct_state as "acct_state",
	acct_banner_country as "acct_banner_country",
	acct_banner_division as "acct_banner_division",
	acct_banner_type as "acct_banner_type",
	acct_banner as "acct_banner",
	acct_type as "acct_type",
	acct_sub_type as "acct_sub_type",
	acct_grade as "acct_grade",
	acct_nz_pharma_country as "acct_nz_pharma_country",
	acct_nz_pharma_state as "acct_nz_pharma_state",
	acct_nz_pharma_territory as "acct_nz_pharma_territory",
	acct_nz_groc_country as "acct_nz_groc_country",
	acct_nz_groc_state as "acct_nz_groc_state",
	acct_nz_groc_territory as "acct_nz_groc_territory",
	acct_ssr_country as "acct_ssr_country",
	acct_ssr_state as "acct_ssr_state",
	acct_ssr_team_leader as "acct_ssr_team_leader",
	acct_ssr_territory as "acct_ssr_territory",
	acct_ssr_sub_territory as "acct_ssr_sub_territory",
	acct_ind_groc_country as "acct_ind_groc_country",
	acct_ind_groc_state as "acct_ind_groc_state",
	acct_ind_groc_territory as "acct_ind_groc_territory",
	acct_ind_groc_sub_territory as "acct_ind_groc_sub_territory",
	acct_au_pharma_country as "acct_au_pharma_country",
	acct_au_pharma_state as "acct_au_pharma_state",
	acct_au_pharma_territory as "acct_au_pharma_territory",
	acct_au_pharma_ssr_country as "acct_au_pharma_ssr_country",
	acct_au_pharma_ssr_state as "acct_au_pharma_ssr_state",
	acct_au_pharma_ssr_territory as "acct_au_pharma_ssr_territory",
	acct_tsm as "acct_tsm",
	acct_terriroty as "acct_terriroty",
	acct_store_code as "acct_store_code",
	acct_fax_opt_out as "acct_fax_opt_out",
	acct_email_opt_out as "acct_email_opt_out",
	acct_contact_method as "acct_contact_method",
	ssr_grade as "ssr_grade",
	create_user_key as "create_user_key",
	create_user_name as "create_user_name",
	create_user_desc as "create_user_desc",
	create_user_email_address as "create_user_email_address",
	store_chk_date as "store_chk_date",
	prod_grp_key as "prod_grp_key",
	prod_grp_desc as "prod_grp_desc",
	todo_desc as "todo_desc",
	to_do_start_date as "to_do_start_date",
	to_do_end_date as "to_do_end_date",
	work_item_desc as "work_item_desc",
	work_item_type as "work_item_type",
	work_item_start_date as "work_item_start_date",
	work_item_end_date as "work_item_end_date",
	survery_notes as "survery_notes",
	fail_reason_desc as "fail_reason_desc",
	req_start_date as "req_start_date",
	req_end_date as "req_end_date",
	oa_acct_key as "oa_acct_key",
	oa_start_date as "oa_start_date",
	oa_end_date as "oa_end_date",
	oa_points as "oa_points",
	batch_count as "batch_count",
	activated as "activated",
	over_and_above_notes as "over_and_above_notes",
	load_date as "load_date",
	question_response as "question_response",
	dash_start_time as "dash_start_time",
	dash_end_time as "dash_end_time",
	cycle_start_date as "cycle_start_date",
	cycle_end_date as "cycle_end_date",
	cycle_number as "cycle_number",
	parent_question as "parent_question",
	question_order as "question_order",
	survey_target_type as "survey_target_type",
	survey_target as "survey_target",
	survey_category as "survey_category",
	call_weekly_targets as "call_weekly_targets",
	call_monthly_targets as "call_monthly_targets",
	call_yearly_targets as "call_yearly_targets",
	calls_per_week as "calls_per_week",
	call_description as "call_description",
	assigned_user_key as "assigned_user_key",
	assigned_user_name as "assigned_user_name",
	due_dt as "due_dt",
	completed_dt as "completed_dt",
	status as "status",
	diary_session_start_time as "diary_session_start_time",
	diary_session_end_time as "diary_session_end_time",
	duration as "duration",
	latitude as "latitude",
	longitude as "longitude"
from pcfedw_integration.edw_pacific_field_sales_analysis;
create or replace view EDW_PACIFIC_METCASH_DSTRBTN_ANALYSIS(
	"delvry_dt",
	"time_id",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_mnth_id",
	"cal_mnth_nm",
	"prod_key",
	"prod_desc",
	"prod_sapbw_code",
	"prod_ean",
	"prod_jj_franchise",
	"prod_jj_category",
	"prod_jj_brand",
	"prod_sap_franchise",
	"prod_sap_profit_centre",
	"prod_sap_product_major",
	"prod_grocery_franchise",
	"prod_grocery_category",
	"prod_grocery_brand",
	"prod_active_status",
	"prod_pbs",
	"prod_ims_brand",
	"prod_nz_code",
	"prod_metcash_code",
	"prod_old_id",
	"prod_old_ean",
	"prod_tax",
	"prod_bwp_aud",
	"prod_bwp_nzd",
	"acct_key",
	"acct_display_name",
	"acct_type_desc",
	"acct_street_1",
	"acct_street_2",
	"acct_street_3",
	"acct_suburb",
	"acct_postcode",
	"acct_phone_number",
	"acct_fax_number",
	"acct_email",
	"acct_country",
	"acct_region",
	"acct_state",
	"acct_banner_country",
	"acct_banner_division",
	"acct_banner_type",
	"acct_banner",
	"acct_type",
	"acct_sub_type",
	"acct_grade",
	"acct_nz_pharma_country",
	"acct_nz_pharma_state",
	"acct_nz_pharma_territory",
	"acct_nz_groc_country",
	"acct_nz_groc_state",
	"acct_nz_groc_territory",
	"acct_ssr_country",
	"acct_ssr_state",
	"acct_ssr_team_leader",
	"acct_ssr_territory",
	"acct_ssr_sub_territory",
	"acct_ind_groc_country",
	"acct_ind_groc_state",
	"acct_ind_groc_territory",
	"acct_ind_groc_sub_territory",
	"acct_au_pharma_country",
	"acct_au_pharma_state",
	"acct_au_pharma_territory",
	"acct_au_pharma_ssr_country",
	"acct_au_pharma_ssr_state",
	"acct_au_pharma_ssr_territory",
	"acct_tsm",
	"acct_terriroty",
	"acct_store_code",
	"acct_fax_opt_out",
	"acct_email_opt_out",
	"acct_contact_method",
	"curnt_mnth_nis",
	"curnt_mnth_qty",
	"curnt_mnth_avg_lp",
	"lst_mnth_nis",
	"lst_mnth_qty",
	"lst_mnth_avg_lp",
	"lst3_mnth_nis",
	"lst3_mnth_qty",
	"lst3_mnth_avg_lp",
	"lst6_mnth_nis",
	"lst6_mnth_qty",
	"lst6_mnth_avg_lp",
	"lst12_mnth_nis",
	"lst12_mnth_qty",
	"lst12_mnth_avg_lp",
	"curnt_mnth_dstrbtn_flag",
	"lst_mnth_dstrbtn_flag",
	"lst3_mnth_dstrbtn_flag",
	"lst6_mnth_dstrbtn_flag",
	"lst12_mnth_dstrbtn_flag",
	"curnt_mnth_dstrbtn_trgt",
	"lst_mnth_dstrbtn_trgt",
	"lst3_mnth_dstrbtn_trgt",
	"lst6_mnth_dstrbtn_trgt",
	"lst12_mnth_dstrbtn_trgt",
	"ig_msl_rank",
	"ig_msl_flag",
	"load_date"
) as
select 
	delvry_dt as "delvry_dt",
	time_id as "time_id",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	prod_key as "prod_key",
	prod_desc as "prod_desc",
	prod_sapbw_code as "prod_sapbw_code",
	prod_ean as "prod_ean",
	prod_jj_franchise as "prod_jj_franchise",
	prod_jj_category as "prod_jj_category",
	prod_jj_brand as "prod_jj_brand",
	prod_sap_franchise as "prod_sap_franchise",
	prod_sap_profit_centre as "prod_sap_profit_centre",
	prod_sap_product_major as "prod_sap_product_major",
	prod_grocery_franchise as "prod_grocery_franchise",
	prod_grocery_category as "prod_grocery_category",
	prod_grocery_brand as "prod_grocery_brand",
	prod_active_status as "prod_active_status",
	prod_pbs as "prod_pbs",
	prod_ims_brand as "prod_ims_brand",
	prod_nz_code as "prod_nz_code",
	prod_metcash_code as "prod_metcash_code",
	prod_old_id as "prod_old_id",
	prod_old_ean as "prod_old_ean",
	prod_tax as "prod_tax",
	prod_bwp_aud as "prod_bwp_aud",
	prod_bwp_nzd as "prod_bwp_nzd",
	acct_key as "acct_key",
	acct_display_name as "acct_display_name",
	acct_type_desc as "acct_type_desc",
	acct_street_1 as "acct_street_1",
	acct_street_2 as "acct_street_2",
	acct_street_3 as "acct_street_3",
	acct_suburb as "acct_suburb",
	acct_postcode as "acct_postcode",
	acct_phone_number as "acct_phone_number",
	acct_fax_number as "acct_fax_number",
	acct_email as "acct_email",
	acct_country as "acct_country",
	acct_region as "acct_region",
	acct_state as "acct_state",
	acct_banner_country as "acct_banner_country",
	acct_banner_division as "acct_banner_division",
	acct_banner_type as "acct_banner_type",
	acct_banner as "acct_banner",
	acct_type as "acct_type",
	acct_sub_type as "acct_sub_type",
	acct_grade as "acct_grade",
	acct_nz_pharma_country as "acct_nz_pharma_country",
	acct_nz_pharma_state as "acct_nz_pharma_state",
	acct_nz_pharma_territory as "acct_nz_pharma_territory",
	acct_nz_groc_country as "acct_nz_groc_country",
	acct_nz_groc_state as "acct_nz_groc_state",
	acct_nz_groc_territory as "acct_nz_groc_territory",
	acct_ssr_country as "acct_ssr_country",
	acct_ssr_state as "acct_ssr_state",
	acct_ssr_team_leader as "acct_ssr_team_leader",
	acct_ssr_territory as "acct_ssr_territory",
	acct_ssr_sub_territory as "acct_ssr_sub_territory",
	acct_ind_groc_country as "acct_ind_groc_country",
	acct_ind_groc_state as "acct_ind_groc_state",
	acct_ind_groc_territory as "acct_ind_groc_territory",
	acct_ind_groc_sub_territory as "acct_ind_groc_sub_territory",
	acct_au_pharma_country as "acct_au_pharma_country",
	acct_au_pharma_state as "acct_au_pharma_state",
	acct_au_pharma_territory as "acct_au_pharma_territory",
	acct_au_pharma_ssr_country as "acct_au_pharma_ssr_country",
	acct_au_pharma_ssr_state as "acct_au_pharma_ssr_state",
	acct_au_pharma_ssr_territory as "acct_au_pharma_ssr_territory",
	acct_tsm as "acct_tsm",
	acct_terriroty as "acct_terriroty",
	acct_store_code as "acct_store_code",
	acct_fax_opt_out as "acct_fax_opt_out",
	acct_email_opt_out as "acct_email_opt_out",
	acct_contact_method as "acct_contact_method",
	curnt_mnth_nis as "curnt_mnth_nis",
	curnt_mnth_qty as "curnt_mnth_qty",
	curnt_mnth_avg_lp as "curnt_mnth_avg_lp",
	lst_mnth_nis as "lst_mnth_nis",
	lst_mnth_qty as "lst_mnth_qty",
	lst_mnth_avg_lp as "lst_mnth_avg_lp",
	lst3_mnth_nis as "lst3_mnth_nis",
	lst3_mnth_qty as "lst3_mnth_qty",
	lst3_mnth_avg_lp as "lst3_mnth_avg_lp",
	lst6_mnth_nis as "lst6_mnth_nis",
	lst6_mnth_qty as "lst6_mnth_qty",
	lst6_mnth_avg_lp as "lst6_mnth_avg_lp",
	lst12_mnth_nis as "lst12_mnth_nis",
	lst12_mnth_qty as "lst12_mnth_qty",
	lst12_mnth_avg_lp as "lst12_mnth_avg_lp",
	curnt_mnth_dstrbtn_flag as "curnt_mnth_dstrbtn_flag",
	lst_mnth_dstrbtn_flag as "lst_mnth_dstrbtn_flag",
	lst3_mnth_dstrbtn_flag as "lst3_mnth_dstrbtn_flag",
	lst6_mnth_dstrbtn_flag as "lst6_mnth_dstrbtn_flag",
	lst12_mnth_dstrbtn_flag as "lst12_mnth_dstrbtn_flag",
	curnt_mnth_dstrbtn_trgt as "curnt_mnth_dstrbtn_trgt",
	lst_mnth_dstrbtn_trgt as "lst_mnth_dstrbtn_trgt",
	lst3_mnth_dstrbtn_trgt as "lst3_mnth_dstrbtn_trgt",
	lst6_mnth_dstrbtn_trgt as "lst6_mnth_dstrbtn_trgt",
	lst12_mnth_dstrbtn_trgt as "lst12_mnth_dstrbtn_trgt",
	ig_msl_rank as "ig_msl_rank",
	ig_msl_flag as "ig_msl_flag",
	load_date as "load_date"
from pcfedw_integration.edw_pacific_metcash_dstrbtn_analysis;
create or replace view EDW_PACIFIC_PERENSO_IMS_ANALYSIS(
	"order_type",
	"delvry_dt",
	"time_id",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_wk",
	"cal_mnth_wk",
	"cal_mnth_id",
	"cal_mnth_nm",
	"prod_key",
	"prod_probe_id",
	"prod_desc",
	"prod_sapbw_code",
	"prod_ean",
	"prod_jj_franchise",
	"prod_jj_category",
	"prod_jj_brand",
	"prod_sap_franchise",
	"prod_sap_profit_centre",
	"prod_sap_product_major",
	"prod_grocery_franchise",
	"prod_grocery_category",
	"prod_grocery_brand",
	"prod_active_status",
	"prod_pbs",
	"prod_ims_brand",
	"prod_nz_code",
	"prod_metcash_code",
	"prod_old_id",
	"prod_old_ean",
	"prod_tax",
	"prod_bwp_aud",
	"prod_bwp_nzd",
	"prod_wholesaler_code",
	"acct_key",
	"acct_probe_id",
	"acct_metcash_store_code",
	"acct_display_name",
	"acct_type_desc",
	"acct_street_1",
	"acct_street_2",
	"acct_street_3",
	"acct_suburb",
	"acct_postcode",
	"acct_phone_number",
	"acct_fax_number",
	"acct_email",
	"acct_country",
	"acct_region",
	"acct_state",
	"acct_banner_country",
	"acct_banner_division",
	"acct_banner_type",
	"acct_banner",
	"acct_type",
	"acct_sub_type",
	"acct_grade",
	"acct_nz_pharma_country",
	"acct_nz_pharma_state",
	"acct_nz_pharma_territory",
	"acct_nz_groc_country",
	"acct_nz_groc_state",
	"acct_nz_groc_territory",
	"acct_ssr_country",
	"acct_ssr_state",
	"acct_ssr_team_leader",
	"acct_ssr_territory",
	"acct_ssr_sub_territory",
	"acct_ind_groc_country",
	"acct_ind_groc_state",
	"acct_ind_groc_territory",
	"acct_ind_groc_sub_territory",
	"acct_au_pharma_country",
	"acct_au_pharma_state",
	"acct_au_pharma_territory",
	"acct_au_pharma_ssr_country",
	"acct_au_pharma_ssr_state",
	"acct_au_pharma_ssr_territory",
	"acct_tsm",
	"acct_terriroty",
	"acct_store_code",
	"acct_fax_opt_out",
	"acct_email_opt_out",
	"acct_contact_method",
	"ssr_grade",
	"order_key",
	"order_date",
	"sent_dt",
	"delvry_instns",
	"branch_key",
	"batch_key",
	"line_key",
	"unit_qty",
	"entered_qty",
	"entered_unit_key",
	"list_price",
	"nis",
	"rrp",
	"deal_desc",
	"deal_start_date",
	"deal_end_date",
	"deal_short_desc",
	"discount_desc",
	"discount_per",
	"discount_amt",
	"order_status",
	"batch_status",
	"order_currency_cd",
	"create_user_name",
	"create_user_desc",
	"create_user_email_address",
	"distributor",
	"distributor_display_name",
	"pharmacy_msl_rank",
	"pharmacy_msl_flag",
	"exch_rate_to_aud",
	"aud_nis",
	"exch_rate_to_usd",
	"usd_nis",
	"exch_rate_to_nzd",
	"nzd_nis",
	"distribution_flag"
) as
select 
	order_type as "order_type",
	delvry_dt as "delvry_dt",
	time_id as "time_id",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_wk as "jj_mnth_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_wk as "cal_wk",
	cal_mnth_wk as "cal_mnth_wk",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	prod_key as "prod_key",
	prod_probe_id as "prod_probe_id",
	prod_desc as "prod_desc",
	prod_sapbw_code as "prod_sapbw_code",
	prod_ean as "prod_ean",
	prod_jj_franchise as "prod_jj_franchise",
	prod_jj_category as "prod_jj_category",
	prod_jj_brand as "prod_jj_brand",
	prod_sap_franchise as "prod_sap_franchise",
	prod_sap_profit_centre as "prod_sap_profit_centre",
	prod_sap_product_major as "prod_sap_product_major",
	prod_grocery_franchise as "prod_grocery_franchise",
	prod_grocery_category as "prod_grocery_category",
	prod_grocery_brand as "prod_grocery_brand",
	prod_active_status as "prod_active_status",
	prod_pbs as "prod_pbs",
	prod_ims_brand as "prod_ims_brand",
	prod_nz_code as "prod_nz_code",
	prod_metcash_code as "prod_metcash_code",
	prod_old_id as "prod_old_id",
	prod_old_ean as "prod_old_ean",
	prod_tax as "prod_tax",
	prod_bwp_aud as "prod_bwp_aud",
	prod_bwp_nzd as "prod_bwp_nzd",
	prod_wholesaler_code as "prod_wholesaler_code",
	acct_key as "acct_key",
	acct_probe_id as "acct_probe_id",
	acct_metcash_store_code as "acct_metcash_store_code",
	acct_display_name as "acct_display_name",
	acct_type_desc as "acct_type_desc",
	acct_street_1 as "acct_street_1",
	acct_street_2 as "acct_street_2",
	acct_street_3 as "acct_street_3",
	acct_suburb as "acct_suburb",
	acct_postcode as "acct_postcode",
	acct_phone_number as "acct_phone_number",
	acct_fax_number as "acct_fax_number",
	acct_email as "acct_email",
	acct_country as "acct_country",
	acct_region as "acct_region",
	acct_state as "acct_state",
	acct_banner_country as "acct_banner_country",
	acct_banner_division as "acct_banner_division",
	acct_banner_type as "acct_banner_type",
	acct_banner as "acct_banner",
	acct_type as "acct_type",
	acct_sub_type as "acct_sub_type",
	acct_grade as "acct_grade",
	acct_nz_pharma_country as "acct_nz_pharma_country",
	acct_nz_pharma_state as "acct_nz_pharma_state",
	acct_nz_pharma_territory as "acct_nz_pharma_territory",
	acct_nz_groc_country as "acct_nz_groc_country",
	acct_nz_groc_state as "acct_nz_groc_state",
	acct_nz_groc_territory as "acct_nz_groc_territory",
	acct_ssr_country as "acct_ssr_country",
	acct_ssr_state as "acct_ssr_state",
	acct_ssr_team_leader as "acct_ssr_team_leader",
	acct_ssr_territory as "acct_ssr_territory",
	acct_ssr_sub_territory as "acct_ssr_sub_territory",
	acct_ind_groc_country as "acct_ind_groc_country",
	acct_ind_groc_state as "acct_ind_groc_state",
	acct_ind_groc_territory as "acct_ind_groc_territory",
	acct_ind_groc_sub_territory as "acct_ind_groc_sub_territory",
	acct_au_pharma_country as "acct_au_pharma_country",
	acct_au_pharma_state as "acct_au_pharma_state",
	acct_au_pharma_territory as "acct_au_pharma_territory",
	acct_au_pharma_ssr_country as "acct_au_pharma_ssr_country",
	acct_au_pharma_ssr_state as "acct_au_pharma_ssr_state",
	acct_au_pharma_ssr_territory as "acct_au_pharma_ssr_territory",
	acct_tsm as "acct_tsm",
	acct_terriroty as "acct_terriroty",
	acct_store_code as "acct_store_code",
	acct_fax_opt_out as "acct_fax_opt_out",
	acct_email_opt_out as "acct_email_opt_out",
	acct_contact_method as "acct_contact_method",
	ssr_grade as "ssr_grade",
	order_key as "order_key",
	order_date as "order_date",
	sent_dt as "sent_dt",
	delvry_instns as "delvry_instns",
	branch_key as "branch_key",
	batch_key as "batch_key",
	line_key as "line_key",
	unit_qty as "unit_qty",
	entered_qty as "entered_qty",
	entered_unit_key as "entered_unit_key",
	list_price as "list_price",
	nis as "nis",
	rrp as "rrp",
	deal_desc as "deal_desc",
	deal_start_date as "deal_start_date",
	deal_end_date as "deal_end_date",
	deal_short_desc as "deal_short_desc",
	discount_desc as "discount_desc",
	discount_per as "discount_per",
	discount_amt as "discount_amt",
	order_status as "order_status",
	batch_status as "batch_status",
	order_currency_cd as "order_currency_cd",
	create_user_name as "create_user_name",
	create_user_desc as "create_user_desc",
	create_user_email_address as "create_user_email_address",
	distributor as "distributor",
	distributor_display_name as "distributor_display_name",
	pharmacy_msl_rank as "pharmacy_msl_rank",
	pharmacy_msl_flag as "pharmacy_msl_flag",
	exch_rate_to_aud as "exch_rate_to_aud",
	aud_nis as "aud_nis",
	exch_rate_to_usd as "exch_rate_to_usd",
	usd_nis as "usd_nis",
	exch_rate_to_nzd as "exch_rate_to_nzd",
	nzd_nis as "nzd_nis",
	distribution_flag as "distribution_flag"
from pcfedw_integration.edw_pacific_perenso_ims_analysis;
create or replace view EDW_PACIFIC_PERENSO_IMS_PHARMACY_SNPSHOT_ANALYSIS(
	"delvry_dt",
	"snapshot_dt",
	"jj_year",
	"jj_qrtr",
	"jj_mnth_id",
	"jj_mnth_shrt",
	"acct_key",
	"acct_banner_division",
	"acct_banner",
	"acct_display_name",
	"acct_tsm",
	"acct_terriroty",
	"prod_sapbw_code",
	"prod_desc",
	"prod_jj_brand",
	"prod_ean",
	"prod_jj_franchise",
	"prod_jj_category",
	"unit_qty",
	"nis",
	"aud_nis",
	"usd_nis"
) as
select 
	delvry_dt as "delvry_dt",
	snapshot_dt as "snapshot_dt",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_shrt as "jj_mnth_shrt",
	acct_key as "acct_key",
	acct_banner_division as "acct_banner_division",
	acct_banner as "acct_banner",
	acct_display_name as "acct_display_name",
	acct_tsm as "acct_tsm",
	acct_terriroty as "acct_terriroty",
	prod_sapbw_code as "prod_sapbw_code",
	prod_desc as "prod_desc",
	prod_jj_brand as "prod_jj_brand",
	prod_ean as "prod_ean",
	prod_jj_franchise as "prod_jj_franchise",
	prod_jj_category as "prod_jj_category",
	unit_qty as "unit_qty",
	nis as "nis",
	aud_nis as "aud_nis",
	usd_nis as "usd_nis"
from pcfedw_integration.edw_pacific_perenso_ims_pharmacy_snpshot_analysis;
create or replace view EDW_PACIFIC_PHARMACY_DSTRBTN_ANALYSIS(
	"delvry_dt",
	"time_id",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_mnth_id",
	"cal_mnth_nm",
	"prod_key",
	"prod_desc",
	"prod_sapbw_code",
	"prod_ean",
	"prod_jj_franchise",
	"prod_jj_category",
	"prod_jj_brand",
	"prod_sap_franchise",
	"prod_sap_profit_centre",
	"prod_sap_product_major",
	"prod_grocery_franchise",
	"prod_grocery_category",
	"prod_grocery_brand",
	"prod_active_status",
	"prod_pbs",
	"prod_ims_brand",
	"prod_nz_code",
	"prod_metcash_code",
	"prod_old_id",
	"prod_old_ean",
	"prod_tax",
	"prod_bwp_aud",
	"prod_bwp_nzd",
	"acct_key",
	"acct_display_name",
	"acct_type_desc",
	"acct_street_1",
	"acct_street_2",
	"acct_street_3",
	"acct_suburb",
	"acct_postcode",
	"acct_phone_number",
	"acct_fax_number",
	"acct_email",
	"acct_country",
	"acct_region",
	"acct_state",
	"acct_banner_country",
	"acct_banner_division",
	"acct_banner_type",
	"acct_banner",
	"acct_type",
	"acct_sub_type",
	"acct_grade",
	"acct_nz_pharma_country",
	"acct_nz_pharma_state",
	"acct_nz_pharma_territory",
	"acct_nz_groc_country",
	"acct_nz_groc_state",
	"acct_nz_groc_territory",
	"acct_ssr_country",
	"acct_ssr_state",
	"acct_ssr_team_leader",
	"acct_ssr_territory",
	"acct_ssr_sub_territory",
	"acct_ind_groc_country",
	"acct_ind_groc_state",
	"acct_ind_groc_territory",
	"acct_ind_groc_sub_territory",
	"acct_au_pharma_country",
	"acct_au_pharma_state",
	"acct_au_pharma_territory",
	"acct_au_pharma_ssr_country",
	"acct_au_pharma_ssr_state",
	"acct_au_pharma_ssr_territory",
	"acct_tsm",
	"acct_terriroty",
	"acct_store_code",
	"acct_fax_opt_out",
	"acct_email_opt_out",
	"acct_contact_method",
	"curnt_mnth_nis",
	"curnt_mnth_qty",
	"curnt_mnth_avg_lp",
	"lst_mnth_nis",
	"lst_mnth_qty",
	"lst_mnth_avg_lp",
	"lst3_mnth_nis",
	"lst3_mnth_qty",
	"lst3_mnth_avg_lp",
	"lst6_mnth_nis",
	"lst6_mnth_qty",
	"lst6_mnth_avg_lp",
	"lst12_mnth_nis",
	"lst12_mnth_qty",
	"lst12_mnth_avg_lp",
	"curnt_mnth_dstrbtn_flag",
	"lst_mnth_dstrbtn_flag",
	"lst3_mnth_dstrbtn_flag",
	"lst6_mnth_dstrbtn_flag",
	"lst12_mnth_dstrbtn_flag",
	"curnt_mnth_dstrbtn_trgt",
	"lst_mnth_dstrbtn_trgt",
	"lst3_mnth_dstrbtn_trgt",
	"lst6_mnth_dstrbtn_trgt",
	"lst12_mnth_dstrbtn_trgt",
	"pharmacy_msl_rank",
	"pharmacy_msl_flag",
	"load_date"
) as
select 
	delvry_dt as "delvry_dt",
	time_id as "time_id",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	prod_key as "prod_key",
	prod_desc as "prod_desc",
	prod_sapbw_code as "prod_sapbw_code",
	prod_ean as "prod_ean",
	prod_jj_franchise as "prod_jj_franchise",
	prod_jj_category as "prod_jj_category",
	prod_jj_brand as "prod_jj_brand",
	prod_sap_franchise as "prod_sap_franchise",
	prod_sap_profit_centre as "prod_sap_profit_centre",
	prod_sap_product_major as "prod_sap_product_major",
	prod_grocery_franchise as "prod_grocery_franchise",
	prod_grocery_category as "prod_grocery_category",
	prod_grocery_brand as "prod_grocery_brand",
	prod_active_status as "prod_active_status",
	prod_pbs as "prod_pbs",
	prod_ims_brand as "prod_ims_brand",
	prod_nz_code as "prod_nz_code",
	prod_metcash_code as "prod_metcash_code",
	prod_old_id as "prod_old_id",
	prod_old_ean as "prod_old_ean",
	prod_tax as "prod_tax",
	prod_bwp_aud as "prod_bwp_aud",
	prod_bwp_nzd as "prod_bwp_nzd",
	acct_key as "acct_key",
	acct_display_name as "acct_display_name",
	acct_type_desc as "acct_type_desc",
	acct_street_1 as "acct_street_1",
	acct_street_2 as "acct_street_2",
	acct_street_3 as "acct_street_3",
	acct_suburb as "acct_suburb",
	acct_postcode as "acct_postcode",
	acct_phone_number as "acct_phone_number",
	acct_fax_number as "acct_fax_number",
	acct_email as "acct_email",
	acct_country as "acct_country",
	acct_region as "acct_region",
	acct_state as "acct_state",
	acct_banner_country as "acct_banner_country",
	acct_banner_division as "acct_banner_division",
	acct_banner_type as "acct_banner_type",
	acct_banner as "acct_banner",
	acct_type as "acct_type",
	acct_sub_type as "acct_sub_type",
	acct_grade as "acct_grade",
	acct_nz_pharma_country as "acct_nz_pharma_country",
	acct_nz_pharma_state as "acct_nz_pharma_state",
	acct_nz_pharma_territory as "acct_nz_pharma_territory",
	acct_nz_groc_country as "acct_nz_groc_country",
	acct_nz_groc_state as "acct_nz_groc_state",
	acct_nz_groc_territory as "acct_nz_groc_territory",
	acct_ssr_country as "acct_ssr_country",
	acct_ssr_state as "acct_ssr_state",
	acct_ssr_team_leader as "acct_ssr_team_leader",
	acct_ssr_territory as "acct_ssr_territory",
	acct_ssr_sub_territory as "acct_ssr_sub_territory",
	acct_ind_groc_country as "acct_ind_groc_country",
	acct_ind_groc_state as "acct_ind_groc_state",
	acct_ind_groc_territory as "acct_ind_groc_territory",
	acct_ind_groc_sub_territory as "acct_ind_groc_sub_territory",
	acct_au_pharma_country as "acct_au_pharma_country",
	acct_au_pharma_state as "acct_au_pharma_state",
	acct_au_pharma_territory as "acct_au_pharma_territory",
	acct_au_pharma_ssr_country as "acct_au_pharma_ssr_country",
	acct_au_pharma_ssr_state as "acct_au_pharma_ssr_state",
	acct_au_pharma_ssr_territory as "acct_au_pharma_ssr_territory",
	acct_tsm as "acct_tsm",
	acct_terriroty as "acct_terriroty",
	acct_store_code as "acct_store_code",
	acct_fax_opt_out as "acct_fax_opt_out",
	acct_email_opt_out as "acct_email_opt_out",
	acct_contact_method as "acct_contact_method",
	curnt_mnth_nis as "curnt_mnth_nis",
	curnt_mnth_qty as "curnt_mnth_qty",
	curnt_mnth_avg_lp as "curnt_mnth_avg_lp",
	lst_mnth_nis as "lst_mnth_nis",
	lst_mnth_qty as "lst_mnth_qty",
	lst_mnth_avg_lp as "lst_mnth_avg_lp",
	lst3_mnth_nis as "lst3_mnth_nis",
	lst3_mnth_qty as "lst3_mnth_qty",
	lst3_mnth_avg_lp as "lst3_mnth_avg_lp",
	lst6_mnth_nis as "lst6_mnth_nis",
	lst6_mnth_qty as "lst6_mnth_qty",
	lst6_mnth_avg_lp as "lst6_mnth_avg_lp",
	lst12_mnth_nis as "lst12_mnth_nis",
	lst12_mnth_qty as "lst12_mnth_qty",
	lst12_mnth_avg_lp as "lst12_mnth_avg_lp",
	curnt_mnth_dstrbtn_flag as "curnt_mnth_dstrbtn_flag",
	lst_mnth_dstrbtn_flag as "lst_mnth_dstrbtn_flag",
	lst3_mnth_dstrbtn_flag as "lst3_mnth_dstrbtn_flag",
	lst6_mnth_dstrbtn_flag as "lst6_mnth_dstrbtn_flag",
	lst12_mnth_dstrbtn_flag as "lst12_mnth_dstrbtn_flag",
	curnt_mnth_dstrbtn_trgt as "curnt_mnth_dstrbtn_trgt",
	lst_mnth_dstrbtn_trgt as "lst_mnth_dstrbtn_trgt",
	lst3_mnth_dstrbtn_trgt as "lst3_mnth_dstrbtn_trgt",
	lst6_mnth_dstrbtn_trgt as "lst6_mnth_dstrbtn_trgt",
	lst12_mnth_dstrbtn_trgt as "lst12_mnth_dstrbtn_trgt",
	pharmacy_msl_rank as "pharmacy_msl_rank",
	pharmacy_msl_flag as "pharmacy_msl_flag",
	load_date as "load_date"
from pcfedw_integration.edw_pacific_pharmacy_dstrbtn_analysis;
create or replace view EDW_PHARMACY_ECOMMERCE_ANALYSIS(
	"week_end_dt",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_mnth_id",
	"cal_mnth_nm",
	"prod_key",
	"product_probe_id",
	"prod_desc",
	"prod_sapbw_code",
	"prod_ean",
	"prod_jj_franchise",
	"prod_jj_category",
	"iqvia_prod_category",
	"prod_jj_brand",
	"prod_sap_franchise",
	"prod_sap_profit_centre",
	"prod_sap_product_major",
	"prod_grocery_franchise",
	"prod_grocery_category",
	"prod_grocery_brand",
	"prod_pbs",
	"prod_ims_brand",
	"prod_nz_code",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment",
	"cust_group",
	"ecomm_cust",
	"manufacturer",
	"unit_online",
	"aud_sales_online",
	"exch_rate_to_usd",
	"usd_sales_online"
) as
select 
	week_end_dt as "week_end_dt",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	prod_key as "prod_key",
	product_probe_id as "product_probe_id",
	prod_desc as "prod_desc",
	prod_sapbw_code as "prod_sapbw_code",
	prod_ean as "prod_ean",
	prod_jj_franchise as "prod_jj_franchise",
	prod_jj_category as "prod_jj_category",
	iqvia_prod_category as "iqvia_prod_category",
	prod_jj_brand as "prod_jj_brand",
	prod_sap_franchise as "prod_sap_franchise",
	prod_sap_profit_centre as "prod_sap_profit_centre",
	prod_sap_product_major as "prod_sap_product_major",
	prod_grocery_franchise as "prod_grocery_franchise",
	prod_grocery_category as "prod_grocery_category",
	prod_grocery_brand as "prod_grocery_brand",
	prod_pbs as "prod_pbs",
	prod_ims_brand as "prod_ims_brand",
	prod_nz_code as "prod_nz_code",
	gcph_franchise as "gcph_franchise",
	gcph_brand as "gcph_brand",
	gcph_subbrand as "gcph_subbrand",
	gcph_variant as "gcph_variant",
	gcph_needstate as "gcph_needstate",
	gcph_category as "gcph_category",
	gcph_subcategory as "gcph_subcategory",
	gcph_segment as "gcph_segment",
	gcph_subsegment as "gcph_subsegment",
	cust_group as "cust_group",
	ecomm_cust as "ecomm_cust",
	manufacturer as "manufacturer",
	unit_online as "unit_online",
	aud_sales_online as "aud_sales_online",
	exch_rate_to_usd as "exch_rate_to_usd",
	usd_sales_online as "usd_sales_online"
from pcfedw_integration.edw_pharmacy_ecommerce_analysis;
create or replace view EDW_PROMAX_ANALYSIS_SNAPSHOT(
	"snapshot_date",
	"snapshot_month",
	"snapshot_year",
	"ac_code",
	"ac_longname",
	"activity_longname",
	"channel_desc",
	"closed_switch",
	"confirmed_switch",
	"country",
	"curr_cd",
	"cust_no",
	"cust_del_flag",
	"cust_nm",
	"fran_desc",
	"gltt_rowid",
	"grp_fran_desc",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_mnth",
	"jj_mnth_id",
	"jj_qrtr",
	"jj_wk",
	"jj_year",
	"local_ccy",
	"matl_desc",
	"matl_id",
	"mega_brnd_desc",
	"prod_fran_desc",
	"prod_mjr_desc",
	"prod_mnr_desc",
	"promax_bucket",
	"p_buystartdatedef",
	"p_buystopdatedef",
	"p_deleted",
	"promotionforecastweek",
	"p_promonumber",
	"promotionrowid",
	"p_startdate",
	"p_stopdate",
	"sales_grp_desc",
	"sales_office_desc",
	"sap_accnt_nm",
	"sap_account",
	"transaction_longname",
	"updt_dt",
	"buyperiod_length",
	"case_deal",
	"case_quantity",
	"committed_spend",
	"aud_rate",
	"open_total",
	"paid_total",
	"planspend_total",
	"promo_length"
) as
select
    snapshot_date as "snapshot_date",
snapshot_month as "snapshot_month",
snapshot_year as "snapshot_year",
ac_code as "ac_code",
ac_longname as "ac_longname",
activity_longname as "activity_longname",
channel_desc as "channel_desc",
closed_switch as "closed_switch",
confirmed_switch as "confirmed_switch",
country as "country",
curr_cd as "curr_cd",
cust_no as "cust_no",
cust_del_flag as "cust_del_flag",
cust_nm as "cust_nm",
fran_desc as "fran_desc",
gltt_rowid as "gltt_rowid",
grp_fran_desc as "grp_fran_desc",
jj_mnth_day as "jj_mnth_day",
jj_mnth_shrt as "jj_mnth_shrt",
jj_mnth_long as "jj_mnth_long",
jj_mnth as "jj_mnth",
jj_mnth_id as "jj_mnth_id",
jj_qrtr as "jj_qrtr",
jj_wk as "jj_wk",
jj_year as "jj_year",
local_ccy as "local_ccy",
matl_desc as "matl_desc",
matl_id as "matl_id",
mega_brnd_desc as "mega_brnd_desc",
prod_fran_desc as "prod_fran_desc",
prod_mjr_desc as "prod_mjr_desc",
prod_mnr_desc as "prod_mnr_desc",
promax_bucket as "promax_bucket",
p_buystartdatedef as "p_buystartdatedef",
p_buystopdatedef as "p_buystopdatedef",
p_deleted as "p_deleted",
promotionforecastweek as "promotionforecastweek",
p_promonumber as "p_promonumber",
promotionrowid as "promotionrowid",
p_startdate as "p_startdate",
p_stopdate as "p_stopdate",
sales_grp_desc as "sales_grp_desc",
sales_office_desc as "sales_office_desc",
sap_accnt_nm as "sap_accnt_nm",
sap_account as "sap_account",
transaction_longname as "transaction_longname",
updt_dt as "updt_dt",
buyperiod_length as "buyperiod_length",
case_deal as "case_deal",
case_quantity as "case_quantity",
committed_spend as "committed_spend",
aud_rate as "aud_rate",
open_total as "open_total",
paid_total as "paid_total",
planspend_total as "planspend_total",
promo_length as "promo_length"
from pcfedw_integration.edw_promax_analysis_snapshot;
create or replace view EDW_PROMAX_CIW_SNAPSHOT(
	"snapshot_date",
	"snapshot_month",
	"snapshot_year",
	"jj_period",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"cust_no",
	"cmp_desc",
	"channel_desc",
	"cust_nm",
	"sales_office_desc",
	"sales_grp_desc",
	"matl_id",
	"matl_desc",
	"parent_matl_id",
	"parent_matl_desc",
	"fran_desc",
	"grp_fran_desc",
	"matl_type_desc",
	"prod_fran_desc",
	"prod_mjr_desc",
	"prod_mnr_desc",
	"base_curr_cd",
	"to_ccy",
	"px_qty",
	"px_gts",
	"px_eff_val",
	"px_jgf_si_val",
	"px_pmt_terms_val",
	"px_datains_val",
	"px_exp_adj_val",
	"px_jgf_sd_val",
	"px_ciw_tot",
	"px_nts"
) as
select
    snapshot_date as "snapshot_date",
snapshot_month as "snapshot_month",
snapshot_year as "snapshot_year",
jj_period as "jj_period",
jj_wk as "jj_wk",
jj_mnth as "jj_mnth",
jj_mnth_shrt as "jj_mnth_shrt",
jj_mnth_long as "jj_mnth_long",
jj_qrtr as "jj_qrtr",
jj_year as "jj_year",
cust_no as "cust_no",
cmp_desc as "cmp_desc",
channel_desc as "channel_desc",
cust_nm as "cust_nm",
sales_office_desc as "sales_office_desc",
sales_grp_desc as "sales_grp_desc",
matl_id as "matl_id",
matl_desc as "matl_desc",
parent_matl_id as "parent_matl_id",
parent_matl_desc as "parent_matl_desc",
fran_desc as "fran_desc",
grp_fran_desc as "grp_fran_desc",
matl_type_desc as "matl_type_desc",
prod_fran_desc as "prod_fran_desc",
prod_mjr_desc as "prod_mjr_desc",
prod_mnr_desc as "prod_mnr_desc",
base_curr_cd as "base_curr_cd",
to_ccy as "to_ccy",
px_qty as "px_qty",
px_gts as "px_gts",
px_eff_val as "px_eff_val",
px_jgf_si_val as "px_jgf_si_val",
px_pmt_terms_val as "px_pmt_terms_val",
px_datains_val as "px_datains_val",
px_exp_adj_val as "px_exp_adj_val",
px_jgf_sd_val as "px_jgf_sd_val",
px_ciw_tot as "px_ciw_tot",
px_nts as "px_nts"
from pcfedw_integration.edw_promax_ciw_snapshot;
create or replace view EDW_SALES_REPORTING(
	"snap_shot_dt",
	"pac_source_type",
	"pac_subsource_type",
	"jj_period",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"jj_mnth_tot",
	"prcnt_elpsd",
	"elpsd_jj_period",
	"cust_no",
	"cmp_id",
	"channel_cd",
	"channel_desc",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"mercia_ref",
	"pln_cnnl_cd",
	"pln_chnl_desc",
	"cust_curr_cd",
	"matl_id",
	"matl_desc",
	"master_code",
	"parent_matl_id",
	"parent_matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"prft_ctr",
	"divest_flag",
	"key_measure",
	"ciw_ctgry",
	"ciw_accnt_grp",
	"px_gl_trans_desc",
	"px_measure",
	"px_bucket",
	"sap_accnt",
	"sap_accnt_desc",
	"local_curr_cd",
	"to_ccy",
	"exch_rate",
	"base_measure",
	"sales_qty",
	"gts",
	"gts_less_rtrn",
	"eff_val",
	"jgf_si_val",
	"pmt_terms_val",
	"datains_val",
	"exp_adj_val",
	"jgf_sd_val",
	"nts_val",
	"tot_ciw_val",
	"posted_cogs",
	"posted_con_free_goods_val",
	"posted_gp",
	"cogs",
	"gp",
	"futr_sls_qty",
	"futr_gts",
	"futr_ts",
	"futr_nts",
	"px_qty",
	"px_gts",
	"px_gts_less_rtrn",
	"px_eff_val",
	"px_jgf_si_val",
	"px_pmt_terms_val",
	"px_datains_val",
	"px_exp_adj_val",
	"px_jgf_sd_val",
	"px_nts",
	"px_ciw_tot",
	"px_cogs",
	"px_gp",
	"projected_qty",
	"projected_gts_less_rtrn",
	"projected_eff_val",
	"projected_jgf_si_val",
	"projected_pmt_terms_val",
	"projected_datains_val",
	"projected_exp_adj_val",
	"projected_jgf_sd_val",
	"projected_ciw_tot",
	"projected_nts",
	"projected_cogs_current",
	"projected_gp_current",
	"projected_cogs_actual",
	"projected_gp_actual",
	"goal_qty",
	"goal_gts",
	"goal_eff_val",
	"goal_jgf_si_val",
	"goal_pmt_terms_val",
	"goal_datains_val",
	"goal_exp_adj_val",
	"goal_jgf_sd_val",
	"goal_ciw_tot",
	"goal_nts",
	"goal_cogs",
	"goal_gp",
	"bp_qty",
	"bp_gts",
	"bp_eff_val",
	"bp_jgf_si_val",
	"bp_pmt_terms_val",
	"bp_datains_val",
	"bp_exp_adj_val",
	"bp_jgf_sd_val",
	"bp_ciw_tot",
	"bp_nts",
	"bp_cogs",
	"bp_gp",
	"ju_qty",
	"ju_gts",
	"ju_eff_val",
	"ju_jgf_si_val",
	"ju_pmt_terms_val",
	"ju_datains_val",
	"ju_exp_adj_val",
	"ju_jgf_sd_val",
	"ju_ciw_tot",
	"ju_nts",
	"ju_cogs",
	"ju_gp",
	"nu_qty",
	"nu_gts",
	"nu_eff_val",
	"nu_jgf_si_val",
	"nu_pmt_terms_val",
	"nu_datains_val",
	"nu_exp_adj_val",
	"nu_jgf_sd_val",
	"nu_ciw_tot",
	"nu_nts",
	"nu_cogs",
	"nu_gp",
	"bme_trans",
	"incr_gts",
	"px_case_qty",
	"px_tot_planspend",
	"px_tot_paid",
	"px_committed_spend",
	"finance_cogs",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment"
) as
select 
	snap_shot_dt as "snap_shot_dt",
	pac_source_type as "pac_source_type",
	pac_subsource_type as "pac_subsource_type",
	jj_period as "jj_period",
	jj_wk as "jj_wk",
	jj_mnth as "jj_mnth",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	jj_qrtr as "jj_qrtr",
	jj_year as "jj_year",
	jj_mnth_tot as "jj_mnth_tot",
	prcnt_elpsd as "prcnt_elpsd",
	elpsd_jj_period as "elpsd_jj_period",
	cust_no as "cust_no",
	cmp_id as "cmp_id",
	channel_cd as "channel_cd",
	channel_desc as "channel_desc",
	ctry_key as "ctry_key",
	country as "country",
	state_cd as "state_cd",
	post_cd as "post_cd",
	cust_suburb as "cust_suburb",
	cust_nm as "cust_nm",
	sales_office_cd as "sales_office_cd",
	sales_office_desc as "sales_office_desc",
	sales_grp_cd as "sales_grp_cd",
	sales_grp_desc as "sales_grp_desc",
	mercia_ref as "mercia_ref",
	pln_cnnl_cd as "pln_cnnl_cd",
	pln_chnl_desc as "pln_chnl_desc",
	cust_curr_cd as "cust_curr_cd",
	matl_id as "matl_id",
	matl_desc as "matl_desc",
	master_code as "master_code",
	parent_matl_id as "parent_matl_id",
	parent_matl_desc as "parent_matl_desc",
	mega_brnd_cd as "mega_brnd_cd",
	mega_brnd_desc as "mega_brnd_desc",
	brnd_cd as "brnd_cd",
	brnd_desc as "brnd_desc",
	base_prod_cd as "base_prod_cd",
	base_prod_desc as "base_prod_desc",
	variant_cd as "variant_cd",
	variant_desc as "variant_desc",
	fran_cd as "fran_cd",
	fran_desc as "fran_desc",
	grp_fran_cd as "grp_fran_cd",
	grp_fran_desc as "grp_fran_desc",
	matl_type_cd as "matl_type_cd",
	matl_type_desc as "matl_type_desc",
	prod_fran_cd as "prod_fran_cd",
	prod_fran_desc as "prod_fran_desc",
	prod_hier_cd as "prod_hier_cd",
	prod_hier_desc as "prod_hier_desc",
	prod_mjr_cd as "prod_mjr_cd",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_cd as "prod_mnr_cd",
	prod_mnr_desc as "prod_mnr_desc",
	mercia_plan as "mercia_plan",
	putup_cd as "putup_cd",
	putup_desc as "putup_desc",
	bar_cd as "bar_cd",
	prft_ctr as "prft_ctr",
	divest_flag as "divest_flag",
	key_measure as "key_measure",
	ciw_ctgry as "ciw_ctgry",
	ciw_accnt_grp as "ciw_accnt_grp",
	px_gl_trans_desc as "px_gl_trans_desc",
	px_measure as "px_measure",
	px_bucket as "px_bucket",
	sap_accnt as "sap_accnt",
	sap_accnt_desc as "sap_accnt_desc",
	local_curr_cd as "local_curr_cd",
	to_ccy as "to_ccy",
	exch_rate as "exch_rate",
	base_measure as "base_measure",
	sales_qty as "sales_qty",
	gts as "gts",
	gts_less_rtrn as "gts_less_rtrn",
	eff_val as "eff_val",
	jgf_si_val as "jgf_si_val",
	pmt_terms_val as "pmt_terms_val",
	datains_val as "datains_val",
	exp_adj_val as "exp_adj_val",
	jgf_sd_val as "jgf_sd_val",
	nts_val as "nts_val",
	tot_ciw_val as "tot_ciw_val",
	posted_cogs as "posted_cogs",
	posted_con_free_goods_val as "posted_con_free_goods_val",
	posted_gp as "posted_gp",
	cogs as "cogs",
	gp as "gp",
	futr_sls_qty as "futr_sls_qty",
	futr_gts as "futr_gts",
	futr_ts as "futr_ts",
	futr_nts as "futr_nts",
	px_qty as "px_qty",
	px_gts as "px_gts",
	px_gts_less_rtrn as "px_gts_less_rtrn",
	px_eff_val as "px_eff_val",
	px_jgf_si_val as "px_jgf_si_val",
	px_pmt_terms_val as "px_pmt_terms_val",
	px_datains_val as "px_datains_val",
	px_exp_adj_val as "px_exp_adj_val",
	px_jgf_sd_val as "px_jgf_sd_val",
	px_nts as "px_nts",
	px_ciw_tot as "px_ciw_tot",
	px_cogs as "px_cogs",
	px_gp as "px_gp",
	projected_qty as "projected_qty",
	projected_gts_less_rtrn as "projected_gts_less_rtrn",
	projected_eff_val as "projected_eff_val",
	projected_jgf_si_val as "projected_jgf_si_val",
	projected_pmt_terms_val as "projected_pmt_terms_val",
	projected_datains_val as "projected_datains_val",
	projected_exp_adj_val as "projected_exp_adj_val",
	projected_jgf_sd_val as "projected_jgf_sd_val",
	projected_ciw_tot as "projected_ciw_tot",
	projected_nts as "projected_nts",
	projected_cogs_current as "projected_cogs_current",
	projected_gp_current as "projected_gp_current",
	projected_cogs_actual as "projected_cogs_actual",
	projected_gp_actual as "projected_gp_actual",
	goal_qty as "goal_qty",
	goal_gts as "goal_gts",
	goal_eff_val as "goal_eff_val",
	goal_jgf_si_val as "goal_jgf_si_val",
	goal_pmt_terms_val as "goal_pmt_terms_val",
	goal_datains_val as "goal_datains_val",
	goal_exp_adj_val as "goal_exp_adj_val",
	goal_jgf_sd_val as "goal_jgf_sd_val",
	goal_ciw_tot as "goal_ciw_tot",
	goal_nts as "goal_nts",
	goal_cogs as "goal_cogs",
	goal_gp as "goal_gp",
	bp_qty as "bp_qty",
	bp_gts as "bp_gts",
	bp_eff_val as "bp_eff_val",
	bp_jgf_si_val as "bp_jgf_si_val",
	bp_pmt_terms_val as "bp_pmt_terms_val",
	bp_datains_val as "bp_datains_val",
	bp_exp_adj_val as "bp_exp_adj_val",
	bp_jgf_sd_val as "bp_jgf_sd_val",
	bp_ciw_tot as "bp_ciw_tot",
	bp_nts as "bp_nts",
	bp_cogs as "bp_cogs",
	bp_gp as "bp_gp",
	ju_qty as "ju_qty",
	ju_gts as "ju_gts",
	ju_eff_val as "ju_eff_val",
	ju_jgf_si_val as "ju_jgf_si_val",
	ju_pmt_terms_val as "ju_pmt_terms_val",
	ju_datains_val as "ju_datains_val",
	ju_exp_adj_val as "ju_exp_adj_val",
	ju_jgf_sd_val as "ju_jgf_sd_val",
	ju_ciw_tot as "ju_ciw_tot",
	ju_nts as "ju_nts",
	ju_cogs as "ju_cogs",
	ju_gp as "ju_gp",
	nu_qty as "nu_qty",
	nu_gts as "nu_gts",
	nu_eff_val as "nu_eff_val",
	nu_jgf_si_val as "nu_jgf_si_val",
	nu_pmt_terms_val as "nu_pmt_terms_val",
	nu_datains_val as "nu_datains_val",
	nu_exp_adj_val as "nu_exp_adj_val",
	nu_jgf_sd_val as "nu_jgf_sd_val",
	nu_ciw_tot as "nu_ciw_tot",
	nu_nts as "nu_nts",
	nu_cogs as "nu_cogs",
	nu_gp as "nu_gp",
	bme_trans as "bme_trans",
	incr_gts as "incr_gts",
	px_case_qty as "px_case_qty",
	px_tot_planspend as "px_tot_planspend",
	px_tot_paid as "px_tot_paid",
	px_committed_spend as "px_committed_spend",
	finance_cogs as "finance_cogs",
	gcph_franchise as "gcph_franchise",
	gcph_brand as "gcph_brand",
	gcph_subbrand as "gcph_subbrand",
	gcph_variant as "gcph_variant",
	gcph_needstate as "gcph_needstate",
	gcph_category as "gcph_category",
	gcph_subcategory as "gcph_subcategory",
	gcph_segment as "gcph_segment",
	gcph_subsegment as "gcph_subsegment"
from pcfedw_integration.edw_sales_reporting;
create or replace view EDW_SALES_REPORTING_SNAPSHOT(
	"snap_shot_dt",
	"snap_shot_mnth",
	"snap_shot_year",
	"pac_source_type",
	"pac_subsource_type",
	"jj_period",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"jj_mnth_tot",
	"prcnt_elpsd",
	"elpsd_jj_period",
	"cust_no",
	"cmp_id",
	"channel_cd",
	"channel_desc",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"mercia_ref",
	"pln_cnnl_cd",
	"pln_chnl_desc",
	"cust_curr_cd",
	"matl_id",
	"matl_desc",
	"master_code",
	"parent_matl_id",
	"parent_matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"prft_ctr",
	"divest_flag",
	"key_measure",
	"ciw_ctgry",
	"ciw_accnt_grp",
	"px_gl_trans_desc",
	"px_measure",
	"px_bucket",
	"sap_accnt",
	"sap_accnt_desc",
	"local_curr_cd",
	"to_ccy",
	"exch_rate",
	"base_measure",
	"sales_qty",
	"gts",
	"gts_less_rtrn",
	"eff_val",
	"jgf_si_val",
	"pmt_terms_val",
	"datains_val",
	"exp_adj_val",
	"jgf_sd_val",
	"nts_val",
	"tot_ciw_val",
	"posted_cogs",
	"posted_con_free_goods_val",
	"posted_gp",
	"cogs",
	"gp",
	"futr_sls_qty",
	"futr_gts",
	"futr_ts",
	"futr_nts",
	"px_qty",
	"px_gts",
	"px_gts_less_rtrn",
	"px_eff_val",
	"px_jgf_si_val",
	"px_pmt_terms_val",
	"px_datains_val",
	"px_exp_adj_val",
	"px_jgf_sd_val",
	"px_nts",
	"px_ciw_tot",
	"px_cogs",
	"px_gp",
	"projected_qty",
	"projected_gts_less_rtrn",
	"projected_eff_val",
	"projected_jgf_si_val",
	"projected_pmt_terms_val",
	"projected_datains_val",
	"projected_exp_adj_val",
	"projected_jgf_sd_val",
	"projected_ciw_tot",
	"projected_nts",
	"projected_cogs_current",
	"projected_gp_current",
	"projected_cogs_actual",
	"projected_gp_actual",
	"goal_qty",
	"goal_gts",
	"goal_eff_val",
	"goal_jgf_si_val",
	"goal_pmt_terms_val",
	"goal_datains_val",
	"goal_exp_adj_val",
	"goal_jgf_sd_val",
	"goal_ciw_tot",
	"goal_nts",
	"goal_cogs",
	"goal_gp",
	"bp_qty",
	"bp_gts",
	"bp_eff_val",
	"bp_jgf_si_val",
	"bp_pmt_terms_val",
	"bp_datains_val",
	"bp_exp_adj_val",
	"bp_jgf_sd_val",
	"bp_ciw_tot",
	"bp_nts",
	"bp_cogs",
	"bp_gp",
	"ju_qty",
	"ju_gts",
	"ju_eff_val",
	"ju_jgf_si_val",
	"ju_pmt_terms_val",
	"ju_datains_val",
	"ju_exp_adj_val",
	"ju_jgf_sd_val",
	"ju_ciw_tot",
	"ju_nts",
	"ju_cogs",
	"ju_gp",
	"nu_qty",
	"nu_gts",
	"nu_eff_val",
	"nu_jgf_si_val",
	"nu_pmt_terms_val",
	"nu_datains_val",
	"nu_exp_adj_val",
	"nu_jgf_sd_val",
	"nu_ciw_tot",
	"nu_nts",
	"nu_cogs",
	"nu_gp",
	"bme_trans",
	"incr_gts",
	"px_case_qty",
	"px_tot_planspend",
	"px_tot_paid",
	"px_committed_spend",
	"finance_cogs",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment"
) as
select 
	snap_shot_dt as "snap_shot_dt",
	snap_shot_mnth as "snap_shot_mnth",
	snap_shot_year as "snap_shot_year",
	pac_source_type as "pac_source_type",
	pac_subsource_type as "pac_subsource_type",
	jj_period as "jj_period",
	jj_wk as "jj_wk",
	jj_mnth as "jj_mnth",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	jj_qrtr as "jj_qrtr",
	jj_year as "jj_year",
	jj_mnth_tot as "jj_mnth_tot",
	prcnt_elpsd as "prcnt_elpsd",
	elpsd_jj_period as "elpsd_jj_period",
	cust_no as "cust_no",
	cmp_id as "cmp_id",
	channel_cd as "channel_cd",
	channel_desc as "channel_desc",
	ctry_key as "ctry_key",
	country as "country",
	state_cd as "state_cd",
	post_cd as "post_cd",
	cust_suburb as "cust_suburb",
	cust_nm as "cust_nm",
	sales_office_cd as "sales_office_cd",
	sales_office_desc as "sales_office_desc",
	sales_grp_cd as "sales_grp_cd",
	sales_grp_desc as "sales_grp_desc",
	mercia_ref as "mercia_ref",
	pln_cnnl_cd as "pln_cnnl_cd",
	pln_chnl_desc as "pln_chnl_desc",
	cust_curr_cd as "cust_curr_cd",
	matl_id as "matl_id",
	matl_desc as "matl_desc",
	master_code as "master_code",
	parent_matl_id as "parent_matl_id",
	parent_matl_desc as "parent_matl_desc",
	mega_brnd_cd as "mega_brnd_cd",
	mega_brnd_desc as "mega_brnd_desc",
	brnd_cd as "brnd_cd",
	brnd_desc as "brnd_desc",
	base_prod_cd as "base_prod_cd",
	base_prod_desc as "base_prod_desc",
	variant_cd as "variant_cd",
	variant_desc as "variant_desc",
	fran_cd as "fran_cd",
	fran_desc as "fran_desc",
	grp_fran_cd as "grp_fran_cd",
	grp_fran_desc as "grp_fran_desc",
	matl_type_cd as "matl_type_cd",
	matl_type_desc as "matl_type_desc",
	prod_fran_cd as "prod_fran_cd",
	prod_fran_desc as "prod_fran_desc",
	prod_hier_cd as "prod_hier_cd",
	prod_hier_desc as "prod_hier_desc",
	prod_mjr_cd as "prod_mjr_cd",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_cd as "prod_mnr_cd",
	prod_mnr_desc as "prod_mnr_desc",
	mercia_plan as "mercia_plan",
	putup_cd as "putup_cd",
	putup_desc as "putup_desc",
	bar_cd as "bar_cd",
	prft_ctr as "prft_ctr",
	divest_flag as "divest_flag",
	key_measure as "key_measure",
	ciw_ctgry as "ciw_ctgry",
	ciw_accnt_grp as "ciw_accnt_grp",
	px_gl_trans_desc as "px_gl_trans_desc",
	px_measure as "px_measure",
	px_bucket as "px_bucket",
	sap_accnt as "sap_accnt",
	sap_accnt_desc as "sap_accnt_desc",
	local_curr_cd as "local_curr_cd",
	to_ccy as "to_ccy",
	exch_rate as "exch_rate",
	base_measure as "base_measure",
	sales_qty as "sales_qty",
	gts as "gts",
	gts_less_rtrn as "gts_less_rtrn",
	eff_val as "eff_val",
	jgf_si_val as "jgf_si_val",
	pmt_terms_val as "pmt_terms_val",
	datains_val as "datains_val",
	exp_adj_val as "exp_adj_val",
	jgf_sd_val as "jgf_sd_val",
	nts_val as "nts_val",
	tot_ciw_val as "tot_ciw_val",
	posted_cogs as "posted_cogs",
	posted_con_free_goods_val as "posted_con_free_goods_val",
	posted_gp as "posted_gp",
	cogs as "cogs",
	gp as "gp",
	futr_sls_qty as "futr_sls_qty",
	futr_gts as "futr_gts",
	futr_ts as "futr_ts",
	futr_nts as "futr_nts",
	px_qty as "px_qty",
	px_gts as "px_gts",
	px_gts_less_rtrn as "px_gts_less_rtrn",
	px_eff_val as "px_eff_val",
	px_jgf_si_val as "px_jgf_si_val",
	px_pmt_terms_val as "px_pmt_terms_val",
	px_datains_val as "px_datains_val",
	px_exp_adj_val as "px_exp_adj_val",
	px_jgf_sd_val as "px_jgf_sd_val",
	px_nts as "px_nts",
	px_ciw_tot as "px_ciw_tot",
	px_cogs as "px_cogs",
	px_gp as "px_gp",
	projected_qty as "projected_qty",
	projected_gts_less_rtrn as "projected_gts_less_rtrn",
	projected_eff_val as "projected_eff_val",
	projected_jgf_si_val as "projected_jgf_si_val",
	projected_pmt_terms_val as "projected_pmt_terms_val",
	projected_datains_val as "projected_datains_val",
	projected_exp_adj_val as "projected_exp_adj_val",
	projected_jgf_sd_val as "projected_jgf_sd_val",
	projected_ciw_tot as "projected_ciw_tot",
	projected_nts as "projected_nts",
	projected_cogs_current as "projected_cogs_current",
	projected_gp_current as "projected_gp_current",
	projected_cogs_actual as "projected_cogs_actual",
	projected_gp_actual as "projected_gp_actual",
	goal_qty as "goal_qty",
	goal_gts as "goal_gts",
	goal_eff_val as "goal_eff_val",
	goal_jgf_si_val as "goal_jgf_si_val",
	goal_pmt_terms_val as "goal_pmt_terms_val",
	goal_datains_val as "goal_datains_val",
	goal_exp_adj_val as "goal_exp_adj_val",
	goal_jgf_sd_val as "goal_jgf_sd_val",
	goal_ciw_tot as "goal_ciw_tot",
	goal_nts as "goal_nts",
	goal_cogs as "goal_cogs",
	goal_gp as "goal_gp",
	bp_qty as "bp_qty",
	bp_gts as "bp_gts",
	bp_eff_val as "bp_eff_val",
	bp_jgf_si_val as "bp_jgf_si_val",
	bp_pmt_terms_val as "bp_pmt_terms_val",
	bp_datains_val as "bp_datains_val",
	bp_exp_adj_val as "bp_exp_adj_val",
	bp_jgf_sd_val as "bp_jgf_sd_val",
	bp_ciw_tot as "bp_ciw_tot",
	bp_nts as "bp_nts",
	bp_cogs as "bp_cogs",
	bp_gp as "bp_gp",
	ju_qty as "ju_qty",
	ju_gts as "ju_gts",
	ju_eff_val as "ju_eff_val",
	ju_jgf_si_val as "ju_jgf_si_val",
	ju_pmt_terms_val as "ju_pmt_terms_val",
	ju_datains_val as "ju_datains_val",
	ju_exp_adj_val as "ju_exp_adj_val",
	ju_jgf_sd_val as "ju_jgf_sd_val",
	ju_ciw_tot as "ju_ciw_tot",
	ju_nts as "ju_nts",
	ju_cogs as "ju_cogs",
	ju_gp as "ju_gp",
	nu_qty as "nu_qty",
	nu_gts as "nu_gts",
	nu_eff_val as "nu_eff_val",
	nu_jgf_si_val as "nu_jgf_si_val",
	nu_pmt_terms_val as "nu_pmt_terms_val",
	nu_datains_val as "nu_datains_val",
	nu_exp_adj_val as "nu_exp_adj_val",
	nu_jgf_sd_val as "nu_jgf_sd_val",
	nu_ciw_tot as "nu_ciw_tot",
	nu_nts as "nu_nts",
	nu_cogs as "nu_cogs",
	nu_gp as "nu_gp",
	bme_trans as "bme_trans",
	incr_gts as "incr_gts",
	px_case_qty as "px_case_qty",
	px_tot_planspend as "px_tot_planspend",
	px_tot_paid as "px_tot_paid",
	px_committed_spend as "px_committed_spend",
	finance_cogs as "finance_cogs",
	gcph_franchise as "gcph_franchise",
	gcph_brand as "gcph_brand",
	gcph_subbrand as "gcph_subbrand",
	gcph_variant as "gcph_variant",
	gcph_needstate as "gcph_needstate",
	gcph_category as "gcph_category",
	gcph_subcategory as "gcph_subcategory",
	gcph_segment as "gcph_segment",
	gcph_subsegment as "gcph_subsegment"
from pcfedw_integration.edw_sales_reporting_snapshot;
create or replace view EDW_SLS_EVOLUTION(
	"country",
	"snapshot_date",
	"cust_no",
	"matl_id",
	"grp_fran_desc",
	"prod_fran_desc",
	"prod_mjr_desc",
	"prod_mnr_desc",
	"matl_desc",
	"brnd_desc",
	"gcph_franchise",
	"gcph_brand",
	"gcph_subbrand",
	"gcph_variant",
	"gcph_needstate",
	"gcph_category",
	"gcph_subcategory",
	"gcph_segment",
	"gcph_subsegment",
	"master_code",
	"channel_desc",
	"sales_office_desc",
	"cust_nm",
	"sales_grp_desc",
	"key_measure",
	"ciw_ctgry",
	"ciw_accnt_grp",
	"sap_accnt",
	"local_curr_cd",
	"curr_jj_period",
	"prev_jj_period",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_year",
	"jj_period",
	"jj_qrtr",
	"to_ccy",
	"exch_rate",
	"gts",
	"futr_gts"
) as
select 
	country as "country",
	snapshot_date as "snapshot_date",
	cust_no as "cust_no",
	matl_id as "matl_id",
	grp_fran_desc as "grp_fran_desc",
	prod_fran_desc as "prod_fran_desc",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_desc as "prod_mnr_desc",
	matl_desc as "matl_desc",
	brnd_desc as "brnd_desc",
	gcph_franchise as "gcph_franchise",
	gcph_brand as "gcph_brand",
	gcph_subbrand as "gcph_subbrand",
	gcph_variant as "gcph_variant",
	gcph_needstate as "gcph_needstate",
	gcph_category as "gcph_category",
	gcph_subcategory as "gcph_subcategory",
	gcph_segment as "gcph_segment",
	gcph_subsegment as "gcph_subsegment",
	master_code as "master_code",
	channel_desc as "channel_desc",
	sales_office_desc as "sales_office_desc",
	cust_nm as "cust_nm",
	sales_grp_desc as "sales_grp_desc",
	key_measure as "key_measure",
	ciw_ctgry as "ciw_ctgry",
	ciw_accnt_grp as "ciw_accnt_grp",
	sap_accnt as "sap_accnt",
	local_curr_cd as "local_curr_cd",
	curr_jj_period as "curr_jj_period",
	prev_jj_period as "prev_jj_period",
	jj_mnth as "jj_mnth",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_year as "jj_year",
	jj_period as "jj_period",
	jj_qrtr as "jj_qrtr",
	to_ccy as "to_ccy",
	exch_rate as "exch_rate",
	gts as "gts",
	futr_gts as "futr_gts"
from pcfedw_integration.edw_sls_evolution;
create or replace view VW_COMPETITIVE_BANNER_GROUP(
	"market",
	"banner",
	"banner_classification",
	"manufacturer",
	"brand",
	"sku_name",
	"ean_number",
	"unit",
	"dollar",
	"year",
	"month",
	"quarter",
	"jj_mnth",
	"jj_qrtr",
	"jj_year",
	"country",
	"currency",
	"crt_dttm"
) as
select market AS "market",
	banner AS "banner",
	banner_classification AS "banner_classification",
	manufacturer AS "manufacturer",
	brand AS "brand",
	sku_name AS "sku_name",
	ean_number AS "ean_number",
	unit AS "unit",
	dollar AS "dollar",
	year AS "year",
	month AS "month",
	quarter AS "quarter",
	jj_mnth AS "jj_mnth",
	jj_qrtr AS "jj_qrtr",
	jj_year AS "jj_year",
	country AS "country",
	currency AS "currency",
	crt_dttm AS "crt_dttm"
from PCFEDW_INTEGRATION.VW_COMPETITIVE_BANNER_GROUP;
create or replace view VW_DEMAND_FORECAST_ANALYSIS(
	"pac_source_type",
	"pac_subsource_type",
	"jj_period",
	"jj_week_no",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"jj_mnth_tot",
	"week_date",
	"matl_no",
	"matl_desc",
	"master_code",
	"parent_id",
	"parent_matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"cust_no",
	"cmp_id",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"fcst_chnl",
	"fcst_chnl_desc",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"curr_cd",
	"actual_sales_qty",
	"apo_tot_frcst",
	"apo_base_frcst",
	"apo_promo_frcst",
	"px_tot_frcst",
	"px_base_frcst",
	"px_promo_frcst",
	"projected_apo_tot_frcst",
	"projected_px_tot_frcst"
) as
select
	pac_source_type as "pac_source_type",
	pac_subsource_type as "pac_subsource_type",
	jj_period as "jj_period",
	jj_week_no as "jj_week_no",
	jj_wk as "jj_wk",
	jj_mnth as "jj_mnth",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	jj_qrtr as "jj_qrtr",
	jj_year as "jj_year",
	jj_mnth_tot as "jj_mnth_tot",
	week_date as "week_date",
	matl_no as "matl_no",
	matl_desc as "matl_desc",
	master_code as "master_code",
	parent_id as "parent_id",
	parent_matl_desc as "parent_matl_desc",
	mega_brnd_cd as "mega_brnd_cd",
	mega_brnd_desc as "mega_brnd_desc",
	brnd_cd as "brnd_cd",
	brnd_desc as "brnd_desc",
	base_prod_cd as "base_prod_cd",
	base_prod_desc as "base_prod_desc",
	variant_cd as "variant_cd",
	variant_desc as "variant_desc",
	fran_cd as "fran_cd",
	fran_desc as "fran_desc",
	grp_fran_cd as "grp_fran_cd",
	grp_fran_desc as "grp_fran_desc",
	matl_type_cd as "matl_type_cd",
	matl_type_desc as "matl_type_desc",
	prod_fran_cd as "prod_fran_cd",
	prod_fran_desc as "prod_fran_desc",
	prod_hier_cd as "prod_hier_cd",
	prod_hier_desc as "prod_hier_desc",
	prod_mjr_cd as "prod_mjr_cd",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_cd as "prod_mnr_cd",
	prod_mnr_desc as "prod_mnr_desc",
	mercia_plan as "mercia_plan",
	putup_cd as "putup_cd",
	putup_desc as "putup_desc",
	bar_cd as "bar_cd",
	cust_no as "cust_no",
	cmp_id as "cmp_id",
	ctry_key as "ctry_key",
	country as "country",
	state_cd as "state_cd",
	post_cd as "post_cd",
	cust_suburb as "cust_suburb",
	cust_nm as "cust_nm",
	fcst_chnl as "fcst_chnl",
	fcst_chnl_desc as "fcst_chnl_desc",
	sales_office_cd as "sales_office_cd",
	sales_office_desc as "sales_office_desc",
	sales_grp_cd as "sales_grp_cd",
	sales_grp_desc as "sales_grp_desc",
	curr_cd as "curr_cd",
	actual_sales_qty as "actual_sales_qty",
	apo_tot_frcst as "apo_tot_frcst",
	apo_base_frcst as "apo_base_frcst",
	apo_promo_frcst as "apo_promo_frcst",
	px_tot_frcst as "px_tot_frcst",
	px_base_frcst as "px_base_frcst",
	px_promo_frcst as "px_promo_frcst",
	projected_apo_tot_frcst as "projected_apo_tot_frcst",
	projected_px_tot_frcst as "projected_px_tot_frcst"
from pcfedw_integration.vw_demand_forecast_analysis;
create or replace view VW_IRI_SCAN_SALES_ANALYSIS(
	"time_id",
	"jj_year",
	"jj_qrtr",
	"jj_mnth",
	"jj_wk",
	"jj_mnth_wk",
	"jj_mnth_id",
	"jj_mnth_tot",
	"jj_mnth_day",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"cal_year",
	"cal_qrtr",
	"cal_mnth",
	"cal_wk",
	"cal_mnth_wk",
	"cal_mnth_id",
	"cal_mnth_nm",
	"wk_end_dt",
	"representative_cust_cd",
	"representative_cust_nm",
	"channel_cd",
	"channel_desc",
	"country",
	"sales_grp_cd",
	"sales_grp_nm",
	"iri_market",
	"ac_nielsencode",
	"ac_longname",
	"iri_ean",
	"iri_prod_desc",
	"matl_id",
	"matl_desc",
	"master_code",
	"parent_matl_id",
	"parent_matl_desc",
	"brnd_cd",
	"brnd_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"scan_units",
	"scan_sales",
	"pka_productkey",
	"pka_productdesc",
	"lst_sku",
	"gph_region",
	"gph_reg_frnchse",
	"gph_reg_frnchse_grp",
	"gph_prod_frnchse",
	"gph_prod_brnd",
	"gph_prod_sub_brnd",
	"gph_prod_vrnt",
	"gph_prod_needstate",
	"gph_prod_ctgry",
	"gph_prod_subctgry",
	"gph_prod_sgmnt",
	"gph_prod_subsgmnt",
	"gph_prod_put_up_cd",
	"gph_prod_put_up_desc"
) as
select
    time_id as "time_id",
	jj_year as "jj_year",
	jj_qrtr as "jj_qrtr",
	jj_mnth as "jj_mnth",
	jj_wk as "jj_wk",
	jj_mnth_wk as "jj_mnth_wk",
	jj_mnth_id as "jj_mnth_id",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	cal_year as "cal_year",
	cal_qrtr as "cal_qrtr",
	cal_mnth as "cal_mnth",
	cal_wk as "cal_wk",
	cal_mnth_wk as "cal_mnth_wk",
	cal_mnth_id as "cal_mnth_id",
	cal_mnth_nm as "cal_mnth_nm",
	wk_end_dt as "wk_end_dt",
	representative_cust_cd as "representative_cust_cd",
	representative_cust_nm as "representative_cust_nm",
	channel_cd as "channel_cd",
	channel_desc as "channel_desc",
	country as "country",
	sales_grp_cd as "sales_grp_cd",
	sales_grp_nm as "sales_grp_nm",
	iri_market as "iri_market",
	ac_nielsencode as "ac_nielsencode",
	ac_longname as "ac_longname",
	iri_ean as "iri_ean",
	iri_prod_desc as "iri_prod_desc",
	matl_id as "matl_id",
	matl_desc as "matl_desc",
	master_code as "master_code",
	parent_matl_id as "parent_matl_id",
	parent_matl_desc as "parent_matl_desc",
	brnd_cd as "brnd_cd",
	brnd_desc as "brnd_desc",
	fran_cd as "fran_cd",
	fran_desc as "fran_desc",
	grp_fran_cd as "grp_fran_cd",
	grp_fran_desc as "grp_fran_desc",
	prod_fran_cd as "prod_fran_cd",
	prod_fran_desc as "prod_fran_desc",
	prod_mjr_cd as "prod_mjr_cd",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_cd as "prod_mnr_cd",
	prod_mnr_desc as "prod_mnr_desc",
	scan_units as "scan_units",
	scan_sales as "scan_sales",
	pka_productkey as "pka_productkey",
	pka_productdesc as "pka_productdesc",
	lst_sku as "lst_sku",
	gph_region as "gph_region",
	gph_reg_frnchse as "gph_reg_frnchse",
	gph_reg_frnchse_grp as "gph_reg_frnchse_grp",
	gph_prod_frnchse as "gph_prod_frnchse",
	gph_prod_brnd as "gph_prod_brnd",
	gph_prod_sub_brnd as "gph_prod_sub_brnd",
	gph_prod_vrnt as "gph_prod_vrnt",
	gph_prod_needstate as "gph_prod_needstate",
	gph_prod_ctgry as "gph_prod_ctgry",
	gph_prod_subctgry as "gph_prod_subctgry",
	gph_prod_sgmnt as "gph_prod_sgmnt",
	gph_prod_subsgmnt as "gph_prod_subsgmnt",
	gph_prod_put_up_cd as "gph_prod_put_up_cd",
	gph_prod_put_up_desc as "gph_prod_put_up_desc"
from pcfedw_integration.vw_iri_scan_sales_analysis;
create or replace view VW_PX_MASTER_ANALYSIS(
	"cal_date",
	"time_id",
	"jj_wk",
	"jj_mnth",
	"jj_mnth_shrt",
	"jj_mnth_long",
	"jj_qrtr",
	"jj_year",
	"cal_mnth_id",
	"jj_mnth_id",
	"cal_mnth",
	"cal_qrtr",
	"cal_year",
	"jj_mnth_tot",
	"jj_mnth_day",
	"cal_mnth_nm",
	"cust_no",
	"cmp_id",
	"channel_cd",
	"channel_desc",
	"ctry_key",
	"country",
	"state_cd",
	"post_cd",
	"cust_suburb",
	"cust_nm",
	"sls_org",
	"cust_del_flag",
	"sales_office_cd",
	"sales_office_desc",
	"sales_grp_cd",
	"sales_grp_desc",
	"mercia_ref",
	"curr_cd",
	"matl_id",
	"matl_desc",
	"mega_brnd_cd",
	"mega_brnd_desc",
	"brnd_cd",
	"brnd_desc",
	"base_prod_cd",
	"base_prod_desc",
	"variant_cd",
	"variant_desc",
	"fran_cd",
	"fran_desc",
	"grp_fran_cd",
	"grp_fran_desc",
	"matl_type_cd",
	"matl_type_desc",
	"prod_fran_cd",
	"prod_fran_desc",
	"prod_hier_cd",
	"prod_hier_desc",
	"prod_mjr_cd",
	"prod_mjr_desc",
	"prod_mnr_cd",
	"prod_mnr_desc",
	"mercia_plan",
	"putup_cd",
	"putup_desc",
	"bar_cd",
	"updt_dt",
	"ac_code",
	"ac_longname",
	"p_promonumber",
	"p_startdate",
	"p_stopdate",
	"promo_length",
	"promotionforecastweek",
	"p_buystartdatedef",
	"p_buystopdatedef",
	"buyperiod_length",
	"hierarchy_rowid",
	"hierarchy_longname",
	"activity_longname",
	"confirmed_switch",
	"closed_switch",
	"sku_longname",
	"sku_profitcentre",
	"sku_attribute",
	"gltt_rowid",
	"transaction_longname",
	"case_deal",
	"case_quantity",
	"planspend_total",
	"paid_total",
	"open_total",
	"committed_spend",
	"p_deleted",
	"local_ccy",
	"aud_rate",
	"sgd_rate",
	"sap_account",
	"sap_accnt_nm",
	"promax_measure",
	"promax_bucket",
	"promotionrowid"
) as
select
	cal_date as "cal_date",
	time_id as "time_id",
	jj_wk as "jj_wk",
	jj_mnth as "jj_mnth",
	jj_mnth_shrt as "jj_mnth_shrt",
	jj_mnth_long as "jj_mnth_long",
	jj_qrtr as "jj_qrtr",
	jj_year as "jj_year",
	cal_mnth_id as "cal_mnth_id",
	jj_mnth_id as "jj_mnth_id",
	cal_mnth as "cal_mnth",
	cal_qrtr as "cal_qrtr",
	cal_year as "cal_year",
	jj_mnth_tot as "jj_mnth_tot",
	jj_mnth_day as "jj_mnth_day",
	cal_mnth_nm as "cal_mnth_nm",
	cust_no as "cust_no",
	cmp_id as "cmp_id",
	channel_cd as "channel_cd",
	channel_desc as "channel_desc",
	ctry_key as "ctry_key",
	country as "country",
	state_cd as "state_cd",
	post_cd as "post_cd",
	cust_suburb as "cust_suburb",
	cust_nm as "cust_nm",
	sls_org as "sls_org",
	cust_del_flag as "cust_del_flag",
	sales_office_cd as "sales_office_cd",
	sales_office_desc as "sales_office_desc",
	sales_grp_cd as "sales_grp_cd",
	sales_grp_desc as "sales_grp_desc",
	mercia_ref as "mercia_ref",
	curr_cd as "curr_cd",
	matl_id as "matl_id",
	matl_desc as "matl_desc",
	mega_brnd_cd as "mega_brnd_cd",
	mega_brnd_desc as "mega_brnd_desc",
	brnd_cd as "brnd_cd",
	brnd_desc as "brnd_desc",
	base_prod_cd as "base_prod_cd",
	base_prod_desc as "base_prod_desc",
	variant_cd as "variant_cd",
	variant_desc as "variant_desc",
	fran_cd as "fran_cd",
	fran_desc as "fran_desc",
	grp_fran_cd as "grp_fran_cd",
	grp_fran_desc as "grp_fran_desc",
	matl_type_cd as "matl_type_cd",
	matl_type_desc as "matl_type_desc",
	prod_fran_cd as "prod_fran_cd",
	prod_fran_desc as "prod_fran_desc",
	prod_hier_cd as "prod_hier_cd",
	prod_hier_desc as "prod_hier_desc",
	prod_mjr_cd as "prod_mjr_cd",
	prod_mjr_desc as "prod_mjr_desc",
	prod_mnr_cd as "prod_mnr_cd",
	prod_mnr_desc as "prod_mnr_desc",
	mercia_plan as "mercia_plan",
	putup_cd as "putup_cd",
	putup_desc as "putup_desc",
	bar_cd as "bar_cd",
	updt_dt as "updt_dt",
	ac_code as "ac_code",
	ac_longname as "ac_longname",
	p_promonumber as "p_promonumber",
	p_startdate as "p_startdate",
	p_stopdate as "p_stopdate",
	promo_length as "promo_length",
	promotionforecastweek as "promotionforecastweek",
	p_buystartdatedef as "p_buystartdatedef",
	p_buystopdatedef as "p_buystopdatedef",
	buyperiod_length as "buyperiod_length",
	hierarchy_rowid as "hierarchy_rowid",
	hierarchy_longname as "hierarchy_longname",
	activity_longname as "activity_longname",
	confirmed_switch as "confirmed_switch",
	closed_switch as "closed_switch",
	sku_longname as "sku_longname",
	sku_profitcentre as "sku_profitcentre",
	sku_attribute as "sku_attribute",
	gltt_rowid as "gltt_rowid",
	transaction_longname as "transaction_longname",
	case_deal as "case_deal",
	case_quantity as "case_quantity",
	planspend_total as "planspend_total",
	paid_total as "paid_total",
	open_total as "open_total",
	committed_spend as "committed_spend",
	p_deleted as "p_deleted",
	local_ccy as "local_ccy",
	aud_rate as "aud_rate",
	sgd_rate as "sgd_rate",
	sap_account as "sap_account",
	sap_accnt_nm as "sap_accnt_nm",
	promax_measure as "promax_measure",
	promax_bucket as "promax_bucket",
	promotionrowid as "promotionrowid"
from pcfedw_integration.vw_px_master_analysis;
create or replace view V_RPT_PROMO_ANALYSIS(
	"cmp_id",
	"country",
	"cust_no",
	"promo_number",
	"px_jj_year",
	"px_jj_mnth",
	"matl_id",
	"sku_name",
	"hierarchy_longname",
	"promo_name",
	"promo_start_date",
	"promo_stop_date",
	"local_ccy",
	"cust_nm",
	"channel_desc",
	"sales_office_desc",
	"sales_grp_desc",
	"matl_desc",
	"mega_brnd_desc",
	"brnd_desc",
	"variant_desc",
	"fran_desc",
	"grp_fran_desc",
	"prod_fran_desc",
	"prod_hier_desc",
	"prod_major_desc",
	"prod_minor_desc",
	"px_base_qty",
	"px_base_gts",
	"px_promo_qty",
	"px_promo_gts",
	"px_total_qty",
	"px_total_gts",
	"px_base_cogs",
	"px_promo_cogs",
	"px_total_cogs",
	"px_base_terms",
	"px_promo_terms",
	"px_total_terms",
	"case_qty",
	"total_plan_spend",
	"total_paid",
	"committed_spend",
	"finance_cogs"
) as
select
	cmp_id as "cmp_id",
	country as "country",
	cust_no as "cust_no",
	promo_number as "promo_number",
	px_jj_year as "px_jj_year",
	px_jj_mnth as "px_jj_mnth",
	matl_id as "matl_id",
	sku_name as "sku_name",
	hierarchy_longname as "hierarchy_longname",
	promo_name as "promo_name",
	promo_start_date as "promo_start_date",
	promo_stop_date as "promo_stop_date",
	local_ccy as "local_ccy",
	cust_nm as "cust_nm",
	channel_desc as "channel_desc",
	sales_office_desc as "sales_office_desc",
	sales_grp_desc as "sales_grp_desc",
	matl_desc as "matl_desc",
	mega_brnd_desc as "mega_brnd_desc",
	brnd_desc as "brnd_desc",
	variant_desc as "variant_desc",
	fran_desc as "fran_desc",
	grp_fran_desc as "grp_fran_desc",
	prod_fran_desc as "prod_fran_desc",
	prod_hier_desc as "prod_hier_desc",
	prod_major_desc as "prod_major_desc",
	prod_minor_desc as "prod_minor_desc",
	px_base_qty as "px_base_qty",
	px_base_gts as "px_base_gts",
	px_promo_qty as "px_promo_qty",
	px_promo_gts as "px_promo_gts",
	px_total_qty as "px_total_qty",
	px_total_gts as "px_total_gts",
	px_base_cogs as "px_base_cogs",
	px_promo_cogs as "px_promo_cogs",
	px_total_cogs as "px_total_cogs",
	px_base_terms as "px_base_terms",
	px_promo_terms as "px_promo_terms",
	px_total_terms as "px_total_terms",
	case_qty as "case_qty",
	total_plan_spend as "total_plan_spend",
	total_paid as "total_paid",
	committed_spend as "committed_spend",
	finance_cogs as "finance_cogs"
from pcfedw_integration.v_rpt_promo_analysis;
