drop table PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_REGIONAL_SELLOUT_MAPPED_SKU_CD;

create table PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_REGIONAL_SELLOUT_MAPPED_SKU_CD as (

with edw_rpt_regional_sellout_offtake as (
    select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.ASPEDW_INTEGRATION__EDW_RPT_REGIONAL_SELLOUT_OFFTAKE
)
SELECT *
	FROM (SELECT DISTINCT LTRIM(MSL_PRODUCT_CODE,'0') AS EAN_NUM,
				 LTRIM(SKU_CODE,'0') AS SKU_CODE,
				 MSL_PRODUCT_DESC AS SKU_DESCRIPTION,
				 ROW_NUMBER() OVER (PARTITION BY LTRIM(MSL_PRODUCT_CODE,0) ORDER BY cal_date DESC,LENGTH(LTRIM(SKU_CODE,'0')) DESC) AS RNO
		  FROM EDW_RPT_REGIONAL_SELLOUT_OFFTAKE 
		  WHERE COUNTRY_CODE = 'HK'
		  AND   DATA_SOURCE = 'SELL-OUT')
	WHERE RNO = 1
);
