drop table PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_BASE_RETAIL_EXCELLENCE;
create table PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_BASE_RETAIL_EXCELLENCE as (

with edw_rpt_regional_sellout_offtake as (
    select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.ASPEDW_INTEGRATION__EDW_RPT_REGIONAL_SELLOUT_OFFTAKE
),
edw_vw_cal_retail_excellence_dim as (
    select * from PROD_DNA_CORE.ASPEDW_INTEGRATION.V_EDW_VW_CAL_RETAIL_EXCELLENCE_DIM
),
wks_hk_regional_sellout_mapped_sku_cd as (
    select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_REGIONAL_SELLOUT_MAPPED_SKU_CD
)

    SELECT COUNTRY_CODE AS CNTRY_CD,
       COUNTRY_NAME AS CNTRY_NM,
       DATA_SOURCE,
       MD5(NVL (DISTRIBUTOR_CODE,'DC') ||NVL (DISTRIBUTOR_NAME,'DN') ||NVL (SOLDTO_CODE,'STC') || NVL (STORE_CODE,'SC') ||
       NVL (STORE_NAME,'SN') || NVL (EAN,'EAN') || NVL (CHANNEL,'CHN') || NVL (STORE_GRADE,'SG') || NVL (SKU_CODE,'SKU') ||
       NVL (SKU_DESCRIPTION,'SKUD') || NVL (STORE_TYPE,'ST') ||NVL (SAP_PARENT_CUSTOMER_KEY,'SPCK') ||NVL (SAP_PARENT_CUSTOMER_DESCRIPTION,'SPSCD') ||
       NVL (SAP_CUSTOMER_CHANNEL_KEY,'SCCK') ||NVL (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'SCCD') || NVL (SAP_CUSTOMER_SUB_CHANNEL_KEY,'SCSCK') ||
       NVL (SAP_SUB_CHANNEL_DESCRIPTION,'SSCD') || NVL (CUSTOMER_SEGMENT_KEY,'CSK') ||NVL (CUSTOMER_SEGMENT_DESCRIPTION,'CSD') ||
       NVL (SAP_GO_TO_MDL_KEY,'SGMK') || NVL (SAP_GO_TO_MDL_DESCRIPTION,'SGMD') ||NVL (SAP_BANNER_KEY,'SBK') ||NVL (SAP_BANNER_DESCRIPTION,'SBD') ||
       NVL (SAP_BANNER_FORMAT_KEY,'SBFK') ||NVL (SAP_BANNER_FORMAT_DESCRIPTION,'SBFD') ||NVL (RETAIL_ENV,'RE') ||
       NVL (GLOBAL_PRODUCT_FRANCHISE,'GPF') ||NVL (GLOBAL_PRODUCT_BRAND,'GPB') ||NVL (GLOBAL_PRODUCT_SUB_BRAND,'GPSB') ||
       NVL (GLOBAL_PRODUCT_VARIANT,'GPV') ||NVL (GLOBAL_PRODUCT_SEGMENT,'GPS') ||NVL (GLOBAL_PRODUCT_SUBSEGMENT,'GPSS') ||
       NVL (GLOBAL_PRODUCT_CATEGORY,'GPC') ||NVL (GLOBAL_PRODUCT_SUBCATEGORY,'GPSC') ||NVL (GLOBAL_PUT_UP_DESCRIPTION,'GPUD') ||
       NVL (PKA_PRODUCT_KEY,'PK') ||NVL (PKA_PRODUCT_KEY_DESCRIPTION,'PKD') ||NVL (REGION,'REG') ||NVL (ZONE_OR_AREA,'ZN')) AS DIM_KEY,
       YEAR :: numeric(18,0) as YEAR,
       MNTH_ID,
       SOLDTO_CODE,
       DISTRIBUTOR_CODE,
       UPPER(DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,
       UPPER(STORE_CODE) AS STORE_CODE,
       UPPER(STORE_NAME) AS STORE_NAME,
	   LIST_PRICE :: numeric(38,6) as list_price,
       STORE_TYPE,
       CHANNEL,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_GO_TO_MDL_KEY,
       SAP_GO_TO_MDL_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       UPPER(RETAIL_ENV) AS RETAIL_ENVIRONMENT,
       REGION,
       ZONE_OR_AREA,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       EAN,
       SKU_CODE,
       SKU_DESCRIPTION,
       STORE_GRADE,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       SUM(SELLOUT_SALES_QUANTITY) :: NUMERIC(38,6) AS SO_SLS_QTY,
       SUM(SELLOUT_SALES_VALUE) :: NUMERIC(38,6) AS SO_SLS_VALUE,
       AVG(SELLOUT_SALES_QUANTITY) :: NUMERIC(38,6) AS SO_AVG_QTY,
       SUM(SALES_VALUE_LIST_PRICE) :: numeric(38,6) AS SALES_VALUE_LIST_PRICE,
       SYSDATE() AS CRT_DTTM
FROM (SELECT COUNTRY_CODE,
             COUNTRY_NAME,
             DATA_SOURCE,
             YEAR,
             MNTH_ID,
             LTRIM(SOLDTO_CODE,'0') AS SOLDTO_CODE,
             UPPER(DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,
			 DISTRIBUTOR_NAME|| '#' ||LTRIM(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_NAME,
             STORE_CODE,
			 STORE_NAME|| '#' ||LTRIM(STORE_CODE,'0') AS STORE_NAME,
			 LIST_PRICE,
             UPPER(STORE_TYPE) AS STORE_TYPE,
             UPPER(CHANNEL) AS CHANNEL,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENV,
             REGION,
             ZONE_OR_AREA,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             MSCD.EAN_NUM AS EAN,
             MSCD.SKU_CODE,
             MSCD.SKU_DESCRIPTION,
             STORE_GRADE,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
             SELLOUT_SALES_QUANTITY,
             SELLOUT_SALES_VALUE,
             SALES_VALUE_LIST_PRICE
      FROM (SELECT COUNTRY_CODE,
                   COUNTRY_NAME,
                   DATA_SOURCE,
                   YEAR,
                   MNTH_ID,
                   MAX(SOLDTO_CODE) OVER (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SOLDTO_CODE,
                   LTRIM(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_CODE,
                   MAX(DISTRIBUTOR_NAME) OVER (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DISTRIBUTOR_NAME,
                   LTRIM(STORE_CODE,'0') AS STORE_CODE,
                   MAX(STORE_NAME) OVER (PARTITION BY LTRIM(STORE_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS STORE_NAME,
				   MAX(LIST_PRICE) OVER (PARTITION BY ltrim(msl_product_code,0) ORDER BY LENGTH(SKU_CODE) DESC, cal_date DESC, SKU_CODE DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS LIST_PRICE,
                   STORE_TYPE,
                   CHANNEL,
                   SAP_PARENT_CUSTOMER_KEY,
                   SAP_PARENT_CUSTOMER_DESCRIPTION,
                   SAP_CUSTOMER_CHANNEL_KEY,
                   SAP_CUSTOMER_CHANNEL_DESCRIPTION,
                   SAP_CUSTOMER_SUB_CHANNEL_KEY,
                   SAP_SUB_CHANNEL_DESCRIPTION,
                   SAP_GO_TO_MDL_KEY,
                   SAP_GO_TO_MDL_DESCRIPTION,
                   SAP_BANNER_KEY,
                   SAP_BANNER_DESCRIPTION,
                   SAP_BANNER_FORMAT_KEY,
                   SAP_BANNER_FORMAT_DESCRIPTION,
                   RETAIL_ENV,
                   REGION,
                   ZONE_OR_AREA,
                   CUSTOMER_SEGMENT_KEY,
                   CUSTOMER_SEGMENT_DESCRIPTION,
                   GLOBAL_PRODUCT_FRANCHISE,
                   GLOBAL_PRODUCT_BRAND,
                   GLOBAL_PRODUCT_SUB_BRAND,
                   GLOBAL_PRODUCT_VARIANT,
                   GLOBAL_PRODUCT_SEGMENT,
                   GLOBAL_PRODUCT_SUBSEGMENT,
                   GLOBAL_PRODUCT_CATEGORY,
                   GLOBAL_PRODUCT_SUBCATEGORY,
                   GLOBAL_PUT_UP_DESCRIPTION,
                   LTRIM(msl_product_code,'0') AS EAN,
				   LTRIM(SKU_CODE,'0') AS SKU_CODE,
                   STORE_GRADE,
                   PKA_PRODUCT_KEY,
                   PKA_PRODUCT_KEY_DESCRIPTION,
                   SELLOUT_SALES_QUANTITY,
                   SELLOUT_SALES_VALUE,
                   SELLOUT_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE
            FROM EDW_RPT_REGIONAL_SELLOUT_OFFTAKE
            WHERE COUNTRY_CODE = 'HK'
            AND   DATA_SOURCE = 'SELL-OUT'
            AND   MNTH_ID >= (SELECT last_27mnths
                  FROM edw_vw_cal_retail_excellence_dim)::NUMERIC
            AND   MNTH_ID <= (SELECT prev_mnth FROM edw_vw_cal_retail_excellence_dim)::NUMERIC
			) MAIN
        LEFT JOIN WKS_HK_REGIONAL_SELLOUT_MAPPED_SKU_CD MSCD ON LTRIM (MAIN.EAN,'0') = LTRIM (MSCD.EAN_NUM,'0')
		)
GROUP BY COUNTRY_CODE,
         COUNTRY_NAME,
         DATA_SOURCE,
         YEAR,
         MNTH_ID,
         SOLDTO_CODE,
         DISTRIBUTOR_CODE,
         DISTRIBUTOR_NAME,
         STORE_CODE,
         STORE_NAME,
		 LIST_PRICE,
         STORE_TYPE,
         CHANNEL,
         SAP_PARENT_CUSTOMER_KEY,
         SAP_PARENT_CUSTOMER_DESCRIPTION,
         SAP_CUSTOMER_CHANNEL_KEY,
         SAP_CUSTOMER_CHANNEL_DESCRIPTION,
         SAP_CUSTOMER_SUB_CHANNEL_KEY,
         SAP_SUB_CHANNEL_DESCRIPTION,
         SAP_GO_TO_MDL_KEY,
         SAP_GO_TO_MDL_DESCRIPTION,
         SAP_BANNER_KEY,
         SAP_BANNER_DESCRIPTION,
         SAP_BANNER_FORMAT_KEY,
         SAP_BANNER_FORMAT_DESCRIPTION,
         RETAIL_ENV,
         REGION,
         ZONE_OR_AREA,
         CUSTOMER_SEGMENT_KEY,
         CUSTOMER_SEGMENT_DESCRIPTION,
         GLOBAL_PRODUCT_FRANCHISE,
         GLOBAL_PRODUCT_BRAND,
         GLOBAL_PRODUCT_SUB_BRAND,
         GLOBAL_PRODUCT_VARIANT,
         GLOBAL_PRODUCT_SEGMENT,
         GLOBAL_PRODUCT_SUBSEGMENT,
         GLOBAL_PRODUCT_CATEGORY,
         GLOBAL_PRODUCT_SUBCATEGORY,
         GLOBAL_PUT_UP_DESCRIPTION,
         EAN,
         SKU_CODE,
         SKU_DESCRIPTION,
         STORE_GRADE,
         PKA_PRODUCT_KEY,
         PKA_PRODUCT_KEY_DESCRIPTION
);

------------------------------------

delete from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAITG_INTEGRATION__ITG_HK_RE_MSL_LIST;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAITG_INTEGRATION__ITG_HK_RE_MSL_LIST (

with itg_re_msl_input_definition as (
    select * from PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_RE_MSL_INPUT_DEFINITION
),
edw_calendar_dim as (
    select * from PROD_DNA_CORE.ASPEDW_INTEGRATION.EDW_CALENDAR_DIM
),
edw_vw_cal_retail_excellence_dim as (
    select * from PROD_DNA_CORE.ASPEDW_INTEGRATION.V_EDW_VW_CAL_RETAIL_EXCELLENCE_DIM
),
wks_hk_base_retail_excellence as (
    select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.NTAWKS_INTEGRATION__WKS_HK_BASE_RETAIL_EXCELLENCE
),

MSL as 
(
    SELECT DISTINCT CAL.FISC_YR AS YEAR,
       MARKET,
       CAL.JJ_MNTH_ID,
       MSL_DEF.CUSTOMER,
       MSL_DEF.STORE_GRADE,
       UPPER(MSL_DEF.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,
       LTRIM(MSL_DEF.SKU_UNIQUE_IDENTIFIER,'0') AS sku_unique_identifier
    FROM ITG_RE_MSL_INPUT_DEFINITION MSL_DEF
    LEFT JOIN (SELECT DISTINCT FISC_YR,
                    SUBSTRING(FISC_PER,1,4)||SUBSTRING(FISC_PER,6,7) AS JJ_MNTH_ID
             FROM edw_calendar_dim) CAL
         ON TO_CHAR (TO_DATE (MSL_DEF.START_DATE,'DD/MM/YYYY'),'YYYYMM') <= CAL.JJ_MNTH_ID
        AND TO_CHAR (TO_DATE (MSL_DEF.END_DATE,'DD/MM/YYYY'),'YYYYMM') >= CAL.JJ_MNTH_ID
    WHERE UPPER(market) = 'HONG KONG'
    AND   active_status_code = 'Y'
),

REG_SO as 
(SELECT DISTINCT data_source,
                SOLDTO_CODE as sold_to_code,
                distributor_code,
                distributor_name,
                store_code,
                store_name,
                ltrim(ean,'0') as ean,
                sku_description,
                sku_code,
                retail_environment,
                store_grade,
                channel AS CHANNEL_DESC,
                store_type,
                CNTRY_CD,
                CNTRY_NM as country
                FROM WKS_HK_BASE_RETAIL_EXCELLENCE)
				
    SELECT DISTINCT MSL.YEAR :: numeric(18,0) as fisc_yr,
       MSL.JJ_MNTH_ID :: numeric(18,0) as fisc_per,
       REG_SO.COUNTRY,
       REG_SO.DATA_SOURCE,
       REG_SO.CHANNEL_DESC,
       REG_SO.RETAIL_ENVIRONMENT,
       REG_SO.DISTRIBUTOR_CODE,	
       REG_SO.DISTRIBUTOR_NAME,
       REG_SO.SOLD_TO_CODE,	
       REG_SO.STORE_CODE,
       REG_SO.STORE_NAME,
	   REG_SO.STORE_GRADE,
	   REG_SO.STORE_TYPE,
       LTRIM(MSL.SKU_UNIQUE_IDENTIFIER,'0') AS EAN,
	   REG_SO.SKU_CODE,	
	   REG_SO.SKU_DESCRIPTION,
       SYSDATE() AS CRTD_DTTM 
    FROM MSL
    LEFT JOIN REG_SO ON  UPPER (LTRIM(MSL.sku_unique_identifier,'0')) = UPPER (LTRIM(REG_SO.EAN,'0'))
				     AND UPPER (MSL.retail_environment) = UPPER (REG_SO.RETAIL_ENVIRONMENT)
                     --AND UPPER (MSL.store_grade) = UPPER (REG_SO.store_grade)
    WHERE MSL.JJ_MNTH_ID >= (SELECT last_16mnths
                         FROM edw_vw_cal_Retail_excellence_Dim)
    AND   MSL.JJ_MNTH_ID <= (SELECT prev_mnth FROM edw_vw_cal_Retail_excellence_Dim)
    AND   STORE_CODE IS NOT NULL
    AND   DISTRIBUTOR_CODE IS NOT NULL
);
