create or replace view PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.ASPEDW_ACCESS__EDW_RPT_RETAIL_EXCELLENCE_SUMMARY(
	"fisc_yr",
	"fisc_per",
	"cluster",
	"market",
	"data_src",
	"flag_agg_dim_key",
	"distributor_code",
	"distributor_name",
	"sell_out_channel",
	"region",
	"zone_name",
	"city",
	"retail_environment",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"global_product_franchise",
	"global_product_brand",
	"global_product_sub_brand",
	"global_product_segment",
	"global_product_subsegment",
	"global_product_category",
	"global_product_subcategory",
	"lm_sales_flag",
	"p3m_sales_flag",
	"p6m_sales_flag",
	"p12m_sales_flag",
	"mdp_flag",
	"target_complaince",
	"sales_value",
	"sales_qty",
	"avg_sales_qty",
	"lm_sales",
	"lm_sales_qty",
	"lm_avg_sales_qty",
	"p3m_sales",
	"p3m_qty",
	"p3m_avg_qty",
	"p6m_sales",
	"p6m_qty",
	"p6m_avg_qty",
	"p12m_sales",
	"p12m_qty",
	"p12m_avg_qty",
	"f3m_sales",
	"f3m_qty",
	"f3m_avg_qty",
	"size_of_price_lm",
	"size_of_price_p3m",
	"size_of_price_p6m",
	"size_of_price_p12m",
	"lm_sales_flag_count",
	"p3m_sales_flag_count",
	"p6m_sales_flag_count",
	"p12m_sales_flag_count",
	"mdp_flag_count",
	"list_price",
	"sales_value_list_price",
	"lm_sales_lp",
	"p3m_sales_lp",
	"p6m_sales_lp",
	"p12m_sales_lp",
	"size_of_price_lm_lp",
	"size_of_price_p3m_lp",
	"size_of_price_p6m_lp",
	"size_of_price_p12m_lp",
	"crt_dttm",
	"cm_actual_stores",
	"cm_universe_stores",
	"cm_numeric_distribution",
	"lm_actual_stores",
	"lm_universe_stores",
	"lm_numeric_distribution",
	"l3m_actual_stores",
	"l3m_universe_stores",
	"l3m_numeric_distribution",
	"l6m_actual_stores",
	"l6m_universe_stores",
	"l6m_numeric_distribution",
	"l12m_actual_stores",
	"l12m_universe_stores",
	"l12m_numeric_distribution"
) as (
    with edw_rpt_retail_excellence_summary as (
    select * from PROD_DNA_CORE.dbt_cloud_pr_5458_1220.aspedw_integration__edw_rpt_retail_excellence_summary
),

final as (
    select
 fisc_yr as "fisc_yr",
fisc_per as "fisc_per",
"cluster" as "cluster",
market as "market",
data_src as "data_src",
flag_agg_dim_key as "flag_agg_dim_key",
distributor_code as "distributor_code",
distributor_name as "distributor_name",
sell_out_channel as "sell_out_channel",
region as "region",
zone_name as "zone_name",
city as "city",
retail_environment as "retail_environment",
prod_hier_l1 as "prod_hier_l1",
prod_hier_l2 as "prod_hier_l2",
prod_hier_l3 as "prod_hier_l3",
prod_hier_l4 as "prod_hier_l4",
prod_hier_l5 as "prod_hier_l5",
prod_hier_l6 as "prod_hier_l6",
prod_hier_l7 as "prod_hier_l7",
prod_hier_l8 as "prod_hier_l8",
prod_hier_l9 as "prod_hier_l9",
global_product_franchise as "global_product_franchise",
global_product_brand as "global_product_brand",
global_product_sub_brand as "global_product_sub_brand",
global_product_segment as "global_product_segment",
global_product_subsegment as "global_product_subsegment",
global_product_category as "global_product_category",
global_product_subcategory as "global_product_subcategory",
lm_sales_flag as "lm_sales_flag",
p3m_sales_flag as "p3m_sales_flag",
p6m_sales_flag as "p6m_sales_flag",
p12m_sales_flag as "p12m_sales_flag",
mdp_flag as "mdp_flag",
target_complaince as "target_complaince",
sales_value as "sales_value",
sales_qty as "sales_qty",
avg_sales_qty as "avg_sales_qty",
lm_sales as "lm_sales",
lm_sales_qty as "lm_sales_qty",
lm_avg_sales_qty as "lm_avg_sales_qty",
p3m_sales as "p3m_sales",
p3m_qty as "p3m_qty",
p3m_avg_qty as "p3m_avg_qty",
p6m_sales as "p6m_sales",
p6m_qty as "p6m_qty",
p6m_avg_qty as "p6m_avg_qty",
p12m_sales as "p12m_sales",
p12m_qty as "p12m_qty",
p12m_avg_qty as "p12m_avg_qty",
f3m_sales as "f3m_sales",
f3m_qty as "f3m_qty",
f3m_avg_qty as "f3m_avg_qty",
size_of_price_lm as "size_of_price_lm",
size_of_price_p3m as "size_of_price_p3m",
size_of_price_p6m as "size_of_price_p6m",
size_of_price_p12m as "size_of_price_p12m",
lm_sales_flag_count as "lm_sales_flag_count",
p3m_sales_flag_count as "p3m_sales_flag_count",
p6m_sales_flag_count as "p6m_sales_flag_count",
p12m_sales_flag_count as "p12m_sales_flag_count",
mdp_flag_count as "mdp_flag_count",
list_price as "list_price",
sales_value_list_price as "sales_value_list_price",
lm_sales_lp as "lm_sales_lp",
p3m_sales_lp as "p3m_sales_lp",
p6m_sales_lp as "p6m_sales_lp",
p12m_sales_lp as "p12m_sales_lp",
size_of_price_lm_lp as "size_of_price_lm_lp",
size_of_price_p3m_lp as "size_of_price_p3m_lp",
size_of_price_p6m_lp as "size_of_price_p6m_lp",
size_of_price_p12m_lp as "size_of_price_p12m_lp",
crt_dttm as "crt_dttm",
cm_actual_stores as "cm_actual_stores",
cm_universe_stores as "cm_universe_stores",
cm_numeric_distribution as "cm_numeric_distribution",
lm_actual_stores as "lm_actual_stores",
lm_universe_stores as "lm_universe_stores",
lm_numeric_distribution as "lm_numeric_distribution",
l3m_actual_stores as "l3m_actual_stores",
l3m_universe_stores as "l3m_universe_stores",
l3m_numeric_distribution as "l3m_numeric_distribution",
l6m_actual_stores as "l6m_actual_stores",
l6m_universe_stores as "l6m_universe_stores",
l6m_numeric_distribution as "l6m_numeric_distribution",
l12m_actual_stores as "l12m_actual_stores",
l12m_universe_stores as "l12m_universe_stores",
l12m_numeric_distribution as "l12m_numeric_distribution"
    from edw_rpt_retail_excellence_summary
)

select * from final
  );

----------------------------

create or replace view PROD_DNA_CORE.DBT_CLOUD_PR_5458_1220.ASPEDW_ACCESS__EDW_RPT_RETAIL_EXCELLENCE_DETAILS(
	"fisc_yr",
	"fisc_per",
	"cluster",
	"market",
	"channel_name",
	"distributor_code",
	"distributor_name",
	"sell_out_channel",
	"store_type",
	"prioritization_segmentation",
	"store_category",
	"store_code",
	"store_name",
	"store_grade",
	"store_size",
	"region",
	"zone_name",
	"city",
	"rtrlatitude",
	"rtrlongitude",
	"customer_segment_key",
	"customer_segment_description",
	"retail_environment",
	"sap_customer_channel_key",
	"sap_customer_channel_description",
	"sap_customer_sub_channel_key",
	"sap_sub_channel_description",
	"sap_parent_customer_key",
	"sap_parent_customer_description",
	"sap_banner_key",
	"sap_banner_description",
	"sap_banner_format_key",
	"sap_banner_format_description",
	"customer_name",
	"customer_code",
	"product_code",
	"product_name",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"mapped_sku_cd",
	"sap_prod_sgmt_cd",
	"sap_prod_sgmt_desc",
	"sap_base_prod_desc",
	"sap_mega_brnd_desc",
	"sap_brnd_desc",
	"sap_vrnt_desc",
	"sap_put_up_desc",
	"sap_grp_frnchse_cd",
	"sap_grp_frnchse_desc",
	"sap_frnchse_cd",
	"sap_frnchse_desc",
	"sap_prod_frnchse_cd",
	"sap_prod_frnchse_desc",
	"sap_prod_mjr_cd",
	"sap_prod_mjr_desc",
	"sap_prod_mnr_cd",
	"sap_prod_mnr_desc",
	"sap_prod_hier_cd",
	"sap_prod_hier_desc",
	"pka_franchise_desc",
	"pka_brand_desc",
	"pka_sub_brand_desc",
	"pka_variant_desc",
	"pka_sub_variant_desc",
	"global_product_franchise",
	"global_product_brand",
	"global_product_sub_brand",
	"global_product_variant",
	"global_product_segment",
	"global_product_subsegment",
	"global_product_category",
	"global_product_subcategory",
	"global_put_up_description",
	"ean",
	"sku_code",
	"sku_description",
	"pka_product_key",
	"pka_product_key_description",
	"sales_value",
	"sales_qty",
	"avg_sales_qty",
	"lm_sales",
	"lm_sales_qty",
	"lm_avg_sales_qty",
	"p3m_sales",
	"p3m_qty",
	"p3m_avg_qty",
	"p6m_sales",
	"p6m_qty",
	"p6m_avg_qty",
	"p12m_sales",
	"p12m_qty",
	"p12m_avg_qty",
	"f3m_sales",
	"f3m_qty",
	"f3m_avg_qty",
	"lm_sales_flag",
	"p3m_sales_flag",
	"p6m_sales_flag",
	"p12m_sales_flag",
	"mdp_flag",
	"target_complaince",
	"list_price",
	"size_of_price_lm",
	"size_of_price_p3m",
	"size_of_price_p6m",
	"size_of_price_p12m",
	"lm_sales_flag_count",
	"p3m_sales_flag_count",
	"p6m_sales_flag_count",
	"p12m_sales_flag_count",
	"mdp_flag_count",
	"data_src",
	"sales_value_list_price",
	"lm_sales_lp",
	"p3m_sales_lp",
	"p6m_sales_lp",
	"p12m_sales_lp",
	"size_of_price_lm_lp",
	"size_of_price_p3m_lp",
	"size_of_price_p6m_lp",
	"size_of_price_p12m_lp",
	"soldto_code",
	"crt_dttm"
) as (
    with edw_rpt_retail_excellence_details as (
    select * from PROD_DNA_CORE.dbt_cloud_pr_5458_1220.aspedw_integration__edw_rpt_retail_excellence_details
),

final as (
    select
      fisc_yr as "fisc_yr",
fisc_per as "fisc_per",
"cluster" as "cluster",
market as "market",
channel_name as "channel_name",
distributor_code as "distributor_code",
distributor_name as "distributor_name",
sell_out_channel as "sell_out_channel",
store_type as "store_type",
prioritization_segmentation as "prioritization_segmentation",
store_category as "store_category",
store_code as "store_code",
store_name as "store_name",
store_grade as "store_grade",
store_size as "store_size",
region as "region",
zone_name as "zone_name",
city as "city",
rtrlatitude as "rtrlatitude",
rtrlongitude as "rtrlongitude",
customer_segment_key as "customer_segment_key",
customer_segment_description as "customer_segment_description",
retail_environment as "retail_environment",
sap_customer_channel_key as "sap_customer_channel_key",
sap_customer_channel_description as "sap_customer_channel_description",
sap_customer_sub_channel_key as "sap_customer_sub_channel_key",
sap_sub_channel_description as "sap_sub_channel_description",
sap_parent_customer_key as "sap_parent_customer_key",
sap_parent_customer_description as "sap_parent_customer_description",
sap_banner_key as "sap_banner_key",
sap_banner_description as "sap_banner_description",
sap_banner_format_key as "sap_banner_format_key",
sap_banner_format_description as "sap_banner_format_description",
customer_name as "customer_name",
customer_code as "customer_code",
product_code as "product_code",
product_name as "product_name",
prod_hier_l1 as "prod_hier_l1",
prod_hier_l2 as "prod_hier_l2",
prod_hier_l3 as "prod_hier_l3",
prod_hier_l4 as "prod_hier_l4",
prod_hier_l5 as "prod_hier_l5",
prod_hier_l6 as "prod_hier_l6",
prod_hier_l7 as "prod_hier_l7",
prod_hier_l8 as "prod_hier_l8",
prod_hier_l9 as "prod_hier_l9",
mapped_sku_cd as "mapped_sku_cd",
sap_prod_sgmt_cd as "sap_prod_sgmt_cd",
sap_prod_sgmt_desc as "sap_prod_sgmt_desc",
sap_base_prod_desc as "sap_base_prod_desc",
sap_mega_brnd_desc as "sap_mega_brnd_desc",
sap_brnd_desc as "sap_brnd_desc",
sap_vrnt_desc as "sap_vrnt_desc",
sap_put_up_desc as "sap_put_up_desc",
sap_grp_frnchse_cd as "sap_grp_frnchse_cd",
sap_grp_frnchse_desc as "sap_grp_frnchse_desc",
sap_frnchse_cd as "sap_frnchse_cd",
sap_frnchse_desc as "sap_frnchse_desc",
sap_prod_frnchse_cd as "sap_prod_frnchse_cd",
sap_prod_frnchse_desc as "sap_prod_frnchse_desc",
sap_prod_mjr_cd as "sap_prod_mjr_cd",
sap_prod_mjr_desc as "sap_prod_mjr_desc",
sap_prod_mnr_cd as "sap_prod_mnr_cd",
sap_prod_mnr_desc as "sap_prod_mnr_desc",
sap_prod_hier_cd as "sap_prod_hier_cd",
sap_prod_hier_desc as "sap_prod_hier_desc",
pka_franchise_desc as "pka_franchise_desc",
pka_brand_desc as "pka_brand_desc",
pka_sub_brand_desc as "pka_sub_brand_desc",
pka_variant_desc as "pka_variant_desc",
pka_sub_variant_desc as "pka_sub_variant_desc",
global_product_franchise as "global_product_franchise",
global_product_brand as "global_product_brand",
global_product_sub_brand as "global_product_sub_brand",
global_product_variant as "global_product_variant",
global_product_segment as "global_product_segment",
global_product_subsegment as "global_product_subsegment",
global_product_category as "global_product_category",
global_product_subcategory as "global_product_subcategory",
global_put_up_description as "global_put_up_description",
ean as "ean",
sku_code as "sku_code",
sku_description as "sku_description",
pka_product_key as "pka_product_key",
pka_product_key_description as "pka_product_key_description",
sales_value as "sales_value",
sales_qty as "sales_qty",
avg_sales_qty as "avg_sales_qty",
lm_sales as "lm_sales",
lm_sales_qty as "lm_sales_qty",
lm_avg_sales_qty as "lm_avg_sales_qty",
p3m_sales as "p3m_sales",
p3m_qty as "p3m_qty",
p3m_avg_qty as "p3m_avg_qty",
p6m_sales as "p6m_sales",
p6m_qty as "p6m_qty",
p6m_avg_qty as "p6m_avg_qty",
p12m_sales as "p12m_sales",
p12m_qty as "p12m_qty",
p12m_avg_qty as "p12m_avg_qty",
f3m_sales as "f3m_sales",
f3m_qty as "f3m_qty",
f3m_avg_qty as "f3m_avg_qty",
lm_sales_flag as "lm_sales_flag",
p3m_sales_flag as "p3m_sales_flag",
p6m_sales_flag as "p6m_sales_flag",
p12m_sales_flag as "p12m_sales_flag",
mdp_flag as "mdp_flag",
target_complaince as "target_complaince",
list_price as "list_price",
size_of_price_lm as "size_of_price_lm",
size_of_price_p3m as "size_of_price_p3m",
size_of_price_p6m as "size_of_price_p6m",
size_of_price_p12m as "size_of_price_p12m",
lm_sales_flag_count as "lm_sales_flag_count",
p3m_sales_flag_count as "p3m_sales_flag_count",
p6m_sales_flag_count as "p6m_sales_flag_count",
p12m_sales_flag_count as "p12m_sales_flag_count",
mdp_flag_count as "mdp_flag_count",
data_src as "data_src",
sales_value_list_price as "sales_value_list_price",
lm_sales_lp as "lm_sales_lp",
p3m_sales_lp as "p3m_sales_lp",
p6m_sales_lp as "p6m_sales_lp",
p12m_sales_lp as "p12m_sales_lp",
size_of_price_lm_lp as "size_of_price_lm_lp",
size_of_price_p3m_lp as "size_of_price_p3m_lp",
size_of_price_p6m_lp as "size_of_price_p6m_lp",
size_of_price_p12m_lp as "size_of_price_p12m_lp",
soldto_code as "soldto_code",
crt_dttm as "crt_dttm"
    from edw_rpt_retail_excellence_details
)

select * from final
  );
