create or replace TABLE ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS (
	COUNTRY_CODE VARCHAR(20),
	PARAMETER_NAME VARCHAR(300),
	PARAMETER_VALUE VARCHAR(300)
);

COPY INTO ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS FROM '@UTILITY_RAW.PROD_CORE_STAGE_S3/RG_ITG_ITG_QUERY_PARAMETERS/' FILE_FORMAT = 'UTILITY_RAW.PROD_CORE_CSV_FILEFORMAT' ;
