update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='OTHERS', latest_outlet_type='UNRECOGNIZE', latest_cust_grp2='Unrecognize' where bill_doc='8220521613';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='OTHERS', latest_outlet_type='UNRECOGNIZE', latest_cust_grp2='Unrecognize' where bill_doc='8220523245';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT WHOLESALER', latest_cust_grp2='Wholesaler Grocery' where bill_doc='0832018817';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='271317001466-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='271317000967-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141317021212-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141317003602-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141317022267-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141317003203-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='271317000198-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='271317000171-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141223036211-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141223047190-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141323010494-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='141323008245-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='271317002688-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391217037989-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391223012503-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391223002234-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391217017351-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391222065393-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391222056378-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391223020933-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391217041055-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='291217004140-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Cosmetic Store' where bill_doc='391217014334-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_jjid='135994MILL', latest_chnl='GENERAL TRADE', latest_outlet_type='GT RETAILER', latest_cust_grp2='Provision' where bill_doc='CS-23020275';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317014572-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001478-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000716-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000347-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317008900-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317000370-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141223052613-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000148-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000827-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317003303-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000082-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001208-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001768-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317020961-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141317002214-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000446-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317004455-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317003674-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317002725-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318000679-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001988-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318000205-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141223054246-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318002244-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141223080654-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001379-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317000883-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317003342-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318002136-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318000252-2';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317004304-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317004612-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='141318030761-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318002708-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318000384-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317003149-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317004140-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317003815-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317002272-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318001449-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317001819-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271318001641-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='271317002497-1';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='FJ/ST/24/07/17/0154';
update PROD_DNA_CORE.IDNWKS_INTEGRATION.WKS_INDONESIA_NOO_ANALYSIS set latest_chnl='MEDICAL', latest_outlet_type='MEDICAL RETAILER', latest_cust_grp2='Apothecary' where bill_doc='FJ/ST/24/09/25/0152';
