create or replace TABLE PROD_DNA_CORE.VNMEDW_INTEGRATION.EDW_VW_VN_MT_SELLIN_TARGET (
	CUST_CODE VARCHAR(20),
	DATA_TYPE VARCHAR(4),
	TARGET NUMBER(20,5),
	SELLIN_CYCLE NUMBER(18,0),
	SELLIN_YEAR VARCHAR(10),
	VISIT VARCHAR(10)
);

create or replace TABLE PROD_DNA_CORE.VNMEDW_INTEGRATION.EDW_VW_VN_MT_POS_PRODUCTS (
	BARCODE VARCHAR(200),
	CODE VARCHAR(500),
	CUSTOMER VARCHAR(200),
	CUSTOMER_SKU VARCHAR(200),
	NAME VARCHAR(500)
);
