CREATE OR REPLACE VIEW ASPEDW_ACCESS.v_rpt_copa_sku AS
SELECT
    "fisc_yr",
	"fisc_yr_per",
	"fisc_day",
	"ctry_nm",
	"cluster",
	"obj_crncy_co_obj",
	"b1 mega-brand",
	"b2 brand",
	"b3 base product",
	"b4 variant",
	"b5 put-up",
	"prod h1 operating group",
	"prod h2 franchise group",
	"prod h3 franchise",
	"prod h4 product franchise",
	"prod h5 product major",
	"prod h6 product minor",
	"pka_franchise_desc",
	"pka_brand_desc",
	"pka_sub_brand_desc",
	"pka_variant_desc",
	"pka_sub_variant_desc",
	"pka_flavor_desc",
	"pka_ingredient_desc",
	"pka_application_desc",
	"pka_length_desc",
	"pka_shape_desc",
	"pka_spf_desc",
	"pka_cover_desc",
	"pka_form_desc",
	"pka_size_desc",
	"pka_character_desc",
	"pka_package_desc",
	"pka_attribute_13_desc",
	"pka_attribute_14_desc",
	"pka_sku_identification_desc",
	"pka_one_time_relabeling_desc",
	"pka_product_key",
	"pka_product_key_description",
	"pka_product_key_description_2",
	"pka_root_code",
	"pka_root_code_desc_1",
	"pka_root_code_desc_2",
	"greenlight_sku_flag",
	"parent customer",
	"banner",
	"banner format",
	"channel",
	"go to model",
	"sub channel",
	"retail_env",
	"nts_usd",
	"nts_lcy",
	"gts_usd",
	"gts_lcy",
	"eq_usd",
	"eq_lcy",
	"from_crncy",
	"to_crncy",
	"nts_qty",
	"gts_qty",
	"eq_qty",
	"product code",
	"product name"
from aspedw_integration.v_rpt_copa_sku;
