--jp

delete from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1525.JPNWKS_INTEGRATION__wks_japan_regional_sellout;

insert into PROD_DNA_CORE.DBT_CLOUD_PR_5458_1525.JPNWKS_INTEGRATION__wks_japan_regional_sellout (

with
edw_vw_os_time_dim as(
	select * from PROD_DNA_CORE.sgpedw_integration.edw_vw_os_time_dim
),
edi_chn_m as (
	select * from PROD_DNA_CORE.jpnedw_integration.edi_chn_m
),
edi_cstm_m as (
	select * from PROD_DNA_CORE.jpnedw_integration.edi_cstm_m
),
wks_japan_regional_sellout_base as(
	select * from PROD_DNA_CORE.DBT_CLOUD_PR_5458_1525.JPNWKS_INTEGRATION__WKS_JAPAN_REGIONAL_SELLOUT_BASE
),
edw_material_dim as (
	select * from PROD_DNA_CORE.aspedw_integration.edw_material_dim
),
edw_gch_producthierarchy as (
	select * from PROD_DNA_CORE.aspedw_integration.edw_gch_producthierarchy
),
edw_product_key_attributes as (
	select * from PROD_DNA_CORE.aspedw_integration.edw_product_key_attributes
),
edw_gch_customerhierarchy as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_gch_customerhierarchy
),
edw_customer_sales_dim as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_customer_sales_dim
),
edw_customer_base_dim as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_customer_base_dim
),
edw_company_dim as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_company_dim
),
edw_dstrbtn_chnl as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_dstrbtn_chnl
),
edw_sales_org_dim as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_sales_org_dim
),
edw_code_descriptions as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_code_descriptions
),
edw_subchnl_retail_env_mapping as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_subchnl_retail_env_mapping
),
edw_sales_org_dim as(
	select * from PROD_DNA_CORE.aspedw_integration.edw_sales_org_dim
),
jp_inv_coverage_area_region_mapping as(
	select * from PROD_DNA_CORE.jpnedw_integration.jp_inv_coverage_area_region_mapping
),
vw_edw_reg_exch_rate as(
	select * from PROD_DNA_CORE.aspedw_integration.vw_edw_reg_exch_rate
),
cal as(
	SELECT DISTINCT CAL_YEAR AS YEAR,
			CAL_QRTR_NO AS QRTR_NO,
			CAL_MNTH_ID AS MNTH_ID,
			CAL_MNTH_NO AS MNTH_NO
		FROM EDW_VW_OS_TIME_DIM
),
product as(
			SELECT DISTINCT EMD.matl_num AS SAP_MATL_NUM,
			EMD.MATL_DESC AS SAP_MAT_DESC,
			EMD.MATL_TYPE_CD AS SAP_MAT_TYPE_CD,
			EMD.MATL_TYPE_DESC AS SAP_MAT_TYPE_DESC,
			--EMD.SAP_BASE_UOM_CD AS SAP_BASE_UOM_CD,
			--EMD.SAP_PRCHSE_UOM_CD AS SAP_PRCHSE_UOM_CD,
			EMD.PRODH1 AS SAP_PROD_SGMT_CD,
			EMD.PRODH1_TXTMD AS SAP_PROD_SGMT_DESC,
			--EMD.SAP_BASE_PROD_CD AS SAP_BASE_PROD_CD,
			EMD.BASE_PROD_DESC AS SAP_BASE_PROD_DESC,
			--EMD.SAP_MEGA_BRND_CD AS SAP_MEGA_BRND_CD,
			EMD.MEGA_BRND_DESC AS SAP_MEGA_BRND_DESC,
			--EMD.SAP_BRND_CD AS SAP_BRND_CD,
			EMD.BRND_DESC AS SAP_BRND_DESC,
			--EMD.SAP_VRNT_CD AS SAP_VRNT_CD,
			EMD.VARNT_DESC AS SAP_VRNT_DESC,
			--EMD.SAP_PUT_UP_CD AS SAP_PUT_UP_CD,
			EMD.PUT_UP_DESC AS SAP_PUT_UP_DESC,
			EMD.PRODH2 AS SAP_GRP_FRNCHSE_CD,
			EMD.PRODH2_TXTMD AS SAP_GRP_FRNCHSE_DESC,
			EMD.PRODH3 AS SAP_FRNCHSE_CD,
			EMD.PRODH3_TXTMD AS SAP_FRNCHSE_DESC,
			EMD.PRODH4 AS SAP_PROD_FRNCHSE_CD,
			EMD.PRODH4_TXTMD AS SAP_PROD_FRNCHSE_DESC,
			EMD.PRODH5 AS SAP_PROD_MJR_CD,
			EMD.PRODH5_TXTMD AS SAP_PROD_MJR_DESC,
			EMD.PRODH5 AS SAP_PROD_MNR_CD,
			EMD.PRODH5_TXTMD AS SAP_PROD_MNR_DESC,
			EMD.PRODH6 AS SAP_PROD_HIER_CD,
			EMD.PRODH6_TXTMD AS SAP_PROD_HIER_DESC,
			--EMD.SLS_ORG AS SLS_ORG,
			--EMD.GREENLIGHT_SKU_FLAG AS GREENLIGHT_SKU_FLAG,
			EMD.PKA_PRODUCT_KEY AS PKA_PRODUCT_KEY,
			EMD.PKA_PRODUCT_KEY_DESCRIPTION AS PKA_PRODUCT_KEY_DESCRIPTION,
			EGPH."region" AS GPH_REGION,
			EGPH.REGIONAL_FRANCHISE AS GPH_REG_FRNCHSE,
			EGPH.REGIONAL_FRANCHISE_GROUP AS GPH_REG_FRNCHSE_GRP,
			EGPH.GCPH_FRANCHISE AS GPH_PROD_FRNCHSE,
			EGPH.GCPH_BRAND AS GPH_PROD_BRND,
			EGPH.GCPH_SUBBRAND AS GPH_PROD_SUB_BRND,
			EGPH.GCPH_VARIANT AS GPH_PROD_VRNT,
			EGPH.GCPH_NEEDSTATE AS GPH_PROD_NEEDSTATE,
			EGPH.GCPH_CATEGORY AS GPH_PROD_CTGRY,
			EGPH.GCPH_SUBCATEGORY AS GPH_PROD_SUBCTGRY,
			EGPH.GCPH_SEGMENT AS GPH_PROD_SGMNT,
			EGPH.GCPH_SUBSEGMENT AS GPH_PROD_SUBSGMNT,
			EGPH.PUT_UP_CODE AS GPH_PROD_PUT_UP_CD,
			EGPH.PUT_UP_DESCRIPTION AS GPH_PROD_PUT_UP_DESC,
			EGPH.SIZE AS GPH_PROD_SIZE,
			EGPH.UNIT_OF_MEASURE AS GPH_PROD_SIZE_UOM,
            EMD.PKA_PACKAGE_DESC AS PKA_PACKAGE,
			row_number() OVER (
				PARTITION BY sap_matl_num ORDER BY sap_matl_num
				) rnk
		FROM
			--(SELECT * FROM (SELECT *,ROW_NUMBER() OVER (PARTITION BY matl_num ORDER BY matl_num ASC NULLS LAST) AS rank
			--		FROM edw_vw_greenlight_skus WHERE sls_org IN 
			--('3100','310A','3110','3121','311A')
			--		(select distinct sls_org from edw_sales_org_dim where stats_crncy = 'JPY')) WHERE rank = 1)
			edw_material_dim EMD,
			EDW_GCH_PRODUCTHIERARCHY EGPH
		WHERE LTRIM(EMD.MATL_NUM, '0') = LTRIM(EGPH.MATERIALNUMBER(+), 0)
			AND EMD.PROD_HIER_CD <> ''
			--AND   LTRIM(EMD.MATL_NUM,0) IN  (SELECT DISTINCT LTRIM(MATL_NUM,'0')FROM edw_material_sales_dim
			--WHERE sls_org in 
			--('3100','310A','3110','3121','311A')
			--(select distinct sls_org from edw_sales_org_dim where stats_crncy = 'JPY')) 

),
PROD_KEY1 as(
			SELECT a.ctry_nm,
			a.ean_upc,
			a.sku,
			a.pka_productkey,
			a.pka_productdesc
		FROM (
			SELECT ctry_nm,
				ltrim(ean_upc, '0') AS ean_upc,
				ltrim(matl_num, '0') AS sku,
				pka_productkey,
				pka_productdesc,
				lst_nts AS nts_date
			FROM edw_product_key_attributes
			WHERE (
					matl_type_cd = 'FERT'
					OR matl_type_cd = 'HALB'
					OR matl_type_cd = 'SAPR'
					)
				AND lst_nts IS NOT NULL
			) a
		JOIN (
			SELECT ctry_nm,
				ltrim(ean_upc, '0') AS ean_upc,
				ltrim(matl_num, '0') AS sku,
				lst_nts AS latest_nts_date,
				row_number() OVER (
					PARTITION BY ctry_nm,
					ean_upc ORDER BY lst_nts DESC
					) AS row_number
			FROM edw_product_key_attributes
			WHERE (
					matl_type_cd = 'FERT'
					OR matl_type_cd = 'HALB'
					OR matl_type_cd = 'SAPR'
					)
				AND lst_nts IS NOT NULL
			) b ON a.ctry_nm = b.ctry_nm
			AND a.ean_upc = b.ean_upc
			AND a.sku = b.sku
			AND b.latest_nts_date = a.nts_date
			AND b.row_number = 1
			AND a.ctry_nm = 'Japan'
),
PROD_KEY2 as(
			SELECT a.ctry_nm,
			a.ean_upc,
			a.sku,
			a.pka_productkey,
			a.pka_productdesc
		FROM (
			SELECT ctry_nm,
				ltrim(ean_upc, '0') AS ean_upc,
				ltrim(matl_num, '0') AS sku,
				pka_productkey,
				pka_productdesc,
				lst_nts AS nts_date
			FROM edw_product_key_attributes
			WHERE (
					matl_type_cd = 'FERT'
					OR matl_type_cd = 'HALB'
					OR matl_type_cd = 'SAPR'
					)
				AND lst_nts IS NOT NULL
			) a
		JOIN (
			SELECT ctry_nm,
				ltrim(ean_upc, '0') AS ean_upc,
				ltrim(matl_num, '0') AS sku,
				lst_nts AS latest_nts_date,
				row_number() OVER (
					PARTITION BY ctry_nm,
					ean_upc ORDER BY lst_nts DESC
					) AS row_number
			FROM edw_product_key_attributes
			WHERE (
					matl_type_cd = 'FERT'
					OR matl_type_cd = 'HALB'
					OR matl_type_cd = 'SAPR'
					)
				AND lst_nts IS NOT NULL
			) b ON a.ctry_nm = b.ctry_nm
			AND a.ean_upc = b.ean_upc
			AND a.sku = b.sku
			AND b.latest_nts_date = a.nts_date
			AND b.row_number = 1
			AND a.ctry_nm = 'Japan'
),
customer as(
			SELECT *
		FROM (
			SELECT DISTINCT LTRIM(ECBD.CUST_NUM, '0') AS SAP_CUST_ID,
				ECBD.CUST_NM AS SAP_CUST_NM,
				ECSD.SLS_ORG AS SAP_SLS_ORG,
				ECD.COMPANY AS SAP_CMP_ID,
				ECD.CTRY_KEY AS SAP_CNTRY_CD,
				ECD.CTRY_NM AS SAP_CNTRY_NM,
				ECSD.PRNT_CUST_KEY AS SAP_PRNT_CUST_KEY,
				CDDES_PCK.CODE_DESC AS SAP_PRNT_CUST_DESC,
				ECSD.CHNL_KEY AS SAP_CUST_CHNL_KEY,
				CDDES_CHNL.CODE_DESC AS SAP_CUST_CHNL_DESC,
				ECSD.SUB_CHNL_KEY AS SAP_CUST_SUB_CHNL_KEY,
				CDDES_SUBCHNL.CODE_DESC AS SAP_SUB_CHNL_DESC,
				ECSD.GO_TO_MDL_KEY AS SAP_GO_TO_MDL_KEY,
				CDDES_GTM.CODE_DESC AS SAP_GO_TO_MDL_DESC,
				ECSD.BNR_KEY AS SAP_BNR_KEY,
				CDDES_BNRKEY.CODE_DESC AS SAP_BNR_DESC,
				ECSD.BNR_FRMT_KEY AS SAP_BNR_FRMT_KEY,
				CDDES_BNRFMT.CODE_DESC AS SAP_BNR_FRMT_DESC,
				SUBCHNL_RETAIL_ENV.RETAIL_ENV,
				REG_JAPAN.REGION AS REGION, --ADDED REGION 
				REG_JAPAN.PREFECTURE_NAME_ENG AS ZONE_OR_AREA, ---ADDED AREA 
				EGCH.GCGH_REGION AS GCH_REGION,
				EGCH.GCGH_CLUSTER AS GCH_CLUSTER,
				EGCH.GCGH_SUBCLUSTER AS GCH_SUBCLUSTER,
				EGCH.GCGH_MARKET AS GCH_MARKET,
				EGCH.GCCH_RETAIL_BANNER AS GCH_RETAIL_BANNER,
				ROW_NUMBER() OVER (
					PARTITION BY SAP_CUST_ID ORDER BY SAP_PRNT_CUST_KEY DESC
					) AS RANK
			--ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY NULLIF(ECSD.PRNT_CUST_KEY,''),NULLIF(ECSD.BNR_KEY,''),NULLIF(ECSD.BNR_FRMT_KEY,''),NULLIF(ECSD.SEGMT_KEY,'') ASC NULLS LAST) AS RANK
			FROM 
				EDW_GCH_CUSTOMERHIERARCHY EGCH,
				EDW_CUSTOMER_SALES_DIM ECSD,
				EDW_CUSTOMER_BASE_DIM ECBD,
				EDW_COMPANY_DIM ECD,
				EDW_DSTRBTN_CHNL EDC,
				EDW_SALES_ORG_DIM ESOD,
				EDW_CODE_DESCRIPTIONS CDDES_PCK,
				EDW_CODE_DESCRIPTIONS CDDES_BNRKEY,
				EDW_CODE_DESCRIPTIONS CDDES_BNRFMT,
				EDW_CODE_DESCRIPTIONS CDDES_CHNL,
				EDW_CODE_DESCRIPTIONS CDDES_GTM,
				EDW_CODE_DESCRIPTIONS CDDES_SUBCHNL,
				EDW_SUBCHNL_RETAIL_ENV_MAPPING SUBCHNL_RETAIL_ENV,
				--EDW_CODE_DESCRIPTIONS_MANUAL CODES_SEGMENT,
				/*(SELECT CUST_NUM,
             MIN(DECODE(CUST_DEL_FLAG,NULL,'O','','O',CUST_DEL_FLAG)) AS CUST_DEL_FLAG
      FROM EDW_CUSTOMER_SALES_DIM
      WHERE SLS_ORG IN ('3100')
      GROUP BY CUST_NUM) A,*/
				(
					SELECT DISTINCT CUST_NUM,
						REC_CRT_DT,
						PRNT_CUST_KEY,
						ROW_NUMBER() OVER (
							PARTITION BY CUST_NUM ORDER BY REC_CRT_DT DESC
							) RN
					FROM EDW_CUSTOMER_SALES_DIM
						--where sls_org in
						--('3100','310A','3110','3121','311A') 
						--(select distinct sls_org from edw_sales_org_dim where stats_crncy = 'JPY')
					) A,
				(
					SELECT DISTINCT JIS_CD,
						REGION,
						PREFECTURE_NAME_ENG
					FROM JP_INV_COVERAGE_AREA_REGION_MAPPING
					) REG_JAPAN,
				(
					SELECT DISTINCT CSTM_CD,
						JIS_PRFCT_CD
					FROM EDI_CSTM_M
					) REG_CUST_JAP_REGION
			WHERE EGCH.CUSTOMER(+) = ECBD.CUST_NUM
				AND ECSD.CUST_NUM = ECBD.CUST_NUM
				AND LTRIM(ECBD.CUST_NUM, 0) = REG_CUST_JAP_REGION.CSTM_CD(+)
				AND REG_CUST_JAP_REGION.JIS_PRFCT_CD = REG_JAPAN.JIS_CD
				-- AND   REG_CUST_JAP_REGION.cstm_cd=ltrim(ECBD.CUST_NUM,0)
				-- AND   REG_CUST_JAP_REGION.jis_prfct_cd=REG_JAPAN.jis_cd 
				--AND   DECODE(ECSD.CUST_DEL_FLAG,NULL,'O','','O',ECSD.CUST_DEL_FLAG) = A.CUST_DEL_FLAG
				AND A.CUST_NUM = ECSD.CUST_NUM
				AND ECSD.DSTR_CHNL = EDC.DISTR_CHAN
				AND ECSD.SLS_ORG = ESOD.SLS_ORG
				AND ESOD.SLS_ORG_CO_CD = ECD.CO_CD
				AND ECSD.SLS_ORG IN
				--('3100','310A','3110','3121','311A')
				(
					SELECT DISTINCT sls_org
					FROM edw_sales_org_dim
					WHERE stats_crncy = 'JPY'
					)
				AND A.RN = 1
				AND TRIM(UPPER(CDDES_PCK.CODE_TYPE(+))) = 'PARENT CUSTOMER KEY'
				AND CDDES_PCK.CODE(+) = ECSD.PRNT_CUST_KEY
				AND TRIM(UPPER(CDDES_BNRKEY.CODE_TYPE(+))) = 'BANNER KEY'
				AND CDDES_BNRKEY.CODE(+) = ECSD.BNR_KEY
				AND TRIM(UPPER(CDDES_BNRFMT.CODE_TYPE(+))) = 'BANNER FORMAT KEY'
				AND CDDES_BNRFMT.CODE(+) = ECSD.BNR_FRMT_KEY
				AND TRIM(UPPER(CDDES_CHNL.CODE_TYPE(+))) = 'CHANNEL KEY'
				AND CDDES_CHNL.CODE(+) = ECSD.CHNL_KEY
				AND TRIM(UPPER(CDDES_GTM.CODE_TYPE(+))) = 'GO TO MODEL KEY'
				AND CDDES_GTM.CODE(+) = ECSD.GO_TO_MDL_KEY
				AND TRIM(UPPER(CDDES_SUBCHNL.CODE_TYPE(+))) = 'SUB CHANNEL KEY'
				AND CDDES_SUBCHNL.CODE(+) = ECSD.SUB_CHNL_KEY
				AND UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL(+)) = UPPER(CDDES_SUBCHNL.CODE_DESC)
			) --AND   LTRIM(ECSD.CUST_NUM,'0') = REG_JAPAN.CUSTOMER_CODE(+)
		--AND   CODES_SEGMENT.code_type(+) = 'Customer Segmentation Key'
		--AND   CODES_SEGMENT.CODE(+) = ECSD.segmt_key
		WHERE RANK = 1
),
CURRENCY as(
			SELECT *
		FROM VW_EDW_REG_EXCH_RATE
		WHERE CNTRY_KEY = 'JP'
			AND TO_CCY = 'USD'
			AND JJ_MNTH_ID = (
				SELECT MAX(JJ_MNTH_ID)
				FROM VW_EDW_REG_EXCH_RATE
				)
)

SELECT YEAR,
	QRTR_NO,
	MNTH_ID,
	mnth_no,
	CAL_DATE,
	COUNTRY_CODE,
	COUNTRY_NAME,
	DATA_SOURCE,
	SOLDTO_CODE,
	DISTRIBUTOR_CODE,
	DISTRIBUTOR_NAME,
	STORE_CODE,
	trim(STORE_NAME) as STORE_NAME,
	store_type,
	DISTRIBUTOR_ADDITIONAL_ATTRIBUTE1,
	DISTRIBUTOR_ADDITIONAL_ATTRIBUTE2,
	DISTRIBUTOR_ADDITIONAL_ATTRIBUTE3,
	SAP_PARENT_CUSTOMER_KEY,
	SAP_PARENT_CUSTOMER_DESCRIPTION,
	SAP_CUSTOMER_CHANNEL_KEY,
	SAP_CUSTOMER_CHANNEL_DESCRIPTION,
	SAP_CUSTOMER_SUB_CHANNEL_KEY,
	SAP_SUB_CHANNEL_DESCRIPTION,
	SAP_GO_TO_MDL_KEY,
	SAP_GO_TO_MDL_DESCRIPTION,
	SAP_BANNER_KEY,
	SAP_BANNER_DESCRIPTION,
	SAP_BANNER_FORMAT_KEY,
	SAP_BANNER_FORMAT_DESCRIPTION,
	RETAIL_ENVIRONMENT,
	REGION,
	ZONE_OR_AREA,
	CUSTOMER_SEGMENT_KEY,
	CUSTOMER_SEGMENT_DESCRIPTION,
	GLOBAL_PRODUCT_FRANCHISE,
	GLOBAL_PRODUCT_BRAND,
	GLOBAL_PRODUCT_SUB_BRAND,
	GLOBAL_PRODUCT_VARIANT,
	GLOBAL_PRODUCT_SEGMENT,
	GLOBAL_PRODUCT_SUBSEGMENT,
	GLOBAL_PRODUCT_CATEGORY,
	GLOBAL_PRODUCT_SUBCATEGORY,
	GLOBAL_PUT_UP_DESCRIPTION,
	EAN,
	SKU_CODE,
	SKU_DESCRIPTION,
	--GREENLIGHT_SKU_FLAG,
	CASE 
		WHEN PKA_PRODUCT_KEY IN ('N/A', 'NA')
			THEN 'NA'
		ELSE PKA_PRODUCT_KEY
		END AS PKA_PRODUCT_KEY,
	CASE 
		WHEN PKA_PRODUCT_KEY_DESCRIPTION IN ('N/A', 'NA')
			THEN 'NA'
		ELSE PKA_PRODUCT_KEY_DESCRIPTION
		END AS PKA_PRODUCT_KEY_DESCRIPTION,
	--SLS_ORG AS SLS_ORG,
	Customer_Product_Desc,
	FROM_CURRENCY,
	TO_CURRENCY,
	EXCHANGE_RATE,
	SELLOUT_SALES_QUANTITY,
	SELLOUT_SALES_VALUE,
	SELLOUT_SALES_VALUE_USD,
	msl_product_code,
	msl_product_desc,
	retail_env,
	channel,
	crtd_dttm,
	updt_dttm
FROM (
	SELECT CAL.YEAR,
		CAST(CAL.QRTR_NO AS VARCHAR) AS QRTR_NO,
		CAST(CAL.MNTH_ID AS VARCHAR) AS MNTH_ID,
		CAL.MNTH_NO AS MNTH_NO,
		--CAL.CAL_DATE,
		SELLOUT.DAY AS CAL_DATE,
		SELLOUT.CNTRY_CD AS COUNTRY_CODE,
		SELLOUT.CNTRY_NM AS COUNTRY_NAME,
		SELLOUT.DATA_SRC AS DATA_SOURCE,
		TRIM(NVL(NULLIF(SELLOUT.SOLD_TO_CODE, ''), 'NA')) AS SOLDTO_CODE,
		TRIM(NVL(NULLIF(SELLOUT.DISTRIBUTOR_CODE, ''), 'NA')) AS DISTRIBUTOR_CODE,
		TRIM(NVL(NULLIF(SELLOUT.DISTRIBUTOR_NAME, ''), 'NA')) AS DISTRIBUTOR_NAME,
		TRIM(NVL(NULLIF(SELLOUT.STORE_CODE, ''), 'NA')) AS STORE_CODE,
		TRIM(NVL(NULLIF(SELLOUT.STORE_NAME, ''), 'NA')) AS STORE_NAME,
		TRIM(NVL(NULLIF(SELLOUT.STORE_TYPE_CODE, ''), 'NA')) AS STORE_TYPE,
		'NA' AS DISTRIBUTOR_ADDITIONAL_ATTRIBUTE1,
		'NA' AS DISTRIBUTOR_ADDITIONAL_ATTRIBUTE2,
		'NA' AS DISTRIBUTOR_ADDITIONAL_ATTRIBUTE3,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_PRNT_CUST_KEY, ''), 'NA')) AS SAP_PARENT_CUSTOMER_KEY,
		UPPER(TRIM(NVL(NULLIF(CUSTOMER.SAP_PRNT_CUST_DESC, ''), 'NA'))) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_CUST_CHNL_KEY, ''), 'NA')) AS SAP_CUSTOMER_CHANNEL_KEY,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_CUST_CHNL_DESC, ''), 'NA')) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_CUST_SUB_CHNL_KEY, ''), 'NA')) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_SUB_CHNL_DESC, ''), 'NA')) AS SAP_SUB_CHANNEL_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_GO_TO_MDL_KEY, ''), 'NA')) AS SAP_GO_TO_MDL_KEY,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_GO_TO_MDL_DESC, ''), 'NA')) AS SAP_GO_TO_MDL_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_BNR_KEY, ''), 'NA')) AS SAP_BANNER_KEY,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_BNR_DESC, ''), 'NA')) AS SAP_BANNER_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_BNR_FRMT_KEY, ''), 'NA')) AS SAP_BANNER_FORMAT_KEY,
		TRIM(NVL(NULLIF(CUSTOMER.SAP_BNR_FRMT_DESC, ''), 'NA')) AS SAP_BANNER_FORMAT_DESCRIPTION,
		TRIM(NVL(NULLIF(CUSTOMER.RETAIL_ENV, ''), 'NA')) AS RETAIL_ENVIRONMENT,
		TRIM(NVL(NULLIF(CUSTOMER.REGION, ''), 'NA')) AS REGION,
		TRIM(NVL(NULLIF(CUSTOMER.ZONE_OR_AREA, ''), 'NA')) AS ZONE_OR_AREA,
		--TRIM(NVL (NULLIF(CUSTOMER.CUST_SEGMT_KEY,''),'NA')) AS CUSTOMER_SEGMENT_KEY,
		--TRIM(NVL (NULLIF(CUSTOMER.CUST_SEGMENT_DESC,''),'NA')) AS CUSTOMER_SEGMENT_DESCRIPTION, 
		'NA' AS CUSTOMER_SEGMENT_KEY,
		'NA' AS CUSTOMER_SEGMENT_DESCRIPTION,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_FRNCHSE, ''), 'NA')) AS GLOBAL_PRODUCT_FRANCHISE,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_BRND, ''), 'NA')) AS GLOBAL_PRODUCT_BRAND,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_SUB_BRND, ''), 'NA')) AS GLOBAL_PRODUCT_SUB_BRAND,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_VRNT, ''), 'NA')) AS GLOBAL_PRODUCT_VARIANT,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_SGMNT, ''), 'NA')) AS GLOBAL_PRODUCT_SEGMENT,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_SUBSGMNT, ''), 'NA')) AS GLOBAL_PRODUCT_SUBSEGMENT,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_CTGRY, ''), 'NA')) AS GLOBAL_PRODUCT_CATEGORY,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_SUBCTGRY, ''), 'NA')) AS GLOBAL_PRODUCT_SUBCATEGORY,
		TRIM(NVL(NULLIF(PRODUCT.GPH_PROD_PUT_UP_DESC, ''), 'NA')) AS GLOBAL_PUT_UP_DESCRIPTION,
		SELLOUT.EAN AS EAN,
		TRIM(NVL(NULLIF(PRODUCT.SAP_MATL_NUM, ''), 'NA')) AS SKU_CODE,
		UPPER(TRIM(NVL(NULLIF(PRODUCT.SAP_MAT_DESC, ''), 'NA'))) AS SKU_DESCRIPTION,
		--TRIM(NVL(NULLIF(PRODUCT.GREENLIGHT_SKU_FLAG,''),'NA')) AS GREENLIGHT_SKU_FLAG,
		CASE 
			WHEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA'))
			ELSE TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA'))
			END AS PKA_PRODUCT_KEY,
		CASE 
			WHEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productdesc, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productdesc, ''), 'NA'))
			ELSE TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION, ''), 'NA'))
			END AS PKA_PRODUCT_KEY_DESCRIPTION,
		--TRIM(NVL (NULLIF(PRODUCT.SLS_ORG,''),'NA')) AS SLS_ORG,
		TRIM(NVL(NULLIF(SELLOUT.Customer_Product_Desc, ''), 'NA')) AS Customer_Product_Desc,
		CURRENCY.FROM_CCY AS FROM_CURRENCY,
		CURRENCY.TO_CCY AS TO_CURRENCY,
		--CURRENCY.EXCH_RATE/100 AS EXCHANGE_RATE,
		trunc((CURRENCY.EXCH_RATE / (CURRENCY.from_ratio * CURRENCY.to_ratio)),5) AS EXCHANGE_RATE,
		SUM(SELLOUT.SO_SLS_QTY) AS SELLOUT_SALES_QUANTITY,
		SUM(SELLOUT.SO_SLS_VALUE) AS SELLOUT_SALES_VALUE,
		SUM(SELLOUT.SO_SLS_VALUE * (CURRENCY.EXCH_RATE / (CURRENCY.from_ratio * CURRENCY.to_ratio)))::NUMERIC(38, 11) AS SELLOUT_SALES_VALUE_USD,
		TRIM(NVL(NULLIF(SELLOUT.msl_product_code, ''), 'NA')) AS msl_product_code,
		--TRIM(NVL(NULLIF(SELLOUT.msl_product_desc, ''), 'NA')) AS msl_product_desc,
        CASE WHEN (UPPER(PRODUCT.PKA_PACKAGE) IN ('MIX PACK', 'ASSORTED PACK') OR PRODUCT.PKA_PACKAGE IS NULL) THEN UPPER(TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')))
        ELSE (CASE WHEN TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))
            WHEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productdesc,''),'NA'))
            WHEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productdesc,''),'NA'))
            ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END)
        END AS msl_product_desc,
		TRIM(NVL(NULLIF(SELLOUT.retail_env, ''), 'NA')) AS retail_env,
		TRIM(NVL(NULLIF(SELLOUT.channel, ''), 'NA')) AS channel,
		SELLOUT.crtd_dttm,
		SELLOUT.updt_dttm
	FROM WKS_JAPAN_REGIONAL_SELLOUT_BASE SELLOUT
	LEFT JOIN CAL ON SELLOUT.MNTH_ID = CAL.MNTH_ID
	LEFT JOIN PRODUCT ON LTRIM(SELLOUT.SKU_CD, '0') = LTRIM(PRODUCT.SAP_MATL_NUM, '0')
		AND rnk = 1
	LEFT JOIN PROD_KEY1 ON ltrim(SELLOUT.SKU_CD, '0') = ltrim(PROD_KEY1.sku, '0')
	LEFT JOIN PROD_KEY2 ON ltrim(SELLOUT.ean, '0') = ltrim(PROD_KEY2.ean_upc, '0')
	LEFT JOIN CUSTOMER ON LTRIM(SELLOUT.SOLD_TO_CODE, '0') = LTRIM(CUSTOMER.SAP_CUST_ID, '0')
	LEFT JOIN CURRENCY ON UPPER(SELLOUT.CNTRY_NM) = UPPER(CURRENCY.CNTRY_NM)
	WHERE CURRENCY.FROM_CCY = 'JPY'
	GROUP BY CAL.YEAR,
		CAL.QRTR_NO,
		CAL.MNTH_ID,
		CAL.MNTH_NO,
		--CAL.CAL_DATE ,
		SELLOUT.DAY,
		SELLOUT.CNTRY_CD,
		SELLOUT.CNTRY_NM,
		SELLOUT.DATA_SRC,
		SELLOUT.SOLD_TO_CODE,
		SELLOUT.DISTRIBUTOR_CODE,
		SELLOUT.DISTRIBUTOR_NAME,
		SELLOUT.STORE_CODE,
		SELLOUT.STORE_NAME,
		SELLOUT.STORE_TYPE_CODE,
		CUSTOMER.SAP_PRNT_CUST_KEY,
		CUSTOMER.SAP_PRNT_CUST_DESC,
		CUSTOMER.SAP_CUST_CHNL_KEY,
		CUSTOMER.SAP_CUST_CHNL_DESC,
		CUSTOMER.SAP_CUST_SUB_CHNL_KEY,
		CUSTOMER.SAP_SUB_CHNL_DESC,
		CUSTOMER.SAP_GO_TO_MDL_KEY,
		CUSTOMER.SAP_GO_TO_MDL_DESC,
		CUSTOMER.SAP_BNR_KEY,
		CUSTOMER.SAP_BNR_DESC,
		CUSTOMER.SAP_BNR_FRMT_KEY,
		CUSTOMER.SAP_BNR_FRMT_DESC,
		CUSTOMER.RETAIL_ENV,
		CUSTOMER.REGION,
		CUSTOMER.ZONE_OR_AREA,
		PRODUCT.GPH_PROD_FRNCHSE,
		PRODUCT.GPH_PROD_BRND,
		PRODUCT.GPH_PROD_SUB_BRND,
		PRODUCT.GPH_PROD_VRNT,
		PRODUCT.GPH_PROD_SGMNT,
		PRODUCT.GPH_PROD_SUBSGMNT,
		PRODUCT.GPH_PROD_CTGRY,
		PRODUCT.GPH_PROD_SUBCTGRY,
		PRODUCT.GPH_PROD_PUT_UP_DESC,
		SELLOUT.EAN,
		PRODUCT.SAP_MATL_NUM,
		PRODUCT.SAP_MAT_DESC,
		--PRODUCT.GREENLIGHT_SKU_FLAG, 
		--	PRODUCT.PKA_PRODUCT_KEY, 
		--	PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION, 
		CASE 
			WHEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA'))
			ELSE TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA'))
			END,
		CASE 
			WHEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY1.pka_productdesc, ''), 'NA'))
			WHEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productkey, ''), 'NA')) NOT IN ('N/A', 'NA')
				THEN TRIM(NVL(NULLIF(PROD_KEY2.pka_productdesc, ''), 'NA'))
			ELSE TRIM(NVL(NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION, ''), 'NA'))
			END,
        PRODUCT.PKA_PACKAGE,
		--PRODUCT.SLS_ORG,
		SELLOUT.customer_product_desc,
		CURRENCY.FROM_CCY,
		CURRENCY.TO_CCY,
		trunc((CURRENCY.EXCH_RATE / (CURRENCY.from_ratio * CURRENCY.to_ratio)),5),
		SELLOUT.msl_product_code,
		--SELLOUT.msl_product_desc,
		SELLOUT.retail_env,
		SELLOUT.channel,
		SELLOUT.crtd_dttm,
		SELLOUT.updt_dttm
	HAVING NOT (
			SUM(SELLOUT.SO_SLS_VALUE) = 0
			AND SUM(SELLOUT.SO_SLS_QTY) = 0
			)
	)
);
