create or replace TABLE PROD_DNA_CORE.DBT_CLOUD_PR_5458_1544.VNMWKS_INTEGRATION__TRATBL_SDL_VN_DKSH_OTC__NULL_TEST (
	FILE_NAME VARCHAR(100),
	FAILURE_REASON VARCHAR(24),
	BUSINESS_UNIT VARCHAR(100),
	DATE VARCHAR(100),
	STOCK_TYPE VARCHAR(100),
	PRODUCT_CODE VARCHAR(100),
	PRODUCT_NAME VARCHAR(100),
	BATCH VARCHAR(100),
	PLANT_CODE VARCHAR(100)
);

create or replace TABLE  PROD_DNA_CORE.DBT_CLOUD_PR_5458_1544.VNMWKS_INTEGRATION__TRATBL_SDL_VN_DKSH_OTC__DUPLICATE_TEST (
	FILE_NAME VARCHAR(100),
	FAILURE_REASON VARCHAR(25),
	BUSINESS_UNIT VARCHAR(300),
	DATE VARCHAR(300),
	STOCK_TYPE VARCHAR(300),
	PRODUCT_CODE VARCHAR(300),
	PRODUCT_NAME VARCHAR(300),
	BATCH VARCHAR(300),
	PLANT_CODE VARCHAR(300)
);

create or replace TABLE PROD_DNA_CORE.DBT_CLOUD_PR_5458_1544.VNMWKS_INTEGRATION__TRATBL_SDL_VN_DKSH_OTC__DATE_FORMAT_TEST (
	FILE_NAME VARCHAR(100),
	FAILURE_REASON VARCHAR(22),
	BUSINESS_UNIT VARCHAR(100),
	DATE VARCHAR(100),
	STOCK_TYPE VARCHAR(100),
	PRODUCT_CODE VARCHAR(100),
	PRODUCT_NAME VARCHAR(100),
	BATCH VARCHAR(100),
	EXPIRY_DATE VARCHAR(100),
	BASE_UOM VARCHAR(100),
	SHELF_LIFE VARCHAR(100),
	COGS VARCHAR(100),
	REGION VARCHAR(100),
	QUANTITY NUMBER(20,0),
	VALUE VARCHAR(100),
	PLANT_CODE VARCHAR(100),
	PLANT_NAME VARCHAR(100),
	SYSLOT VARCHAR(100),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);
