create table PROD_DNA_CORE.PHLWKS_INTEGRATION.WKS_PH_POS_DYNA_SALES_11112024 as select * from PROD_DNA_CORE.PHLWKS_INTEGRATION.WKS_PH_POS_DYNA_SALES;
delete from PROD_DNA_CORE.PHLWKS_INTEGRATION.WKS_PH_POS_DYNA_SALES;
create table PROD_DNA_CORE.PHLITG_INTEGRATION.ITG_PH_POS_SALES_FACT_11112024 as select * from PROD_DNA_CORE.PHLITG_INTEGRATION.ITG_PH_POS_SALES_FACT ;
delete from PROD_DNA_CORE.PHLITG_INTEGRATION.ITG_PH_POS_SALES_FACT where CUST_CD='DYNA' and JJ_MNTH_ID>=202312;
