
create table PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERDETAIL_bkp20241111 
as select * from PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERDETAIL;

create table PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERHEADER_bkp20241111 
as select * from PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERHEADER;

commit;


delete from PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERDETAIL 
where filename='rt_ruralstoreorderdetail_20242310.csv';

commit;



delete from PROD_DNA_CORE.INDITG_INTEGRATION.ITG_RURALSTOREORDERHEADER
where filename ='rt_ruralstoreorderheader_20242310.csv';

commit;