UPDATE PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_MDS_AP_CUSTOMER360_CONFIG
   SET param_value = '36'
Where code = 'base_load_cn_otc';

UPDATE PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_MDS_AP_CUSTOMER360_CONFIG
   SET param_value = '52'
Where code = 'base_load_ph';
