	create or replace table INDITG_INTEGRATION.ITG_PILOT_NUP_TARGET_BKP AS SELECT * FROM INDITG_INTEGRATION.ITG_PILOT_NUP_TARGET;
	
	INSERT INTO PROD_DNA_CORE.INDITG_INTEGRATION.ITG_PILOT_NUP_TARGET
  (SELECT * FROM PROD_DNA_CORE.INDITG_INTEGRATION.ITG_PILOT_NUP_TARGET_tmp);