create or replace TABLE PROD_DNA_CORE.INDITG_INTEGRATION.LKP_HARMONIZATION_PATTERNS (
	PATTERN_ID VARCHAR(100) NOT NULL,
	PATTERN VARCHAR(100) NOT NULL,
	PATTERN_DESCRIPTION VARCHAR(100) NOT NULL
);

create or replace TABLE PROD_DNA_CORE.INDITG_INTEGRATION.LKP_HARMONIZATION_UNIVERAL_EXCEPTION (
	EXPTN_DATA_SRC VARCHAR(100) NOT NULL,
	SOURCE_FIELD VARCHAR(100),
	VALUE VARCHAR(100),
	MASTER_VALUE VARCHAR(100),
	HARMONIZATION_TYPE VARCHAR(100),
	GCGH_REGION VARCHAR(100)
);

create or replace TABLE PROD_DNA_CORE.INDITG_INTEGRATION.T_HARMONIZATION_RULE_MSTR (
	SRC_NAME VARCHAR(100) NOT NULL,
	TABLENAME VARCHAR(1000) NOT NULL,
	RULE_SEQ VARCHAR(100) NOT NULL,
	HRM_TYPE VARCHAR(100) NOT NULL,
	COLUMN_NAME VARCHAR(1000) NOT NULL,
	PATTERN_ID VARCHAR(100) NOT NULL,
	ACTIVE_FLAG VARCHAR(1),
	FILTER_CONDITION VARCHAR(1000)
);
