create or replace TABLE PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_QUERY_PARAMETERS_TEMP CLONE PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_QUERY_PARAMETERS;
INSERT INTO PROD_DNA_CORE.NTAITG_INTEGRATION.ITG_QUERY_PARAMETERS_temp VALUES ('TW','A-Mart 愛買','120821','sold_to_party');
