create or replace view PROD_DNA_CORE.HCPEDW_ACCESS.EDW_RPT_RX_TO_CX_TO_POB(
	"year",
	"month",
	"urc",
	"ventasys_product",
	"franchise_name",
	"brand_name",
	"sales_qty",
	"sales_ach_nr",
	"pob_units",
	"hcp_id",
	"hcp_name",
	"rx_factorized",
	"rx_units",
	"urc_name",
	"distributor_code",
	"distributor_name",
	"channel_name",
	"class_desc",
	"retailer_category_name",
	"retailer_channel_1",
	"retailer_channel_2",
	"retailer_channel_3",
	"region_name",
	"zone_name",
	"territory_name",
	"salesman_code_sales",
	"salesman_name_sales",
	"emp_id",
	"emp_name",
	"region_vent",
	"territory_vent",
	"zone_vent",
	"urc active flag",
	"urc active flag ventasys",
    "latest_customer_code",
    "latest_customer_name",
    "latest_salesman_code",
    "latest_salesman_name",
    "latest_region",
    "latest_zone",
	"latest_territory",
    "emp_hq_name",
    "city",
    "state",
    "customer_type",
    "core_noncore",
	"is_active",
	"load_dttm"
    
) as 
select
year as "year",
month as "month",
urc as "urc",
ventasys_product as "ventasys_product",
franchise_name as "franchise_name",
brand_name as "brand_name",
sales_qty as "sales_qty",
sales_ach_nr as "sales_ach_nr",
pob_units as "pob_units",
hcp_id as "hcp_id",
hcp_name as "hcp_name",
rx_factorized as "rx_factorized",
rx_units as "rx_units",
urc_name as "urc_name",
distributor_code as "distributor_code",
distributor_name as "distributor_name",
channel_name as "channel_name",
class_desc as "class_desc",
retailer_category_name as "retailer_category_name",
retailer_channel_1 as "retailer_channel_1",
retailer_channel_2 as "retailer_channel_2",
retailer_channel_3 as "retailer_channel_3",
region_name as "region_name",
zone_name as "zone_name",
territory_name as "territory_name",
salesman_code_sales as "salesman_code_sales",
salesman_name_sales as "salesman_name_sales",
emp_id as "emp_id",
emp_name as "emp_name",
region_vent as "region_vent",
territory_vent as "territory_vent",
zone_vent as "zone_vent",
"urc active flag" as "urc active flag",
"urc active flag ventasys" as "urc active flag ventasys",
latest_customer_code as "latest_customer_code",
latest_customer_name as "latest_customer_name",
latest_salesman_code as "latest_salesman_code",
latest_salesman_name as "latest_salesman_name",
latest_region as "latest_region",
latest_zone as "latest_zone",
latest_territory as "latest_territory",
emp_hq_name as "emp_hq_name",
city as "city",
state as "state",
customer_type as "customer_type",
core_noncore as "core_noncore",
is_active as "is_active",
load_dttm as "load_dttm"
from PROD_DNA_CORE.hcpedw_integration.edw_rpt_rx_to_cx_to_pob
;