create or replace TABLE PROD_DNA_CORE.dbt_cloud_pr_5458_1579.ntaitg_integration__itg_pos_invoice_prc_lookup (
	POS_DT DATE,
	EAN_NUM VARCHAR(100),
	SOLD_TO_PARTY VARCHAR(100),
	CALC_INVOICE_PRICE NUMBER(16,5),
	MATL_NUM VARCHAR(40),
	MATL_DESC VARCHAR(100),
	CTRY_CD VARCHAR(10),
	WAVE NUMBER(18,0),
	CRT_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9),
	SLS_GRP_CD VARCHAR(18),
	PRICING_SOLD_TO VARCHAR(100)
);
