create or replace table 
prod_dna_core.dbt_cloud_pr_5458_1580.ntaitg_integration__itg_pos 
clone prod_dna_core.ntaitg_integration.itg_pos;

create or replace table 
prod_dna_core.dbt_cloud_pr_5458_1580.ntaedw_integration__edw_pos_fact 
clone prod_dna_core.ntaedw_integration.edw_pos_fact;
