drop table PROD_DNA_CORE.dbt_cloud_pr_5458_1590.vnmitg_integration__itg_mds_vn_customer_segmentation;

create or replace TABLE PROD_DNA_CORE.dbt_cloud_pr_5458_1590.vnmitg_integration__itg_mds_vn_customer_segmentation (
	CUST_NUM VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_1_CODE VARCHAR(500),
	CUSTOMER_SEGMENTATION_LEVEL_2_CODE VARCHAR(500),
	ACCOUNTTYPE_CODE VARCHAR(500),
	REGIONALRE_CODE VARCHAR(500),
	CHANNEL_CODE VARCHAR(500),
	CHANNEL_NAME VARCHAR(500),
	SOLD_TO_CODE_NAME VARCHAR(500),
	CRT_DTTM TIMESTAMP_NTZ(9)
);
