 insert into PROD_DNA_CORE.ASPITG_INTEGRATION.ITG_QUERY_PARAMETERS
 select COUNTRY_CODE,PARAMETER_NAME,PARAMETER_VALUE from 
 PROD_DNA_CORE.SGPITG_INTEGRATION.ITG_QUERY_PARAMETERS
 where left(country_code,7) = 'VN_COPA';
