update PROD_DNA_CORE.INDITG_INTEGRATION.t_harmonization_rule_mstr
set tablename = 'FCT_TRADITIONAL_TV_SPENDS_INDIA_MONTHLY'
WHERE SRC_NAME = 'TRADITIONAL_ACTUAL_TV_SPEND';

update PROD_DNA_CORE.INDITG_INTEGRATION.t_harmonization_rule_mstr
set tablename = 'FCT_TV_GRP_SPENDS_GLOBAL_MONTHLY'
WHERE SRC_NAME = 'TRADITIONAL_COMPETITIVE_TV_GRP_SPENDS';

update PROD_DNA_CORE.INDITG_INTEGRATION.T_HARMONIZATION_RULE_MSTR 
set tablename = 'FCT_TRADITIONAL_PRINT_COMP_SPENDS_INDIA_MONTHLY'
WHERE SRC_NAME = 'TRADITIONAL_PRINT_COMP_SPEND';

update PROD_DNA_CORE.INDITG_INTEGRATION.T_HARMONIZATION_RULE_MSTR 
set tablename = 'FCT_DIGITAL_MICRO_LEVEL_REACH_INDIA_MONTHLY'
WHERE SRC_NAME = 'TRAD_MICROLEVEL_REACH';

update PROD_DNA_CORE.INDITG_INTEGRATION.T_HARMONIZATION_RULE_MSTR 
set tablename = 'FCT_DIGITAL_PLATFORM_LEVEL_REACH_INDIA_MONTHLY'
WHERE SRC_NAME = 'TRAD_PLATFORMLEVEL_REACH';




