create table PROD_DNA_CORE.PCFWKS_INTEGRATION.WKS_RF_VALUATION_LIST_PRICE_EXP_LOOKUP_TEST
(material_no varchar(100));
insert into PROD_DNA_CORE.PCFWKS_INTEGRATION.WKS_RF_VALUATION_LIST_PRICE_EXP_LOOKUP_TEST
select '100' as material_no;
