USE SCHEMA PCFITG_INTEGRATION;

CREATE TABLE IF NOT EXISTS SDL_SYMBION_DSTR_RAW (
	INV_DT VARCHAR(50),
	STATE VARCHAR(100),
	WAREHOUSE VARCHAR(255),
	WAREHOUSE_DESC VARCHAR(255),
	SYMBION_PRODUCT_NO VARCHAR(255),
	SYMBION_PRODUCT_DESC VARCHAR(255),
	SUPPLIER_PART_NO VARCHAR(255),
	EAN VARCHAR(255),
	GLOBAL_STD_COST NUMBER(10,4),
	DATE_INTRODUCED VARCHAR(255),
	DATE_LAST_RECIVED VARCHAR(255),
	OOSR VARCHAR(255),
	SOH_AMT NUMBER(10,4),
	SOH_QTY NUMBER(10,4),
	ON_ORDER NUMBER(10,4),
	BACK_ORDER NUMBER(10,4),
	RESERVED_AMT_FOR_ORDER NUMBER(10,4),
	RESERVED_QTY_FOR_ORDER NUMBER(10,4),
	RESERVED_AMT_FOR_QA NUMBER(10,4),
	RESERVED_QTY_FOR_QA NUMBER(10,4),
	AVAILABLE_AMT NUMBER(10,4),
	AVAILABLE_QTY NUMBER(10,4),
	MTD NUMBER(10,4),
	MONTH_01 NUMBER(10,4),
	MONTH_02 NUMBER(10,4),
	MONTH_03 NUMBER(10,4),
	MONTH_04 NUMBER(10,4),
	MONTH_05 NUMBER(10,4),
	MONTH_06 NUMBER(10,4),
	MONTH_07 NUMBER(10,4),
	MONTH_08 NUMBER(10,4),
	MONTH_09 NUMBER(10,4),
	MONTH_10 NUMBER(10,4),
	MONTH_11 NUMBER(10,4),
	MONTH_12 NUMBER(10,4),
	MONTH_13 NUMBER(10,4),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);
CREATE TABLE IF NOT EXISTS SDL_PHARM_SELLOUT_WEEKLY_RAW (
	OUTLET_NUMBER VARCHAR(10),
	NAME VARCHAR(30),
	PFC VARCHAR(10),
	PACK_LONG_DESC VARCHAR(60),
	WEEK_ENDING_DATE VARCHAR(8),
	UNITS NUMBER(18,0),
	DERIVED_PRICE NUMBER(18,6),
	AMOUNT NUMBER(18,6),
	CRT_DTTM TIMESTAMP_NTZ(9),
	RUN_ID NUMBER(14,0)
);

CREATE TABLE IF NOT EXISTS SDL_IG_INVENTORY_DATA_RAW (
	INV_DT VARCHAR(100),
	STATE VARCHAR(100),
	WARE_HOUSE NUMBER(18,0),
	PE_ITEM_NO NUMBER(18,0),
	ITEM_DESCRIPTION VARCHAR(30),
	STOCK_DETAILS_PROMO_IND VARCHAR(100),
	STOCK_DETAILS_VENDOR NUMBER(18,0),
	STOCK_DETAILS_VENDOR_DESCRIPTION VARCHAR(30),
	STOCK_DETAILS_SUB_VENDOR NUMBER(18,0),
	STOCK_DETAILS_LEAD_TIME NUMBER(18,0),
	STOCK_DETAILS_BUYER_NUMBER VARCHAR(100),
	STOCK_DETAILS_BUYER_NAME VARCHAR(30),
	STOCK_DETAILS_STOCK_CONTROL_EMAIL VARCHAR(30),
	STOCK_DETAILS_SOH NUMBER(18,0),
	STOCK_DETAILS_SOO NUMBER(18,0),
	STOCK_DETAILS_AWD NUMBER(10,5),
	STOCK_DETAILS_WEEKS_COVER NUMBER(10,5),
	INBOUND_ORDERED_CASES NUMBER(18,0),
	INBOUND_RECEIVED_CASES NUMBER(18,0),
	INBOUND_PO_NUMBER VARCHAR(30),
	ITEM_DETAILS_ITEM_SUB_RANGE_CODE NUMBER(18,0),
	ITEM_DETAILS_ITEM_SUB_RANGE_DESCRIPTION VARCHAR(30),
	ITEM_DETAILS_PACK_SIZE NUMBER(18,0),
	ITEM_DETAILS_BUYING_MASTER_PACK NUMBER(18,0),
	ITEM_DETAILS_RETAIL_UNIT NUMBER(18,0),
	ITEM_DETAILS_BUY_IN_PALLET VARCHAR(100),
	ITEM_DETAILS_TI NUMBER(18,0),
	ITEM_DETAILS_HI NUMBER(18,0),
	ITEM_DETAILS_PALLET NUMBER(18,0),
	ITEM_DETAILS_ITEM_STATUS VARCHAR(100),
	ITEM_DETAILS_DELETE_CODE VARCHAR(100),
	ITEM_DETAILS_DELETION_DATE VARCHAR(100),
	ITEM_DETAILS_METCASH_ITEM_TYPE VARCHAR(100),
	ITEM_DETAILS_ORD_SPLIT_CAT_CODE VARCHAR(100),
	ITEM_DETAILS_NDC_ITEM VARCHAR(100),
	ITEM_DETAILS_IMPORTED_GOODS VARCHAR(100),
	ITEM_DETAILS_CODE_DATE VARCHAR(100),
	ITEM_DETAILS_PACKED_ON_DATE VARCHAR(100),
	ITEM_DETAILS_INCREMENTAL_DAYS NUMBER(18,0),
	ITEM_DETAILS_MAX_SHELF_DAYS NUMBER(18,0),
	ITEM_DETAILS_RECEIVING_LIMIT NUMBER(18,0),
	ITEM_DETAILS_DISPATCH_LIMIT NUMBER(18,0),
	ITEM_DETAILS_CURRENT_DD NUMBER(10,5),
	ITEM_DETAILS_DATE_ADDED_TO_OG VARCHAR(100),
	ITEM_DETAILS_CONSUMER_GTIN NUMBER(18,0),
	ITEM_DETAILS_INNER_GTIN NUMBER(18,0),
	ITEM_DETAILS_OUTER_GTIN NUMBER(18,0),
	SALES_WEEK_6 NUMBER(18,0),
	SALES_WEEK_100 NUMBER(18,0),
	SALES_WEEK_4 NUMBER(18,0),
	SALES_WEEK_3 NUMBER(18,0),
	SALES_WEEK_2 NUMBER(18,0),
	SALES_WEEK_1 NUMBER(18,0),
	SALES_THIS_WEEK NUMBER(18,0),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS SDL_DSTR_WOOLWORTH_INV_RAW (
	INV_DATE VARCHAR(20),
	RANK VARCHAR(10),
	ARTICLE_CODE VARCHAR(20),
	ARTICLEDESC VARCHAR(100),
	MM_CODE VARCHAR(20),
	MM_NAME VARCHAR(50),
	CM_CODE VARCHAR(20),
	CM_NAME VARCHAR(50),
	RM_CODE VARCHAR(20),
	RM_NAME VARCHAR(20),
	REP_CODE VARCHAR(20),
	REPLENISHER VARCHAR(50),
	GOODS_SUPPLIER_CODE VARCHAR(100),
	GOODS_SUPPLIER_NAME VARCHAR(100),
	LT VARCHAR(20),
	DC_CODE VARCHAR(50),
	ACD VARCHAR(50),
	RP_TYPE VARCHAR(100),
	ALC_STATUS VARCHAR(100),
	OM VARCHAR(50),
	VP VARCHAR(50),
	TI VARCHAR(50),
	HI VARCHAR(50),
	WW_STORES VARCHAR(100),
	SL_PERC VARCHAR(100),
	SL_MISSED_VALUE VARCHAR(100),
	SOH_OMS VARCHAR(100),
	SOO_OMS VARCHAR(100),
	SOH_PRICE VARCHAR(100),
	DEMAND_OMS VARCHAR(100),
	ISSUES_OMS VARCHAR(100),
	NOT_SUPPLIED_OMS VARCHAR(100),
	FAIRSHARE_OMS VARCHAR(100),
	OVERLAY_OMS VARCHAR(100),
	AWD_OMS VARCHAR(100),
	AVG_ISSUES VARCHAR(100),
	DOS_OMS VARCHAR(100),
	DUE_DATE VARCHAR(100),
	REASON VARCHAR(100),
	OOS_COMMENTS VARCHAR(200),
	OOS_28_DAYS VARCHAR(100),
	CONS_DAYS_OOS VARCHAR(100),
	TOTAL_WHOLESALE_DEMAND_OM VARCHAR(100),
	TOTAL_WHOLESALE_ISSUE_OM VARCHAR(100),
	WHOLESALE_FLAG VARCHAR(100),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS SDL_API_DSTR_RAW (
	INVT_DT VARCHAR(50),
	ARTICLE_ID VARCHAR(50),
	ARTICLE_DESC VARCHAR(100),
	PRODUCT_EAN VARCHAR(50),
	SITE_ID VARCHAR(50),
	SITE_DESC VARCHAR(100),
	VENDOR VARCHAR(50),
	VENDOR_DESC VARCHAR(100),
	PRODUCT_SAP_ID VARCHAR(50),
	COST_PRICE NUMBER(10,4),
	CROSS_SITE_STATUS VARCHAR(100),
	MONTH_13 NUMBER(10,4),
	MONTH_12 NUMBER(10,4),
	MONTH_11 NUMBER(10,4),
	MONTH_10 NUMBER(10,4),
	MONTH_09 NUMBER(10,4),
	MONTH_08 NUMBER(10,4),
	MONTH_07 NUMBER(10,4),
	MONTH_06 NUMBER(10,4),
	MONTH_05 NUMBER(10,4),
	MONTH_04 NUMBER(10,4),
	MONTH_03 NUMBER(10,4),
	MONTH_02 NUMBER(10,4),
	MONTH_01 NUMBER(10,4),
	NULL_COLOUMN VARCHAR(10),
	MTH_TOTAL_INVOICED_QTY NUMBER(10,4),
	SOH_QTY NUMBER(10,4),
	DC_SOO_QTY NUMBER(10,4),
	SO_BACKORDER_QTY NUMBER(10,4),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS SDL_CHS_DSTR_RAW (
	INV_DT VARCHAR(30),
	WAREHOUSE VARCHAR(255),
	PRODUCT_CODE VARCHAR(255),
	PRODUCT_DESC VARCHAR(255),
	SUPPLIER_PRODUCT_CODE VARCHAR(255),
	PRIMARY_GTIN VARCHAR(255),
	ABC_CODE VARCHAR(255),
	STATUS VARCHAR(255),
	LAST_COST NUMBER(10,4),
	SOH_QTY NUMBER(10,4),
	SOH_AMT NUMBER(10,4),
	SOO_QTY NUMBER(10,4),
	SOO_AMT NUMBER(10,4),
	BACK_ORDER_QTY NUMBER(10,4),
	MONTH_01 NUMBER(10,4),
	MONTH_02 NUMBER(10,4),
	MONTH_03 NUMBER(10,4),
	MONTH_04 NUMBER(10,4),
	MONTH_05 NUMBER(10,4),
	MONTH_06 NUMBER(10,4),
	MONTH_07 NUMBER(10,4),
	MONTH_08 NUMBER(10,4),
	MONTH_09 NUMBER(10,4),
	MONTH_10 NUMBER(10,4),
	MONTH_11 NUMBER(10,4),
	MONTH_12 NUMBER(10,4),
	CRTD_DTM TIMESTAMP_NTZ(9)
);
CREATE TABLE IF NOT EXISTS SDL_DSTR_COLES_INV_RAW (
	VENDOR VARCHAR(50),
	VENDOR_NAME VARCHAR(100),
	DC_STATE_SHRT_DESC VARCHAR(100),
	DC_STATE_DESC VARCHAR(100),
	DC VARCHAR(50),
	DC_DESC VARCHAR(200),
	CATEGORY VARCHAR(100),
	CATEGORY_DESC VARCHAR(200),
	ORDER_ITEM VARCHAR(50),
	ORDER_ITEM_DESC VARCHAR(200),
	EAN VARCHAR(100),
	INV_DATE VARCHAR(20),
	CLOSING_SOH_NIC VARCHAR(100),
	CLOSING_SOH_QTY_CTNS VARCHAR(100),
	CLOSING_SOH_QTY_OCTNS VARCHAR(100),
	CLOSING_SOH_QTY_UNIT VARCHAR(100),
	DC_DAYS_ON_HAND VARCHAR(100),
	CRTD_DT TIMESTAMP_NTZ(9)
);
CREATE TABLE IF NOT EXISTS SDL_RAW_IRI_SCAN_SALES (
	IRI_MARKET VARCHAR(255),
	WK_END_DT VARCHAR(100),
	IRI_PROD_DESC VARCHAR(255),
	IRI_EAN VARCHAR(100),
	SCAN_SALES NUMBER(20,4),
	SCAN_UNITS NUMBER(20,4),
	AC_NIELSENCODE VARCHAR(100),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS SDL_RAW_METCASH_IND_GROCERY (
	SUPP_ID VARCHAR(20),
	SUPP_NAME VARCHAR(50),
	STATE VARCHAR(50),
	BANNER_ID VARCHAR(10),
	BANNER VARCHAR(50),
	CUSTOMER_ID VARCHAR(20),
	CUSTOMER VARCHAR(50),
	PRODUCT_ID VARCHAR(20),
	PRODUCT VARCHAR(50),
	GROSS_SALES_WK1 VARCHAR(20),
	GROSS_SALES_WK2 VARCHAR(20),
	GROSS_SALES_WK3 VARCHAR(20),
	GROSS_SALES_WK4 VARCHAR(20),
	GROSS_SALES_WK5 VARCHAR(20),
	GROSS_CASES_WK1 VARCHAR(20),
	GROSS_CASES_WK2 VARCHAR(20),
	GROSS_CASES_WK3 VARCHAR(20),
	GROSS_CASES_WK4 VARCHAR(20),
	GROSS_CASES_WK5 VARCHAR(20),
	RUN_ID VARCHAR(20),
	FILE_NAME VARCHAR(100),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_OVER_AND_ABOVE_POINTS (
	DISPLAY_TYPE VARCHAR(256),
	POINTS NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PACIFIC_PERENSO_CALL_COVERAGE_TARGETS (
	ACCOUNT_TYPE_DESCRIPTION VARCHAR(256),
	ACCOUNT_GRADE VARCHAR(50),
	WEEKLY_TARGETS NUMBER(10,0),
	MONTHLY_TARGETS NUMBER(10,0),
	YEARLY_TARGETS NUMBER(10,3),
	CALL_PER_WEEK NUMBER(10,5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT (
	ACCT_KEY NUMBER(10,0),
	DISP_NAME VARCHAR(256),
	ACCT_TYPE_KEY NUMBER(10,0),
	ACTIVE VARCHAR(10),
	ACCT_STREET1 VARCHAR(256),
	ACCT_STREET2 VARCHAR(256),
	ACCT_STREET3 VARCHAR(256),
	ACCT_SUBURB VARCHAR(25),
	ACCT_POSTCODE VARCHAR(25),
	ACCT_STATECODE VARCHAR(20),
	ACCT_STATE VARCHAR(20),
	ACCT_COUNTRY VARCHAR(20),
	ACCT_PHONE VARCHAR(50),
	ACCT_FAX VARCHAR(50),
	ACCT_EMAIL VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_CUSTOM_LIST (
	ACCT_KEY NUMBER(10,0),
	FIELD_KEY NUMBER(10,0),
	OPTION_DESC VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_FIELDS (
	FIELD_KEY NUMBER(10,0),
	FIELD_DESC VARCHAR(100),
	FIELD_TYPE NUMBER(10,0),
	ACCT_TYPE_KEY NUMBER(10,0),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_GROUP (
	ACCT_GRP_KEY NUMBER(10,0),
	ACCT_GRP_LEV_KEY NUMBER(10,0),
	GRP_DESC VARCHAR(256),
	DSP_ORDER NUMBER(10,0),
	PARENT_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_GROUP_LVL (
	ACCT_GRP_LEV_KEY NUMBER(10,0),
	ACCT_LEV_DESC VARCHAR(100),
	ACCT_LEV_INDEX NUMBER(10,0),
	FIELD_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_GROUP_RELN (
	ACCT_KEY NUMBER(10,0),
	ACCT_GRP_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_RELN_ID (
	ACCT_KEY NUMBER(10,0),
	FIELD_KEY NUMBER(10,0),
	ID VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCOUNT_TYPE (
	ACCT_TYPE_KEY NUMBER(10,0),
	ACCT_TYPE_DESC VARCHAR(50),
	DSP_ORDER NUMBER(2,0),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ACCT_DIST_ACCT (
	ACCT_KEY NUMBER(10,0),
	BRANCH_KEY NUMBER(10,0),
	ID VARCHAR(10),
	SYSTEM_PRIMARY VARCHAR(10),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_CALL_OBJECTIVES (
	OBJECTIVE_KEY VARCHAR(50),
	CALL_CREATED_DT VARCHAR(50),
	DESCRIPTION VARCHAR(255),
	ACCT_KEY VARCHAR(50),
	ASSIGNED_USER_KEY VARCHAR(50),
	CREATED_USER_KEY VARCHAR(50),
	DUE_DT VARCHAR(50),
	COMPLETED_DT VARCHAR(50),
	STATUS VARCHAR(50),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_CONSTANTS (
	CONST_KEY NUMBER(10,0),
	CONST_DESC VARCHAR(255),
	CONST_TYPE NUMBER(10,0),
	DSPORDER NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_DEAL_DISCOUNT (
	DEAL_KEY NUMBER(10,0),
	DEAL_DESC VARCHAR(255),
	START_DATE VARCHAR(255),
	END_DATE VARCHAR(255),
	SHORT_DESC VARCHAR(255),
	DISC_KEY NUMBER(10,0),
	DISCOUNT_DESC VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_DIARY_ITEM (
	DIARY_ITEM_KEY NUMBER(10,0),
	DIARY_ITEM_TYPE_KEY NUMBER(10,0),
	START_TIME VARCHAR(255),
	END_TIME VARCHAR(255),
	ACCT_KEY NUMBER(10,0),
	ACCT_KEY_1 NUMBER(10,0),
	CREATE_USER_KEY NUMBER(10,0),
	COMPLETE VARCHAR(5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_DIARY_ITEM_TIME (
	DIARY_ITEM_KEY VARCHAR(50),
	DATE_TIME VARCHAR(50),
	START_TIME VARCHAR(50),
	END_TIME VARCHAR(50),
	DURATION VARCHAR(50),
	LATITUDE VARCHAR(50),
	LONGITUDE VARCHAR(50),
	GOOGLE_MAPS_URL VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_DIARY_ITEM_TYPE (
	DIARY_ITEM_TYPE_KEY NUMBER(14,0),
	DIARY_ITEM_TYPE_DESC VARCHAR(255),
	DSP_ORDER NUMBER(14,0),
	ACTIVE VARCHAR(5),
	CATEGORY NUMBER(14,0),
	COUNT_IN_CALL_RATE VARCHAR(5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_DISTRIBUTOR_DETAIL (
	DIST_KEY NUMBER(10,0),
	DISTRIBUTOR VARCHAR(255),
	DIST_ID VARCHAR(255),
	BRANCH_KEY NUMBER(10,0),
	DISPLAY_NAME VARCHAR(255),
	SHORT_NAME VARCHAR(255),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_FSNI_SALES (
	SITE VARCHAR(100),
	VENDOR_ID VARCHAR(20),
	VENDOR_NAME VARCHAR(100),
	DEPARTMENT VARCHAR(50),
	MERCHANDISE_GROUP VARCHAR(50),
	ARTICLE VARCHAR(30),
	ARTICLE_DESCRIPTION VARCHAR(100),
	RETAIL_BARCODE VARCHAR(30),
	BANNER VARCHAR(50),
	STORE_NUMBER VARCHAR(20),
	STORE_NAME VARCHAR(100),
	BILLING_DOCUMENT VARCHAR(30),
	BILLING_DATE VARCHAR(20),
	PRICING_DATE VARCHAR(20),
	NET_SALES NUMBER(10,2),
	QTY_IN_SALES NUMBER(18,0),
	SALES_UOM VARCHAR(10),
	QTY_IN_BASE NUMBER(18,0),
	BASE_UOM VARCHAR(10),
	FILE_NAME VARCHAR(100),
	CRT_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_FSSI_SALES (
	ARTICLE VARCHAR(30),
	ARTICLE_DESCRIPTION VARCHAR(150),
	OLD_ARTICLE_NUM VARCHAR(30),
	EAN VARCHAR(30),
	GROSS_WEIGHT VARCHAR(20),
	SHIP_TO_STORE VARCHAR(20),
	STORE_NAME VARCHAR(100),
	SALES_VOLUME NUMBER(18,0),
	SALES_VALUE NUMBER(10,2),
	FILE_NAME VARCHAR(100),
	CRT_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_HEAD_OFFICE_REQ_CHECK (
	STORE_CHK_HDR_KEY NUMBER(10,0),
	TODO_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	NOTES VARCHAR(256),
	FAIL_REASON_KEY VARCHAR(256),
	FAIL_REASON_DESC VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_HEAD_OFFICE_REQ_STATE (
	ACCT_KEY NUMBER(10,0),
	TODO_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	START_DATE VARCHAR(255),
	END_DATE VARCHAR(255),
	REQ_STATE NUMBER(10,0),
	STORE_CHK_HDR_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ORDER_BATCH (
	ORD_KEY NUMBER(10,0),
	BATCH_KEY NUMBER(10,0),
	BRANCH_KEY NUMBER(10,0),
	DIST_ACCT VARCHAR(100),
	DELVRY_DT VARCHAR(255),
	STATUS NUMBER(10,0),
	SUFFIX VARCHAR(10),
	SENT_DT VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ORDER_DETAIL (
	ORDER_KEY NUMBER(10,0),
	BATCH_KEY NUMBER(10,0),
	LINE_KEY NUMBER(10,0),
	PROD_KEY NUMBER(10,0),
	UNIT_QTY NUMBER(10,0),
	ENTERED_QTY NUMBER(10,0),
	ENTERED_UNIT_KEY NUMBER(10,0),
	LIST_PRICE NUMBER(10,2),
	NIS NUMBER(10,2),
	RRP NUMBER(10,2),
	DISC_KEY NUMBER(10,0),
	CREDIT_LINE_KEY NUMBER(10,0),
	CREDITED VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ORDER_HEADER (
	ORDER_KEY NUMBER(10,0),
	ORDER_TYPE_KEY NUMBER(10,0),
	ACCT_KEY NUMBER(10,0),
	ORDER_DATE VARCHAR(255),
	STATUS NUMBER(10,0),
	CHARGE VARCHAR(256),
	CONFIRMATION VARCHAR(256),
	DIARY_ITEM_KEY NUMBER(10,0),
	WORK_ITEM_KEY NUMBER(10,0),
	ACCOUNT_ORDER_NO VARCHAR(256),
	DELVRY_INSTNS VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_ORDER_TYPE (
	ORDER_TYPE_KEY NUMBER(10,0),
	ORDER_TYPE_DESC VARCHAR(255),
	SOURCE NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_OVER_AND_ABOVE (
	OVER_AND_ABOVE_KEY NUMBER(10,0),
	ACCT_KEY NUMBER(10,0),
	TODO_OPTION_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	ACTIVATED VARCHAR(10),
	NOTES VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_OVER_AND_ABOVE_STATE (
	OVER_AND_ABOVE_KEY NUMBER(10,0),
	START_DATE VARCHAR(100),
	END_DATE VARCHAR(100),
	BATCH_COUNT NUMBER(10,0),
	STORE_CHK_HDR_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT (
	PROD_KEY NUMBER(10,0),
	PROD_ID VARCHAR(50),
	PROD_DESC VARCHAR(100),
	PROD_EAN VARCHAR(50),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT_FIELDS (
	FIELD_KEY NUMBER(10,0),
	FIELD_DESC VARCHAR(100),
	FIELD_TYPE NUMBER(10,0),
	ACTIVE VARCHAR(10),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT_GROUP (
	PROD_GRP_KEY NUMBER(10,0),
	PROD_GRP_LEV_KEY NUMBER(10,0),
	PROD_GRP_DESC VARCHAR(100),
	DSP_ORDER NUMBER(10,0),
	PARENT_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT_GROUP_LVL (
	PROD_GRP_LEV_KEY NUMBER(10,0),
	PROD_LEV_DESC VARCHAR(100),
	PROD_LEV_INDEX NUMBER(10,0),
	FIELD_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT_GROUP_RELN (
	PROD_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PRODUCT_RELN_ID (
	PROD_KEY NUMBER(10,0),
	FIELD_KEY NUMBER(10,0),
	ID VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PROD_BRANCH_IDENTIFIER (
	PROD_KEY NUMBER(10,0),
	BRANCH_KEY NUMBER(10,0),
	IDENTIFIER VARCHAR(250),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_PROD_CHK_DISTRIBUTION (
	ACCT_KEY NUMBER(10,0),
	PROD_KEY NUMBER(10,0),
	START_DATE VARCHAR(100),
	END_DATE VARCHAR(100),
	IN_DISTRIBUTION VARCHAR(5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_RANGING (
	RANGING_KEY NUMBER(10,0),
	RANGING_DESC VARCHAR(255),
	ACCT_GRP_LEV_KEY NUMBER(10,0),
	ACTIVE VARCHAR(5),
	ALL_ACCOUNTS VARCHAR(5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_RANGING_ACCT_GRP_REL (
	RANGING_KEY NUMBER(10,0),
	ACCT_GRP_KEY NUMBER(10,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_RANGING_PRODUCT (
	RANGING_KEY NUMBER(10,0),
	PROD_KEY NUMBER(10,0),
	ACCT_GRP_KEY NUMBER(10,0),
	CORE VARCHAR(5),
	RANGE_RANK VARCHAR(500),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9)
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_STORE_CHK_HDR (
	STORE_CHK_HDR_KEY NUMBER(10,0),
	DIARY_ITEM_KEY NUMBER(10,0),
	ACCT_KEY NUMBER(10,0),
	WORK_ITEM_KEY NUMBER(10,0),
	STORE_CHK_DATE VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_SURVEY_RESULT (
	STORE_CHK_HDR_KEY NUMBER(10,0),
	LINE_KEY NUMBER(10,0),
	TODO_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	OPTIONANS NUMBER(10,0),
	NOTESANS VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_TODO (
	TODO_KEY NUMBER(10,0),
	TODO_TYPE NUMBER(10,0),
	TODO_DESC VARCHAR(255),
	WORK_ITEM_KEY NUMBER(10,0),
	START_DATE VARCHAR(255),
	END_DATE VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	DSP_ORDER NUMBER(10,0),
	ANS_TYPE NUMBER(10,0),
	CASCADEON_ANSWERMODE NUMBER(10,0),
	CASCADE_TODO_KEY NUMBER(10,0),
	CASCADE_NEXT_TODO_KEY NUMBER(10,0)
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_TODO_OPTION (
	OPTION_KEY NUMBER(10,0),
	TODO_KEY NUMBER(10,0),
	OPTION_DESC VARCHAR(256),
	DSP_ORDER NUMBER(14,0),
	ACTIVE VARCHAR(5),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	CASCADE_NEXT_TODO_KEY NUMBER(10,0),
	CASCADEON_ANSWERMODE NUMBER(10,0)
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_USERS (
	USER_KEY NUMBER(10,0),
	DISPLAY_NAME VARCHAR(100),
	USER_TYPE_KEY NUMBER(10,0),
	USER_TYPE_DESC VARCHAR(100),
	ACTIVE VARCHAR(5),
	EMAIL_ADDRESS VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_PERENSO_WORK_ITEM (
	WORK_ITEM_KEY NUMBER(10,0),
	WORK_ITEM_DESC VARCHAR(255),
	WORK_ITEM_TYPE NUMBER(10,0),
	DIARY_ITEM_TYPE_KEY NUMBER(10,0),
	START_DATE VARCHAR(255),
	END_DATE VARCHAR(255),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_SURVEY_PRODUCT_GRP_TO_CATEGORY_MAP (
	CATEGORY VARCHAR(256),
	QUESTION_PRODUCT_GROUP VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_SURVEY_TARGETS (
	YEAR VARCHAR(256),
	CYCLE_START_DATE VARCHAR(256),
	CYCLE_END_DATE VARCHAR(256),
	ACCOUNT_TYPE_DESCRIPTION VARCHAR(256),
	TARGET_TYPE VARCHAR(256),
	CATEGORY VARCHAR(256),
	TERRITORY_REGION VARCHAR(256),
	TERRITORY VARCHAR(256),
	TARGET NUMBER(20,0),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
CREATE TABLE IF NOT EXISTS SDL_RAW_SURVEY_TYPE_TO_QUESTION_MAP (
	ACCOUNT_TYPE_DESCRIPTION VARCHAR(256),
	TARGET_TYPE VARCHAR(256),
	PERENSO_QUESTIONS VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
