USE DATABASE PROD_DNA_CORE;
USE schema ASPEDW_ACCESS;

create or replace view EDW_PERFECT_STORE_REBASE_WT(
	"hashkey",
	"hash_row",
	"dataset",
	"customerid",
	"salespersonid",
	"visitid",
	"questiontext",
	"productid",
	"kpi",
	"scheduleddate",
	"latestdate",
	"fiscal_year",
	"fiscal_month",
	"merchandiser_name",
	"customername",
	"country",
	"state",
	"parent_customer",
	"retail_environment",
	"channel",
	"retailer",
	"business_unit",
	"eannumber",
	"matl_num",
	"prod_hier_l1",
	"prod_hier_l2",
	"prod_hier_l3",
	"prod_hier_l4",
	"prod_hier_l5",
	"prod_hier_l6",
	"prod_hier_l7",
	"prod_hier_l8",
	"prod_hier_l9",
	"ques_type",
	"y/n_flag",
	"priority_store_flag",
	"add_info",
	"response",
	"response_score",
	"kpi_chnl_wt",
	"channel_weightage",
	"weight_msl",
	"weight_oos",
	"weight_soa",
	"weight_sos",
	"weight_promo",
	"weight_planogram",
	"weight_display",
	"mkt_share",
	"salience_val",
	"actual_value",
	"ref_value",
	"kpi_actual_wt_val",
	"kpi_ref_val",
	"kpi_ref_wt_val",
	"photo_url",
	"compliance",
	"gap_to_target",
	"compliance_propogated",
	"gap_propagated",
	"full_opportunity_lcy",
	"weighted_opportunity_lcy",
	"full_opportunity_usd",
	"weighted_opportunity_usd",
	"sotp_lcy",
	"sotp_usd",
	"store_grade"
) as
SELECT
    hashkey AS "hashkey",
    hash_row AS "hash_row",
    dataset AS "dataset",
    customerid AS "customerid",
    salespersonid AS "salespersonid",
    visitid AS "visitid",
    questiontext AS "questiontext",
    productid AS "productid",
    kpi AS "kpi",
    scheduleddate AS "scheduleddate",
    latestdate AS "latestdate",
    fisc_yr AS "fiscal_year",
    fisc_per AS "fiscal_month",
    merchandiser_name AS "merchandiser_name",
    customername AS "customername",
    country AS "country",
    state AS "state",
    parent_customer AS "parent_customer",
    retail_environment AS "retail_environment",
    channel AS "channel",
    retailer AS "retailer",
    business_unit AS "business_unit",
    eannumber AS "eannumber",
    matl_num AS "matl_num",
    prod_hier_l1 AS "prod_hier_l1",
    prod_hier_l2 AS "prod_hier_l2",
    prod_hier_l3 AS "prod_hier_l3",
    prod_hier_l4 AS "prod_hier_l4",
    prod_hier_l5 AS "prod_hier_l5",
    prod_hier_l6 AS "prod_hier_l6",
    prod_hier_l7 AS "prod_hier_l7",
    prod_hier_l8 AS "prod_hier_l8",
    prod_hier_l9 AS "prod_hier_l9",
    ques_type AS "ques_type",
    "y/n_flag" AS "y/n_flag",
    priority_store_flag AS "priority_store_flag",
    add_info AS "add_info",
    response AS "response",
    response_score AS "response_score",
    kpi_chnl_wt AS "kpi_chnl_wt",
    channel_weightage AS "channel_weightage",
    weight_msl AS "weight_msl",
    weight_oos AS "weight_oos",
    weight_soa AS "weight_soa",
    weight_sos AS "weight_sos",
    weight_promo AS "weight_promo",
    weight_planogram AS "weight_planogram",
    weight_display AS "weight_display",
    mkt_share AS "mkt_share",
    salience_val AS "salience_val",
    actual_value AS "actual_value",
    ref_value AS "ref_value",
    kpi_actual_wt_val AS "kpi_actual_wt_val",
    kpi_ref_val AS "kpi_ref_val",
    kpi_ref_wt_val AS "kpi_ref_wt_val",
    photo_url AS "photo_url",
    compliance AS "compliance",
    gap_to_target AS "gap_to_target",
    compliance_propogated AS "compliance_propogated",
    gap_propagated AS "gap_propagated",
    full_opportunity_lcy AS "full_opportunity_lcy",
    weighted_opportunity_lcy AS "weighted_opportunity_lcy",
    full_opportunity_usd AS "full_opportunity_usd",
    weighted_opportunity_usd AS "weighted_opportunity_usd",
    sotp_lcy AS "sotp_lcy",
    sotp_usd AS "sotp_usd",
    store_grade AS "store_grade"
FROM PROD_DNA_CORE.ASPEDW_INTEGRATION.EDW_PERFECT_STORE_REBASE_WT;




create or replace view EDW_RPT_REGIONAL_SELLOUT_OFFTAKE(
	"year",
	"qrtr_no",
	"mnth_id",
	"mnth_no",
	"cal_date",
	"week_start_date",
	"univ_year",
	"univ_month",
	"country_code",
	"country_name",
	"data_source",
	"soldto_code",
	"distributor_code",
	"distributor_name",
	"store_code",
	"store_name",
	"store_type",
	"distributor_additional_attribute1",
	"distributor_additional_attribute2",
	"distributor_additional_attribute3",
	"sap_parent_customer_key",
	"sap_parent_customer_description",
	"sap_customer_channel_key",
	"sap_customer_channel_description",
	"sap_customer_sub_channel_key",
	"sap_sub_channel_description",
	"sap_go_to_mdl_key",
	"sap_go_to_mdl_description",
	"sap_banner_key",
	"sap_banner_description",
	"sap_banner_format_key",
	"sap_banner_format_description",
	"retail_environment",
	"region",
	"zone_or_area",
	"customer_segment_key",
	"customer_segment_description",
	"global_product_franchise",
	"global_product_brand",
	"global_product_sub_brand",
	"global_product_variant",
	"global_product_segment",
	"global_product_subsegment",
	"global_product_category",
	"global_product_subcategory",
	"global_put_up_description",
	"ean",
	"sku_code",
	"sku_description",
	"pka_product_key",
	"pka_product_key_description",
	"from_currency",
	"to_currency",
	"exchange_rate",
	"sellout_sales_quantity",
	"sellout_sales_value",
	"sellout_sales_value_usd",
	"list_price",
	"sellout_value_list_price",
	"sellout_value_list_price_usd",
	"selling_price",
	"first_scan_flag_parent_customer_level",
	"first_scan_flag_market_level",
	"npd_flag_market_level",
	"npd_flag_parent_customer_level",
	"customer_product_desc",
	"crtd_dttm",
	"updt_dttm"
) as
SELECT
    year AS "year",
    qrtr_no AS "qrtr_no",
    mnth_id AS "mnth_id",
    mnth_no AS "mnth_no",
    cal_date AS "cal_date",
    week_start_date AS "week_start_date",
    univ_year AS "univ_year",
    univ_month AS "univ_month",
    country_code AS "country_code",
    country_name AS "country_name",
    data_source AS "data_source",
    soldto_code AS "soldto_code",
    distributor_code AS "distributor_code",
    distributor_name AS "distributor_name",
    store_code AS "store_code",
    store_name AS "store_name",
    store_type AS "store_type",
    distributor_additional_attribute1 AS "distributor_additional_attribute1",
    distributor_additional_attribute2 AS "distributor_additional_attribute2",
    distributor_additional_attribute3 AS "distributor_additional_attribute3",
    sap_parent_customer_key AS "sap_parent_customer_key",
    sap_parent_customer_description AS "sap_parent_customer_description",
    sap_customer_channel_key AS "sap_customer_channel_key",
    sap_customer_channel_description AS "sap_customer_channel_description",
    sap_customer_sub_channel_key AS "sap_customer_sub_channel_key",
    sap_sub_channel_description AS "sap_sub_channel_description",
    sap_go_to_mdl_key AS "sap_go_to_mdl_key",
    sap_go_to_mdl_description AS "sap_go_to_mdl_description",
    sap_banner_key AS "sap_banner_key",
    sap_banner_description AS "sap_banner_description",
    sap_banner_format_key AS "sap_banner_format_key",
    sap_banner_format_description AS "sap_banner_format_description",
    retail_environment AS "retail_environment",
    region AS "region",
    zone_or_area AS "zone_or_area",
    customer_segment_key AS "customer_segment_key",
    customer_segment_description AS "customer_segment_description",
    global_product_franchise AS "global_product_franchise",
    global_product_brand AS "global_product_brand",
    global_product_sub_brand AS "global_product_sub_brand",
    global_product_variant AS "global_product_variant",
    global_product_segment AS "global_product_segment",
    global_product_subsegment AS "global_product_subsegment",
    global_product_category AS "global_product_category",
    global_product_subcategory AS "global_product_subcategory",
    global_put_up_description AS "global_put_up_description",
    ean AS "ean",
    sku_code AS "sku_code",
    sku_description AS "sku_description",
    pka_product_key AS "pka_product_key",
    pka_product_key_description AS "pka_product_key_description",
    from_currency AS "from_currency",
    to_currency AS "to_currency",
    exchange_rate AS "exchange_rate",
    sellout_sales_quantity AS "sellout_sales_quantity",
    sellout_sales_value AS "sellout_sales_value",
    sellout_sales_value_usd AS "sellout_sales_value_usd",
    list_price AS "list_price",
    sellout_value_list_price AS "sellout_value_list_price",
    sellout_value_list_price_usd AS "sellout_value_list_price_usd",
    selling_price AS "selling_price",
    first_scan_flag_parent_customer_level AS "first_scan_flag_parent_customer_level",
    first_scan_flag_market_level AS "first_scan_flag_market_level",
    npd_flag_market_level AS "npd_flag_market_level",
    npd_flag_parent_customer_level AS "npd_flag_parent_customer_level",
    customer_product_desc AS "customer_product_desc",
    crtd_dttm AS "crtd_dttm",
    updt_dttm AS "updt_dttm"
FROM PROD_DNA_CORE.ASPEDW_INTEGRATION.EDW_RPT_REGIONAL_SELLOUT_OFFTAKE;
