use database PROD_DNA_CORE;

CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ACCT_TEXT (
	CHRT_ACCT VARCHAR(4),
	ACCT_NUM VARCHAR(10),
	LANG_KEY VARCHAR(2),
	SHRT_DESC VARCHAR(5000),
	MED_DESC VARCHAR(5000),
	CRT_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9)
);

CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ACCOUNT_DIM (
	CHRT_ACCT VARCHAR(4) NOT NULL,
	ACCT_NUM VARCHAR(10) NOT NULL,
	ACCT_NM VARCHAR(5000),
	OBJ_VER VARCHAR(1) NOT NULL,
	CHG_FLG VARCHAR(1),
	BAL_FLAG VARCHAR(1),
	CSTEL_FLAG VARCHAR(1),
	GLACC_FLAG VARCHAR(1),
	SRC_SYS VARCHAR(10),
	SEM_POSIT VARCHAR(16),
	BRAVO_ACCT_L1 VARCHAR(18),
	BRAVO_ACCT_L2 VARCHAR(18),
	BRAVO_ACCT_L3 VARCHAR(18),
	BRAVO_ACCT_L4 VARCHAR(18),
	BRAVO_ACCT_L5 VARCHAR(18),
	FIN_STAT_ITM VARCHAR(18),
	CRT_DTTM TIMESTAMP_NTZ(9),
	UPDT_DTTM TIMESTAMP_NTZ(9),
	primary key (CHRT_ACCT, ACCT_NUM, OBJ_VER)
);


CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CUSTOMER_SEGMENTATION CLONE SNAPASPEDW_INTEGRATION.EDW_CUSTOMER_SEGMENTATION;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_PRODUCT_KEY_ATTRIBUTES CLONE SNAPASPEDW_INTEGRATION.EDW_PRODUCT_KEY_ATTRIBUTES;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_MATERIAL_UOM CLONE SNAPASPEDW_INTEGRATION.EDW_MATERIAL_UOM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_COMPANY_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_COMPANY_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CUSTOMER_BASE_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_CUSTOMER_BASE_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_PROFIT_CENTER_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_PROFIT_CENTER_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_SALES_ORG_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_SALES_ORG_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CRNCY_EXCH CLONE SNAPASPEDW_INTEGRATION.EDW_CRNCY_EXCH;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CODE_DESCRIPTIONS CLONE SNAPASPEDW_INTEGRATION.EDW_CODE_DESCRIPTIONS;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ECC_MARM CLONE SNAPASPEDW_INTEGRATION.EDW_ECC_MARM;
INSERT INTO ASPEDW_INTEGRATION.EDW_ACCOUNT_DIM SELECT * FROM SNAPASPEDW_INTEGRATION.EDW_ACCOUNT_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_MATERIAL_SALES_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_MATERIAL_SALES_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_PLANT_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_PLANT_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_MATERIAL_PLANT_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_MATERIAL_PLANT_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_SAP_BW_DNA_MATERIAL_BOMLIST CLONE SNAPASPEDW_INTEGRATION.EDW_SAP_BW_DNA_MATERIAL_BOMLIST;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ECC_STANDARD_COST CLONE SNAPASPEDW_INTEGRATION.EDW_ECC_STANDARD_COST;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_MATERIAL_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_MATERIAL_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_SAP_MATL_NUM_EAN_MAPPING CLONE SNAPASPEDW_INTEGRATION.EDW_SAP_MATL_NUM_EAN_MAPPING;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_LIST_PRICE CLONE SNAPASPEDW_INTEGRATION.EDW_LIST_PRICE;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_GCH_PRODUCTHIERARCHY CLONE SNAPASPEDW_INTEGRATION.EDW_GCH_PRODUCTHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_GCH_CUSTOMERHIERARCHY CLONE SNAPASPEDW_INTEGRATION.EDW_GCH_CUSTOMERHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_GCH_GEOGRAPHYHIERARCHY CLONE SNAPASPEDW_INTEGRATION.EDW_GCH_GEOGRAPHYHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_INVENTORY_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_INVENTORY_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_BILLING_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_BILLING_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_RG_TRAVEL_RETAIL CLONE SNAPASPEDW_INTEGRATION.EDW_RG_TRAVEL_RETAIL;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_COPA_TRANS_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_COPA_TRANS_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_COPA_PLAN_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_COPA_PLAN_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_INVOICE_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_INVOICE_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_DELIVERY_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_DELIVERY_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_SALES_ORDER_FACT CLONE SNAPASPEDW_INTEGRATION.EDW_SALES_ORDER_FACT;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CALENDAR_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_CALENDAR_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ACCOUNT_CIW_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_ACCOUNT_CIW_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_RPT_RG_TRAVEL_RETAIL CLONE SNAPASPEDW_INTEGRATION.EDW_RPT_RG_TRAVEL_RETAIL;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ECOMM_PLAN CLONE SNAPASPEDW_INTEGRATION.EDW_ECOMM_PLAN;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_PROFIT_CENTER_FRANCHISE_MAPPING CLONE SNAPASPEDW_INTEGRATION.EDW_PROFIT_CENTER_FRANCHISE_MAPPING;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CUSTOMER_SALES_DIM CLONE SNAPASPEDW_INTEGRATION.EDW_CUSTOMER_SALES_DIM;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_CODE_DESCRIPTIONS_MANUAL CLONE SNAPASPEDW_INTEGRATION.EDW_CODE_DESCRIPTIONS_MANUAL;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_DSTRBTN_CHNL CLONE SNAPASPEDW_INTEGRATION.EDW_DSTRBTN_CHNL;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_PROD_HIER CLONE SNAPASPEDW_INTEGRATION.EDW_PROD_HIER;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_MATERIAL_TYP CLONE SNAPASPEDW_INTEGRATION.EDW_MATERIAL_TYP;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_OKR_BRAND_MAP CLONE SNAPASPEDW_INTEGRATION.EDW_OKR_BRAND_MAP;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ACCOUNT_JJPLBW_HIER CLONE SNAPASPEDW_INTEGRATION.EDW_ACCOUNT_JJPLBW_HIER;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ACCOUNT_XREF CLONE SNAPASPEDW_INTEGRATION.EDW_ACCOUNT_XREF;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_SUBCHNL_RETAIL_ENV_MAPPING CLONE SNAPASPEDW_INTEGRATION.EDW_SUBCHNL_RETAIL_ENV_MAPPING;
CREATE TABLE IF NOT EXISTS ASPEDW_INTEGRATION.EDW_ACCOUNT_CIW_XREF CLONE SNAPASPEDW_INTEGRATION.EDW_ACCOUNT_CIW_XREF;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_INVNT CLONE SNAPASPITG_INTEGRATION.ITG_INVNT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ACCOUNT_ATTR_CIW CLONE SNAPASPITG_INTEGRATION.ITG_ACCOUNT_ATTR_CIW;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATERIAL_PKA_MARA_EXTRACT CLONE SNAPASPITG_INTEGRATION.ITG_MATERIAL_PKA_MARA_EXTRACT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CRNCY_MULT CLONE SNAPASPITG_INTEGRATION.ITG_CRNCY_MULT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SAP_BILLING_CONDITION CLONE SNAPASPITG_INTEGRATION.ITG_SAP_BILLING_CONDITION;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_LIST_PRICE CLONE SNAPASPITG_INTEGRATION.ITG_LIST_PRICE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_LOG CLONE SNAPASPITG_INTEGRATION.ITG_MDS_LOG;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_NTS_TARGET CLONE SNAPASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_NTS_TARGET;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CUST_SLS CLONE SNAPASPITG_INTEGRATION.ITG_CUST_SLS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_MATL_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_BASE_PROD_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_BASE_PROD_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_BRND_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_BRND_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_COMP CLONE SNAPASPITG_INTEGRATION.ITG_COMP;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_COMP_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_COMP_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CUST_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_CUST_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CUST_BASE CLONE SNAPASPITG_INTEGRATION.ITG_CUST_BASE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MEGA_BRND_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_MEGA_BRND_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SLS_ORG_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_SLS_ORG_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SLS_OFF_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_SLS_OFF_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SLS_ORG CLONE SNAPASPITG_INTEGRATION.ITG_SLS_ORG;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PRFT_CTR CLONE SNAPASPITG_INTEGRATION.ITG_PRFT_CTR;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_VARNT_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_VARNT_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CRNCY_EXCH CLONE SNAPASPITG_INTEGRATION.ITG_CRNCY_EXCH;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PRFT_CTR_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_PRFT_CTR_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PUT_UP_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_PUT_UP_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SLS_GRP_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_SLS_GRP_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_BASE CLONE SNAPASPITG_INTEGRATION.ITG_MATL_BASE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ECC_MARM CLONE SNAPASPITG_INTEGRATION.ITG_ECC_MARM;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_TIME CLONE SNAPASPITG_INTEGRATION.ITG_TIME;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CTRY_CD_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_CTRY_CD_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_NEEDSTATES_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_NEEDSTATES_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CODE_DESCRIPTIONS CLONE SNAPASPITG_INTEGRATION.ITG_CODE_DESCRIPTIONS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_STRONGHOLDS_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_STRONGHOLDS_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_DSTRBTN_CHNL CLONE SNAPASPITG_INTEGRATION.ITG_DSTRBTN_CHNL;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PROD_HIER CLONE SNAPASPITG_INTEGRATION.ITG_PROD_HIER;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATERIAL_TYP CLONE SNAPASPITG_INTEGRATION.ITG_MATERIAL_TYP;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATERIAL_DIM CLONE SNAPASPITG_INTEGRATION.ITG_MATERIAL_DIM;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CUST_SLS_ATTR CLONE SNAPASPITG_INTEGRATION.ITG_CUST_SLS_ATTR;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ACCT CLONE SNAPASPITG_INTEGRATION.ITG_ACCT;
INSERT INTO ASPITG_INTEGRATION.ITG_ACCT_TEXT SELECT * FROM SNAPASPITG_INTEGRATION.ITG_ACCT_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_PLNT CLONE SNAPASPITG_INTEGRATION.ITG_MATL_PLNT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_SLS CLONE SNAPASPITG_INTEGRATION.ITG_MATL_SLS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_PLNT_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_MATL_PLNT_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATL_SLS_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_MATL_SLS_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PLNT CLONE SNAPASPITG_INTEGRATION.ITG_PLNT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_PLNT_TEXT CLONE SNAPASPITG_INTEGRATION.ITG_PLNT_TEXT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SAP_BW_DNA_MATERIAL_BOMLIST CLONE SNAPASPITG_INTEGRATION.ITG_SAP_BW_DNA_MATERIAL_BOMLIST;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_PRE_APSC_MASTER CLONE SNAPASPITG_INTEGRATION.ITG_MDS_PRE_APSC_MASTER;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_GREENLIGHT_SKUS CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_GREENLIGHT_SKUS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_CHANNEL_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_CHANNEL_MAPPING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_PRODUCT_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_PRODUCT_MAPPING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CRNCY_CONV CLONE SNAPASPITG_INTEGRATION.ITG_CRNCY_CONV;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATERIAL_UOM CLONE SNAPASPITG_INTEGRATION.ITG_MATERIAL_UOM;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_ECOM_DIGITAL_SHELF_CUSTOMER_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_ECOM_DIGITAL_SHELF_CUSTOMER_MAPPING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_ECOM_PRODUCT CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_ECOM_PRODUCT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_SKU_BENCHMARKS CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_SKU_BENCHMARKS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_LOOKUP_CATEGORY_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_LOOKUP_CATEGORY_MAPPING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_SALES_OPS_MAP CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_SALES_OPS_MAP;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_DSO CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_DSO;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_ECOM_ONEVIEW_CONFIG CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_ECOM_ONEVIEW_CONFIG;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_PS_MARKET_COVERAGE CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_PS_MARKET_COVERAGE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_TIH_DISTRIBUTOR_CLOSURE CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_TIH_DISTRIBUTOR_CLOSURE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_SFMC_GENDER CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_SFMC_GENDER;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_RG_SFMC_ATTRIBUTES CLONE SNAPASPITG_INTEGRATION.ITG_MDS_RG_SFMC_ATTRIBUTES;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ECOM_DIGITAL_SALESWEIGHT CLONE SNAPASPITG_INTEGRATION.ITG_ECOM_DIGITAL_SALESWEIGHT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_OKR_ACTUALS CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_OKR_ACTUALS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_OKR_TARGETS CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_OKR_TARGETS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_COMPANY_DIM CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_COMPANY_DIM;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_CUSTOMER360_CONFIG CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_CUSTOMER360_CONFIG;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_CUSTGP_PORTFOLIO_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_MDS_CUSTGP_PORTFOLIO_MAPPING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_EDW_MATERIAL_DIM_UPDT CLONE SNAPASPITG_INTEGRATION.ITG_EDW_MATERIAL_DIM_UPDT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_ECC_STANDARD_COST CLONE SNAPASPITG_INTEGRATION.ITG_ECC_STANDARD_COST;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MATERIAL_BASE CLONE SNAPASPITG_INTEGRATION.ITG_MATERIAL_BASE;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_COPA17_TRANS CLONE SNAPASPITG_INTEGRATION.ITG_COPA17_TRANS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_COPA_TRANS CLONE SNAPASPITG_INTEGRATION.ITG_COPA_TRANS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_INVC_SLS CLONE SNAPASPITG_INTEGRATION.ITG_INVC_SLS;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_BILLING_FACT CLONE SNAPASPITG_INTEGRATION.ITG_BILLING_FACT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_DELIVERY_FACT CLONE SNAPASPITG_INTEGRATION.ITG_DELIVERY_FACT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_SALES_ORDER_FACT CLONE SNAPASPITG_INTEGRATION.ITG_SALES_ORDER_FACT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_SELLOUT CLONE SNAPASPITG_INTEGRATION.ITG_RG_TRAVEL_RETAIL_SELLOUT;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_OTIF_GLBL_CON_REPORTING CLONE SNAPASPITG_INTEGRATION.ITG_OTIF_GLBL_CON_REPORTING;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_MDS_AP_OTIF CLONE SNAPASPITG_INTEGRATION.ITG_MDS_AP_OTIF;
CREATE TABLE IF NOT EXISTS ASPITG_INTEGRATION.ITG_CIW_ACCT_HIER_NAME_MAPPING CLONE SNAPASPITG_INTEGRATION.ITG_CIW_ACCT_HIER_NAME_MAPPING;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ACCOUNT_ATTR_CIW CLONE SNAPASPWKS_INTEGRATION.WKS_ACCOUNT_ATTR_CIW;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_LIST_PRICE CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_LIST_PRICE;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_STRONGHOLDS_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_STRONGHOLDS_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_COPA_PLAN_FACT CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_COPA_PLAN_FACT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_COPA17_TRANS CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_COPA17_TRANS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_INVNT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_INVNT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_INVENTORY_FACT CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_INVENTORY_FACT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_COPA_TRANS CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_COPA_TRANS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_INVC_SLS CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_INVC_SLS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_INVC_FACT CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_INVC_FACT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CUST_SLS CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CUST_SLS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATL_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATL_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_BASE_PROD_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_BASE_PROD_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_BRND_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_BRND_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_COMP CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_COMP;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_COMPANY_CODE_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_COMPANY_CODE_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CUST_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CUST_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CUST_BASE CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CUST_BASE;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MEGA_BRND_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MEGA_BRND_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_SALES_ORG_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_SALES_ORG_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_SLS_OFF_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_SLS_OFF_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_SALES_ORG CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_SALES_ORG;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PRFT_CTR CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PRFT_CTR;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_VARNT_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_VARNT_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CRNCY_EXCH CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CRNCY_EXCH;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PRFT_CTR_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PRFT_CTR_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PUT_UP_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PUT_UP_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_SLS_GRP_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_SLS_GRP_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATL_BASE CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATL_BASE;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_COMPANY_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_COMPANY_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_CUSTOMER_BASE_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_CUSTOMER_BASE_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_PROFIT_CENTER_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_PROFIT_CENTER_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_SALES_ORG_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_SALES_ORG_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_CALENDAR_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_CALENDAR_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_CODE_DESCRIPTIONS CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_CODE_DESCRIPTIONS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_ECC_MARM CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_ECC_MARM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_ECC_MARM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_ECC_MARM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_TIME CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_TIME;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_COUNTRY_CODE_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_COUNTRY_CODE_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_NEEDSTATES_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_NEEDSTATES_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CODE_DESCRIPTIONS CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CODE_DESCRIPTIONS;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_DSTRBTN_CHNL CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_DSTRBTN_CHNL;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PROD_HIER CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PROD_HIER;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATERIAL_TYP CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATERIAL_TYP;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATERIAL_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATERIAL_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_CUST_SLS_ATTR CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_CUST_SLS_ATTR;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_ACCT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_ACCT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_ACCT_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_ACCT_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATL_PLNT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATL_PLNT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATERIAL_SALES CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATERIAL_SALES;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATL_PLNT_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATL_PLNT_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_MATL_SLS_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_MATL_SLS_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PLNT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PLNT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_ITG_PLANT_TEXT CLONE SNAPASPWKS_INTEGRATION.WKS_ITG_PLANT_TEXT;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_ACCOUNT_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_ACCOUNT_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_MATERIAL_SALES_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_MATERIAL_SALES_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_PLANT_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_PLANT_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_MATERIAL_PLANT_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_MATERIAL_PLANT_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_SAP_BW_DNA_MATERIAL_BOMLIST CLONE SNAPASPWKS_INTEGRATION.WKS_SAP_BW_DNA_MATERIAL_BOMLIST;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_GCH_PRODUCTHIERARCHY CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_GCH_PRODUCTHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_GCH_CUSTOMERHIERARCHY CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_GCH_CUSTOMERHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_GCH_GEOGRAPHYHIERARCHY CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_GCH_GEOGRAPHYHIERARCHY;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_CNSC CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_CNSC;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_DFS_HAINAN CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_DFS_HAINAN;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_DUFRY_HAINAN CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_DUFRY_HAINAN;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_LSTR CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_LSTR;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_INVENTORY_EXCL_SKU CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_INVENTORY_EXCL_SKU;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_INVENTORY CLONE SNAPASPWKS_INTEGRATION.WKS_RG_TRAVEL_RETAIL_INVENTORY;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_DSTRBTN_CHNL CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_DSTRBTN_CHNL;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_PROD_HIER CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_PROD_HIER;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_MATERIAL_TYP CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_MATERIAL_TYP;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_CUSTOMER_SALES_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_CUSTOMER_SALES_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_EDW_ECC_STANDARD_COST CLONE SNAPASPWKS_INTEGRATION.WKS_EDW_ECC_STANDARD_COST;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_MATERIAL_DIM CLONE SNAPASPWKS_INTEGRATION.WKS_MATERIAL_DIM;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_SDL_DSTRBTN_CHNL CLONE SNAPASPWKS_INTEGRATION.WKS_SDL_DSTRBTN_CHNL;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_SDL_PROD_HIER CLONE SNAPASPWKS_INTEGRATION.WKS_SDL_PROD_HIER;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_SDL_MATERIAL_TYP CLONE SNAPASPWKS_INTEGRATION.WKS_SDL_MATERIAL_TYP;
CREATE TABLE IF NOT EXISTS ASPWKS_INTEGRATION.WKS_APAC_DCL_TARGETS_HEADER CLONE SNAPASPWKS_INTEGRATION.WKS_APAC_DCL_TARGETS_HEADER;
