create or replace TABLE PROD_DNA_LOAD.NTASDL_RAW.SDL_KR_IQVIA_OFFTAKE_TEMP (
	AUDIT_CODE VARCHAR(255),
	DATA_PERIOD VARCHAR(255),
	PERIOD_YYYYMM VARCHAR(6),
	PRODUCT_NAME VARCHAR(500),
	PRODUCT_NAME_KOR VARCHAR(500),
	FORM_DESCRIPTION VARCHAR(255),
	PACK_SIZE VARCHAR(100),
	MOLECULE_DESC VARCHAR(500),
	MFR_NAME VARCHAR(255),
	MFR_NAME_KOR VARCHAR(255),
	MFR_TYPE VARCHAR(100),
	NHI_TYPE VARCHAR(100),
	CHC_1_CODE VARCHAR(50),
	CHC_1_DESC VARCHAR(255),
	CHC_2_CODE VARCHAR(50),
	CHC_2_DESC VARCHAR(255),
	CHC_3_CODE VARCHAR(50),
	CHC_3_DESC VARCHAR(255),
	CHC_4_CODE VARCHAR(50),
	CHC_4_DESC VARCHAR(255),
	ATC_1_CODE VARCHAR(50),
	ATC_1_DESC VARCHAR(255),
	ATC_2_CODE VARCHAR(50),
	ATC_2_DESC VARCHAR(255),
	ATC_3_CODE VARCHAR(50),
	ATC_3_DESC VARCHAR(255),
	ATC_4_CODE VARCHAR(50),
	ATC_4_DESC VARCHAR(255),
	UNITS FLOAT,
	PRICE FLOAT,
	VALUES_LC_SI_PRICE FLOAT,
	VALUES_LC_SO_PRICE FLOAT,
	FILE_NAME VARCHAR(255),
	CRTD_DTTM VARCHAR(255)
);




COPY INTO PROD_DNA_LOAD.NTASDL_RAW.SDL_KR_IQVIA_OFFTAKE_TEMP
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/kr_iqvia_offtake.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
