update META_RAW.parameters set parameter_value= 'TH_MT/transaction/BIG_C/source/' where parameter_id =3195;

update meta_raw.Parameters set parameter_value = 'TH_MDSPROD_to_SnowflakePROD' where parameter_id=2217;

INSERT INTO META_RAW.USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (55,'TH_PERFECT_STORE_TRANSACTION','TH_PERFECT_STORE','thailand perfect store load files','TRUE',1);


INSERT INTO META_RAW.PROCESS VALUES (171,171,'TH_Perfect_Store_Consumerreach_cvs',171,1,1,TRUE,TRUE,55,1,1,null,'','','','THASDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO META_RAW.PROCESS VALUES (172,172,'TH_Perfect_Store_Consumerreach_711',172,1,1,TRUE,TRUE,55,1,1,null,'','','','THASDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO META_RAW.PROCESS VALUES (173,173,'TH_Perfect_Store_COP',173,1,1,TRUE,TRUE,55,1,1,null,'','','','THASDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO META_RAW.PROCESS VALUES (174,174,'TH_Perfect_Store_Share_Of_Shelf',174,1,1,TRUE,TRUE,55,1,1,null,'','','','THASDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO META_RAW.PROCESS VALUES (177,177,'TH_Perfect_store_Osa_Oss_Report',177,1,1,TRUE,TRUE,55,1,1,null,'','','','THASDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO META_RAW.PROCESS VALUES (268,268,'j_th_perfect_store_transaction_dbt_ing',268,1,1,FALSE,TRUE,55,null,2,null,'','','','','','');

INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (88,8,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/TH_MT_7_11/','CA105_TH_TTN_7-11_INV','tha','TH_MT/transaction/TH_MT_7_11/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (89,8,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/TH_MT_Tops/','CA105_TH_TTN_Tops_INV','tha','TH_MT/transaction/TH_MT_Tops/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (90,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/Msl','MSLD','tha','GT_Intervention/master/DnA_VMR/RouteDtl',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (91,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/RouteDtl','RouteDtl','tha','GT_Intervention/master/DnA_VMR/RouteHdr',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (92,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/RouteHdr','RouteHdr','tha','GT_Intervention/master/DnA_VMR/RouteHdr',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (93,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/SalesOrder','SO','tha','GT_Intervention/transaction/DnA_VMR/SalesOrder',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (94,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/Schedule','Schedule','tha','GT_Intervention/master/DnA_VMR/Schedule',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (95,11,'TH','itx-arm-conapdna-thailand-prod-kdp','perfect-store/transaction/','jnj_consumerreach_cvs','tha','perfect-store/transaction/jnj_consumerreach_cvs',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (96,11,'TH','itx-arm-conapdna-thailand-prod-kdp','perfect-store/transaction/','jnj_consumerreach_711','tha','perfect-store/transaction/jnj_consumerreach_711',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (97,11,'TH','itx-arm-conapdna-thailand-prod-kdp','perfect-store/transaction/','(JNJ Mer) - COP_1','tha','perfect-store/transaction/COP_1',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (98,11,'TH','itx-arm-conapdna-thailand-prod-kdp','perfect-store/transaction/','(JNJ Mer) - Share of Shelf','tha','perfect-store/transaction/Share_of_Shelf',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (99,11,'TH','itx-arm-conapdna-thailand-prod-kdp','perfect-store/transaction/','(JNJ) OSA and OOS Report','tha','perfect-store/transaction/OSA_and_OOS_Report',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (100,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Complaint','TH_Action_Complaint','tha','SFMC/transaction/TH_Action_Complaint',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (101,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Bounce','TH_Action_Bounce','tha','SFMC/transaction/TH_Action_Bounce',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (102,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Click','TH_Action_Click','tha','SFMC/transaction/TH_Action_Click',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (103,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Open','TH_Action_Open','tha','SFMC/transaction/TH_Action_Open',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (104,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Sent','TH_Action_Sent','tha','SFMC/transaction/TH_Action_Sent',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (105,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_Action_Unsubscribe','TH_Action_Unsubscribe','tha','SFMC/transaction/TH_Action_Unsubscribe',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (106,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM','Customer_Sale_Report','tha','LCM/transaction/LCM_myanmar_Sales_Data',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (107,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM','Sale_and_Stock_Report','tha','LCM/transaction/LCM_myanmar_inv_Data',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (108,12,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/TH_MT','Yimian_-_JNJ_URL_Daily_Report','tha','TH_MT/transaction/TH_MT_price_data',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (109,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM','Daily_Sales_Report_(RAW)','tha','LCM/transaction/LCM_Cambodia_Sales_Data',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (110,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM','Stock_Aging_Report','tha','LCM/transaction/LCM_Cambodia_Inventory_Data',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (111,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/dms_source/processed_file','S_','tha','GT_Intervention/transaction/DnA_VMR/dms_source',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (112,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/dms_source/processed_file','S_','tha','GT_Intervention/transaction/DnA_VMR/dms_source',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (113,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/dms_source/processed_file','A1_','tha','GT_Intervention/transaction/DnA_VMR/dms_source',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (114,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/dms_source/processed_file','I_','tha','GT_Intervention/transaction/DnA_VMR/dms_source',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (115,10,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/SFMC/TH_CRM_Children/','TH_CRM_Children','tha','SFMC/master/TH_CRM_Children',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (116,10,'TH','itx-arm-conapdna-thailand-prod-kdp','raw-data-lake/SFMC/','TH_CRM_Consumer_Master','tha','SFMC/master/TH_crm_consumer_master',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (117,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Customer_Data/','A1_LAO','tha','LCM/master/Laos_Customer_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (118,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Inventory_Data/','I_LAO','tha','LCM/transaction/Laos_Inventory_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (119,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Sellout_Data/','S_LAO','tha','LCM/transaction/Laos_Sellout_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (120,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Sales_Order_Data/','SO_LAO','tha','LCM/transaction/Laos_Sales_Order_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (121,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Route_Hdr_Data/','RouteHdr_LAO_','tha','LCM/master/Laos_Route_Hdr_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (122,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Route_Dtl_Data/','RouteDtl_LAO_','tha','LCM/master/Laos_Route_Dtl_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (123,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Schedule_Data/','Schedule','tha','LCM/master/Laos_Schedule_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (124,9,'TH','itx-arm-conapdna-thailand-prod-kdp','cert-data-lake/LCM/Laos_Visit_Data/','Visit_','tha','LCM/transaction/Laos_Visit_Data/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (140,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/Visit/TH_GT_VISIT','Visit','tha','GT_Intervention/transaction/DnA_VMR/Visit',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (141,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR/cert-data-lake/CustomerDim/TH_GT_CUSTOMER','A1','tha','GT_Intervention/transaction/DnA_VMR/CustomerDim',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (145,8,'TH','itx-arm-conapdna-thailand-prod-kdp','raw-data-lake/TH_MT/BIG_C/source/','SPS003','tha','TH_MT/transaction/BIG_C/source/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (146,8,'TH','itx-arm-conapdna-thailand-prod-kdp','raw-data-lake/TH_MT/AS_WATSONS/source/','','tha','TH_MT/transaction/AS_WATSONS/source/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (147,8,'TH','itx-arm-conapdna-thailand-prod-kdp','raw-data-lake/TH_MT/MAKRO/source/','Makro','tha','TH_MT/transaction/MAKRO/source/',True);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (148,8,'TH','itx-arm-conapdna-thailand-prod-kdp','TH_POS_TESCO','IRTHST','tha','TH_POS_TESCO',True);


