Delete from meta_raw.s3_to_adls where id in (90,91,92,93,94,140,141);
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (90,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','MSLD','tha','GT_Intervention/master/DnA_VMR/RouteDtl',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (91,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','RouteDtl','tha','GT_Intervention/master/DnA_VMR/RouteHdr',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (92,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','RouteHdr','tha','GT_Intervention/master/DnA_VMR/RouteHdr',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (93,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','SO','tha','GT_Intervention/transaction/DnA_VMR/SalesOrder',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (94,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','Schedule','tha','GT_Intervention/master/DnA_VMR/Schedule',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (140,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','Visit','tha','GT_Intervention/transaction/DnA_VMR/Visit',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive) VALUES (141,8,'TH','itx-arm-conapdna-thailand-prod-kdp','GT_Intervention/DnA_VMR','A1','tha','GT_Intervention/transaction/DnA_VMR/CustomerDim',True,'Y');

