update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'TH_MT/transaction/BIG_C/source/'
WHERE PARAMETER_ID = 3195;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'TH_MT/transaction/AS_WATSONS/source/'
WHERE PARAMETER_ID = 3176;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'TTH_MT/transaction/MAKRO/source/'
WHERE PARAMETER_ID = 3157;

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (3886,251,'TH_MT_Makro','is_direct_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (3887,252,'TH_MT_Watson','is_direct_load','Y',FALSE,TRUE);
