use schema VNMSDL_RAW;

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_SALES_STOCK_FACT (
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	WH_CODE VARCHAR(20),
	DATE VARCHAR(30),
	MATERIAL_CODE VARCHAR(50),
	BAT_NUMBER VARCHAR(20),
	EXPIRY_DATE VARCHAR(30),
	QUANTITY VARCHAR(20),
	UOM VARCHAR(10),
	AMOUNT VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	SOURCE_FILE_NAME VARCHAR(256)
);
