use database PROD_DNA_LOAD;
use schema META_RAW;

INSERT INTO PROCESS VALUES (395,395,'vn_datamart_tableau_refresh',395,1,1,FALSE,TRUE,57,null,3,null,'','','','','','Tableau');

INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (4967,395,'vn_datamart_tableau_refresh_group','container','vnm',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (4968,395,'vn_datamart_tableau_refresh_group','contentUrl','ADB',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (4969,395,'vn_datamart_tableau_refresh_group','refreshType','workbook',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (4970,395,'vn_datamart_tableau_refresh_group','tableauSourceName','Vietnam Geomap Dashboard',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (4971,395,'vn_datamart_tableau_refresh_group','waitTime','30',FALSE,TRUE);
