create or replace TABLE PCFSDL_RAW.SDL_PERENSO_ACCOUNT (
	ACCT_KEY NUMBER(10,0),
	DISP_NAME VARCHAR(256),
	ACCT_TYPE_KEY NUMBER(10,0),
	ACTIVE VARCHAR(10),
	ACCT_STREET1 VARCHAR(256),
	ACCT_STREET2 VARCHAR(256),
	ACCT_STREET3 VARCHAR(256),
	ACCT_SUBURB VARCHAR(255),
	ACCT_POSTCODE VARCHAR(255),
	ACCT_STATECODE VARCHAR(255),
	ACCT_STATE VARCHAR(20),
	ACCT_COUNTRY VARCHAR(20),
	ACCT_PHONE VARCHAR(255),
	ACCT_FAX VARCHAR(255),
	ACCT_EMAIL VARCHAR(256),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
