create or replace TABLE PCFSDL_RAW.SDL_PERENSO_SURVEY_RESULT (
	STORE_CHK_HDR_KEY NUMBER(10,0),
	LINE_KEY NUMBER(10,0),
	TODO_KEY NUMBER(10,0),
	PROD_GRP_KEY NUMBER(10,0),
	OPTIONANS NUMBER(10,0),
	NOTESANS VARCHAR(16777216),
	RUN_ID NUMBER(14,0),
	CREATE_DT TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
