create or replace TABLE PCFSDL_RAW.SDL_PX_TERM_PLAN (
	AC_CODE VARCHAR(50) ,
	AC_ATTRIBUTE VARCHAR(20) ,
	AC_LONGNAME VARCHAR(40) ,
	SKU_STOCKCODE VARCHAR(18) ,
	SKU_ATTRIBUTE VARCHAR(20),
	SKU_LONGNAME VARCHAR(40) ,
	GLTT_LONGNAME VARCHAR(40),
	BD_SHORTNAME VARCHAR(10),
	BD_LONGNAME VARCHAR(40) ,
	ASPS_ROWID NUMBER(18,0) ,
	ASPS_PUBID VARCHAR(30) ,
	ASPS_TYPE NUMBER(38,0) ,
	ASPS_MONTH1 FLOAT,
	ASPS_MONTH2 FLOAT,
	ASPS_MONTH3 FLOAT,
	ASPS_MONTH4 FLOAT,
	ASPS_MONTH5 FLOAT,
	ASPS_MONTH6 FLOAT,
	ASPS_MONTH7 FLOAT,
	ASPS_MONTH8 FLOAT,
	ASPS_MONTH9 FLOAT,
	ASPS_MONTH10 FLOAT,
	ASPS_MONTH11 FLOAT,
	ASPS_MONTH12 FLOAT,
	GLTT_ROWID NUMBER(18,0)
);


update meta_raw.parameters
set PARAMETER_VALUE = 'AU_MDSProd_to_SnowflakeProd_PR'
where PARAMETER_GROUP_ID =229 and PARAMETER_NAME = 'jobname';

update meta_raw.usecase
set is_active = FALSE
WHERE USECASE_ID = 139;

