create or replace TABLE PROD_DNA_LOAD.PHLSDL_RAW.SDL_PH_TBL_SURVEYCPG (
  CUSTCODE VARCHAR(10),
	SLSPERID VARCHAR(10),
	BRANCHCODE VARCHAR(60),
	CREATEDDATE TIMESTAMP_NTZ(9),
	VISITDATE TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(50),
	FILENAME_DT NUMBER(14,0),
	RUN_ID NUMBER(14,0),
	CRT_DTTM TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9)))
);
