update meta_raw.parameters set parameter_value='txt' where parameter_id in (4929,4934,4944,4949,4964,4959);

update meta_raw.s3_to_adls 
set GROUP_ID = 22
where id in (179,180);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1881,'OS_ITG','ITG_PH_DYNA_PRODUCT_DIM','PROD_DNA_CORE','PHLITG_INTEGRATION','ITG_PH_DYNA_PRODUCT_DIM','UTILITY_RAW',TRUE,'PH','FULL_REFRESH',4);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1882,'ID_EDW','EDW_VW_RPT_ID_POS_SALES_STOCK','PROD_DNA_CORE','','EDW_VW_RPT_ID_POS_SALES_STOCK','UTILITY_RAW',TRUE,'Indonesia','FULL_REFRESH',6);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1883,'ID_SDL','SDL_MDS_ID_LAV_PRODUCT_HIERARCHY','PROD_DNA_LOAD','','SDL_MDS_ID_LAV_PRODUCT_HIERARCHY','META_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1884,'ID_EDW','EDW_PRODUCT_DIM','PROD_DNA_CORE','','EDW_PRODUCT_DIM','UTILITY_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1885,'ID_SDL','SDL_MDS_ID_LAV_MCS_LIST','PROD_DNA_LOAD','','SDL_MDS_ID_LAV_MCS_LIST','META_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
