update meta_raw.parameters set parameter_value='PROBE'
where parameter_id in (4924,4935);


delete from META_RAW.HISTORICAL_OBJ_METADATA
where id in(1882,1883,1884,1885);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1882,'ID_EDW','EDW_VW_RPT_ID_POS_SALES_STOCK','PROD_DNA_CORE','IDNEDW_INTEGRATION','EDW_VW_RPT_ID_POS_SALES_STOCK','UTILITY_RAW',TRUE,'Indonesia','FULL_REFRESH',6);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1883,'ID_SDL','SDL_MDS_ID_LAV_PRODUCT_HIERARCHY','PROD_DNA_LOAD','IDNSDL_RAW','SDL_MDS_ID_LAV_PRODUCT_HIERARCHY','META_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1884,'ID_EDW','EDW_PRODUCT_DIM','PROD_DNA_CORE','IDNEDW_INTEGRATION','EDW_PRODUCT_DIM','UTILITY_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1885,'ID_SDL','SDL_MDS_ID_LAV_MCS_LIST','PROD_DNA_LOAD','IDNSDL_RAW','SDL_MDS_ID_LAV_MCS_LIST','META_RAW',TRUE,'Indonesia','FULL_REFRESH',4);
