
update table prod_dna_load.meta_raw.usecase
set category='PACIFIC_SALES_REPORTING_AND_PROMAX'  
where usecase_id in (3,6,29,37,141,142) and category = 'REGIONAL REFRESH';

INSERT INTO META_RAW.CATEGORY_MARKET_MAPPING (CATEGORY, MARKET) VALUES ('PACIFIC_SALES_REPORTING_AND_PROMAX','PACIFIC');
INSERT INTO META_RAW.CATEGORY_MARKET_MAPPING (CATEGORY, MARKET) VALUES ('PCF_BW_INVOICE','PACIFIC');

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1886,'OS_SDL','SDL_PH_DYNA_ITEM_REF_DIM','PROD_DNA_LOAD','PHLSDL_RAW','SDL_PH_DYNA_ITEM_REF_DIM','META_RAW',TRUE,'PH','FULL_REFRESH',3);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1887,'OS_SDL','SDL_PH_711_PRODUCT_DIM','PROD_DNA_LOAD','PHLSDL_RAW','SDL_PH_711_PRODUCT_DIM','META_RAW',TRUE,'PH','FULL_REFRESH',3);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1888,'OS_SDL','SDL_PH_PRICELIST','PROD_DNA_LOAD','PHLSDL_RAW','SDL_PH_PRICELIST','META_RAW',TRUE,'PH','FULL_REFRESH',3);
INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) VALUES (1889,'RG_WKS','WKS_PH_INVENTORY_HEALTH_ANALYSIS_PROPAGATION_PRESTEP','PROD_DNA_CORE','PHLWKS_INTEGRATION','WKS_PH_INVENTORY_HEALTH_ANALYSIS_PROPAGATION_PRESTEP','UTILITY_RAW',TRUE,'PH','FULL_REFRESH',4);


create or replace TABLE PHLSDL_RAW.SDL_PH_711_PRODUCT_DIM (
	YEARMO VARCHAR(255),
	CUST_ITEM_CD VARCHAR(255),
	CUST_ITEM_DESC VARCHAR(255),
	JNJ_ITEM_CD VARCHAR(255),
	JNJ_ITEM_DESC VARCHAR(255),
	CONV_FACTOR VARCHAR(255),
	LAST_PRD VARCHAR(255),
	EARLY_BK_PRD VARCHAR(255)
);

create or replace TABLE PHLSDL_RAW.SDL_PH_DYNA_ITEM_REF_DIM (
	YEARMO VARCHAR(100),
	CUST_ITEM_CD VARCHAR(100),
	OLD_CUST_ITEM_CD VARCHAR(100),
	CUST_ITEM_DESC VARCHAR(100),
	JJ_ITEM_CD VARCHAR(100),
	JJ_ITEM_DESC VARCHAR(100),
	CONV_FACTOR VARCHAR(100),
	LAST_PRD VARCHAR(100),
	EARLY_BK_PRD VARCHAR(100),
	CUST_ITEM_GRP VARCHAR(100),
	CURR_DT TIMESTAMP_NTZ(9)
);

create or replace TABLE PHLSDL_RAW.SDL_PH_PRICELIST (
	JJ_MNTH_ID VARCHAR(256),
	ITEM_CD VARCHAR(256),
	ITEM_DESC VARCHAR(256),
	CONSUMER_BAR_CD VARCHAR(256),
	SHIPPERS_BAR_CD VARCHAR(256),
	DZ_PER_CASE VARCHAR(256),
	LST_PRICE_CASE VARCHAR(256),
	LST_PRICE_DZ VARCHAR(256),
	LST_PRICE_UNIT VARCHAR(256),
	SRP VARCHAR(256),
	STATUS VARCHAR(256),
	SAP_ITEM_DESC VARCHAR(256),
	BRND_VRNT VARCHAR(256),
	FRNCHSE_CD VARCHAR(256),
	CDL_DTTM VARCHAR(256),
	CURR_DATE TIMESTAMP_NTZ(9)
);
