use schema meta_raw;
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (194,'TH_Tesco_Transdata','TH_TESCO_TRANSDATA','TH_Tesco_Transdata','TRUE ',1);
INSERT INTO PROCESS VALUES (724,724,'TH_Tesco_Transdata_file_system',724,1,1,FALSE,TRUE,194,7,1,null,'','','','','','');
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (9004,724,'TH_Tesco_Transdata_file_system_group','filename','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (9005,724,'TH_Tesco_Transdata_file_system_group','adls_path','TH_POS_TESCO',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (9006,724,'TH_Tesco_Transdata_file_system_group','container','tha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (9007,724,'TH_Tesco_Transdata_file_system_group','filesystemName','sawsbtasgpw0000',FALSE,TRUE);

update META_RAW.s3_to_adls
set ISACTIVE = FALSE
WHERE ID = 148;
