update PROD_DNA_LOAD.META_RAW.PROCESS
    set sequence_id = 3
    where usecase_id = 112  and parameter_group_id = 666 
    and process_name = 'ph_sfmc_analysis_refresh_dbt_tran';
USE SCHEMA META_RAW;
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10120,792,'ph_crm_dbt_tran_group','jobId','8848',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10121,792,'ph_crm_dbt_tran_group','accountId','99',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10122,792,'ph_crm_dbt_tran_group','waitTime','20',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10123,792,'ph_crm_dbt_tran_group','tempId','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10124,792,'ph_crm_dbt_tran_group','transformationType','transformation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (10125,792,'ph_crm_dbt_tran_group','container','phl',FALSE,TRUE);

INSERT INTO PROCESS VALUES (792,792,'ph_crm_dbt_tran',792,1,2,FALSE,TRUE,112,NULL,2,NULL,'','','','','','');
