

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5000,'ID_EDW','EDW_RPT_ID_RE','PROD_DNA_CORE','IDNEDW_INTEGRATION','EDW_RPT_ID_RE','UTILITY_RAW',TRUE,'INDONESIA','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5001,'AU_EDW','EDW_RPT_ANZ_RE','PROD_DNA_CORE','PCFEDW_INTEGRATION','EDW_RPT_ANZ_RE','UTILITY_RAW',TRUE,'PACIFIC','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5002,'CN_EDW','EDW_RPT_RETAIL_EXCELLENCE_CNPC','PROD_DNA_CORE','CHNEDW_INTEGRATION','EDW_RPT_RETAIL_EXCELLENCE_CNPC','UTILITY_RAW',TRUE,'CNPC','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5003,'CN_EDW','EDW_RPT_RETAIL_EXCELLENCE_CNSC','PROD_DNA_CORE','CHNEDW_INTEGRATION','EDW_RPT_RETAIL_EXCELLENCE_CNSC','UTILITY_RAW',TRUE,'CNSC','FULL_REFRESH',5);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5004,'IN_EDW','EDW_RPT_RETAIL_EXCELLENCE','PROD_DNA_CORE','INDEDW_INTEGRATION','EDW_RPT_RETAIL_EXCELLENCE','UTILITY_RAW',TRUE,'INDIA','FULL_REFRESH',6);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5005,'JP_EDW','EDW_RPT_RETAIL_EXCELLENCE','PROD_DNA_CORE','JPNEDW_INTEGRATION','EDW_RPT_RETAIL_EXCELLENCE','UTILITY_RAW',TRUE,'JAPAN','FULL_REFRESH',4);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5006,'NA_EDW','EDW_KR_RPT_RETAIL_EXCELLENCE','PROD_DNA_CORE','NTAEDW_INTEGRATION','EDW_KR_RPT_RETAIL_EXCELLENCE','UTILITY_RAW',TRUE,'KOREA','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5007,'OS_EDW','EDW_RPT_MY_RE','PROD_DNA_CORE','MYSEDW_INTEGRATION','EDW_RPT_MY_RE','UTILITY_RAW',TRUE,'MALAYSIA','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5008,'OS_EDW','EDW_PH_RPT_RETAIL_EXCELLENCE','PROD_DNA_CORE','PHLEDW_INTEGRATION','EDW_PH_RPT_RETAIL_EXCELLENCE','UTILITY_RAW',TRUE,'PHILIPPINES','FULL_REFRESH',4);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5009,'OS_EDW','EDW_SG_RPT_RETAIL_EXCELLENCE','PROD_DNA_CORE','SGPEDW_INTEGRATION','EDW_SG_RPT_RETAIL_EXCELLENCE','UTILITY_RAW',TRUE,'SINGAPORE','FULL_REFRESH',1);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5010,'OS_EDW','EDW_RPT_RETAIL_EXCELLENCE_TH','PROD_DNA_CORE','THAEDW_INTEGRATION','EDW_RPT_RETAIL_EXCELLENCE_TH','UTILITY_RAW',TRUE,'THAILAND','FULL_REFRESH',3);

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5011,'RG_ITG','ITG_RE_MSL_INPUT_DEFINITION','PROD_DNA_CORE','ASPITG_INTEGRATION','ITG_RE_MSL_INPUT_DEFINITION','UTILITY_RAW',TRUE,'RE_MSL_MDS','FULL_REFRESH',1);

