create or replace stage IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN
 storage_integration =  PROD_DNA_LOAD_AZURE23_SI
 url = 'azure://dlsadbplt001.blob.core.windows.net/idn/';

use schema meta_raw;

INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (184,'ID_POS','ID_POS','Ingest Indonesia POS files','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (205,'ID_IVY','ID_IVY','ID_IVY','TRUE',2);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (207,'ID_ps','ID_PS','ID_ps desc','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (214,'INDONESIA_MDS_SDL','IDN_MDS_SDL','Indonesia MDS Usecase','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (218,'id_cd_server_data','ID_IVY','id_cd_server_data desc','TRUE',3);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (239,'ID_IVY_Altryx_dna_to_mds_sync','ID_IVY','Indonesia Reverse MDS Usecase','TRUE',4);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (245,'id_stock_load','IDN_MDS_SDL','id stock load desc','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (246,'ID_POS_Daily','ID_POS_DAILY','ID_POS_Daily desc','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (247,'id_ps_product_availability_visibility','ID_PS','id_ps_product_availability_visibility','TRUE',2);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (248,'ID_IVY_Manual_Upload','ID_IVY','ID_IVY_Manual_Upload','TRUE',1);

INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (279,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Superindo/','Sellout_Superindo','idn','POS/transaction/Superindo/sellout/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (280,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Superindo/','Stock_Superindo','idn','POS/transaction/Superindo/stock/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (281,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/SAT/','Sellout_Alfamart','idn','POS/transaction/SAT/sellout/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (282,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/SAT/','Stock_Alfamart','idn','POS/transaction/SAT/stock/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (283,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Carrefour/','Sellout_Carrefour','idn','POS/transaction/Carrefour/sellout/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (284,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Carrefour/','Stock_Carrefour','idn','POS/transaction/Carrefour/stock/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (285,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Watson','Sellout_Watsons','idn','POS/transaction/Watson/sellout/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (286,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Watson','Stock_Watson','idn','POS/transaction/Watson/stock/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (287,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/Diamond','Sellout_Diamond','idn','POS/transaction/diamond',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (288,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/igr','Sellout_Indogrosir','idn','POS/transaction/igr',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (289,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/igr','Stock_Indogrosir','idn','POS/transaction/igr',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (290,33,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/MIDI','Sellout_Alfamidi','idn','POS/transaction/MIDI/sellout/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (291,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/MIDI','Stock_Alfamidi','idn','POS/transaction/MIDI/stock/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (292,32,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/idm','Stock_Indomaret','idn','POS/transaction/idm',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (293,33,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/POS/idm','Sellout_Indomaret','idn','POS/transaction/idm',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (294,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','UserMaster','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (295,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','OutletMaster','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (296,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','Inventory','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (297,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','Merchandising','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (298,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','OrderDetail','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (299,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/IVY/Manual_Upload/','Invoice','idn','IVY/Manual_Upload',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (300,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Visibility','VISIBILITY','idn','5Ps/transaction/Visibility',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (301,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Brand Blocking','BRAND BLOCKING','idn','5Ps/transaction/Brand_Blocking',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (302,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Planogram','PLANOGRAM','idn','5Ps/transaction/Planogram',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (303,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Pricing','PRICING','idn','5Ps/transaction/Pricing',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (304,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/promo','PROMO','idn','5Ps/transaction/promo',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (305,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Secondary Display','SECONDARY DISPLAY','idn','5Ps/transaction/secondary_display',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (306,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','5Ps/Product Availability','PRODUCT AVAILABILITY','idn','5Ps/transaction/product_availability',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (307,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/alteryx/customermaster/','Customer','idn','alteryx/transaction/customermaster',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (308,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/alteryx/sellout/','Sellout','idn','alteryx/transaction/sellout',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (309,34,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/alteryx/sellin/','Sellin','idn','alteryx/transaction/sellin',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (310,35,'IDN','itx-arm-conapdna-indonesia-prod-kdp','raw_data_lake/alteryx/stock/','Stock','idn','alteryx/transaction/stock',TRUE,'Y');

INSERT INTO PROCESS VALUES (686,686,'POS_Superindo_sellout',686,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (687,687,'POS_Superindo_stock',687,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (688,688,'POS_Alfamart_sellout',688,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (689,689,'POS_Alfamart_stock',689,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (702,702,'POS_Diamond',702,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (703,703,'POS_Guardian',703,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (704,704,'POS_idm_sellout',704,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (705,705,'POS_idm_stock',705,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (706,706,'POS_igr_sellout',706,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (707,707,'POS_igr_stock',707,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (708,708,'POS_matahari_beauty',708,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (709,709,'POS_matahari_jb',709,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (710,710,'POS_matahari_otc',710,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (713,713,'POS_Carrefour_sellout',713,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (714,714,'POS_Carrefour_stock',714,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (754,754,'POS_Watson_sellout',754,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (755,755,'POS_Watson_stock',755,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (757,757,'ID_POS_Alfamidi_Sellout',757,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (758,758,'ID_POS_Alfamidi_Stock',758,1,1,FALSE,TRUE,184,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (796,796,'ID_IVY_UserMaster',796,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (797,797,'ID_IVY_OutletMaster',797,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (798,798,'ID_IVY_Inventory',798,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (800,800,'id_ps_promo_competitor',800,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (813,813,'ID_IVY_Merchandising',813,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (823,823,'id_ps_brand_blocking',823,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (824,824,'id_ps_planogram',824,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (825,825,'id_ps_pricing',825,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (826,826,'id_ps_promo',826,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (827,827,'id_ps_secondary_display',827,1,1,FALSE,TRUE,207,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (882,882,'ID_IVY_Order',882,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (913,913,'ID_IVY_Invoice',913,1,1,FALSE,TRUE,205,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (879,879,'id_mds_sdl_refresh_ID_distributor_customer_update',879,1,1,FALSE,TRUE,214,5,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (971,971,'id_cd_server_data_sellin',971,1,1,FALSE,TRUE,218,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (972,972,'id_cd_server_data_sellout',972,1,1,FALSE,TRUE,218,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (973,973,'id_cd_server_data_customermaster',973,1,1,FALSE,TRUE,218,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (793,793,'id_pos_daily_idm_sellout',793,1,1,FALSE,TRUE,246,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (794,794,'id_pos_daily_sat_sellout',794,1,1,FALSE,TRUE,246,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (795,795,'id_pos_daily_basedline',795,1,1,FALSE,TRUE,246,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (822,822,'id_ps_visibility',822,1,1,FALSE,TRUE,247,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (828,828,'id_ps_product_availability',828,1,1,FALSE,TRUE,247,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (891,891,'id_stock_load',891,1,1,FALSE,TRUE,245,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (960,960,'ID_IVY_UserMaster_Manual_Upload',960,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (961,961,'ID_IVY_OutletMaster_Manual_Upload',961,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (962,962,'ID_IVY_Inventory_Manual_Upload',962,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (963,963,'ID_IVY_Merchandising_Manual_Upload',963,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (964,964,'ID_IVY_Order_Manual_Upload',964,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (965,965,'ID_IVY_Invoice_Manual_Upload',965,1,1,FALSE,TRUE,248,1,1,NULL,'','','','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','','');
INSERT INTO PROCESS VALUES (976,976,'ID_IVY_OUTLET_MASTER_SYNC_TO_MDS',976,1,1,FALSE,TRUE,239,9,1,NULL,'','','','','','','');
INSERT INTO PROCESS VALUES (977,977,'ID_ALTRYX_CUST_DIM_SYNC_TO_MDS',977,1,2,FALSE,TRUE,239,9,1,NULL,'','','','','','','');
