use schema meta_raw;

INSERT INTO PROCESS VALUES (1340,1340,'Kenvue_Weekly_National_eCommerce_sftp',1340,1,1,FALSE,TRUE,101,4,1,NULL,'','','','PCFSDL_RAW.DEV_LOAD_STAGE_ADLS','','');
INSERT INTO PROCESS VALUES (1341,1341,'Kenvue_Weekly_CHW_eCommerce_sftp',1341,1,1,FALSE,TRUE,101,4,1,NULL,'','','','PCFSDL_RAW.DEV_LOAD_STAGE_ADLS','','');


INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15519,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','file_spec','Kenvue_Weekly_CHW_eCommerce_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15520,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','folder_path','pharm_ecommerce/transaction/kenvue_weekly_national_ecommerce_data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15521,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','container','pac',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15522,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15523,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15524,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','ftpName','iqviaaus',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15525,1340,'Kenvue_Weekly_National_eCommerce_sftp_group','ftpDirectory','Home/EDELIVERY/AU/01_KENVUE/MONTHLY',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15526,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','file_spec','Kenvue_Weekly_CHW_eCommerce_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15527,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','folder_path','pharm_ecommerce/transaction/kenvue_weekly_chw_ecommerce_data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15528,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','container','pac',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15529,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15530,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15531,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','ftpName','iqviaaus',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (15532,1341,'Kenvue_Weekly_CHW_eCommerce_sftp_group','ftpDirectory','Home/EDELIVERY/AU/01_KENVUE/MONTHLY',FALSE,TRUE);
