use schema meta_raw;

INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (217,'IN_MDS_SALESCUBE_REFRESH','IN_MDS_REFRESH_PERFECT_STORE_TRANS','IN_MDS_REFRESH_PERFECT_STORE_TRANS','TRUE',1);
delete from usecase where usecase_id=251;
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (251,'IN_PERFECT_STORE_TRANSACTION','IN_MDS_REFRESH_PERFECT_STORE_TRANS','Ingestion for India perfect store files','TRUE',3);
