ALTER TABLE PROD_DNA_LOAD.PCFSDL_RAW.SDL_PERENSO_HEAD_OFFICE_REQ_CHECK 
ALTER NOTES SET DATA TYPE VARCHAR(600);

ALTER TABLE PROD_DNA_LOAD.PCFSDL_RAW.SDL_RAW_PERENSO_HEAD_OFFICE_REQ_CHECK 
ALTER NOTES SET DATA TYPE VARCHAR(600);
