INSERT INTO PROD_DNA_LOAD.META_RAW.USECASE (USECASE_ID,	USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID)
VALUES (116,'anz_perenso_weekly_load','anz_perenso_weekly_load','anz_perenso_weekly_load_desc',TRUE,1);

UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='Display_Type|Points' WHERE parameter_group_id=408 AND PARAMETER_NAME='val_file_header' and PARAMETER_ID=5190
