DELETE FROM META_RAW.HISTORICAL_OBJ_METADATA WHERE ID IN ('5017','5018');

INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5017,'CN_ITG','ITG_MDS_CN_OTC_PRODUCT_MAPPING','PROD_DNA_CORE','CHNITG_INTEGRATION','ITG_MDS_CN_OTC_PRODUCT_MAPPING','UTILITY_RAW',TRUE,'CNSC','FULL_REFRESH',1);


INSERT INTO META_RAW.HISTORICAL_OBJ_METADATA (ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5018,'CN_ITG','ITG_CS_RE_STORE','PROD_DNA_CORE','CHNITG_INTEGRATION','ITG_CS_RE_STORE','UTILITY_RAW',TRUE,'CNSC','FULL_REFRESH',3);
