UPDATE PROD_DNA_LOAD.META_RAW.PROCESS SET SNOWFLAKE_STAGE='ASPSDL_RAW.PROD_LOAD_STAGE_ADLS' WHERE USECASE_ID=501

UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='prd/transactional/' WHERE parameter_group_id=2001 AND PARAMETER_NAME='landing_file_path' and PARAMETER_ID=25002
UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='SELECT * from delv.otif_d_cnsmr_attr_detl LIMIT 10' WHERE parameter_group_id=2001 AND PARAMETER_NAME='ms_query' and PARAMETER_ID=25008
