
use schema meta_raw;
INSERT INTO PROCESS VALUES (1799,1799,'kr_master_mds_sdl_itg_load_dbt_tran',1799,1,1,FALSE,TRUE,342,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1800,1800,'tw_ims_distributor_prod_map_dbt_tran',1800,1,3,FALSE,TRUE,222,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1801,1801,'tw_ims_distributor_standard_sell_out_dbt_ing',1801,1,1,FALSE,TRUE,203,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1802,1802,'tw_ims_distributor_standard_sell_out_dbt_tran',1802,1,2,FALSE,TRUE,203,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1803,1803,'tw_ims_distributor_standard_stock_dbt_ing',1803,1,1,FALSE,TRUE,203,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1804,1804,'tw_ims_distributor_standard_stock_dbt_tran',1804,1,2,FALSE,TRUE,203,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1805,1805,'gt_sellout_nh_dbt_ing',1805,1,1,FALSE,TRUE,264,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1806,1806,'gt_sellout_nh_dbt_tran',1806,1,2,FALSE,TRUE,264,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1807,1807,'j_kr_nts_target_load_dbt_ing',1807,1,3,FALSE,TRUE,300,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1808,1808,'j_kr_nts_target_load_dbt_tran',1808,1,4,FALSE,TRUE,300,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1809,1809,'j_tw_sell_in_forecast_transaction_data_dbt_ing',1809,1,1,FALSE,TRUE,186,NULL,2,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1810,1810,'j_tw_sell_in_forecast_transaction_data_dbt_tran',1810,1,2,FALSE,TRUE,186,NULL,2,NULL,'','','','','','');

INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (342,'kr_master_mds_sdl_itg_load','NA_MDS_KR_POS','kr_master_mds_sdl_itg_load_dbt_tran','TRUE',2);
update usecase
set SEQUENCE_ID = 3
where usecase_id = 202;

INSERT INTO PROCESS VALUES (1775,1775,'KR_DADS_Coupang_search_keyword_sftp',1775,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1776,1776,'KR_DADS_COUPANG_PRICE_sftp',1776,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1777,1777,'KR_DADS_Naver_GMV_sftp',1777,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1778,1778,'KR_DADS_Naver_keyword_volume_sftp',1778,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1779,1779,'KR_DADS_Naver_search_channel_sftp',1779,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1780,1780,'KR_DADS_Coupang_PA_ads_sftp',1780,1,1,FALSE,TRUE,235,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1781,1781,'KR_DADS_Coupang_BPA_ads_sftp',1781,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');
INSERT INTO PROCESS VALUES (1782,1782,'KR_DADS_Naver_ads_sftp',1782,1,1,FALSE,TRUE,237,4,1,NULL,'','','','','','');



INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20348,1775,'KR_DADS_Coupang_search_keyword_sftp','file_spec','search-keyword-by-category-A00165277-monthly',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20349,1775,'KR_DADS_Coupang_search_keyword_sftp','folder_path','dads/transaction/couapng_search_keyword/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20350,1775,'KR_DADS_Coupang_search_keyword_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20351,1775,'KR_DADS_Coupang_search_keyword_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20352,1775,'KR_DADS_Coupang_search_keyword_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20353,1775,'KR_DADS_Coupang_search_keyword_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20354,1775,'KR_DADS_Coupang_search_keyword_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20355,1776,'KR_DADS_COUPANG_PRICE_sftp','file_spec','Price-Products',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20356,1776,'KR_DADS_COUPANG_PRICE_sftp','folder_path','dads/transaction/couapng_price/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20357,1776,'KR_DADS_COUPANG_PRICE_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20358,1776,'KR_DADS_COUPANG_PRICE_sftp','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20359,1776,'KR_DADS_COUPANG_PRICE_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20360,1776,'KR_DADS_COUPANG_PRICE_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20361,1776,'KR_DADS_COUPANG_PRICE_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20362,1777,'KR_DADS_Naver_GMV_sftp','file_spec','Product_performance_weekly',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20363,1777,'KR_DADS_Naver_GMV_sftp','folder_path','dads/transaction/sales_product_performance/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20364,1777,'KR_DADS_Naver_GMV_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20365,1777,'KR_DADS_Naver_GMV_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20366,1777,'KR_DADS_Naver_GMV_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20367,1777,'KR_DADS_Naver_GMV_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20368,1777,'KR_DADS_Naver_GMV_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20369,1778,'KR_DADS_Naver_keyword_volume_sftp','file_spec','JNJ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20370,1778,'KR_DADS_Naver_keyword_volume_sftp','folder_path','dads/transaction/naver_keyword/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20371,1778,'KR_DADS_Naver_keyword_volume_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20372,1778,'KR_DADS_Naver_keyword_volume_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20373,1778,'KR_DADS_Naver_keyword_volume_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20374,1778,'KR_DADS_Naver_keyword_volume_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20375,1778,'KR_DADS_Naver_keyword_volume_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20376,1779,'KR_DADS_Naver_search_channel_sftp','file_spec','search_channel',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20377,1779,'KR_DADS_Naver_search_channel_sftp','folder_path','dads/transaction/naver_search_channel/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20378,1779,'KR_DADS_Naver_search_channel_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20379,1779,'KR_DADS_Naver_search_channel_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20380,1779,'KR_DADS_Naver_search_channel_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20381,1779,'KR_DADS_Naver_search_channel_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20382,1779,'KR_DADS_Naver_search_channel_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20383,1780,'KR_DADS_Coupang_PA_ads_sftp','file_spec','A00165277_pa_daily_keyword',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20384,1780,'KR_DADS_Coupang_PA_ads_sftp','folder_path','dads/transaction/couapng_pa/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20385,1780,'KR_DADS_Coupang_PA_ads_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20386,1780,'KR_DADS_Coupang_PA_ads_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20387,1780,'KR_DADS_Coupang_PA_ads_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20388,1780,'KR_DADS_Coupang_PA_ads_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20389,1780,'KR_DADS_Coupang_PA_ads_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20390,1781,'KR_DADS_Coupang_BPA_ads_sftp','file_spec','A00165277_ba_daily_creative',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20391,1781,'KR_DADS_Coupang_BPA_ads_sftp','folder_path','dads/transaction/couapng_bpa/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20392,1781,'KR_DADS_Coupang_BPA_ads_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20393,1781,'KR_DADS_Coupang_BPA_ads_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20394,1781,'KR_DADS_Coupang_BPA_ads_sftp','isUnzipNeeded','N',FALSE,TRUE);

INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20395,1781,'KR_DADS_Coupang_BPA_ads_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20396,1781,'KR_DADS_Coupang_BPA_ads_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20397,1782,'KR_DADS_Naver_ads_sftp','file_spec','Naver_keyword',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20398,1782,'KR_DADS_Naver_ads_sftp','folder_path','dads/transaction/naver_keyword weekly/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20399,1782,'KR_DADS_Naver_ads_sftp','container','kor',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20400,1782,'KR_DADS_Naver_ads_sftp','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20401,1782,'KR_DADS_Naver_ads_sftp','isUnzipNeeded','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20402,1782,'KR_DADS_Naver_ads_sftp','ftpName','exacttargettha',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20403,1782,'KR_DADS_Naver_ads_sftp','ftpDirectory','Import/CONSUMER_Data',FALSE,TRUE);

Delete from S3_TO_ADLS where group_id=38;

UPDATE process
SET sequence_id = 2
WHERE process_id IN (764, 765, 949, 951, 956, 969, 974, 975);
