UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='otif/transaction/' WHERE PARAMETER_GROUP_ID=2001 AND PARAMETER_NAME='landing_file_path' and PARAMETER_ID=25002;
UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='OTIF_Server' WHERE PARAMETER_GROUP_ID=2001 AND PARAMETER_NAME='decide_source' and PARAMETER_ID=25007;
UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='ASPSDL_RAW' WHERE PARAMETER_GROUP_ID=2001 AND PARAMETER_NAME='target_schema' and PARAMETER_ID=25005;
UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='SELECT * FROM DELV.OTIF_D_CNSMR_ATTR_DETL 
WHERE CAST(FISC_YR_NBR AS INT) >= YEAR(GETDATE()) 
AND CAST((SUBSTRING(FISC_YR_MO_NUM,6,2))AS INT)>
(MONTH(GETDATE())-3);' WHERE PARAMETER_GROUP_ID=2001 AND PARAMETER_NAME='ms_query' and PARAMETER_ID=25008;
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25009,2001,'OTIFD_Data_Ingestion','map_names','N',FALSE,TRUE);
UPDATE PROD_DNA_LOAD.META_RAW.PROCESS SET SOURCE_ID=5 WHERE PROCESS_ID=2001 AND PARAMETER_GROUP_ID=2001;
