ALTER TABLE META_RAW.S3_TO_ADLS
DROP COLUMN DELETE_SOURCE_FILE;

ALTER TABLE meta_raw.s3_to_adls
ADD COLUMN delete_source_file VARCHAR(1) DEFAULT 'N';

delete from META_RAW.S3_TO_ADLS
where country = 'MY';

INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (21,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Master','MY_Sellin_CustomerMaster','mys','prd/master/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (22,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Others','MY_Accrual','mys','prd/others/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (23,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Others','MY_AFGR','mys','prd/others/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (24,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Others','MY_CIW','mys','prd/others/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (25,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Target','MY_LE_Target','mys','prd/targets/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (26,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellIn/Target','MY_Targets','mys','prd/targets/sellin',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (27,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','POS/Transaction','MY_POS_MT_Cust_Sales','mys','prd/pos/transaction',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (28,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','POS/Master','MY_POS_OutletMaster','mys','prd/pos/master',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (29,5,'MYS','itx-arm-conapdna-malaysia-prod-kdp','POS/Inventory','MY_WATSONS_INV','mys','prd/pos/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (30,7,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Joint','MY_GT_Distributor_Integrated_Sales','mys','prd/transaction/sellout/distributor_integrated',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (31,7,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Joint','MY_GT_Distributor_Integrated_inv','mys','prd/transaction/sellout/distributor_integrated',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (32,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133986_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (33,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133980_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (34,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133981_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (35,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133982_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (36,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133983_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (37,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133984_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (38,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_133985_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (39,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_131164_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (40,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_131165_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (41,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_131166_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (42,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_131167_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (43,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130516_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (44,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130517_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (45,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130518_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (46,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130519_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (47,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130520_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (48,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_130521_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (49,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_119024_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (50,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_119025_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (51,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_108129_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (52,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_108273_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (53,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_108565_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (54,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_118477_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (55,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_109772_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (56,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_135976_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (57,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Sales','MY_GT_137021_Sales','mys','prd/transaction/sellout/sales',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (58,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Master','MY_GT_Distributor_Hierarchy','mys','prd/master/sellout',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (59,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Master','MY_GT_Distributor_Doc_Type','mys','prd/master/sellout',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (60,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Others','MY_GT_In_Transit_Inv','mys','prd/transaction/sellout/others',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (61,4,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Others','MY_GT_IDS_EXCHNG_RATE','mys','prd/transaction/sellout/others',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (62,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133986_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (63,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133980_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (64,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133981_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (65,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133982_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (66,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133983_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (67,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133984_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (68,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_133985_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (69,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_131164_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (70,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_131165_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (71,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_131166_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (72,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_131167_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (73,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130516_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (74,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130517_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (75,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130518_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (76,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130519_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (77,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130520_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (78,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_130521_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (79,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_119024_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (80,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_119025_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (81,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_108129_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (82,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_108273_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (83,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_108565_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (84,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_118477_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (85,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_109772_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (86,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_135976_Inv','mys','prd/transaction/sellout/inventory',True,'Y');
INSERT INTO META_RAW.s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,delete_source_file) VALUES (87,6,'MYS','itx-arm-conapdna-malaysia-prod-kdp','SellOut/Transaction/Inventory','MY_GT_137021_Inv','mys','prd/transaction/sellout/inventory',True,'Y');

