DELETE FROM PROD_DNA_LOAD.META_RAW.PARAMETERS WHERE PARAMETER_ID =25008 AND PARAMETER_GROUP_ID =2001;

INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25008,2001,'OTIFD_Data_Ingestion','ms_query','SELECT * from delv.otif_d_cnsmr_attr_detl LIMIT 10;',FALSE,TRUE);
