UPDATE PROD_DNA_LOAD.META_RAW.PARAMETERS SET PARAMETER_VALUE='SELECT * from delv.otif_d_cnsmr_attr_detl WHERE RGN_CD = "APAC"
AND CAST(FISC_YR_NBR AS INT) >= YEAR(GETDATE()) 
AND CAST((SUBSTRING(FISC_YR_MO_NUM,6,2))AS INT)>
(MONTH(GETDATE())-3);' WHERE parameter_group_id=2001 AND PARAMETER_NAME='ms_query' and PARAMETER_ID=25008
