use schema meta_raw;
delete from usecase where usecase_id in (15,118,167);

INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (15,'MALAYSIA_WATSONS_INV','J_RG_WATSONS_INV_MY_PH_TW','malaysia watsons inv file load','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (118,'CAPAI34_j_rg_watsons_inv_ingestion','J_RG_WATSONS_INV_MY_PH_TW','CAPAI34_j_rg_watsons_inv_ingestion_desc','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (167,'TW_AS_WATSONS_INVENTORY','J_RG_WATSONS_INV_MY_PH_TW','TW_AS_WATSONS_INVENTORY','TRUE',1);


INSERT INTO PROCESS VALUES (623,623,'TW_AS_WATSONS_INVENTORY',623,1,1,FALSE,TRUE,167,1,1,null,'','','','NTASDL_RAW.DEV_LOAD_STAGE_ADLS_TWN','','');
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7532,623,'TW_AS_WATSONS_INVENTORY','business_mail_trigger','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7533,623,'TW_AS_WATSONS_INVENTORY','file_spec','TW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7534,623,'TW_AS_WATSONS_INVENTORY','val_file_name','TW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7535,623,'TW_AS_WATSONS_INVENTORY','val_file_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7536,623,'TW_AS_WATSONS_INVENTORY','load_method','sp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7537,623,'TW_AS_WATSONS_INVENTORY','sp_name','NTASDL_RAW.SDL_TW_AS_WATSONS_INVENTORY_preprocessing',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7538,623,'TW_AS_WATSONS_INVENTORY','sheet_index','2',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7539,623,'TW_AS_WATSONS_INVENTORY','folder_path','pos/transaction/watsons/inventory',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7540,623,'TW_AS_WATSONS_INVENTORY','target_table','SDL_TW_AS_WATSONS_INVENTORY',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7541,623,'TW_AS_WATSONS_INVENTORY','container','twn',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7542,623,'TW_AS_WATSONS_INVENTORY','target_schema','NTASDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7543,623,'TW_AS_WATSONS_INVENTORY','validation','1-1-1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7544,623,'TW_AS_WATSONS_INVENTORY','index','full',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7545,623,'TW_AS_WATSONS_INVENTORY','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7546,623,'TW_AS_WATSONS_INVENTORY','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (7547,623,'TW_AS_WATSONS_INVENTORY','val_file_header','Supplier|SKU_No|Buy_code|Home_cdesc|Prdt_grp|Grp_desc|Prdt_cat|Cat_desc|C_cdesc_|Type',FALSE,TRUE);
