use database PROD_DNA_LOAD;

CREATE OR REPLACE FILE FORMAT JPDCLSDL_RAW.FILE_FORMAT_COMMA
	TYPE = csv
	SKIP_HEADER = 1
	NULL_IF = ('')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	EMPTY_FIELD_AS_NULL = FALSE
	ENCODING = 'UTF-8'
;

CREATE OR REPLACE FILE FORMAT JPDCLSDL_RAW.FILE_FORMAT_QUOTE
	TYPE = csv
	SKIP_HEADER = 1
	FIELD_OPTIONALLY_ENCLOSED_BY = '\"'
	NULL_IF = ('')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	EMPTY_FIELD_AS_NULL = FALSE
	ENCODING = 'UTF-8'
;

CREATE OR REPLACE FILE FORMAT JPDCLSDL_RAW.FILE_FORMAT_SOH
	TYPE = csv
	FIELD_DELIMITER = '\u0001'
	SKIP_HEADER = 1
	NULL_IF = ('')
	ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
	EMPTY_FIELD_AS_NULL = FALSE
	ENCODING = 'UTF-8'
;
