INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5027,'CN_EDW','EDW_PERFECT_STORE_PRODUCT_MASTER','PROD_DNA_CORE','CHNEDW_INTEGRATION','EDW_PERFECT_STORE_PRODUCT_MASTER','UTILITY_RAW',TRUE,'EDW_PERFECT_STORE_PRODUCT_MASTER','FULL_REFRESH',1);

