--Korea Market

--Insert New task (table in the MDS Korea Job(s))
INSERT INTO META_RAW.PROCESS VALUES (2004,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute',2004,1,1,FALSE,TRUE,242,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');
INSERT INTO META_RAW.PROCESS VALUES (2005,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute_1',2005,1,1,FALSE,TRUE,254,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');
INSERT INTO META_RAW.PROCESS VALUES (2006,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute_2',2006,1,1,FALSE,TRUE,271,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');

--Insert New parameters
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25022,2004,'SDL_MDS_KR_Product_Attribute_group','container','kor',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25023,2004,'SDL_MDS_KR_Product_Attribute_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25024,2004,'SDL_MDS_KR_Product_Attribute_group','landing_file_name','SDL_MDS_KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25025,2004,'SDL_MDS_KR_Product_Attribute_group','landing_file_path','sql_server/MDS/SDL_MDS_KR_Product_Attribute/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25026,2004,'SDL_MDS_KR_Product_Attribute_group','ms_query','SELECT * FROM MDS.mdm.KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25027,2004,'SDL_MDS_KR_Product_Attribute_group','target_schema','NTASDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25028,2004,'SDL_MDS_KR_Product_Attribute_group','target_table','SDL_MDS_KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25029,2004,'SDL_MDS_KR_Product_Attribute_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26474,2004,'SDL_MDS_KR_Product_Attribute_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26656,984,'SDL_MDS_KR_sales_cust_prod_master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26657,985,'SDL_MDS_KR_sales_store_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26658,986,'SDL_MDS_KR_sales_store_master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26659,987,'SDL_MDS_KR_pos_store_code_sold_to_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26660,988,'SDL_MDS_KR_Ecom_Offtake_Product_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26661,989,'SDL_MDS_KR_Retailer_Price_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26662,990,'SDL_MDS_KR_Sub_Customer_Master','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26663,991,'SDL_MDS_KR_Target_GROUP','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26664,992,'SDL_MDS_KR_PS_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26665,993,'SDL_MDS_KR_PS_Weights_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26666,994,'SDL_MDS_KR_Product_EAN_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26667,1001,'SDL_MDS_KR_SKU_BENCHMARKS_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26668,995,'SDL_MDS_KR_Cost_Of_Goods_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26669,996,'SDL_MDS_KR_TP_Target_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26670,997,'SDL_MDS_KR_Brand_Campaign_Promotion_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26671,998,'SDL_MDS_KR_Naver_Product_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26672,999,'SDL_MDS_KR_Keyword_Classification_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26673,1000,'SDL_MDS_KR_Product_Hierarchy_group','map_names','Y',FALSE,TRUE);


--Updates in existing parameters to follow on the MDS standard
UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = Replace(PARAMETER_VALUE, 'KR_MDSProd_to_RedshiftProd','MDS')
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_KR_%' 
and PARAMETER_NAME = 'landing_file_path';

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT * FROM MDS.mdm.KR_sales_cust_prod_master'
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_KR_%' 
and PARAMETER_NAME = 'ms_query'
and LOWER(PARAMETER_VALUE) not like 'select * from %'
and PARAMETER_ID = 12485;

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT * FROM MDS.mdm.KR_sales_store_master' 
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_KR_%' 
and PARAMETER_NAME = 'ms_query'
and LOWER(PARAMETER_VALUE) not like 'select * from %'
and PARAMETER_ID = 12501;

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT * FROM MDS.mdm.KR_TP_Target' 
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_KR_%' 
and PARAMETER_NAME = 'ms_query'
and LOWER(PARAMETER_VALUE) not like 'select * from %'
and PARAMETER_ID = 12589;

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT * FROM MDS.mdm.KR_pos_store_code_sold_to_map'
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_KR_%' 
and PARAMETER_NAME = 'ms_query'
and LOWER(PARAMETER_VALUE) not like 'select * from %'
and PARAMETER_ID = 12509;

UPDATE META_RAW.PARAMETERS
SET PARAMETER_GROUP_NAME = Replace(PARAMETER_GROUP_NAME, '_GROUP','_group')
where parameter_group_name like 'SDL_MDS_KR_%'
and parameter_group_name not like '%_group'
and PARAMETER_GROUP_ID = 991;

UPDATE META_RAW.PARAMETERS
SET PARAMETER_GROUP_NAME = concat(PARAMETER_GROUP_NAME, '_group')
where parameter_group_name like 'SDL_MDS_KR_%'
and parameter_group_name not like '%_group'
and PARAMETER_GROUP_ID = 990;

--DDL statement change in the MDS table structure
create or replace TABLE PROD_DNA_LOAD.NTASDL_RAW.SDL_MDS_KR_SUB_CUSTOMER_MASTER (
	ID NUMBER(18,0),
	MUID VARCHAR(100),
	VERSIONNAME VARCHAR(100),
	VERSIONNUMBER NUMBER(18,0),
	VERSION_ID NUMBER(18,0),
	VERSIONFLAG VARCHAR(100),
	NAME VARCHAR(500),
	CODE VARCHAR(500),
	CHANGETRACKINGMASK NUMBER(18,0),
	SAP_CUSTOMER_CODE VARCHAR(200),
	RETAILER VARCHAR(200),
	OUTLET_CODE VARCHAR(200),
	BUSINESS_NUMBER VARCHAR(200),
	PHARMACY_NAME VARCHAR(1000),
	ENTERDATETIME TIMESTAMP_NTZ(9),
	ENTERUSERNAME VARCHAR(500),
	ENTERVERSIONNUMBER NUMBER(18,0),
	LASTCHGDATETIME TIMESTAMP_NTZ(9),
	LASTCHGUSERNAME VARCHAR(500),
	LASTCHGVERSIONNUMBER NUMBER(18,0),
	VALIDATIONSTATUS VARCHAR(500),
	"FULL ADDRESS" VARCHAR(1000),
	ADDRESS_1 VARCHAR(200),
	ADDRESS_2 VARCHAR(200),
	ADDRESS_3 VARCHAR(200),
	ADDRESS_4 VARCHAR(200),
	HIRA_CODE VARCHAR(200),
	IQVIA_CODE VARCHAR(200),
	SEGMENT_CODE VARCHAR(500),
	SEGMENT_NAME VARCHAR(500),
	SEGMENT_ID NUMBER(10,0),
	X VARCHAR(200),
	Y VARCHAR(200)
);

create or replace TABLE PROD_DNA_LOAD.NTASDL_RAW.SDL_MDS_KR_PRODUCT_ATTRIBUTE (
	ID NUMBER(10,0),
	MUID VARCHAR(40),
	VERSIONNAME VARCHAR(100),
	VERSIONNUMBER NUMBER(10,0),
	VERSION_ID NUMBER(10,0),
	VERSIONFLAG VARCHAR(100),
	NAME VARCHAR(500),
	CODE VARCHAR(500),
	CHANGETRACKINGMASK NUMBER(10,0),
	EAN VARCHAR(200),
	PRODUCT_NAME_L9 VARCHAR(500),
	BRAND_L4 VARCHAR(200),
	BRAND_KR VARCHAR(200),
	VARIANCE_L7 VARCHAR(200),
	VARIANCE_KR VARCHAR(200),
	PACK_SIZE_L8 VARCHAR(200),
	PACK_SIZE_KR VARCHAR(200),
	PRODUCT_NAME_KR VARCHAR(200),
	"127671_PRODUCT CODE" VARCHAR(200),
	"121151_PRODUCT CODE" VARCHAR(200),
	"130973_PRODUCT CODE" VARCHAR(200),
	"130757_PRODUCT CODE" VARCHAR(200),
	"122140_PRODUCT CODE" VARCHAR(200),
	"131993_PRODUCT CODE" VARCHAR(200),
	"121125_PRODUCT CODE" VARCHAR(200),
	"121207_PRODUCT CODE" VARCHAR(200),
	"122935_PRODUCT CODE" VARCHAR(200),
	"121094_PRODUCT CODE" VARCHAR(200),
	"121088_PRODUCT CODE" VARCHAR(200),
	"124424_PRODUCT CODE" VARCHAR(200),
	ENTERDATETIME TIMESTAMP_NTZ(9),
	ENTERUSERNAME VARCHAR(200),
	ENTERVERSIONNUMBER NUMBER(10,0),
	LASTCHGDATETIME TIMESTAMP_NTZ(9),
	LASTCHGUSERNAME VARCHAR(200),
	LASTCHGVERSIONNUMBER NUMBER(10,0),
	VALIDATIONSTATUS VARCHAR(500)
);
