--Korea Market

--Removing duplicated entried from metadata entry
DELETE FROM META_RAW.PROCESS where process_id in (2004, 2005, 2006);
DELETE FROM meta_raw.parameters where parameter_id in  (25022, 25023, 25024, 25025, 25026, 25027, 25028, 25029, 26474, 26656, 26657, 26658, 26659, 26660, 26661, 26662, 26663, 26664, 26665, 26666, 26667, 26668, 26669, 26670, 26671, 26672, 26673);

--Insert New task (table in the MDS Korea Job(s))
INSERT INTO META_RAW.PROCESS VALUES (2004,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute',2004,1,1,FALSE,TRUE,242,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');
INSERT INTO META_RAW.PROCESS VALUES (2005,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute_1',2005,1,1,FALSE,TRUE,254,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');
INSERT INTO META_RAW.PROCESS VALUES (2006,2004,'KR_MDS_Refresh_SDL_MDS_KR_Product_Attribute_2',2006,1,1,FALSE,TRUE,271,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_KOR','','','');

--Insert New parameters
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25022,2004,'SDL_MDS_KR_Product_Attribute_group','container','kor',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25023,2004,'SDL_MDS_KR_Product_Attribute_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25024,2004,'SDL_MDS_KR_Product_Attribute_group','landing_file_name','SDL_MDS_KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25025,2004,'SDL_MDS_KR_Product_Attribute_group','landing_file_path','sql_server/MDS/SDL_MDS_KR_Product_Attribute/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25026,2004,'SDL_MDS_KR_Product_Attribute_group','ms_query','SELECT * FROM MDS.mdm.KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25027,2004,'SDL_MDS_KR_Product_Attribute_group','target_schema','NTASDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25028,2004,'SDL_MDS_KR_Product_Attribute_group','target_table','SDL_MDS_KR_Product_Attribute',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25029,2004,'SDL_MDS_KR_Product_Attribute_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26474,2004,'SDL_MDS_KR_Product_Attribute_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26656,984,'SDL_MDS_KR_sales_cust_prod_master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26657,985,'SDL_MDS_KR_sales_store_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26658,986,'SDL_MDS_KR_sales_store_master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26659,987,'SDL_MDS_KR_pos_store_code_sold_to_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26660,988,'SDL_MDS_KR_Ecom_Offtake_Product_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26661,989,'SDL_MDS_KR_Retailer_Price_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26662,990,'SDL_MDS_KR_Sub_Customer_Master','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26663,991,'SDL_MDS_KR_Target_GROUP','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26664,992,'SDL_MDS_KR_PS_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26665,993,'SDL_MDS_KR_PS_Weights_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26666,994,'SDL_MDS_KR_Product_EAN_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26667,1001,'SDL_MDS_KR_SKU_BENCHMARKS_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26668,995,'SDL_MDS_KR_Cost_Of_Goods_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26669,996,'SDL_MDS_KR_TP_Target_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26670,997,'SDL_MDS_KR_Brand_Campaign_Promotion_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26671,998,'SDL_MDS_KR_Naver_Product_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26672,999,'SDL_MDS_KR_Keyword_Classification_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26673,1000,'SDL_MDS_KR_Product_Hierarchy_group','map_names','Y',FALSE,TRUE);
