INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5030,'IN_EDW','EDW_SKU_RECOM_SPIKE_MSL','PROD_DNA_CORE','INDEDW_INTEGRATION','EDW_SKU_RECOM_SPIKE_MSL_SYNC','UTILITY_RAW',TRUE,'IN_EDW_SKU_RECOM_SPIKE_MSL','FULL_REFRESH',5);

INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5031,'IN_EDW','EDW_RETAILER_DIM','PROD_DNA_CORE','INDEDW_INTEGRATION','EDW_RETAILER_DIM_SYNC','UTILITY_RAW',TRUE,'IN_EDW_RETAILER_DIM','FULL_REFRESH',5);

INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5032,'IN_EDW','EDW_PRODUCT_DIM','PROD_DNA_CORE','INDEDW_INTEGRATION','EDW_PRODUCT_DIM_SYNC','UTILITY_RAW',TRUE,'IN_EDW_PRODUCT_DIM','FULL_REFRESH',5);

INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5033,'IN_EDW','EDW_CUSTOMER_DIM','PROD_DNA_CORE','INDEDW_INTEGRATION','EDW_CUSTOMER_DIM_SYNC','UTILITY_RAW',TRUE,'IN_EDW_CUSTOMER_DIM','FULL_REFRESH',5);


INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5034,'IN_ITG','ITG_UDCDETAILS','PROD_DNA_CORE','INDITG_INTEGRATION','ITG_UDCDETAILS_SYNC','UTILITY_RAW',TRUE,'IN_ITG_UDCDETAILS','FULL_REFRESH',5);

INSERT INTO PROD_DNA_LOAD.META_RAW.HISTORICAL_OBJ_METADATA 
(ID,SOURCE_SCHEMA,SOURCE_TABLE, TARGET_DB,TARGET_SCHEMA,TARGET_TABLE,STAGE_SCHEMA,ISACTIVE,MARKET,TYPE_OF_LOAD,PRIORITY) 
VALUES (5035,'IN_ITG','ITG_IN_MDS_CHANNEL_MAPPING','PROD_DNA_CORE','INDITG_INTEGRATION','ITG_IN_MDS_CHANNEL_MAPPING_SYNC','UTILITY_RAW',TRUE,'IN_ITG_IN_MDS_CHANNEL_MAPPING','FULL_REFRESH',5);
