--TW Market

--Insert New process (table in the MDS TW Job(s))


INSERT INTO META_RAW.PROCESS VALUES (2007,2007,'TW_MDS_refresh_SDL_MDS_TW_MT_Store_Master',2007,1,1,FALSE,TRUE,244,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN','','','');
INSERT INTO META_RAW.PROCESS VALUES (2008,2007,'TW_MDS_refresh_SDL_MDS_TW_MT_Store_Master_1',2008,1,1,FALSE,TRUE,256,5,1,NULL,'','','','NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN','','','');


--Updates in existing Process to follow on the MDS standard
Update META_RAW.PROCESS Set PROCESS_NAME=replace(PROCESS_NAME,'TW_MDS_SDL_MDS','TW_MDS_REFRESH_SDL_MDS')  where  USECASE_ID in ('244','256');


--Insert New parameters

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25030,2007,'SDL_MDS_TW_MT_Store_Master_group','container','twn',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25031,2007,'SDL_MDS_TW_MT_Store_Master_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25032,2007,'SDL_MDS_TW_MT_Store_Master_group','landing_file_name','SDL_MDS_TW_MT_Store_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25033,2007,'SDL_MDS_TW_MT_Store_Master_group','landing_file_path','sql_server/MDS/SDL_MDS_TW_MT_Store_Master/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25034,2007,'SDL_MDS_TW_MT_Store_Master_group','ms_query','SELECT * FROM MDS.mdm.TW_MT_Store_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25035,2007,'SDL_MDS_TW_MT_Store_Master_group','target_schema','NTASDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25036,2007,'SDL_MDS_TW_MT_Store_Master_group','target_table','SDL_MDS_TW_MT_Store_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25037,2007,'SDL_MDS_TW_MT_Store_Master_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26475,2007,'SDL_MDS_TW_MT_Store_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26674,1015,'SDL_MDS_TW_ims_dstr_customer_mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26675,1016,'SDL_MDS_TW_ims_dstr_prod_price_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26676,1017,'SDL_MDS_TW_pos_promotional_price_ean_map_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26677,1018,'SDL_MDS_TW_SFMC_Channel_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26678,1019,'SDL_MDS_TW_SFMC_Gender_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26679,1020,'SDL_MDS_TW_SFMC_Member_Tier_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26680,1021,'SDL_MDS_TW_PS_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26681,1022,'SDL_MDS_TW_PS_Weights_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26682,1023,'SDL_MDS_TW_ECOM_PRODUCT_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26683,1024,'SDL_MDS_TW_SKU_BENCHMARKS_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26684,1025,'SDL_MDS_TW_Customer_Hierarchy_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26685,1026,'SDL_MDS_TW_Sales_Representative_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26686,1027,'SDL_MDS_TW_Incentive_Schemes_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26687,1028,'SDL_MDS_TW_Customer_Sales_Rep_Mapping_group','map_names','Y',FALSE,TRUE);


--Updates in existing parameters to follow on the MDS standard

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = Replace(PARAMETER_VALUE, 'TW_MDSProd_to_RedshiftProd','MDS')
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_TW_%' 
and PARAMETER_NAME = 'landing_file_path';

UPDATE META_RAW.PARAMETERS
SET PARAMETER_GROUP_NAME = concat(PARAMETER_GROUP_NAME, '_group')
where parameter_group_name like 'SDL_MDS_TW_%'
and parameter_group_name not like '%_group'
and PARAMETER_GROUP_ID in ('1017', '1021', '1022', '1023', '1024', '1025', '1026', '1027', '1028');

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = Concat('SELECT * FROM MDS.mdm.', Replace(Replace(parameter_group_name,'_group',''), 'SDL_MDS_',''))
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_TW_%' 
and PARAMETER_NAME = 'ms_query'
and PARAMETER_ID  in (12735, 12775, 12783, 12791, 12807);

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE = Concat('SELECT * FROM MDS.mdm.', Replace(Replace(parameter_group_name,'_group',''), 'SDL_MDS_',''), 'where ValidationStatus <>''Validation failed''')
WHERE PARAMETER_GROUP_NAME like 'SDL_MDS_TW_%' 
and PARAMETER_NAME = 'ms_query'
and PARAMETER_ID in (12743, 12751);

UPDATE META_RAW.PARAMETERS
SET PARAMETER_GROUP_NAME = Replace(PARAMETER_GROUP_NAME, '_GROUP','_group')
where parameter_group_name like 'SDL_MDS_TW_%'
and parameter_group_name not like '%_group'
and PARAMETER_GROUP_ID = 1018;

--DDL Creation


CREATE OR REPLACE TABLE PROD_DNA_LOAD.NTASDL_RAW.SDL_MDS_TW_MT_STORE_MASTER 
(ID NUMBER(10,0),
MUID VARCHAR(40),
VERSIONNAME VARCHAR(100),
VERSIONNUMBER NUMBER(10,0),
VERSION_ID NUMBER(10,0),
VERSIONFLAG VARCHAR(100),
NAME VARCHAR(500),
CODE VARCHAR(500),
CHANGETRACKINGMASK NUMBER(10,0),
SAP_CUSTOMER_NUMBER_CODE VARCHAR(500),
SAP_CUSTOMER_NUMBER_NAME VARCHAR(500),
SAP_CUSTOMER_NUMBER_ID NUMBER(10,0),
STORE_CODE VARCHAR(200),
STORE_NAME VARCHAR(200),
DISTRICT_CODE VARCHAR(500),
DISTRICT_NAME VARCHAR(500),
DISTRICT_ID NUMBER(10,0),
STORE_TYPE_CODE VARCHAR(500),
STORE_TYPE_NAME VARCHAR(500),
STORE_TYPE_ID NUMBER(10,0),
STORE_STATUS_CODE VARCHAR(500),
STORE_STATUS_NAME VARCHAR(500),
STORE_STATUS_ID NUMBER(10,0),
CHANNEL VARCHAR(200),
"RETAIL ENVIRONMENT (PS)_CODE" VARCHAR(500),
"RETAIL ENVIRONMENT (PS)_NAME" VARCHAR(500),
"RETAIL ENVIRONMENT (PS)_ID" NUMBER(10,0),
"CUSTOMER GRADE" VARCHAR(200),
ENTERDATETIME TIMESTAMP_NTZ(9),
ENTERUSERNAME VARCHAR(200),
ENTERVERSIONNUMBER NUMBER(10,0),
LASTCHGDATETIME TIMESTAMP_NTZ(9),
LASTCHGUSERNAME VARCHAR(200),
LASTCHGVERSIONNUMBER NUMBER(10,0),
VALIDATIONSTATUS VARCHAR(500));
