--MY Market

-- Delete existing process and Parameters and utilising for another process as its reduntant

--Update Active flag to false to stop CData Ingestion

UPDATE META_RAW.PROCESS 
SET Is_Active = false
where process_id = 89;

UPDATE META_RAW.PARAMETERS 
SET Is_Active = false
where parameter_group_id = 89;


--Insert New process (table in the MDS MY Job(s))

INSERT INTO META_RAW.PROCESS VALUES (2042,2042,'MALAYSIA_MDS_SDL_MDS_MY_Customer_Hierarchy',2042,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2043,2043,'MALAYSIA_MDS_SDL_MDS_MY_Distributor_Hierarchy',2043,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2044,2044,'MALAYSIA_MDS_SDL_MDS_MY_ECOM_PRODUCT',2044,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2045,2045,'MALAYSIA_MDS_SDL_MDS_MY_GT_OutletAttributes',2045,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2046,2046,'MALAYSIA_MDS_SDL_MDS_MY_GT_Product_Mapping',2046,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2047,2047,'MALAYSIA_MDS_SDL_MDS_MY_Product_Master',2047,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2048,2048,'MALAYSIA_MDS_SDL_MDS_MY_PS_MSL',2048,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2049,2049,'MALAYSIA_MDS_SDL_MDS_MY_PS_Targets',2049,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2050,2050,'MALAYSIA_MDS_SDL_MDS_MY_PS_Weights',2050,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2051,2051,'MALAYSIA_MDS_SDL_MDS_MY_SKU_BENCHMARKS',2051,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2052,2052,'MALAYSIA_MDS_SDL_MDS_MY_Targets',2052,1,1,FALSE,TRUE,41,5,1,NULL,'','','','MYSSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');


--Updates in existing Process to follow on the MDS standard



--Insert New parameters 

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25311,2042,'SDL_MDS_MY_Customer_Hierarchy_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25312,2042,'SDL_MDS_MY_Customer_Hierarchy_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25313,2042,'SDL_MDS_MY_Customer_Hierarchy_group','landing_file_name','SDL_MDS_MY_Customer_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25314,2042,'SDL_MDS_MY_Customer_Hierarchy_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_Customer_Hierarchy/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25315,2042,'SDL_MDS_MY_Customer_Hierarchy_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_Customer_Hierarchy]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25316,2042,'SDL_MDS_MY_Customer_Hierarchy_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25317,2042,'SDL_MDS_MY_Customer_Hierarchy_group','target_table','SDL_MDS_MY_Customer_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25318,2042,'SDL_MDS_MY_Customer_Hierarchy_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26507,2042,'SDL_MDS_MY_Customer_Hierarchy_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25319,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25320,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25321,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','landing_file_name','SDL_MDS_MY_Distributor_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25322,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_Distributor_Hierarchy/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25323,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_Distributor_Hierarchy]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25324,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25325,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','target_table','SDL_MDS_MY_Distributor_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25326,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26508,2043,'SDL_MDS_MY_Distributor_Hierarchy_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25327,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25328,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25329,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','landing_file_name','SDL_MDS_MY_ECOM_PRODUCT',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25330,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_ECOM_PRODUCT/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25331,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_ECOM_PRODUCT]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25332,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25333,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','target_table','SDL_MDS_MY_ECOM_PRODUCT',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25334,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26509,2044,'SDL_MDS_MY_ECOM_PRODUCT_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25335,2045,'SDL_MDS_MY_GT_OutletAttributes_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25336,2045,'SDL_MDS_MY_GT_OutletAttributes_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25337,2045,'SDL_MDS_MY_GT_OutletAttributes_group','landing_file_name','SDL_MDS_MY_GT_OutletAttributes',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25338,2045,'SDL_MDS_MY_GT_OutletAttributes_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_GT_OutletAttributes/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25339,2045,'SDL_MDS_MY_GT_OutletAttributes_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_GT_OutletAttributes]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25340,2045,'SDL_MDS_MY_GT_OutletAttributes_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25341,2045,'SDL_MDS_MY_GT_OutletAttributes_group','target_table','SDL_MDS_MY_GT_OutletAttributes',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25342,2045,'SDL_MDS_MY_GT_OutletAttributes_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26510,2045,'SDL_MDS_MY_GT_OutletAttributes_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25343,2046,'SDL_MDS_MY_GT_Product_Mapping_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25344,2046,'SDL_MDS_MY_GT_Product_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25345,2046,'SDL_MDS_MY_GT_Product_Mapping_group','landing_file_name','SDL_MDS_MY_GT_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25346,2046,'SDL_MDS_MY_GT_Product_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_GT_Product_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25347,2046,'SDL_MDS_MY_GT_Product_Mapping_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_GT_Product_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25348,2046,'SDL_MDS_MY_GT_Product_Mapping_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25349,2046,'SDL_MDS_MY_GT_Product_Mapping_group','target_table','SDL_MDS_MY_GT_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25350,2046,'SDL_MDS_MY_GT_Product_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26511,2046,'SDL_MDS_MY_GT_Product_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25351,2047,'SDL_MDS_MY_Product_Master_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25352,2047,'SDL_MDS_MY_Product_Master_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25353,2047,'SDL_MDS_MY_Product_Master_group','landing_file_name','SDL_MDS_MY_Product_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25354,2047,'SDL_MDS_MY_Product_Master_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_Product_Master/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25355,2047,'SDL_MDS_MY_Product_Master_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_Product_Master]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25356,2047,'SDL_MDS_MY_Product_Master_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25357,2047,'SDL_MDS_MY_Product_Master_group','target_table','SDL_MDS_MY_Product_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25358,2047,'SDL_MDS_MY_Product_Master_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26512,2047,'SDL_MDS_MY_Product_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25359,2048,'SDL_MDS_MY_PS_MSL_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25360,2048,'SDL_MDS_MY_PS_MSL_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25361,2048,'SDL_MDS_MY_PS_MSL_group','landing_file_name','SDL_MDS_MY_PS_MSL',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25362,2048,'SDL_MDS_MY_PS_MSL_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_PS_MSL/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25363,2048,'SDL_MDS_MY_PS_MSL_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_PS_MSL]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25364,2048,'SDL_MDS_MY_PS_MSL_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25365,2048,'SDL_MDS_MY_PS_MSL_group','target_table','SDL_MDS_MY_PS_MSL',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25366,2048,'SDL_MDS_MY_PS_MSL_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26513,2048,'SDL_MDS_MY_PS_MSL_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25367,2049,'SDL_MDS_MY_PS_Targets_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25368,2049,'SDL_MDS_MY_PS_Targets_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25369,2049,'SDL_MDS_MY_PS_Targets_group','landing_file_name','SDL_MDS_MY_PS_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25370,2049,'SDL_MDS_MY_PS_Targets_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_PS_Targets/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25371,2049,'SDL_MDS_MY_PS_Targets_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_PS_Targets]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25372,2049,'SDL_MDS_MY_PS_Targets_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25373,2049,'SDL_MDS_MY_PS_Targets_group','target_table','SDL_MDS_MY_PS_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25374,2049,'SDL_MDS_MY_PS_Targets_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26514,2049,'SDL_MDS_MY_PS_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25375,2050,'SDL_MDS_MY_PS_Weights_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25376,2050,'SDL_MDS_MY_PS_Weights_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25377,2050,'SDL_MDS_MY_PS_Weights_group','landing_file_name','SDL_MDS_MY_PS_Weights',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25378,2050,'SDL_MDS_MY_PS_Weights_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_PS_Weights/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25379,2050,'SDL_MDS_MY_PS_Weights_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_PS_Weights]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25380,2050,'SDL_MDS_MY_PS_Weights_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25381,2050,'SDL_MDS_MY_PS_Weights_group','target_table','SDL_MDS_MY_PS_Weights',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25382,2050,'SDL_MDS_MY_PS_Weights_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26515,2050,'SDL_MDS_MY_PS_Weights_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25383,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25384,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25385,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','landing_file_name','SDL_MDS_MY_SKU_BENCHMARKS',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25386,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_SKU_BENCHMARKS/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25387,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_SKU_BENCHMARKS]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25388,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25389,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','target_table','SDL_MDS_MY_SKU_BENCHMARKS',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25390,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26516,2051,'SDL_MDS_MY_SKU_BENCHMARKS_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25391,2052,'SDL_MDS_MY_Targets_group','container','mys',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25392,2052,'SDL_MDS_MY_Targets_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25393,2052,'SDL_MDS_MY_Targets_group','landing_file_name','SDL_MDS_MY_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25394,2052,'SDL_MDS_MY_Targets_group','landing_file_path','sql_server/MDS/SDL_MDS_MY_Targets/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25395,2052,'SDL_MDS_MY_Targets_group','ms_query','SELECT * FROM [MDS].[MDM].[MY_Targets]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25396,2052,'SDL_MDS_MY_Targets_group','target_schema','MYSSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25397,2052,'SDL_MDS_MY_Targets_group','target_table','SDL_MDS_MY_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25398,2052,'SDL_MDS_MY_Targets_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26517,2052,'SDL_MDS_MY_Targets_group','map_names','Y',FALSE,TRUE);


--Updates in existing parameters to follow on the MDS standard

