use database PROD_DNA_LOAD;
use schema meta_raw;

INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (520,69,'','itx-arm-conapdna-aspac-prod-kdp','Regional/6PAI_Edge/','6P_AI_Calculated','asp','Regional/transaction/6PAI_Edge/',TRUE,'Y');
INSERT INTO s3_to_adls(id,group_id,country,s3_bucket,s3_path,s3_file,adls_container,adls_path,Isactive,DELETE_SOURCE_FILE) VALUES (555,69,'CHN','itx-arm-conapdna-aspac-prod-kdp','raw-data-lake/OKR/Alteryx/','OKR_Alteryx','asp','OKR/transaction/Alteryx/',TRUE,'Y');


INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (362,'RG_PROX_Ingestion','RG_PROX_Ingestion','PROX Ingestion files','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (350,'Ecommerce_6PAI_Ingestion','Ecommerce_Ingestion','6P_AI_Calculated file ingestion','TRUE',1);
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (374,'OKR_Alteryx_Data_Ingestion','OKR_ALTERYX_INGESTION','OKR_Alteryx_Data_Ingestion file','TRUE',1);


INSERT INTO PROCESS VALUES (1904,1904,'RG_PROX_Material_extraction',1904,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1905,1905,'RG_PROX_Material_ingestion',1905,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1906,1906,'RG_PROX_PPGAllocation_extraction',1906,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1907,1907,'RG_PROX_PPGAllocation_ingestion',1907,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1908,1908,'RG_PROX_Theme_extraction',1908,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1909,1909,'RG_PROX_Theme_ingestion',1909,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1910,1910,'RG_PROX_Department_extraction',1910,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1911,1911,'RG_PROX_Department_ingestion',1911,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1912,1912,'RG_PROX_Budget_extraction',1912,1,1,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1913,1913,'RG_PROX_Budget_ingestion',1913,1,2,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1917,1917,'RG_PROX_Contract_extraction',1917,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1918,1918,'RG_PROX_Contract_ingestion',1918,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1919,1919,'RG_PROX_Payment_extraction',1919,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1920,1920,'RG_PROX_Payment_ingestion',1920,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1921,1921,'RG_PROX_MonthCommitment_extraction',1921,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1922,1922,'RG_PROX_MonthCommitment_ingestion',1922,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1923,1923,'RG_PROX_AccGroup_extraction',1923,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1924,1924,'RG_PROX_AccGroup_ingestion',1924,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1925,1925,'RG_PROX_Channel_extraction',1925,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1926,1926,'RG_PROX_Channel_ingestion',1926,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1927,1927,'RG_PROX_Customer_extraction',1927,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1928,1928,'RG_PROX_Customer_ingestion',1928,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1929,1929,'RG_PROX_ExpenseType_extraction',1929,1,3,FALSE,TRUE,362,5,1,NULL,'','','','','','','');	
INSERT INTO PROCESS VALUES (1930,1930,'RG_PROX_ExpenseType_ingestion',1930,1,4,FALSE,TRUE,362,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','ASPSDL_RAW.CSV_FILE_FORMAT_SOH','','');	
INSERT INTO PROCESS VALUES (1821,1821,'Ecommerce_6PAI_Ingestion',1821,1,1,FALSE,TRUE,350,1,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','','','');
INSERT INTO PROCESS VALUES (1968,1968,'OKR_Alteryx_Data_Ingestion',1968,1,1,FALSE,TRUE,374,NULL,1,NULL,'','','','ASPSDL_RAW.DEV_LOAD_STAGE_ADLS','','','');




INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21099,1904,'RG_PROX_Material_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21100,1904,'RG_PROX_Material_extraction_group','landing_file_path','PRO-X/transaction/MD_Material/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21101,1904,'RG_PROX_Material_extraction_group','landing_file_name','MD_Material',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21102,1904,'RG_PROX_Material_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21103,1904,'RG_PROX_Material_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21104,1904,'RG_PROX_Material_extraction_group','ms_query','select
ID
,Division
,Segment
,MaterialCode
,MaterialName
,MaterialType
,MaterialNameLocal
,BusinessSegmentCode
,RepresentativeItem
,BusinessSegmentName
,MarketSegmentCode
,MarketSegmentName
,ProfitCenter
,BrandName
,BrandCode
,SubBrandCode
,SubBrandName
,PackSizeCode
,PackSizeDesc
,PackSizeGroupCode
,PackSizeGroupDesc
,Plant
,Type
,Bundle
,BaseUnit
,SalesUnit
,ListPrice
,StandardPrice
,IsSensitive
,FlavorCode
,FlavorName
,IsNew
,Status
,FinanceYear
,Comment
,ApplicationID
,Version
,LastModifyUserID
,LastModifyTime
,PackgeCode
,PackgeName
,MarketSegmentDesc
,BarCode
,RepresentativeCode
,RepresentativeName
,RepresentativeNameEn
,SKUAttr
,CategoryCode
,CategoryName
,MaterialStatus
,TDUBarCode
,MCUBarCode
,RSUBarCode
,ProductType
,TradedUnitConfiguration
 from JNJ_TPM.[dbo].[MD_Material];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21105,1904,'RG_PROX_Material_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21106,1904,'RG_PROX_Material_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21107,1904,'RG_PROX_Material_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21108,1904,'RG_PROX_Material_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21109,1905,'RG_PROX_Material_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21110,1905,'RG_PROX_Material_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21111,1905,'RG_PROX_Material_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21112,1905,'RG_PROX_Material_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21113,1905,'RG_PROX_Material_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21114,1905,'RG_PROX_Material_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21115,1905,'RG_PROX_Material_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21116,1905,'RG_PROX_Material_ingestion_group','target_table','sdl_PROX_MD_Material',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21117,1905,'RG_PROX_Material_ingestion_group','folder_path','PRO-X/transaction/MD_Material/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21118,1905,'RG_PROX_Material_ingestion_group','file_spec','MD_Material',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21119,1905,'RG_PROX_Material_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21120,1906,'RG_PROX_PPGAllocation_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21121,1906,'RG_PROX_PPGAllocation_extraction_group','landing_file_path','PRO-X/transaction/MD_PPGAllocation/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21122,1906,'RG_PROX_PPGAllocation_extraction_group','landing_file_name','MD_PPGAllocation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21123,1906,'RG_PROX_PPGAllocation_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21124,1906,'RG_PROX_PPGAllocation_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21125,1906,'RG_PROX_PPGAllocation_extraction_group','ms_query','select
ID
,PPGCode
,MaterialCode
,AllocationRate
,Status
,ApplicationID
,CreateTime
,CreateUserID
,LastModifyTime
,LastModifyUserID
,BatchNo
 from JNJ_TPM.[dbo].[MD_PPGAllocation];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21126,1906,'RG_PROX_PPGAllocation_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21127,1906,'RG_PROX_PPGAllocation_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21128,1906,'RG_PROX_PPGAllocation_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21129,1906,'RG_PROX_PPGAllocation_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21130,1907,'RG_PROX_PPGAllocation_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21131,1907,'RG_PROX_PPGAllocation_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21132,1907,'RG_PROX_PPGAllocation_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21133,1907,'RG_PROX_PPGAllocation_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21134,1907,'RG_PROX_PPGAllocation_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21135,1907,'RG_PROX_PPGAllocation_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21136,1907,'RG_PROX_PPGAllocation_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21137,1907,'RG_PROX_PPGAllocation_ingestion_group','target_table','sdl_PROX_MD_PPGAllocation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21138,1907,'RG_PROX_PPGAllocation_ingestion_group','folder_path','PRO-X/transaction/MD_PPGAllocation/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21139,1907,'RG_PROX_PPGAllocation_ingestion_group','file_spec','MD_PPGAllocation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21140,1907,'RG_PROX_PPGAllocation_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21141,1908,'RG_PROX_Theme_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21142,1908,'RG_PROX_Theme_extraction_group','landing_file_path','PRO-X/transaction/MD_Theme/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21143,1908,'RG_PROX_Theme_extraction_group','landing_file_name','MD_Theme',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21144,1908,'RG_PROX_Theme_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21145,1908,'RG_PROX_Theme_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21146,1908,'RG_PROX_Theme_extraction_group','ms_query','select
ID
,ThemeCode
,ThemeName
,ExpenseSubCategory
,ExpenseTypeCode
,CreateUserID
,Status
,CreateTime
,LastModifyTime
,LastModifyUserID
,ApplicationID
 from JNJ_TPM.[dbo].[MD_Theme];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21147,1908,'RG_PROX_Theme_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21148,1908,'RG_PROX_Theme_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21149,1908,'RG_PROX_Theme_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21150,1908,'RG_PROX_Theme_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21151,1909,'RG_PROX_Theme_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21152,1909,'RG_PROX_Theme_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21153,1909,'RG_PROX_Theme_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21154,1909,'RG_PROX_Theme_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21155,1909,'RG_PROX_Theme_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21156,1909,'RG_PROX_Theme_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21157,1909,'RG_PROX_Theme_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21158,1909,'RG_PROX_Theme_ingestion_group','target_table','sdl_PROX_MD_Theme',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21159,1909,'RG_PROX_Theme_ingestion_group','folder_path','PRO-X/transaction/MD_Theme/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21160,1909,'RG_PROX_Theme_ingestion_group','file_spec','MD_Theme',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21161,1909,'RG_PROX_Theme_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21162,1910,'RG_PROX_Department_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21163,1910,'RG_PROX_Department_extraction_group','landing_file_path','PRO-X/transaction/Sys_Department/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21164,1910,'RG_PROX_Department_extraction_group','landing_file_name','Sys_Department',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21165,1910,'RG_PROX_Department_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21166,1910,'RG_PROX_Department_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21167,1910,'RG_PROX_Department_extraction_group','ms_query','select
DeptID ,
DeptCode  ,
DeptName  ,
DeptNameEN  ,
ParentID  ,
LevelID  ,
SortID ,
Status ,
ApplicationID ,
Col1  ,
Col2  ,
Col3  ,
Version  ,
OrgPath ,
OrgType  ,
CostCenter  ,
CostCenterName ,
LocationCode ,
OrgCode  ,
CreateUserID  ,
CreateTime   ,
LastModifyUserID  ,
LastModifyTime
 from JNJ_TPM.[dbo].[Sys_Department];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21168,1910,'RG_PROX_Department_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21169,1910,'RG_PROX_Department_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21170,1910,'RG_PROX_Department_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21171,1910,'RG_PROX_Department_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21172,1911,'RG_PROX_Department_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21173,1911,'RG_PROX_Department_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21174,1911,'RG_PROX_Department_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21175,1911,'RG_PROX_Department_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21176,1911,'RG_PROX_Department_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21177,1911,'RG_PROX_Department_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21178,1911,'RG_PROX_Department_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21179,1911,'RG_PROX_Department_ingestion_group','target_table','sdl_PROX_Sys_Department',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21180,1911,'RG_PROX_Department_ingestion_group','folder_path','PRO-X/transaction/Sys_Department/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21181,1911,'RG_PROX_Department_ingestion_group','file_spec','Sys_Department',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21182,1911,'RG_PROX_Department_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21183,1912,'RG_PROX_Budget_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21184,1912,'RG_PROX_Budget_extraction_group','landing_file_path','PRO-X/transaction/Report_BI_BudgetUsage/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21185,1912,'RG_PROX_Budget_extraction_group','landing_file_name','Report_BI_BudgetUsage',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21186,1912,'RG_PROX_Budget_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21187,1912,'RG_PROX_Budget_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21188,1912,'RG_PROX_Budget_extraction_group','ms_query','select
RowID
,BudgetYear
,ExpenseSubCategory
,BudgetType
,AccountGroupCode
,AccountGroupName
,BrandCode
,BrandName
,BudgetAmount
,UsedBudget
,BudgetBalance
,YTDCommitment
,YTGCommitment
,Commitment
,PendingAmount
,Paid
,ApprovedPayment
,PendingApprovalPayment
,AvailableToPay
,DraftAmount
,BudgetOwner
,Channel
,SubChannel
,ApplicationID
from JNJ_TPM.[dbo].[Report_BI_BudgetUsage]
where budgetyear in (YEAR(GETDATE()),YEAR(GETDATE())-1);',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21189,1912,'RG_PROX_Budget_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21190,1912,'RG_PROX_Budget_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21191,1912,'RG_PROX_Budget_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21192,1912,'RG_PROX_Budget_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21193,1913,'RG_PROX_Budget_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21194,1913,'RG_PROX_Budget_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21195,1913,'RG_PROX_Budget_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21196,1913,'RG_PROX_Budget_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21197,1913,'RG_PROX_Budget_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21198,1913,'RG_PROX_Budget_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21199,1913,'RG_PROX_Budget_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21200,1913,'RG_PROX_Budget_ingestion_group','target_table','sdl_PROX_Report_BI_BudgetUsage',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21201,1913,'RG_PROX_Budget_ingestion_group','folder_path','PRO-X/transaction/Report_BI_BudgetUsage/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21202,1913,'RG_PROX_Budget_ingestion_group','file_spec','Report_BI_BudgetUsage',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21203,1913,'RG_PROX_Budget_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21230,1917,'RG_PROX_Contract_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21231,1917,'RG_PROX_Contract_extraction_group','landing_file_path','PRO-X/transaction/Report_BI_Contract/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21232,1917,'RG_PROX_Contract_extraction_group','landing_file_name','Report_BI_Contract',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21233,1917,'RG_PROX_Contract_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21234,1917,'RG_PROX_Contract_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21235,1917,'RG_PROX_Contract_extraction_group','ms_query','select  RowID,BudgetYear,ExpenseSubCategory,AccountGroupCode,AccountGroupName,CustomerType,HQSoldToCode,HQSoldToName,ContractNo,ContractTempNo,ContractTitle,ThemeCode,ThemeName,Objective,FeesPaid,ContractRevenueRecognitionStartDate,ContractRevenueRecognitionEndDate,ContractPromoExecutionStartDate,ContractPromoExecutionEndDate,ContractCreateDate,ContractApprovalDate,ContractStatus,DateBack,DateBackReason,ExpenseID,CustomerCode,
REPLACE(REPLACE(replace(CustomerName,'','','' ''), CHAR(13), ''''), CHAR(10), '''')as CustomerName ,
RebateNo,RebateActivityName,CustomerContractNo,ExpenseRevenueRecognitionStartDate,ExpenseRevenueRecognitionEndDate,ExpensePromoExecutionStartDate,ExpensePromoExecutionEndDate,ExpenseClosed,CloseUser,CloseTime,ContractType,ConditionType,GLAccount,ExpenseTypeName,ProfitCenter,PPGCode,PPGName,Rate,MaterialCode,MaterialName,BudgetOwner,Channel,RTMChannel,PaymentMethod,ExpenseAmount,CommitmentAmount,AccrualReleaseAmountWithoutTax,CloseAmount,PaidAmount,ApprovedAmount,UnpaidAmount,AvailableToPay,AgingDays,Aging,Applicant,
--REPLACE(REPLACE(ContractDescription, CHAR(13), ''''), CHAR(10), '''')as ContractDescription,REPLACE(REPLACE(DocumentLink, CHAR(13), ''''), CHAR(10), '''')as DocumentLink,
''NA'' as ContractDescription,''NA'' as DocumentLink,
WithAttachment,DTSMarkupRate,ApplicationID
from JNJ_TPM.[dbo].[Report_BI_Contract]
where budgetyear in (YEAR(GETDATE()),YEAR(GETDATE())-1);',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21236,1917,'RG_PROX_Contract_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21237,1917,'RG_PROX_Contract_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21238,1917,'RG_PROX_Contract_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21239,1917,'RG_PROX_Contract_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21240,1918,'RG_PROX_Contract_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21241,1918,'RG_PROX_Contract_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21242,1918,'RG_PROX_Contract_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21243,1918,'RG_PROX_Contract_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21244,1918,'RG_PROX_Contract_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21245,1918,'RG_PROX_Contract_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21246,1918,'RG_PROX_Contract_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21247,1918,'RG_PROX_Contract_ingestion_group','target_table','sdl_PROX_Report_BI_Contract',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21248,1918,'RG_PROX_Contract_ingestion_group','folder_path','PRO-X/transaction/Report_BI_Contract/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21249,1918,'RG_PROX_Contract_ingestion_group','file_spec','Report_BI_Contract',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21250,1918,'RG_PROX_Contract_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21251,1919,'RG_PROX_Payment_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21252,1919,'RG_PROX_Payment_extraction_group','landing_file_path','PRO-X/transaction/Report_BI_Payment/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21253,1919,'RG_PROX_Payment_extraction_group','landing_file_name','Report_BI_Payment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21254,1919,'RG_PROX_Payment_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21255,1919,'RG_PROX_Payment_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21256,1919,'RG_PROX_Payment_extraction_group','ms_query','select RowID,BudgetYear,PaymentNo,PaymentStatus,AccountGroupCode,AccountGroupName,PayToCode,PayToName,ExpenseSubCategory,PaymentTitle,ReverseNo,OldReverseNo,InvoiceNumber,InvoiceType,SAPDocNumber,SAPDocDate,PaymentMethod,PaymentAmountwithoutTax,InvoiceAmountwithoutTax,VatCode,VATAmount,WHTCode,WHTAmount,AmountPayable,
--REPLACE(REPLACE(SupportingDocuments, CHAR(13), ''''), CHAR(10), '''') as SupportingDocuments,
''NA'' as SupportingDocuments,
CurrentApprovalUser,RejectReason,ContractNo,ContractNoTemp,ThemeCode,ThemeName,ExpenseRevenueRecognitionStartDate,ExpenseRevenueRecognitionEndDate,ExpensePromoExecutionStartDate,ExpensePromoExecutionEndDate,PaymentStartDate,PaymentEndDate,AutoAllocate,Parked,PayFromAccrual,AccrualGLAccount,GLAccount,ExpenseTypeName,ProfitCenter,MaterialCode,MaterialName,ContractOriginalAmount,ContractAvailableToPay,PlannedBalance,SAPRebateNo,RebateSettlementNo,SAPCMNo,SAPCMDate,ContractStatus,ContractDetailStatus,CreateUser,CreateTime,Applicant,ApplicantDate,ApproveDate,PostingDate,PostingPeriod,FillingID,BudgetOwner,Channel,RTMChannel,EndToEndLeadTime,SalesInputLeadTime,SalesApprovalLeadTime,MRC,PrintATDDate,InvoiceNoVat,InvoiceNoWHT,BusinessTaxCode,BusinessTaxAmount,BusinessTax,ApplicationID,ExpenseID,ContractTitle from JNJ_TPM.[dbo].[Report_BI_Payment]
where budgetyear in (YEAR(GETDATE()),YEAR(GETDATE())-1);',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21257,1919,'RG_PROX_Payment_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21258,1919,'RG_PROX_Payment_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21259,1919,'RG_PROX_Payment_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21260,1919,'RG_PROX_Payment_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21261,1920,'RG_PROX_Payment_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21262,1920,'RG_PROX_Payment_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21263,1920,'RG_PROX_Payment_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21264,1920,'RG_PROX_Payment_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21265,1920,'RG_PROX_Payment_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21266,1920,'RG_PROX_Payment_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21267,1920,'RG_PROX_Payment_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21268,1920,'RG_PROX_Payment_ingestion_group','target_table','sdl_PROX_Report_BI_Payment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21269,1920,'RG_PROX_Payment_ingestion_group','folder_path','PRO-X/transaction/Report_BI_Payment/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21270,1920,'RG_PROX_Payment_ingestion_group','file_spec','Report_BI_Payment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21271,1920,'RG_PROX_Payment_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21272,1921,'RG_PROX_MonthCommitment_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21273,1921,'RG_PROX_MonthCommitment_extraction_group','landing_file_path','PRO-X/transaction/Report_BI_MonthCommitment/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21274,1921,'RG_PROX_MonthCommitment_extraction_group','landing_file_name','Report_BI_MonthCommitment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21275,1921,'RG_PROX_MonthCommitment_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21276,1921,'RG_PROX_MonthCommitment_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21277,1921,'RG_PROX_MonthCommitment_extraction_group','ms_query','select
RowID
,ContractNo
,ExpenseID
,Year
,ExpenseMonth
,FinanceMonth
,Commitment
,Flag
,ApplicationID
 from JNJ_TPM.[dbo].[Report_BI_MonthCommitment]
where year in (YEAR(GETDATE()),YEAR(GETDATE())-1);',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21278,1921,'RG_PROX_MonthCommitment_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21279,1921,'RG_PROX_MonthCommitment_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21280,1921,'RG_PROX_MonthCommitment_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21281,1921,'RG_PROX_MonthCommitment_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21282,1922,'RG_PROX_MonthCommitment_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21283,1922,'RG_PROX_MonthCommitment_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21284,1922,'RG_PROX_MonthCommitment_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21285,1922,'RG_PROX_MonthCommitment_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21286,1922,'RG_PROX_MonthCommitment_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21287,1922,'RG_PROX_MonthCommitment_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21288,1922,'RG_PROX_MonthCommitment_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21289,1922,'RG_PROX_MonthCommitment_ingestion_group','target_table','sdl_PROX_Report_BI_MonthCommitment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21290,1922,'RG_PROX_MonthCommitment_ingestion_group','folder_path','PRO-X/transaction/Report_BI_MonthCommitment/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21291,1922,'RG_PROX_MonthCommitment_ingestion_group','file_spec','Report_BI_MonthCommitment',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21292,1922,'RG_PROX_MonthCommitment_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21302,1923,'RG_PROX_AccGroup_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21303,1923,'RG_PROX_AccGroup_extraction_group','landing_file_path','PRO-X/transaction/MD_AccountGroup/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21304,1923,'RG_PROX_AccGroup_extraction_group','landing_file_name','MD_AccountGroup',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21305,1923,'RG_PROX_AccGroup_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21306,1923,'RG_PROX_AccGroup_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21307,1923,'RG_PROX_AccGroup_extraction_group','ms_query','select
 ID
,Division
,Segment
,AccountGroupCode
,AccountGroupName
,ChannelCode
,SubChannelCode
,AccountCategory
,AccountChainCode
,AccountChainName
,DirectSupplier
,HeadquarterSoldToCode
,DistributorCode
,Status
,Comment
,ApplicationID
,Version
,LastModifyUserID
,LastModifyTime
,DataSource
,PlanRequired
,AccountGroupType
,RTMChannelCode
 from JNJ_TPM.[dbo].[MD_AccountGroup];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21308,1923,'RG_PROX_AccGroup_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21309,1923,'RG_PROX_AccGroup_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21310,1923,'RG_PROX_AccGroup_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21311,1923,'RG_PROX_AccGroup_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21312,1924,'RG_PROX_AccGroup_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21313,1924,'RG_PROX_AccGroup_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21314,1924,'RG_PROX_AccGroup_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21315,1924,'RG_PROX_AccGroup_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21316,1924,'RG_PROX_AccGroup_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21317,1924,'RG_PROX_AccGroup_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21318,1924,'RG_PROX_AccGroup_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21319,1924,'RG_PROX_AccGroup_ingestion_group','target_table','sdl_PROX_MD_AccountGroup',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21320,1924,'RG_PROX_AccGroup_ingestion_group','folder_path','PRO-X/transaction/MD_AccountGroup/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21321,1924,'RG_PROX_AccGroup_ingestion_group','file_spec','MD_AccountGroup',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21322,1924,'RG_PROX_AccGroup_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21323,1925,'RG_PROX_Channel_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21324,1925,'RG_PROX_Channel_extraction_group','landing_file_path','PRO-X/transaction/MD_Channel/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21325,1925,'RG_PROX_Channel_extraction_group','landing_file_name','MD_Channel',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21326,1925,'RG_PROX_Channel_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21327,1925,'RG_PROX_Channel_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21328,1925,'RG_PROX_Channel_extraction_group','ms_query','select
ID,
ChannelCode,
ChannelNameCN,
ChannelNameEN,
ParentChannelCode,
LevelId,
Status,
OrderNo,
ChannelLeader,
SIOCode,
ApplicationID
from JNJ_TPM.[dbo].[MD_Channel];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21329,1925,'RG_PROX_Channel_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21330,1925,'RG_PROX_Channel_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21331,1925,'RG_PROX_Channel_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21332,1925,'RG_PROX_Channel_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21333,1926,'RG_PROX_Channel_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21334,1926,'RG_PROX_Channel_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21335,1926,'RG_PROX_Channel_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21336,1926,'RG_PROX_Channel_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21337,1926,'RG_PROX_Channel_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21338,1926,'RG_PROX_Channel_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21339,1926,'RG_PROX_Channel_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21340,1926,'RG_PROX_Channel_ingestion_group','target_table','sdl_PROX_MD_Channel',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21341,1926,'RG_PROX_Channel_ingestion_group','folder_path','PRO-X/transaction/MD_Channel/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21342,1926,'RG_PROX_Channel_ingestion_group','file_spec','MD_Channel',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21343,1926,'RG_PROX_Channel_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21344,1927,'RG_PROX_Customer_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21345,1927,'RG_PROX_Customer_extraction_group','landing_file_path','PRO-X/transaction/MD_Customer/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21346,1927,'RG_PROX_Customer_extraction_group','landing_file_name','MD_Customer',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21347,1927,'RG_PROX_Customer_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21348,1927,'RG_PROX_Customer_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21349,1927,'RG_PROX_Customer_extraction_group','ms_query','select
ID
,Division
,Segment
,CustomerCode
,REPLACE(REPLACE(replace(CustomerName,'','','' ''), CHAR(13), ''''), CHAR(10), '''')as CustomerName
,CustomerNameLocal
,CustomerType
,CustomerTelephone
,CustomerAddress
,CityCode
,ChannelCode
,SubChannelCode
,AccountGroupCode
,DeptCode
,SalesArea
,VendorCode
,DirectSupplier
,AcctAtCust
,BlockCompany
,BlockOrder
,HeadquarterSoldToCode
,replace(DistributorCode,'','','' '') as DistributorCode
,IsHighRisk
,Status
,Comment
,ORG
,CustomerHead
,AccountGroupHeader
,TaxNumber
,Buslic
,MobilePhone
,IsFollow
,FollowDate
,SpOpenID
,PNOpenID
,Contact
,Post
,IsNew
,FinanceYear
,SalesOrgCode
,SalesOrgName
,ApplicationID
,Version
,LastModifyUserID
,LastModifyTime
,CityName
,CityCluster
,CityClusterName
,ProvinceCode
,ProvinceName
,NewTime
,DataSource
,PayerCode
,PayerName
,HQCityCode
,IndirectStoreTye
,AccountGroupType
,RTMChannelCode
,VATCode
from JNJ_TPM.[dbo].[MD_Customer];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21350,1927,'RG_PROX_Customer_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21351,1927,'RG_PROX_Customer_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21352,1927,'RG_PROX_Customer_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21353,1927,'RG_PROX_Customer_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21354,1928,'RG_PROX_Customer_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21355,1928,'RG_PROX_Customer_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21356,1928,'RG_PROX_Customer_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21357,1928,'RG_PROX_Customer_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21358,1928,'RG_PROX_Customer_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21359,1928,'RG_PROX_Customer_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21360,1928,'RG_PROX_Customer_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21361,1928,'RG_PROX_Customer_ingestion_group','target_table','sdl_PROX_MD_Customer',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21362,1928,'RG_PROX_Customer_ingestion_group','folder_path','PRO-X/transaction/MD_Customer/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21363,1928,'RG_PROX_Customer_ingestion_group','file_spec','MD_Customer',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21364,1928,'RG_PROX_Customer_ingestion_group','load_type','FULL',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21365,1929,'RG_PROX_ExpenseType_extraction_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21366,1929,'RG_PROX_ExpenseType_extraction_group','landing_file_path','PRO-X/transaction/MD_ExpenseType/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21367,1929,'RG_PROX_ExpenseType_extraction_group','landing_file_name','MD_ExpenseType',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21368,1929,'RG_PROX_ExpenseType_extraction_group','target_table',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21369,1929,'RG_PROX_ExpenseType_extraction_group','target_schema',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21370,1929,'RG_PROX_ExpenseType_extraction_group','ms_query','select
ID
,Division
,Segment
,ExpenseTypeCode
,ExpenseTypeName
,ExpenseDesc
,ExpenseCategory
,ExpenseCategoryName
,ExpenseModel
,AccountCode
,ExpenseSubject
,ExpenseSubjectName
,AccountName
,Status
,Comment
,ConditionType
,ParentID
,Lever
,OrderReason
,UsageCode
,FinanceYear
,ApplicationID
,Version
,LastModifyUserID
,LastModifyTime
,CopaValueField
,ControlByTPM
,OIAccountCode
,WHTCode
,AccrualCode
 from JNJ_TPM.[dbo].[MD_ExpenseType];',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21371,1929,'RG_PROX_ExpenseType_extraction_group','truncate_and_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21372,1929,'RG_PROX_ExpenseType_extraction_group','decide_source','awsbrasgpw0001',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21373,1929,'RG_PROX_ExpenseType_extraction_group','load_method','none',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21374,1929,'RG_PROX_ExpenseType_extraction_group','sp_name','',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21375,1930,'RG_PROX_ExpenseType_ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21376,1930,'RG_PROX_ExpenseType_ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21377,1930,'RG_PROX_ExpenseType_ingestion_group','load_method','PROX',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21378,1930,'RG_PROX_ExpenseType_ingestion_group','validation','0-0-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21379,1930,'RG_PROX_ExpenseType_ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21380,1930,'RG_PROX_ExpenseType_ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21381,1930,'RG_PROX_ExpenseType_ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21382,1930,'RG_PROX_ExpenseType_ingestion_group','target_table','sdl_PROX_MD_ExpenseType',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21383,1930,'RG_PROX_ExpenseType_ingestion_group','folder_path','PRO-X/transaction/MD_ExpenseType/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21384,1930,'RG_PROX_ExpenseType_ingestion_group','file_spec','MD_ExpenseType',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21385,1930,'RG_PROX_ExpenseType_ingestion_group','load_type','FULL',FALSE,TRUE);



INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20626,1821,'Ecommerce_6PAI_Ingestion_group','trigger_mail','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20627,1821,'Ecommerce_6PAI_Ingestion_group','business_mail_trigger','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20628,1821,'Ecommerce_6PAI_Ingestion_group','val_file_header',' ',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20629,1821,'Ecommerce_6PAI_Ingestion_group','file_spec','6P_AI_Calculated',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20630,1821,'Ecommerce_6PAI_Ingestion_group','val_file_name','6P_AI_Calculated',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20631,1821,'Ecommerce_6PAI_Ingestion_group','val_file_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20632,1821,'Ecommerce_6PAI_Ingestion_group','load_method','sp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20633,1821,'Ecommerce_6PAI_Ingestion_group','sp_name','ASPSDL_RAW.ECOMMERCE_6PAI_PREPROCESSING',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20634,1821,'Ecommerce_6PAI_Ingestion_group','is_direct_load','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20635,1821,'Ecommerce_6PAI_Ingestion_group','folder_path','Regional/6PAI_Edge/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20636,1821,'Ecommerce_6PAI_Ingestion_group','target_table','SDL_ECOMMERCE_6PAI',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20637,1821,'Ecommerce_6PAI_Ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20638,1821,'Ecommerce_6PAI_Ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20639,1821,'Ecommerce_6PAI_Ingestion_group','validation','1-1-0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20640,1821,'Ecommerce_6PAI_Ingestion_group','index','last',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20641,1821,'Ecommerce_6PAI_Ingestion_group','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20642,1821,'Ecommerce_6PAI_Ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20643,1821,'Ecommerce_6PAI_Ingestion_group','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (20644,1821,'Ecommerce_6PAI_Ingestion_group','sheet_index','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21678,1968,'OKR_Alteryx_Data_Ingestion_group','trigger_mail','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21679,1968,'OKR_Alteryx_Data_Ingestion_group','business_mail_trigger','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21680,1968,'OKR_Alteryx_Data_Ingestion_group','val_file_header','KPI,Datatype,Cluster,Market,Segment,Brand,YearMonth,Year,Quarter,Actuals,Target,Target_Type',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21681,1968,'OKR_Alteryx_Data_Ingestion_group','file_spec','OKR_Alteryx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21682,1968,'OKR_Alteryx_Data_Ingestion_group','val_file_name','OKR_Alteryx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21683,1968,'OKR_Alteryx_Data_Ingestion_group','val_file_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21684,1968,'OKR_Alteryx_Data_Ingestion_group','load_method','sp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21685,1968,'OKR_Alteryx_Data_Ingestion_group','sp_name','ASPSDL_RAW.OKR_ALTERYX_DATA_PREPROCESSING',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21686,1968,'OKR_Alteryx_Data_Ingestion_group','is_direct_load','N',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21687,1968,'OKR_Alteryx_Data_Ingestion_group','folder_path','OKR/transaction/Alteryx/',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21688,1968,'OKR_Alteryx_Data_Ingestion_group','target_table','SDL_OKR_ALTERYX_AUTOMATION',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21689,1968,'OKR_Alteryx_Data_Ingestion_group','container','asp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21690,1968,'OKR_Alteryx_Data_Ingestion_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21691,1968,'OKR_Alteryx_Data_Ingestion_group','validation','1-1-1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21692,1968,'OKR_Alteryx_Data_Ingestion_group','index','full',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21693,1968,'OKR_Alteryx_Data_Ingestion_group','source_extn','csv',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21694,1968,'OKR_Alteryx_Data_Ingestion_group','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (21695,1968,'OKR_Alteryx_Data_Ingestion_group','is_truncate','Y',FALSE,TRUE);
