--IN HCP market

-- PRocess name change

Update META_RAW.PROCESS set PROCESS_NAME='IN_HCP360_MDS_Data_Refresh_SDL_MDS_IN_HCP_Targets' where PROCESS_ID='1219';
Update META_RAW.PROCESS set PROCESS_NAME='IN_HCP360_MDS_Data_Refresh_SDL_MDS_IN_HCP_Product_Mapping' where PROCESS_ID='1220';
Update META_RAW.PROCESS set PROCESS_NAME='IN_HCP360_MDS_Data_Refresh_SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping' where PROCESS_ID='1221';
Update META_RAW.PROCESS set PROCESS_NAME='IN_HCP360_MDS_Data_Refresh_SDL_MDS_IN_HCP_Sales_Rep_Mapping' where PROCESS_ID='1222';


-- Delete existing Parameters and re-insert to follow on the MDS standard

DELETE FROM META_RAW.PARAMETERS where PARAMETER_GROUP_ID in
(
'1219',
'1220',
'1221',
'1222'
);

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14300,1219,'SDL_MDS_IN_HCP_Targets_group','container','hcp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14301,1219,'SDL_MDS_IN_HCP_Targets_group','landing_file_path','sql_server/MDS/SDL_MDS_IN_HCP_Targets/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14302,1219,'SDL_MDS_IN_HCP_Targets_group','landing_file_name','SDL_MDS_IN_HCP_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14303,1219,'SDL_MDS_IN_HCP_Targets_group','target_table','SDL_MDS_IN_HCP_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14304,1219,'SDL_MDS_IN_HCP_Targets_group','target_schema','HCPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14305,1219,'SDL_MDS_IN_HCP_Targets_group','ms_query','SELECT * FROM MDS.mdm.[IN_HCP_Targets]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14306,1219,'SDL_MDS_IN_HCP_Targets_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14307,1219,'SDL_MDS_IN_HCP_Targets_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14308,1219,'SDL_MDS_IN_HCP_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14309,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','container','hcp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14310,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_IN_HCP_Product_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14311,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','landing_file_name','SDL_MDS_IN_HCP_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14312,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','target_table','SDL_MDS_IN_HCP360_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14313,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','target_schema','HCPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14314,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','ms_query','SELECT * FROM MDS.mdm.[IN_HCP360_Product_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14315,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14316,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14317,1220,'SDL_MDS_IN_HCP_Product_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14318,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','container','hcp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14319,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14320,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','landing_file_name','SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14321,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','target_table','SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14322,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','target_schema','HCPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14323,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','ms_query','SELECT * FROM MDS.mdm.[IN_HCP_Sales_Hierarchy_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14324,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14325,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14326,1221,'SDL_MDS_IN_HCP_Sales_Hierarchy_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14327,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','container','hcp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14328,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_IN_HCP_Sales_Rep_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14329,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','landing_file_name','SDL_MDS_IN_HCP_Sales_Rep_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14330,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','target_table','SDL_MDS_IN_HCP_Sales_Rep_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14331,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','target_schema','HCPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14332,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','ms_query','SELECT * FROM MDS.mdm.[IN_HCP_Sales_Rep_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14333,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14334,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (14335,1222,'SDL_MDS_IN_HCP_Sales_Rep_Mapping_group','map_names','Y',FALSE,TRUE);
