--SG Market

-- Delete existing process and Parameters and utilising for another process as its reduntant

--Update Active flag to false to stop CData Ingestion

UPDATE META_RAW.PROCESS 
SET Is_Active = false
where process_id = 18;

UPDATE META_RAW.PARAMETERS 
SET Is_Active = false
where parameter_group_id = 18;


--Insert New process (table in the MDS SG Job(s))

INSERT INTO META_RAW.PROCESS VALUES (2084,2084,'sg_mds_to_dna_refresh_SDL_MDS_SG_Product_Mapping',2084,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2085,2085,'sg_mds_to_dna_refresh_SDL_MDS_SG_Store_Master',2085,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2086,2086,'sg_mds_to_dna_refresh_SDL_MDS_SG_Customer_Hierarchy',2086,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2087,2087,'sg_mds_to_dna_refresh_SDL_MDS_SG_ECOM_PRODUCT',2087,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2088,2088,'sg_mds_to_dna_refresh_SDL_MDS_SG_Product_Exceptions',2088,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2089,2089,'sg_mds_to_dna_refresh_SDL_MDS_SG_Product_Hierarchy',2089,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2090,2090,'sg_mds_to_dna_refresh_SDL_MDS_SG_PS_Targets',2090,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2091,2091,'sg_mds_to_dna_refresh_SDL_MDS_SG_PS_Weights',2091,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2092,2092,'sg_mds_to_dna_refresh_SDL_MDS_SG_SKU_BENCHMARKS',2092,1,1,FALSE,TRUE,5,5,1,NULL,'','','','SGPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');


--Updates in existing Process to follow on the MDS standard



--Insert New parameters 

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25647,2084,'SDL_MDS_SG_Product_Mapping_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25648,2084,'SDL_MDS_SG_Product_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25649,2084,'SDL_MDS_SG_Product_Mapping_group','landing_file_name','SDL_MDS_SG_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25650,2084,'SDL_MDS_SG_Product_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_Product_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25651,2084,'SDL_MDS_SG_Product_Mapping_group','ms_query','SELECT * FROM [mdm].[SG_Product_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25652,2084,'SDL_MDS_SG_Product_Mapping_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25653,2084,'SDL_MDS_SG_Product_Mapping_group','target_table','SDL_MDS_SG_Product_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25654,2084,'SDL_MDS_SG_Product_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26549,2084,'SDL_MDS_SG_Product_Mapping_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25655,2085,'SDL_MDS_SG_Store_Master_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25656,2085,'SDL_MDS_SG_Store_Master_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25657,2085,'SDL_MDS_SG_Store_Master_group','landing_file_name','SDL_MDS_SG_Store_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25658,2085,'SDL_MDS_SG_Store_Master_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_Store_Master/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25659,2085,'SDL_MDS_SG_Store_Master_group','ms_query','SELECT * FROM [mdm].[SG_Store_Master]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25660,2085,'SDL_MDS_SG_Store_Master_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25661,2085,'SDL_MDS_SG_Store_Master_group','target_table','SDL_MDS_SG_Store_Master',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25662,2085,'SDL_MDS_SG_Store_Master_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26550,2085,'SDL_MDS_SG_Store_Master_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25663,2086,'SDL_MDS_SG_Customer_Hierarchy_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25664,2086,'SDL_MDS_SG_Customer_Hierarchy_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25665,2086,'SDL_MDS_SG_Customer_Hierarchy_group','landing_file_name','SDL_MDS_SG_Customer_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25666,2086,'SDL_MDS_SG_Customer_Hierarchy_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_Customer_Hierarchy/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25667,2086,'SDL_MDS_SG_Customer_Hierarchy_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_Customer_Hierarchy]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25668,2086,'SDL_MDS_SG_Customer_Hierarchy_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25669,2086,'SDL_MDS_SG_Customer_Hierarchy_group','target_table','SDL_MDS_SG_Customer_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25670,2086,'SDL_MDS_SG_Customer_Hierarchy_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26551,2086,'SDL_MDS_SG_Customer_Hierarchy_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25671,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25672,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25673,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','landing_file_name','SDL_MDS_SG_ECOM_PRODUCT',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25674,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_ECOM_PRODUCT/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25675,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_ECOM_PRODUCT]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25676,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25677,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','target_table','SDL_MDS_SG_ECOM_PRODUCT',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25678,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26552,2087,'SDL_MDS_SG_ECOM_PRODUCT_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25679,2088,'SDL_MDS_SG_Product_Exceptions_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25680,2088,'SDL_MDS_SG_Product_Exceptions_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25681,2088,'SDL_MDS_SG_Product_Exceptions_group','landing_file_name','SDL_MDS_SG_Product_Exceptions',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25682,2088,'SDL_MDS_SG_Product_Exceptions_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_Product_Exceptions/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25683,2088,'SDL_MDS_SG_Product_Exceptions_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_Product_Exceptions]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25684,2088,'SDL_MDS_SG_Product_Exceptions_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25685,2088,'SDL_MDS_SG_Product_Exceptions_group','target_table','SDL_MDS_SG_Product_Exceptions',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25686,2088,'SDL_MDS_SG_Product_Exceptions_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26553,2088,'SDL_MDS_SG_Product_Exceptions_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25687,2089,'SDL_MDS_SG_Product_Hierarchy_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25688,2089,'SDL_MDS_SG_Product_Hierarchy_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25689,2089,'SDL_MDS_SG_Product_Hierarchy_group','landing_file_name','SDL_MDS_SG_Product_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25690,2089,'SDL_MDS_SG_Product_Hierarchy_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_Product_Hierarchy/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25691,2089,'SDL_MDS_SG_Product_Hierarchy_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_Product_Hierarchy]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25692,2089,'SDL_MDS_SG_Product_Hierarchy_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25693,2089,'SDL_MDS_SG_Product_Hierarchy_group','target_table','SDL_MDS_SG_Product_Hierarchy',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25694,2089,'SDL_MDS_SG_Product_Hierarchy_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26554,2089,'SDL_MDS_SG_Product_Hierarchy_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25695,2090,'SDL_MDS_SG_PS_Targets_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25696,2090,'SDL_MDS_SG_PS_Targets_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25697,2090,'SDL_MDS_SG_PS_Targets_group','landing_file_name','SDL_MDS_SG_PS_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25698,2090,'SDL_MDS_SG_PS_Targets_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_PS_Targets/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25699,2090,'SDL_MDS_SG_PS_Targets_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_PS_Targets]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25700,2090,'SDL_MDS_SG_PS_Targets_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25701,2090,'SDL_MDS_SG_PS_Targets_group','target_table','SDL_MDS_SG_PS_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25702,2090,'SDL_MDS_SG_PS_Targets_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26555,2090,'SDL_MDS_SG_PS_Targets_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25703,2091,'SDL_MDS_SG_PS_Weights_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25704,2091,'SDL_MDS_SG_PS_Weights_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25705,2091,'SDL_MDS_SG_PS_Weights_group','landing_file_name','SDL_MDS_SG_PS_Weights',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25706,2091,'SDL_MDS_SG_PS_Weights_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_PS_Weights/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25707,2091,'SDL_MDS_SG_PS_Weights_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_PS_Weights]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25708,2091,'SDL_MDS_SG_PS_Weights_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25709,2091,'SDL_MDS_SG_PS_Weights_group','target_table','SDL_MDS_SG_PS_Weights',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25710,2091,'SDL_MDS_SG_PS_Weights_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26556,2091,'SDL_MDS_SG_PS_Weights_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25711,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','container','sgp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25712,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25713,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','landing_file_name','SDL_MDS_SG_SKU_BENCHMARKS',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25714,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','landing_file_path','sql_server/MDS/SDL_MDS_SG_SKU_BENCHMARKS/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25715,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','ms_query','SELECT * FROM [MDS].[mdm].[SG_SKU_BENCHMARKS]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25716,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','target_schema','SGPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25717,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','target_table','SDL_MDS_SG_SKU_BENCHMARKS',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (25718,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26557,2092,'SDL_MDS_SG_SKU_BENCHMARKS_group','map_names','Y',FALSE,TRUE);


--Updates in existing parameters to follow on the MDS standard

