--APAC DCL Market

-- Delete existing process and Parameters and utilising for another process as its reduntant

--Update Active flag to false to stop CData Ingestion

UPDATE META_RAW.PROCESS 
SET Is_Active = false
where process_id = 22;

UPDATE META_RAW.PARAMETERS 
SET Is_Active = false
where parameter_group_id = 22;


--Insert New process (table in the MDS APAC DCL Job(s))

INSERT INTO META_RAW.PROCESS VALUES (2182,2182,'REGIONAL_TRAVEL_MDS_DNA_SDL_MDS_APAC_DCL_Customers',2182,1,1,FALSE,TRUE,2,5,1,NULL,'','','','ASPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2183,2183,'REGIONAL_TRAVEL_MDS_DNA_SDL_MDS_APAC_DCL_Products',2183,1,1,FALSE,TRUE,2,5,1,NULL,'','','','ASPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
INSERT INTO META_RAW.PROCESS VALUES (2184,2184,'REGIONAL_TRAVEL_MDS_DNA_SDL_MDS_APAC_DCL_Targets',2184,1,1,FALSE,TRUE,2,5,1,NULL,'','','','ASPSDL_RAW.PROD_LOAD_STAGE_ADLS','','','');
7

--Updates in existing Process to follow on the MDS standard



--Insert New parameters 

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26431,2182,'SDL_MDS_APAC_DCL_Customers_group','container','asp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26432,2182,'SDL_MDS_APAC_DCL_Customers_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26433,2182,'SDL_MDS_APAC_DCL_Customers_group','landing_file_name','SDL_MDS_APAC_DCL_Customers',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26434,2182,'SDL_MDS_APAC_DCL_Customers_group','landing_file_path','sql_server/MDS/SDL_MDS_APAC_DCL_Customers/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26435,2182,'SDL_MDS_APAC_DCL_Customers_group','ms_query','SELECT * FROM [MDS].[mdm].[APAC_DCL_Customers]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26436,2182,'SDL_MDS_APAC_DCL_Customers_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26437,2182,'SDL_MDS_APAC_DCL_Customers_group','target_table','SDL_MDS_APAC_DCL_Customers',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26438,2182,'SDL_MDS_APAC_DCL_Customers_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26628,2182,'SDL_MDS_APAC_DCL_Customers_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26439,2183,'SDL_MDS_APAC_DCL_Products_group','container','asp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26440,2183,'SDL_MDS_APAC_DCL_Products_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26441,2183,'SDL_MDS_APAC_DCL_Products_group','landing_file_name','SDL_MDS_APAC_DCL_Products',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26442,2183,'SDL_MDS_APAC_DCL_Products_group','landing_file_path','sql_server/MDS/SDL_MDS_APAC_DCL_Products/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26443,2183,'SDL_MDS_APAC_DCL_Products_group','ms_query','SELECT * FROM [MDS].[mdm].[APAC_DCL_Products]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26444,2183,'SDL_MDS_APAC_DCL_Products_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26445,2183,'SDL_MDS_APAC_DCL_Products_group','target_table','SDL_MDS_APAC_DCL_Products',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26445,2183,'SDL_MDS_APAC_DCL_Products_group','target_table','SDL_MDS_APAC_DCL_Products',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26446,2183,'SDL_MDS_APAC_DCL_Products_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26629,2183,'SDL_MDS_APAC_DCL_Products_group','map_names','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26447,2184,'SDL_MDS_APAC_DCL_Targets_group','container','asp',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26448,2184,'SDL_MDS_APAC_DCL_Targets_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26449,2184,'SDL_MDS_APAC_DCL_Targets_group','landing_file_name','SDL_MDS_APAC_DCL_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26450,2184,'SDL_MDS_APAC_DCL_Targets_group','landing_file_path','sql_server/MDS/SDL_MDS_APAC_DCL_Targets/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26451,2184,'SDL_MDS_APAC_DCL_Targets_group','ms_query','SELECT * FROM [MDS].[mdm].[APAC_DCL_Targets]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26452,2184,'SDL_MDS_APAC_DCL_Targets_group','target_schema','ASPSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26453,2184,'SDL_MDS_APAC_DCL_Targets_group','target_table','SDL_MDS_APAC_DCL_Targets',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26454,2184,'SDL_MDS_APAC_DCL_Targets_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26630,2184,'SDL_MDS_APAC_DCL_Targets_group','map_names','Y',FALSE,TRUE);


--Updates in existing parameters to follow on the MDS standard

