--NA Market

--Updates in existing Process/parameters to follow on the MDS standard
Update META_RAW.PROCESS Set PROCESS_NAME=replace(PROCESS_NAME,'NA_MDS','na_mds_tab_refresh')  where  USECASE_ID='253'
and SOURCE_ID in (2,5) and PHASE_ID='1';

Update META_RAW.PARAMETERS set PARAMETER_GROUP_NAME=concat(replace(PARAMETER_GROUP_NAME,'NA_MDS_',''),'_group')
where PARAMETER_GROUP_ID in ('980','981','982');

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE  = Replace(PARAMETER_VALUE,'NA_MDSProd_to_RedshiftProd','MDS')
where PARAMETER_GROUP_ID in ('980','981','982')
AND PARAMETER_NAME='landing_file_path';

UPDATE META_RAW.PARAMETERS
SET PARAMETER_VALUE  = concat('select * from MDS.mdm.',replace(replace(PARAMETER_GROUP_NAME,'_group',''),'SDL_MDS_',''))
where PARAMETER_GROUP_ID in ('980','981','982')
AND PARAMETER_NAME='ms_query'; 

INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26689,980,'SDL_MDS_NA_VMIMST_HEADER_group','map_names','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26690,981,'SDL_MDS_NA_VMIMST_LINE_group','map_names','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26691,982,'SDL_MDS_NA_pos_prc_condition_map_group','map_names','Y',FALSE,TRUE);

