DELETE FROM  META_RAW.parameters
where parameter_group_id = 2183 and parameter_id = 26445;

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26445,2183,'SDL_MDS_APAC_DCL_Products_group','target_table','SDL_MDS_APAC_DCL_Products',FALSE,TRUE);
