ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_LANDMARK_DS
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_LANDMARK_SM
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_PUREGOLD
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_PUREGOLD
ADD COLUMN DISER_NAME VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_ROBINSONS_DS
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_SHM
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_SHM
ADD COLUMN STORE_LOCATION VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_SUPER_8
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_SVI_SMC
ADD COLUMN SUB_CHANNEL VARCHAR(200);

ALTER TABLE DEV_DNA_LOAD.PHLSDL_RAW.SDL_PH_NON_ISE_SVI_SMC
ADD COLUMN STORE_LOCATION VARCHAR(200);
