delete from META_RAW.PARAMETERS  where  Parameter_id in ('27308','27309');

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27308,2211,'SDL_VW_MY_MONTHLY_SELLOUT_SALES_FACT_MDS_SYNC_group','truncate_source','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27309,2212,'SDL_VW_MY_DAILY_SELLOUT_SALES_FACT_MDS_SYNC_group','truncate_source','Y',FALSE,TRUE);

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27310,2211,'SDL_VW_MY_MONTHLY_SELLOUT_SALES_FACT_MDS_SYNC_group','trunc_source_schema_table','mysitg_integration.sdl_my_monthly_sellout_sales_fact_mds_sync',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27311,2212,'SDL_VW_MY_DAILY_SELLOUT_SALES_FACT_MDS_SYNC_group','trunc_source_schema_table','sdl_my_daily_sellout_sales_fact_mds_sync',FALSE,TRUE);

