UPDATE META_RAW.PARAMETERS SET
PARAMETER_VALUE='MDS_Adhoc_SDL_MDS_ID_distributor_customer_update'
WHERE PARAMETER_ID='26865';
UPDATE META_RAW.PARAMETERS SET
PARAMETER_VALUE='SELECT * FROM MDS.MDM.ID_distributor_customer_update'
WHERE PARAMETER_ID='26867';
UPDATE META_RAW.PARAMETERS SET
PARAMETER_VALUE='SDL_MDS_ID_distributor_customer_update'
WHERE PARAMETER_ID='26869';
