create or replace TABLE PROD_DNA_LOAD.PHLSDL_RAW.SDL_ROSEPHARMACY_PRODUCT_MAPPING (
	ACCTCODE VARCHAR(50),
	SALESCYCLE NUMBER(38,0),
	RKA_SKUCODE NUMBER(38,0),
	RKA_SKUDESC VARCHAR(100),
	JJ_SKUCODE NUMBER(38,0),
	JJ_SKUDESC VARCHAR(100),
	JJ_CONVERSION NUMBER(20,0),
	EFFECTIVESALESCYCLE NUMBER(38,0)
);


create or replace TABLE PROD_DNA_LOAD.PHLSDL_RAW.SDL_ROSEPHARMACY_CUSTOMER_MAPPING (
	ACCTCODE VARCHAR(50),
	BRCODE NUMBER(20,0),
	BRNAME VARCHAR(200),
	REGION VARCHAR(200),
	PROVINCE VARCHAR(200),
	MUNICIPALITY VARCHAR(200)
);
