COPY INTO PROD_DNA_LOAD.PHLSDL_RAW.SDL_ROSEPHARMACY_CUSTOMER_MAPPING
  FROM @PROD_DNA_LOAD.PHLSDL_RAW.PROD_LOAD_STAGE_ADLS/prd/rpharma_mds/RosePharmacy_Customer_Mapping
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
