create or replace TABLE PROD_DNA_LOAD.PHLSDL_RAW.SDL_POS_RKS_ROSE_PHARMA (
	BRANCH_CODE VARCHAR(30),
	BRANCH_NAME VARCHAR(100),
	MONTH VARCHAR(10),
	SKU VARCHAR(100),
	SKU_DESCRIPTION VARCHAR(100),
	QTY NUMBER(20,0),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(100)
);
