INSERT INTO PROD_DNA_LOAD.META_RAW.USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (523,'Retail_Excellence_Data_Ingestion','Retail_Excellence_Data_Load','Retail Excellence Data Ingestion','TRUE',1);

INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (2235,2235,'Retail_Excellence',2235,1,1,FALSE,TRUE,523,NULL,2,NULL,'','','','','','','');

INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27312,2235,'retail_excellence_etl_framework_trans','tempId','1',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27313,2235,'retail_excellence_etl_framework_trans','jobId','17404',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27314,2235,'retail_excellence_etl_framework_trans','accountId','99',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27315,2235,'retail_excellence_etl_framework_trans','waitTime','20',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27316,2235,'retail_excellence_etl_framework_trans','transformationType','transformation',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27317,2235,'retail_excellence_etl_framework_trans','container','asp',FALSE,TRUE);
