Update META_RAW.PROCESS SET SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_HKG' where SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_hkg';
Update META_RAW.PROCESS SET SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN' where SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_twn';
Update META_RAW.PROCESS SET SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN' where SNOWFLAKE_STAGE='NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWn';
