create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_DSTRBTRR_DIM (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	LVL1 VARCHAR(255),
	LVL2 VARCHAR(255),
	LVL3 VARCHAR(255),
	LVL4 VARCHAR(255),
	LVL5 VARCHAR(255),
	TRDNG_TERM_VAL VARCHAR(255),
	ABBREVATION VARCHAR(255),
	BUYER_GLN VARCHAR(255),
	LOCATION_GLN VARCHAR(255),
	CHNL_MANAGER VARCHAR(255),
	CDM VARCHAR(255),
	REGION VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
	FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_CUSTOMER_DIM (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	DSTRBTR_GRP_CD VARCHAR(255),
	DSTRBTR_GRP_NM VARCHAR(255),
	ULLAGE VARCHAR(255),
	CHNL VARCHAR(255),
	TERRITORY VARCHAR(255),
	RETAIL_ENV VARCHAR(255),
	TRDNG_TERM_VAL VARCHAR(255),
	RDD_IND VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_DSTRBTR_DOC_TYPE (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	LVL1 VARCHAR(255),
	LVL2 VARCHAR(255),
	WH_ID VARCHAR(255),
	DOC_TYPE VARCHAR(255),
	DOC_TYPE_DESC VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_ACCRUALS (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	JJ_YEAR VARCHAR(255),
	FILE_TYPE VARCHAR(255),
	JAN_VAL VARCHAR(255),
	FEB_VAL VARCHAR(255),
	MAR_VAL VARCHAR(255),
	APR_VAL VARCHAR(255),
	MAY_VAL VARCHAR(255),
	JUN_VAL VARCHAR(255),
	JUL_VAL VARCHAR(255),
	AUG_VAL VARCHAR(255),
	SEP_VAL VARCHAR(255),
	OCT_VAL VARCHAR(255),
	NOV_VAL VARCHAR(255),
	DEC_VAL VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_POS_CUST_MSTR (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	STORE_CD VARCHAR(255),
	STORE_NM VARCHAR(255),
	DEPT_CD VARCHAR(255),
	DEPT_NM VARCHAR(255),
	REGION VARCHAR(255),
	STORE_FRMT VARCHAR(255),
	STORE_TYPE VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_IN_TRANSIT (
	BILL_DOC VARCHAR(255),
	BILL_DT VARCHAR(255),
	GR_DT VARCHAR(255),
	CLOSING_DT VARCHAR(255),
	REMARKS VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT VARCHAR(255),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_TRGTS (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	BRND_DESC VARCHAR(255),
	SUB_SEGMENT VARCHAR(255),
	JJ_YEAR VARCHAR(255),
	TRGT_TYPE VARCHAR(255),
	TRGT_VAL_TYPE VARCHAR(255),
	JAN_VAL VARCHAR(255),
	FEB_VAL VARCHAR(255),
	MAR_VAL VARCHAR(255),
	APR_VAL VARCHAR(255),
	MAY_VAL VARCHAR(255),
	JUN_VAL VARCHAR(255),
	JUL_VAL VARCHAR(255),
	AUG_VAL VARCHAR(255),
	SEP_VAL VARCHAR(255),
	OCT_VAL VARCHAR(255),
	NOV_VAL VARCHAR(255),
	DEC_VAL VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_AFGR (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	AFGR_NUM VARCHAR(255),
	CUST_DN_NUM VARCHAR(255),
	DN_AMT_EXC_GST_VAL VARCHAR(255),
	AFGR_AMT VARCHAR(255),
	DT_TO_SC VARCHAR(255),
	SC_VALIDATION VARCHAR(255),
	RTN_ORD_NUM VARCHAR(255),
	RTN_ORD_DT VARCHAR(255),
	RTN_ORD_AMT VARCHAR(255),
	CN_EXP_ISSUE_DT VARCHAR(255),
	BILL_NUM VARCHAR(255),
	BILL_DT VARCHAR(255),
	CN_AMT VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_LE_TRGT (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	JJ_YEAR VARCHAR(255),
	MNTH_NM VARCHAR(255),
	TRGT_TYPE VARCHAR(255),
	TRGT_VAL_TYPE VARCHAR(255),
	WK1 VARCHAR(255),
	WK2 VARCHAR(255),
	WK3 VARCHAR(255),
	WK4 VARCHAR(255),
	WK5 VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_CIW_MAP (
	CIW_CTGRY VARCHAR(255),
	CIW_BUCKT1 VARCHAR(255),
	CIW_BUCKT2 VARCHAR(255),
	BRAVO_CD1 VARCHAR(255),
	BRAVO_DESC1 VARCHAR(255),
	BRAVO_CD2 VARCHAR(255),
	BRAVO_DESC2 VARCHAR(255),
	ACCT_TYPE VARCHAR(255),
	ACCT_NUM VARCHAR(255),
	ACCT_DESC VARCHAR(255),
	ACCT_TYPE1 VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);
create or replace TABLE PROD_DNA_LOAD.MYSSDL_RAW.SDL_MY_IDS_RATE (
	CUST_ID VARCHAR(255),
	CUST_NM VARCHAR(255),
	EXCHNG_RATE VARCHAR(255),
	YEARMO VARCHAR(255),
	CDL_DTTM VARCHAR(255),
	CURR_DT TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_YEARLY_TARGET (
	YEAR VARCHAR(10),
	KPI VARCHAR(100),
	CATEGORY VARCHAR(200),
	TARGET VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
    FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_KPI_SELLIN_SELLTHRGH (
	DSTRBTR_ID VARCHAR(30),
	DSTRBTR_TYPE VARCHAR(10),
	DSTRBTR_NAME VARCHAR(100),
	CYCLE VARCHAR(10),
	ORDERTYPE VARCHAR(30),
	SELLIN_TG VARCHAR(100),
	SELLIN_AC VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_PROMOTION_LIST (
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	PROMOTION_ID VARCHAR(50),
	PROMOTION_NAME VARCHAR(200),
	PROMOTION_DESC VARCHAR(200),
	START_DATE VARCHAR(30),
	END_DATE VARCHAR(30),
	STATUS VARCHAR(1),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_SALES_ORG_DIM (
	DSTRBTR_ID VARCHAR(30),
	SALESREP_ID VARCHAR(30),
	SALESREP_NAME VARCHAR(100),
	SUP_CODE VARCHAR(30),
	SALESREP_CRTDATE VARCHAR(50),
	SALESREP_DATEOFF VARCHAR(50),
	SUP_NAME VARCHAR(100),
	SUP_ACTIVE VARCHAR(5),
	SUP_CRTDATE VARCHAR(50),
	SUP_DATEOFF VARCHAR(50),
	ASM_ID VARCHAR(50),
	ASM_NAME VARCHAR(100),
	ACTIVE VARCHAR(5),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_PRODUCT_DIM (
	PRODUCT_CODE VARCHAR(50),
	PRODUCT_NAME VARCHAR(100),
	PRODUCTCODESAP VARCHAR(40),
	PRODUCTNAMESAP VARCHAR(100),
	UNIT VARCHAR(10),
	TAX_RATE VARCHAR(10),
	WEIGHT VARCHAR(20),
	VOLUME VARCHAR(20),
	GROUPJB VARCHAR(20),
	FRANCHISE VARCHAR(50),
	BRAND VARCHAR(100),
	VARIANT VARCHAR(100),
	PRODUCT_GROUP VARCHAR(200),
	ACTIVE VARCHAR(10),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_D_SELLOUT_SALES_FACT (
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	OUTLET_ID VARCHAR(30),
	ORDER_DATE VARCHAR(30),
	INVOICE_DATE VARCHAR(30),
	ORDER_NO VARCHAR(30),
	INVOICE_NO VARCHAR(30),
	SALES_ROUTE_ID VARCHAR(30),
	SALE_ROUTE_NAME VARCHAR(100),
	SALES_GROUP VARCHAR(30),
	SALESREP_ID VARCHAR(30),
	SALESREP_NAME VARCHAR(100),
	MATERIAL_CODE VARCHAR(50),
	UOM VARCHAR(30),
	GROSS_PRICE VARCHAR(100),
	ORDERQTY VARCHAR(30),
	QUANTITY VARCHAR(30),
	TOTAL_SELLOUT_AFVAT_BFDISC VARCHAR(100),
	DISCOUNT VARCHAR(100),
	TOTAL_SELLOUT_AFVAT_AFDISC VARCHAR(100),
	LINE_NUMBER VARCHAR(10),
	PROMOTION_ID VARCHAR(50),
	STATUS VARCHAR(1),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_CALL_DETAILS (
	DSTRBTR_ID VARCHAR(30),
	SALESREP_ID VARCHAR(30),
	OUTLET_ID VARCHAR(30),
	VISIT_DATE VARCHAR(30),
	CHECKIN_TIME VARCHAR(30),
	CHECKOUT_TIME VARCHAR(30),
	REASON VARCHAR(100),
	DISTANCE VARCHAR(30),
	ORDERVISIT VARCHAR(30),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_ORDER_PROMOTION (
	BRANCH_ID VARCHAR(30),
	PRO_ID VARCHAR(50),
	ORD_NO VARCHAR(20),
	LINE_REF VARCHAR(10),
	DISC_TYPE VARCHAR(5),
	BREAK_BY VARCHAR(5),
	DISC_BREAK_LINE_REF VARCHAR(10),
	DISCT_BL_AMT VARCHAR(100),
	DISCT_BL_QTY VARCHAR(20),
	FREE_ITEM_CODE VARCHAR(20),
	FREE_ITEM_QTY VARCHAR(20),
	DISC_AMT VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_MSL (
	MSL_ID VARCHAR(20),
	SUB_CHANNEL VARCHAR(50),
	FROM_CYCLE VARCHAR(10),
	TO_CYCLE VARCHAR(10),
	PRODUCT_ID VARCHAR(50),
	PROUCT_NAME VARCHAR(100),
	ACTIVE VARCHAR(5),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	GROUPMSL VARCHAR(100),
	FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_DISTRIBUTOR_DIM (
	TERRITORY_DIST VARCHAR(100),
	MAPPED_SPK VARCHAR(30),
	DSTRBTR_ID VARCHAR(30),
	DSTRBTR_TYPE VARCHAR(10),
	DSTRBTR_NAME VARCHAR(100),
	DSTRBTR_ADDRESS VARCHAR(500),
	LONGITUDE VARCHAR(20),
	LATITUDE VARCHAR(20),
	REGION VARCHAR(20),
	PROVINCE VARCHAR(100),
	ACTIVE VARCHAR(5),
	ASM_ID VARCHAR(50),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_H_SELLOUT_SALES_FACT (
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	OUTLET_ID VARCHAR(30),
	ORDER_DATE VARCHAR(30),
	INVOICE_DATE VARCHAR(30),
	ORDER_NO VARCHAR(30),
	INVOICE_NO VARCHAR(30),
	SELLOUT_AFVAT_BFDISC VARCHAR(100),
	TOTAL_DISCOUNT VARCHAR(100),
	INVOICE_DISCOUNT VARCHAR(100),
	SELLOUT_AFVAT_AFDISC VARCHAR(100),
	STATUS VARCHAR(1),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_DATA_EXTRACT_SUMMARY (
	DATE_OF_EXTRACTION TIMESTAMP_NTZ(9),
	RECORD_COUNT NUMBER(18,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_CUSTOMER_DIM (
	SAP_ID VARCHAR(30),
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	OUTLET_ID VARCHAR(30),
	OUTLET_NAME VARCHAR(500),
	ADDRESS_1 VARCHAR(200),
	ADDRESS_2 VARCHAR(200),
	TELEPHONE VARCHAR(100),
	FAX VARCHAR(20),
	CITY VARCHAR(100),
	POSTCODE VARCHAR(20),
	REGION VARCHAR(20),
	CHANNEL_GROUP VARCHAR(30),
	SUB_CHANNEL VARCHAR(20),
	SALES_ROUTE_ID VARCHAR(30),
	SALES_ROUTE_NAME VARCHAR(100),
	SALES_GROUP VARCHAR(30),
	SALESREP_ID VARCHAR(30),
	SALESREP_NAME VARCHAR(100),
	GPS_LAT VARCHAR(30),
	GPS_LONG VARCHAR(30),
	STATUS VARCHAR(1),
	DISTRICT VARCHAR(100),
	PROVINCE VARCHAR(100),
	CRT_DATE VARCHAR(50),
	DATE_OFF VARCHAR(50),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	SHOP_TYPE VARCHAR(100),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_SELLTHRGH_SALES_FACT (
	DSTRBTR_ID VARCHAR(30),
	DSTRBTR_TYPE VARCHAR(30),
	MAPPED_SPK VARCHAR(30),
	DOC_NUMBER VARCHAR(30),
	REF_NUMBER VARCHAR(30),
	RECEIPT_DATE VARCHAR(30),
	ORDER_TYPE VARCHAR(10),
	VAT_INVOICE_NUMBER VARCHAR(30),
	VAT_INVOICE_NOTE VARCHAR(30),
	VAT_INVOICE_DATE VARCHAR(30),
	PON_NUMBER VARCHAR(50),
	LINE_REF VARCHAR(20),
	PRODUCT_CODE VARCHAR(50),
	UNIT VARCHAR(10),
	QUANTITY VARCHAR(20),
	PRICE VARCHAR(30),
	AMOUNT VARCHAR(30),
	TAX_AMOUNT VARCHAR(30),
	TAX_ID VARCHAR(30),
	TAX_RATE VARCHAR(30),
	"values" VARCHAR(30),
	LINE_DISCOUNT VARCHAR(30),
	DOC_DISCOUNT VARCHAR(100),
	STATUS VARCHAR(1),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_SALES_STOCK_FACT (
	DSTRBTR_ID VARCHAR(30),
	CNTRY_CODE VARCHAR(10),
	WH_CODE VARCHAR(20),
	DATE VARCHAR(30),
	MATERIAL_CODE VARCHAR(50),
	BAT_NUMBER VARCHAR(20),
	EXPIRY_DATE VARCHAR(30),
	QUANTITY VARCHAR(20),
	UOM VARCHAR(10),
	AMOUNT VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_KPI (
	DSTRBTR_ID VARCHAR(30),
	SALEMAN_CODE VARCHAR(30),
	SALEMAN_NAME VARCHAR(50),
	CYCLE VARCHAR(10),
	EXPORT_DATE VARCHAR(30),
	KPI_TYPE VARCHAR(20),
	TARGET_VALUE VARCHAR(100),
	ACTUAL_VALUE VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);


create or replace TABLE PROD_DNA_LOAD.VNMSDL_RAW.SDL_VN_DMS_FORECAST (
	CYCLE VARCHAR(10),
	CHANNEL VARCHAR(30),
	TERRITORY_DIST VARCHAR(100),
	WAREHOUSE VARCHAR(100),
	FRANCHISE VARCHAR(100),
	BRAND VARCHAR(100),
	VARIANT VARCHAR(100),
	FORECASTSO_MIL VARCHAR(100),
	CURR_DATE TIMESTAMP_NTZ(9) DEFAULT CONVERT_TIMEZONE('SGT', CAST(CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)) AS TIMESTAMP_TZ(9))),
	RUN_ID NUMBER(14,0),
	FILE_NAME VARCHAR(255)
);
