create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_SALESMAN_TARGET (
	DIST_CODE VARCHAR(50),
	SM_CODE VARCHAR(50),
	SM_TARGET NUMBER(38,6),
	BRAND_FOCUS VARCHAR(50),
	MEASURE_TYPE VARCHAR(50),
	CHANNEL VARCHAR(100),
	YEAR NUMBER(18,0),
	MONTH VARCHAR(10),
    FILE_NAME VARCHAR(225)
);

create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_RKEYACCCUSTOMER (
	CUSTOMERCODE VARCHAR(50),
	CUSTOMERNAME VARCHAR(50),
	CUSTOMERADDRESS1 VARCHAR(250),
	CUSTOMERADDRESS2 VARCHAR(250),
	CUSTOMERADDRESS3 VARCHAR(250),
	SAPID VARCHAR(50),
	REGIONCODE VARCHAR(50),
	ZONECODE VARCHAR(50),
	TERRITORYCODE VARCHAR(50),
	STATECODE VARCHAR(50),
	TOWNCODE VARCHAR(50),
	EMAILID VARCHAR(50),
	MOBILELL VARCHAR(50),
	ISACTIVE VARCHAR(1),
	WHOLESALERCODE VARCHAR(50),
	URC VARCHAR(50),
	NKACSTORES VARCHAR(1),
	PARENTCUSTOMERCODE VARCHAR(50),
	ISDIRECTACCT VARCHAR(1),
	ISPARENT VARCHAR(1),
	ABICODE VARCHAR(50),
	DISTRIBUTORSAPID VARCHAR(50),
	ISCONFIRM VARCHAR(1),
	CREATEDDATE TIMESTAMP_NTZ(9),
	CREATEDUSERCODE VARCHAR(50),
	MODDT TIMESTAMP_NTZ(9),
	MODUSERCODE VARCHAR(50),
	CREATEDDT TIMESTAMP_NTZ(9),
	CRT_DTTM TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(225)
);

create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_ITTARGET (
	LAKSHYAT_TERRITORY_NAME VARCHAR(50),
	TARGET_VARIANT VARCHAR(50),
	JANAMOUNT NUMBER(37,5),
	FEBAMOUNT NUMBER(37,5),
	MARAMOUNT NUMBER(37,5),
	APRAMOUNT NUMBER(37,5),
	MAYAMOUNT NUMBER(37,5),
	JUNAMOUNT NUMBER(37,5),
	JULYAMOUNT NUMBER(37,5),
	AUGAMOUNT NUMBER(37,5),
	SEPAMOUNT NUMBER(37,5),
	OCTAMOUNT NUMBER(37,5),
	NOVAMOUNT NUMBER(37,5),
	DECAMOUNT NUMBER(37,5),
	YTDAMOUNT NUMBER(37,5),
	CRT_DTTM TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(225)
);

create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_SKU_RECOM_FLAG (
	MNTH_ID VARCHAR(50),
	MOTHER_SKU_CD VARCHAR(50),
	DIST_OUTLET_CD VARCHAR(50),
	CUST_CD VARCHAR(50),
	OOS_FLAG VARCHAR(50),
	MS_FLAG VARCHAR(50),
	CS_FLAG VARCHAR(50),
	SOQ VARCHAR(50),
	UNIQUE_RET_CD VARCHAR(50),
	RETAILER_CD VARCHAR(50),
	ROUTE_CODE VARCHAR(50),
	SALESMAN_CODE VARCHAR(50),
    FILE_NAME varchar(225)
);
create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_CSL_CLASSMASTER (
	TABLEID NUMBER(18,0),
	PKEY NUMBER(18,0),
	CLASSID NUMBER(18,0),
	CLASSCODE VARCHAR(10),
	CLASSDESC VARCHAR(100),
	TURNOVER NUMBER(18,4),
	AVAILABILTY NUMBER(18,0),
	CREATEDUSERID NUMBER(18,0),
	CREATEDDATE TIMESTAMP_NTZ(9),
	DISTHIERARCHYID NUMBER(18,0),
	CRT_DTTM TIMESTAMP_NTZ(9),
	FILE_NAME VARCHAR(225)
);

create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_RDSSIZE (
	RDSCODE NUMBER(18,0),
	RDSSIZE VARCHAR(100),
	CRT_DTTM TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(225)
);
