create or replace TABLE PROD_DNA_LOAD.PHLSDL_RAW.sdl_pos_rks_rose_pharma_consumer (
	BRANCH_CODE VARCHAR(30),
	BRANCH_NAME VARCHAR(100),
	MONTH VARCHAR(10),
	SKU VARCHAR(100),
	SKU_DESCRIPTION VARCHAR(100),
	QTY NUMBER(20,0),
	CRTD_DTTM TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(100)
);

  COPY INTO prod_DNA_LOAD.PHLSDL_RAW.sdl_pos_rks_rose_pharma_consumer
  FROM @prod_DNA_LOAD.PHLSDL_RAW.prod_LOAD_STAGE_ADLS/prd/rpharma_mds/pos_rks_rose_pharma_consumer
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

