UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='select * from dbo.PH_POS_RKA_Product_ADFTemp' WHERE PARAMETER_ID='26930';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='SDL_MDS_PH_POS_PRODUCT_TEMP' WHERE PARAMETER_ID='26928';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='sql_server/MDS/MDS_Adhoc_SDL_MDS_PH_RKA_PRODUCT_TEMP' WHERE PARAMETER_ID='26929';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='SDL_MDS_PH_POS_PRODUCT_TEMP' WHERE PARAMETER_ID='26932';
