create or replace TABLE PROD_DNA_LOAD.ASPSDL_RAW.SDL_FPA_PROFIT_CENTER_MAPPING (
	DIMENSION VARCHAR(300),
	RULEGROUPNAME VARCHAR(300),
	RULE_TYPE VARCHAR(300),
	RULENAME_SOURCEVALUE VARCHAR(300),
	RULE_DESCRIPTION VARCHAR(300),
	RULE_EXPRESSION VARCHAR(300),
	TARGET_VALUE VARCHAR(300),
	LOGICAL_OPERATOR VARCHAR(300),
	LOGICAL_OPERATOR_NAME VARCHAR(300),
	LOGICAL_EXPRESSION VARCHAR(300),
	DERIVATIVE_TYPE_NAME VARCHAR(300),
	EXECUTION_ORDER VARCHAR(300)
);

COPY INTO PROD_DNA_LOAD.ASPSDL_RAW.SDL_FPA_PROFIT_CENTER_MAPPING
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.ASPSDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('prd/reference/FPA_Profit_Center_Mapping.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT ;

create or replace TABLE PROD_DNA_LOAD.ASPSDL_RAW.SDL_CCR_PRODUCT_MAPPING (
	DIMENSION VARCHAR(300),
	RULEGROUPNAME VARCHAR(300),
	RULE_TYPE VARCHAR(300),
	RULENAME_SOURCEVALUE VARCHAR(300),
	RULE_DESCRIPTION VARCHAR(300),
	RULE_EXPRESSION VARCHAR(300),
	TARGET_VALUE VARCHAR(300),
	LOGICAL_OPERATOR VARCHAR(300),
	EXECUTION_ORDER VARCHAR(300)
);

COPY INTO PROD_DNA_LOAD.ASPSDL_RAW.SDL_CCR_PRODUCT_MAPPING
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.ASPSDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('prd/reference/CCR_Product_Mapping.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT ;
