update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'PACIFIC_CUST_CIW_PLAN_TEMP'
WHERE PARAMETER_ID = 26919;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'sql_server/MDS/MDS_Adhoc_PACIFIC_CUST_CIW_PLAN_TEMP'
WHERE PARAMETER_ID = 26920;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT * from dbo.PACIFIC_CUST_CIW_PLAN_ADFTemp'
WHERE PARAMETER_ID = 26921;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'PACIFIC_CUST_CIW_PLAN_TEMP'
WHERE PARAMETER_ID = 26932;

CREATE OR REPLACE TABLE PROD_DNA_LOAD.PCFSDL_RAW.PACIFIC_CUST_CIW_PLAN_TEMP 
  (ID NUMBER(10,0), MUID VARCHAR(40), VERSIONNAME VARCHAR(100), VERSIONNUMBER NUMBER(10,0), VERSION_ID NUMBER(10,0), 
  VERSIONFLAG VARCHAR(100), NAME VARCHAR(500), CODE VARCHAR(500), CHANGETRACKINGMASK NUMBER(10,0), TIME_PERIOD VARCHAR(200), SALES_GRP_CD VARCHAR(200), PROD_MJR_CD VARCHAR(200), GOAL_QTY NUMBER(38,0), GOAL_GTS NUMBER(38,2), GOAL_EFF_VAL NUMBER(38,2), GOAL_JGF_SI_VAL NUMBER(38,2), GOAL_PMT_TERMS_VAL NUMBER(38,2), GOAL_DATAINS_VAL NUMBER(38,2), GOAL_EXP_ADJ_VAL NUMBER(38,2), GOAL_JGF_SD_VAL NUMBER(38,2), GOAL_CIW_TOT NUMBER(38,2), GOAL_COGS NUMBER(38,2), GOAL_GP NUMBER(38,2), LOCAL_CCY VARCHAR(200), TARGET_TYPE VARCHAR(200), ENTERDATETIME TIMESTAMP_NTZ(9), ENTERUSERNAME VARCHAR(200), ENTERVERSIONNUMBER NUMBER(10,0), LASTCHGDATETIME TIMESTAMP_NTZ(9), LASTCHGUSERNAME VARCHAR(200), LASTCHGVERSIONNUMBER NUMBER(10,0), VALIDATIONSTATUS VARCHAR(500));
