update META_RAW.PARAMETERS SET PARAMETER_VALUE='sql_server/MDS/SDL_MDS_MDS_REDS_MARKET_MSL/' WHERE PARAMETER_ID='26938';
update META_RAW.PARAMETERS SET PARAMETER_VALUE='SELECT * FROM [MDS].[dbo].[MDS_REDS_MARKET_MSL]' WHERE PARAMETER_ID='26939';
update META_RAW.PARAMETERS SET PARAMETER_VALUE='SDL_MDS_MDS_REDS_MARKET_MSL' WHERE PARAMETER_ID='26941';
