create or replace TABLE PROD_DNA_LOAD.IDNSDL_RAW.SDL_DISTRIBUTOR_IVY_OUTLET_MASTER_ADFTEMP (
	DISTRIBUTORCODE VARCHAR(25) NOT NULL,	USERCODE VARCHAR(25),	LOCATIONCODE VARCHAR(25) NOT NULL,	OUTLETCODE VARCHAR(25) NOT NULL,	OUTLETNAME VARCHAR(100) NOT NULL,	OUTLETADDRESS VARCHAR(255) NOT NULL,	PINCODE VARCHAR(10),	CHANNELCODE VARCHAR(100) NOT NULL,
	CHANNELNAME VARCHAR(100),	SUBCHANNELCODE VARCHAR(100) NOT NULL,	SUBCHANNELNAME VARCHAR(100),	TIERINGCODE VARCHAR(100) NOT NULL,
	TIERINGNAME VARCHAR(100),	CLASSCODE VARCHAR(15),	ROUTECODE VARCHAR(25),	VISIT_FREQUENCY VARCHAR(15),	VISITDAY VARCHAR(200),
	JNJ_ID VARCHAR(20) NOT NULL,	CONTACTPERSON VARCHAR(255),	CREDIT_LIMIT NUMBER(18,4),	INVOICE_LIMIT NUMBER(18,4),	CREDIT_PERIOD NUMBER(5,0),
	TIN VARCHAR(50),	IS_DIAMOND_STORE VARCHAR(3),	ID_NO VARCHAR(100),	MASTER_CODE VARCHAR(100),	STORE_CLUSTER VARCHAR(50),	LATTITUDE VARCHAR(20),	LONGITUDE VARCHAR(20),	CDL_DTTM VARCHAR(200),	RUN_ID NUMBER(14,0),	FILE_NAME VARCHAR(255)
);   



call PROD_DNA_LOAD.IDNSDL_RAW.IVY_OUTLETMASTER_PREPROCESSING(['OutletMaster_20240926_0030.csv','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','prd/test/IVY/Manual_Upload/','SDL_DISTRIBUTOR_IVY_OUTLET_MASTER_ADFTEMP']);
