update META_RAW.HISTORICAL_OBJ_METADATA
set TARGET_DB = 'PROD_DNA_LOAD'
where STAGE_SCHEMA = 'META_RAW';

update META_RAW.HISTORICAL_OBJ_METADATA
set TARGET_DB = 'PROD_DNA_CORE'
where STAGE_SCHEMA = 'UTILITY_RAW';
