delete from PROD_DNA_LOAD.IDNSDL_RAW.SDL_DISTRIBUTOR_IVY_OUTLET_MASTER_ADFTEMP;

call PROD_DNA_LOAD.IDNSDL_RAW.IVY_OUTLETMASTER_PREPROCESSING(['OutletMaster_20241007_0030.csv','IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN','prd/test/IVY/Manual_Upload/','SDL_DISTRIBUTOR_IVY_OUTLET_MASTER_ADFTEMP']);
