INSERT INTO META_RAW.PROCESS VALUES (2188,2188,'MDS_tesco_SDL_MDS_TH_PS_HandEye_level',2188,1,1,FALSE,TRUE,83,5,1,NULL,'','','','THASDL_RAW.PROD_LOAD_STAGE_ADLS','','','');

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26769,2188,'SDL_MDS_TH_PS_HandEye_level_group','container','tha',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26770,2188,'SDL_MDS_TH_PS_HandEye_level_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26771,2188,'SDL_MDS_TH_PS_HandEye_level_group','landing_file_name','SDL_MDS_TH_PS_HandEye_level',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26772,2188,'SDL_MDS_TH_PS_HandEye_level_group','landing_file_path','sql_server/MDS/SDL_MDS_TH_PS_HandEye_level',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26773,2188,'SDL_MDS_TH_PS_HandEye_level_group','ms_query','SELECT * FROM MDS.MDM.TH_PS_HandEye_level',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26774,2188,'SDL_MDS_TH_PS_HandEye_level_group','target_schema','THASDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26775,2188,'SDL_MDS_TH_PS_HandEye_level_group','target_table','SDL_MDS_TH_PS_HandEye_level',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26776,2188,'SDL_MDS_TH_PS_HandEye_level_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (26777,2188,'SDL_MDS_TH_PS_HandEye_level_group','map_names','Y',FALSE,TRUE);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_MDS_TH_PS_HANDEYE_LEVEL (
	ID NUMBER(10,0),
	MUID VARCHAR(40),
	VERSIONNAME VARCHAR(100),
	VERSIONNUMBER NUMBER(10,0),
	VERSION_ID NUMBER(10,0),
	VERSIONFLAG VARCHAR(100),
	NAME VARCHAR(500),
	CODE VARCHAR(500),
	CHANGETRACKINGMASK NUMBER(10,0),
	COUNTRY VARCHAR(200),
	RETAIL_ENVIRONMENT_CODE VARCHAR(500),
	RETAIL_ENVIRONMENT_NAME VARCHAR(500),
	RETAIL_ENVIRONMENT_ID NUMBER(10,0),
	TOTAL_LAYERS NUMBER(38,0),
	HAND_EYE_LAYER NUMBER(38,0),
	ENTERDATETIME TIMESTAMP_NTZ(9),
	ENTERUSERNAME VARCHAR(200),
	ENTERVERSIONNUMBER NUMBER(10,0),
	LASTCHGDATETIME TIMESTAMP_NTZ(9),
	LASTCHGUSERNAME VARCHAR(200),
	LASTCHGVERSIONNUMBER NUMBER(10,0),
	VALIDATIONSTATUS VARCHAR(500)
);
