-----------------Use Case
INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (544,'Commercial_Excellence_Data_Ingestion','Commercial_Excellence_Data_Load','Commercial_Excellence_Data_Ingestion','TRUE',1);

-----------------Process
INSERT INTO PROCESS VALUES (5078,5078,'Commercial_Excellence_Base_Load',5078,1,1,FALSE,TRUE,544,,2,,'','','','','','','');
INSERT INTO PROCESS VALUES (5079,5079,'Commercial_Excellence_Datamart_Load',5079,1,2,FALSE,TRUE,544,,2,,'','','','','','','');

-----------------------Parameters
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27318,5078,'Commercial_Excellence_Base_Load_Group','tempId','1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27319,5078,'Commercial_Excellence_Base_Load_Group','jobId','16795',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27320,5078,'Commercial_Excellence_Base_Load_Group','accountId','99',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27321,5078,'Commercial_Excellence_Base_Load_Group','waitTime','20',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27322,5078,'Commercial_Excellence_Base_Load_Group','transformationType','transformation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27323,5078,'Commercial_Excellence_Base_Load_Group','container','asp',FALSE,TRUE);

INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27324,5079,'Commercial_Excellence_Datamart_Load_Group','tempId','1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27325,5079,'Commercial_Excellence_Datamart_Load_Group','jobId','16796',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27326,5079,'Commercial_Excellence_Datamart_Load_Group','accountId','99',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27327,5079,'Commercial_Excellence_Datamart_Load_Group','waitTime','20',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27328,5079,'Commercial_Excellence_Datamart_Load_Group','transformationType','transformation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27329,5079,'Commercial_Excellence_Datamart_Load_Group','container','asp',FALSE,TRUE);
