DELETE from PROD_DNA_LOAD.META_RAW.USECASE
where usecase_id = 544
and usecase_name = 'Commercial_Excellence_Data_Ingestion';

delete from PROD_DNA_LOAD.META_RAW.PROCESS
where process_id in (5078, 5079)
and process_name in ('Commercial_Excellence_Base_Load', 'Commercial_Excellence_Datamart_Load');

delete from PROD_DNA_LOAD.META_RAW.PARAMETERS
where PARAMETER_GROUP_ID in (5078, 5079)
and PARAMETER_GROUP_NAME in ('Commercial_Excellence_Base_Load_Group', 'Commercial_Excellence_Datamart_Load_Group');


INSERT INTO PROD_DNA_LOAD.META_RAW.USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (545,'Commercial_Excellence_Data_Ingestion','Commercial_Excellence_Data_Load','Commercial_Excellence_Data_Ingestion','TRUE',1);


INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (2288,2288,'Commercial_Excellence_Base_Load',2288,1,1,FALSE,TRUE,545,NULL,2,NULL,'','','','','','','');
INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (2289,2289,'Commercial_Excellence_Datamart_Load',2289,1,2,FALSE,TRUE,545,NULL,2,NULL,'','','','','','','');


INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27974,2288,'Commercial_Excellence_Base_Load_Group','tempId','1',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27975,2288,'Commercial_Excellence_Base_Load_Group','jobId','16795',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27976,2288,'Commercial_Excellence_Base_Load_Group','accountId','99',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27977,2288,'Commercial_Excellence_Base_Load_Group','waitTime','20',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27978,2288,'Commercial_Excellence_Base_Load_Group','transformationType','transformation',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27979,2288,'Commercial_Excellence_Base_Load_Group','container','asp',FALSE,TRUE);

INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27980,2289,'Commercial_Excellence_Datamart_Load_Group','tempId','1',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27981,2289,'Commercial_Excellence_Datamart_Load_Group','jobId','16796',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27982,2289,'Commercial_Excellence_Datamart_Load_Group','accountId','99',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27983,2289,'Commercial_Excellence_Datamart_Load_Group','waitTime','20',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27984,2289,'Commercial_Excellence_Datamart_Load_Group','transformationType','transformation',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27985,2289,'Commercial_Excellence_Datamart_Load_Group','container','asp',FALSE,TRUE);
