UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='PACIFIC_CUST_CIW_PLAN' WHERE PARAMETER_ID='26919';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='sql_server/MDS/MDS_Adhoc_PACIFIC_CUST_CIW_PLAN/' WHERE PARAMETER_ID='26920';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='SELECT * from mdm.PACIFIC_CUST_CIW_PLAN' WHERE PARAMETER_ID='26921';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='PACIFIC_CUST_CIW_PLAN' WHERE PARAMETER_ID='26923';
