
DROP TABLE VNMSDL_RAW.SDL_MDS_VN_STORE_RETAIL_ENVIRONMENT_MAPPING_ADFTEMP;

INSERT INTO META_RAW.PROCESS VALUES (2266,2266,'vn_mt_mds_refresh_SDL_MDS_VN_Store_Retail_Environment_Mapping',2266,1,1,FALSE,TRUE,57,5,1,NULL,'','','','VNMSDL_RAW.DEV_LOAD_STAGE_ADLS','','','');

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27759,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','container','vnm',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27760,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27761,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','landing_file_name','SDL_MDS_VN_Store_Retail_Environment_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27762,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','landing_file_path','sql_server/MDS/SDL_MDS_VN_Store_Retail_Environment_Mapping/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27763,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','ms_query','SELECT * FROM [MDS].[mdm].[VN_Store_Retail_Environment_Mapping]',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27764,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','target_schema','VNMSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27765,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','target_table','SDL_MDS_VN_Store_Retail_Environment_Mapping',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27766,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27767,2266,'SDL_MDS_VN_Store_Retail_Environment_Mapping_group','map_names','Y',FALSE,TRUE);
