create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SHOPEE_COMPENSATION (
	PO_CMPT_MNTH VARCHAR(50),
	TYPE VARCHAR(100),
	SCM_BARCODE VARCHAR(100),
	PRODUCT_NAME VARCHAR(255),
	ORDER_NO VARCHAR(255),
	STATUS VARCHAR(50),
	CRT_TM VARCHAR(100),
	DLVRY_TM VARCHAR(100),
	SUM_OF_QTY NUMBER(20,4),
	SUM_OF_RSPXQTY NUMBER(20,4),
	SUM_OF_TOTAL_NET_SELLING_PRICE NUMBER(20,4),
	SUM_OF_DIS_SHOPEE NUMBER(20,4),
	SUM_OF_LTPXQTY NUMBER(20,4),
	SUM_OF_FRONT_MARGIN NUMBER(20,4),
	SUM_OF_ENABLER_MARGIN NUMBER(20,4),
	SUM_OF_COMPENSATION NUMBER(20,4),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SEARCH_ADS_BY_DATE (
	DATE VARCHAR(100),
	REGION VARCHAR(100),
	SHOP_NAME VARCHAR(255),
	SHOP_ID VARCHAR(255),
	TERMINAL VARCHAR(50),
	SALES_USD FLOAT,
	SALES_LCY FLOAT,
	ORDERS NUMBER(38,0),
	UNITS_SOLD NUMBER(38,0),
	VISITS NUMBER(38,0),
	UNIQUE_VISITORS NUMBER(38,0),
	ADD_TO_CART_UNITS NUMBER(38,0),
	ADD_TO_CART_VALUE_USD FLOAT,
	ADD_TO_CART_VALUE_LCY FLOAT,
	BUYERS NUMBER(38,0),
	NEW_BUYERS NUMBER(38,0),
	ITEM_CONVERSION_RATE FLOAT,
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(100) 
);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SEARCH_ADS_BY_CHANNEL (
	TIME_PERIOD VARCHAR(100),
	CHANNEL VARCHAR(255),
	REGION VARCHAR(100),
	SHOP_NAME VARCHAR(255),
	SHOP_ID VARCHAR(255),
	TERMINAL VARCHAR(50),
	SALES_USD FLOAT,
	SALES_LCY FLOAT,
	ORDERS NUMBER(38,0),
	UNITS_SOLD NUMBER(38,0),
	VISITS NUMBER(38,0),
	UNIQUE_VISITORS NUMBER(38,0),
	ADD_TO_CART_UNITS NUMBER(38,0),
	ADD_TO_CART_VALUE_USD FLOAT,
	ADD_TO_CART_VALUE_LCY FLOAT,
	BUYERS NUMBER(38,0),
	NEW_BUYERS NUMBER(38,0),
	ITEM_CONVERSION_RATE FLOAT,
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(100) 
);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_BACKMARGIN (
	ORDERSN VARCHAR(100),
	SHOP_ID VARCHAR(50),
	SELLER_USERNAME VARCHAR(100),
	SKU_ID VARCHAR(100),
	BUNDLE_ORD_ITMID VARCHAR(10),
	PRODUCT_ID VARCHAR(100),
	ITM_NAME VARCHAR(16777216),
	MODEL_ID VARCHAR(100),
	MODEL_NAME VARCHAR(500),
	PURCHASED_TIME VARCHAR(20),
	CATEGORY VARCHAR(100),
	SUB_CATEGORY VARCHAR(100),
	BE_STATUS VARCHAR(100),
	SELLER_VOUCHER VARCHAR(100),
	PLATFORM_VOUCHER VARCHAR(100),
	QUANTITY NUMBER(38,0),
	FLASH_SALE VARCHAR(100),
	FREE_SHIPPING_REBATE NUMBER(20,4),
	SHOPEE_VOUCHER_REBATE NUMBER(20,4),
	SELLER_VOUCHER_REBATE NUMBER(20,4),
	PLATFORM_VOUCHER_SELLER_REBATE NUMBER(20,4),
	PLATFORM_VOUCHER_SHOPEE_REBATE NUMBER(20,4),
	COIN_EARN NUMBER(20,4),
	COIN_USED NUMBER(20,4),
	SPECIFIC_PURCHASE_TIME VARCHAR(50),
	COGS_PER_QUANTITY NUMBER(20,4),
	PRICE_BEFORE_DISCOUNT NUMBER(20,4),
	ITEM_PRICE NUMBER(20,4),
	PERCENT_DISCOUNT NUMBER(20,4),
	PROMOTION_ID VARCHAR(100),
	SHIPPING_CARRIER VARCHAR(255),
	BUNDLE_ID VARCHAR(100),
	ACTUAL_SHIPPING_FEE NUMBER(20,4),
	BUYER_SHIPPING_FEE NUMBER(20,4),
	ADD_ON_DEAL_ID VARCHAR(100),
	IS_ADD_ON_SUB_ITEM NUMBER(38,0),
	BACKMARGIN_CFS NUMBER(20,4),
	BACKMARGIN_NORMAL NUMBER(20,4),
	BACKMARGIN_BUNDLE NUMBER(20,4),
	BACKMARGIN_ADDON NUMBER(20,4),
	BACKMARGIN_SHIPPING NUMBER(20,4),
	SELLER_VOUCHER_COIN_EARN NUMBER(20,4),
	PLATFORM_VOUCHER_COIN_EARN NUMBER(20,4),
	SUPPLIER_ID VARCHAR(100),
	SUPPLIERNAME VARCHAR(255),
	NMV NUMBER(20,4),
	BUNDLE_RULE_TYPE VARCHAR(100),
	BUNDLE_RULE_VALUE VARCHAR(100),
	ITEM_BRAND VARCHAR(100),
	IS_EXCLUSIVE_PRICE NUMBER(38,0),
	ORDER_VALUE NUMBER(20,4),
	IS_NEW_BUYER_PRICE NUMBER(38,0),
	IS_LIVE_ORDER NUMBER(38,0),
	ESCROW_PAID_DATE VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_COGS (
	PLANT VARCHAR(50),
	MAT_TYPE VARCHAR(50),
	PROC_TYPE VARCHAR(50),
	PROFIT_CENTER VARCHAR(100),
	PROFIT_CENTER_DESC VARCHAR(255),
	COST_RELEASE_DT VARCHAR(50),
	COST_REL_YR VARCHAR(10),
	VENDOR_NO VARCHAR(50),
	VENDOR_NAME VARCHAR(255),
	MAT_GROUP VARCHAR(50),
	MATERIAL_GRP_DESC VARCHAR(100),
	PUT_UP VARCHAR(100),
	PUT_UP_DESC VARCHAR(100),
	TECHNOLOGY VARCHAR(50),
	BRAND VARCHAR(100),
	BRAND_DESC VARCHAR(100),
	SITE_ID VARCHAR(100),
	FRANCHISE VARCHAR(100),
	FRANCHISE_DESC VARCHAR(255),
	BOL VARCHAR(50),
	MATERIAL_NO VARCHAR(50),
	MATERIAL_DESC VARCHAR(255),
	UOM VARCHAR(50),
	BOM_QTY NUMBER(20,4),
	UOM_1 VARCHAR(50),
	SCRAP NUMBER(20,4),
	STD_COST NUMBER(20,4),
	UNIT NUMBER(20,4),
	CUR VARCHAR(50),
	COST_SIZE NUMBER(20,4),
	UOM_2 VARCHAR(50),
	TOTAL_COST NUMBER(20,4),
	RAW_PACK NUMBER(20,4),
	PACKAGING NUMBER(20,4),
	LABOUR NUMBER(20,4),
	OH_DIRECT NUMBER(20,4),
	OH_DIR_VAR NUMBER(20,4),
	OH_DIR_FIX NUMBER(20,4),
	OH_INDIRECT NUMBER(20,4),
	OH_IND_VAR NUMBER(20,4),
	OH_IND_FIX NUMBER(20,4),
	DEPRECIATION NUMBER(20,4),
	SUB_CONTRACT NUMBER(20,4),
	PFG_MATERIAL NUMBER(20,4),
	FREIGHT NUMBER(20,4),
	DUTY NUMBER(20,4),
	OTHER_PFG NUMBER(20,4),
	OH_SUBCONTR NUMBER(20,4),
	OH_PFG NUMBER(20,4),
	PROMOT_COST NUMBER(20,4),
	PROMOT_SUBC NUMBER(20,4),
	TOLL_FEE_MK_UP NUMBER(20,4),
	IC_MARK_UP NUMBER(20,4),
	OTHER_OH NUMBER(20,4),
	OTHER_OH_VAR NUMBER(20,4),
	OTHER_OH_FIX NUMBER(20,4),
	FINAL_COST NUMBER(20,4),
	PER_PIECE NUMBER(20,4),
	PER_DOZEN NUMBER(20,4),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);

----------CPAS
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_CPAS (
	DATE VARCHAR(50),
	SHOP VARCHAR(50),
	SPENDING NUMBER(20,4),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);

create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS (
	ORDER_TIME VARCHAR(50),
	ORDER_ID VARCHAR(100),
	ORDER_COMPLETED_TIME VARCHAR(50),
	VERIFIED_STATUS VARCHAR(50),
	CONVERSION_COMPLETED_TIME VARCHAR(50),
	BRAND_COMMISSION NUMBER(20,4),
	ITEM_ID VARCHAR(50),
	ITEM_NAME VARCHAR(500),
	MODEL_ID VARCHAR(50),
	PRICE NUMBER(20,4),
	PROMOTION_ID VARCHAR(100),
	QTY NUMBER(38,0),
	PURCHASE_VALUE NUMBER(20,4),
	L1_GLOBAL_CATEGORY VARCHAR(100),
	L2_GLOBAL_CATEGORY VARCHAR(255),
	L3_GLOBAL_CATEGORY VARCHAR(255),
	ATTRI_COMMI_ID VARCHAR(100),
	CHANNEL VARCHAR(100),
	COMMI_RATE VARCHAR(100),
	EXPENSE VARCHAR(100),
	DEDUCTION_STATUS VARCHAR(100),
	DEDUCTION_METHOD VARCHAR(100),
	DEDUCTION_TIME VARCHAR(100),
	SHOPE_NAME VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);



create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE (
	PRODUCT_NAME VARCHAR(400),
	PRODUCT_ID VARCHAR(255),
	GROSS_SALES NUMBER(20,4),
	GROSS_SALES_GROWTH NUMBER(20,4),
	GROSS_ORDERS NUMBER(20,4),
	GROSS_ORDERS_GROWTH NUMBER(20,4),
	GROSS_UNITS_SOLD NUMBER(20,4),
	GROSS_UNITS_SOLD_GROWTH NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE_GROWTH NUMBER(20,4),
	GROSS_ITEM_PER_ORDER NUMBER(20,4),
	GROSS_ITEM_PER_ORDER_GROWTH NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE_GROWTH NUMBER(20,4),
	PRODUCT_VIEWS NUMBER(20,4),
	PRODUCT_VIEWS_GROWTH NUMBER(20,4),
	PRODUCT_VISITORS NUMBER(20,4),
	PRODUCT_VISITORS_GROWTH NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE_GROWTH NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE_GROWTH NUMBER(20,4),
	DATE VARCHAR(50),
	PLATFORM VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SHOPEE_COMPENSATION
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Compensation.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );


COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SEARCH_ADS_BY_DATE
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Search_ads_day.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_SEARCH_ADS_BY_CHANNEL
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Search_ads_channel.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_BACKMARGIN
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Backmargin.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );


COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_COGS
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Cogs.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_CPAS
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/CPAS.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/AMS.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Shopee.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );


COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_KONVY
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/Konvy.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );


