UPDATE META_RAW.PROCESS SET PARAMETER_GROUP_ID='1105',
PROCESS_NAME='INDONESIA_MDS_SDL_MDS_ID_Ref_CustomerPL_Segmentation',
IS_ACTIVE='TRUE',USECASE_ID='213',SNOWFLAKE_STAGE='IDNSDL_RAW.PROD_LOAD_STAGE_ADLS_IDN' WHERE PROCESS_ID='1105';

INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28406,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','container','idn',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28407,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','landing_file_path','sql_server/MDS/SDL_MDS_ID_Ref_CustomerPL_Segmentation/',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28408,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','landing_file_name','SDL_MDS_ID_Ref_CustomerPL_Segmentation',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28409,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','target_table','SDL_MDS_ID_Ref_CustomerPL_Segmentation',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28410,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','target_schema','IDNSDL_RAW',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28411,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','ms_query','SELECT * FROM MDS.mdm.ID_Ref_CustomerPL_Segmentation',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28412,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28413,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','decide_source','sql_server_mds',FALSE,TRUE);
INSERT INTO META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28414,1105,'SDL_MDS_ID_Ref_CustomerPL_Segmentation_group','map_names','Y',FALSE,TRUE);

CREATE OR REPLACE TABLE PROD_DNA_LOAD.IDNSDL_RAW.SDL_MDS_ID_REF_CUSTOMERPL_SEGMENTATION (ID NUMBER(10,0),
MUID VARCHAR(40),
VERSIONNAME VARCHAR(100),
VERSIONNUMBER NUMBER(10,0),
VERSION_ID NUMBER(10,0),
VERSIONFLAG VARCHAR(100),
NAME VARCHAR(500),
CODE VARCHAR(500),
CHANGETRACKINGMASK NUMBER(10,0),
CUSTOMER_SEGMENT_LEVEL1_CODE VARCHAR(500),
CUSTOMER_SEGMENT_LEVEL1_NAME VARCHAR(500),
CUSTOMER_SEGMENT_LEVEL1_ID NUMBER(10,0),
CUSTOMER_SEGMENT_LEVEL2_CODE VARCHAR(500),
CUSTOMER_SEGMENT_LEVEL2_NAME VARCHAR(500),
CUSTOMER_SEGMENT_LEVEL2_ID NUMBER(10,0),
ENTERDATETIME TIMESTAMP_NTZ(9),
ENTERUSERNAME VARCHAR(200),
ENTERVERSIONNUMBER NUMBER(10,0),
LASTCHGDATETIME TIMESTAMP_NTZ(9),
LASTCHGUSERNAME VARCHAR(200),
LASTCHGVERSIONNUMBER NUMBER(10,0),
VALIDATIONSTATUS VARCHAR(500));
