update PROD_DNA_LOAD.META_RAW.PARAMETERS
set PARAMETER_VALUE='WHERE rsalesinvoiceorders.CreatedDt > CONVERT( '{WATERMARK_VALUE}',date);'
where PARAMETER_ID='12254'
and PARAMETER_GROUP_ID='967';

commit;

update PROD_DNA_LOAD.META_RAW.PARAMETERS
set PARAMETER_VALUE='query:SELECT MAX(CreatedDt) AS NEXT_VALUE FROM INDSDL_RAW.SDL_CSL_SALESINVOICEORDERS'
where PARAMETER_ID='12257'
and PARAMETER_GROUP_ID='967';

commit;

update PROD_DNA_LOAD.META_RAW.PARAMETERS
set PARAMETER_VALUE='WHERE rorderbooking.CreatedDt > CONVERT( ''{WATERMARK_VALUE}'',date);'
where PARAMETER_ID='12242'
and PARAMETER_GROUP_ID='950';

commit;

update PROD_DNA_LOAD.META_RAW.PARAMETERS
set PARAMETER_VALUE='query:SELECT MAX(CreatedDt) AS NEXT_VALUE FROM INDSDL_RAW.SDL_CSL_ORDERBOOKING'
where PARAMETER_ID='12245'
and PARAMETER_GROUP_ID='950';

commit;

