create table PROD_DNA_LOAD.META_RAW.PROCESS_bkp07112024 as select * from PROD_DNA_LOAD.META_RAW.PROCESS;

update PROD_DNA_LOAD.META_RAW.PROCESS
set IS_ACTIVE='FALSE'
where USECASE_ID='208'
and PARAMETER_GROUP_ID IN ('967','950')
AND PROCESS_ID IN ('967','950') ;

commit;