
update PROD_DNA_LOAD.META_RAW.PROCESS
set IS_ACTIVE='TRUE'
where USECASE_ID='208'
and PARAMETER_GROUP_ID IN ('967','950')
AND PROCESS_ID IN ('967','950') ;

update PROD_DNA_LOAD.META_RAW.PROCESS
set IS_ACTIVE='FALSE'
where USECASE_ID='208'
and PARAMETER_GROUP_ID = '1604'
AND PROCESS_ID = '1604' ;

commit;