INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27072,2214,'PH_Pos_Rka_Rose_Pharma_Consumer_group','startRange','A2',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27073,2215,'HCP_OSEA_Ingestion_MC_Cycle','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27074,2215,'HCP_OSEA_Ingestion_MC_Cycle','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27075,2215,'HCP_OSEA_Ingestion_MC_Cycle','landing_file_name','OSEA_MC_CYCLE',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27076,2215,'HCP_OSEA_Ingestion_MC_Cycle','target_table','SDL_HCP_OSEA_MC_CYCLE',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27077,2215,'HCP_OSEA_Ingestion_MC_Cycle','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27078,2215,'HCP_OSEA_Ingestion_MC_Cycle','ms_query','SELECT 
	Id,
OwnerId,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Description_vod__c,
End_Date_vod__c,
External_Id_vod__c,
Over_Reached_Threshold_vod__c,
Start_Date_vod__c,
Status_vod__c,
Under_Reached_Threshold_vod__c,
Calculate_Pull_Through_vod__c,
Activate_Edited_Goals_vod__c,
Goal_Editing_Rules_vod__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c
FROM
    MC_Cycle_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27079,2215,'HCP_OSEA_Ingestion_MC_Cycle','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27080,2215,'HCP_OSEA_Ingestion_MC_Cycle','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27081,2215,'HCP_OSEA_Ingestion_MC_Cycle','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27082,2215,'HCP_OSEA_Ingestion_MC_Cycle','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27083,2215,'HCP_OSEA_Ingestion_MC_Cycle','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27084,2215,'HCP_OSEA_Ingestion_MC_Cycle','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE;',FALSE,TRUE);
