delete from prod_DNA_LOAD.META_RAW.PARAMETERS where parameter_group_id=2214;
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27085,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27086,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27087,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','landing_file_name','OSEA_MC_CYCLE_CHANNEL',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27088,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','target_table','SDL_HCP_OSEA_MC_CYCLE_CHANNEL',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27089,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27090,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','ms_query','SELECT 
	Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_vod__c,
Channel_Criteria_vod__c,
Channel_Label_vod__c,
Channel_Object_vod__c,
Channel_Weight_vod__c,
External_Id_vod__c,
VExternal_Id_vod__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c
FROM
    MC_Cycle_Channel_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27091,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27092,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27093,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27094,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27095,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27096,2216,'HCP_OSEA_Ingestion_MC_Cycle_Channel','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_CHANNEL;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27097,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27098,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27099,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','landing_file_name','OSEA_MC_CYCLE_PLAN',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27100,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','target_table','SDL_HCP_OSEA_MC_CYCLE_PLAN',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27101,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27102,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','ms_query','SELECT 
	Id,
OwnerId,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Channel_Interaction_Attainment_vod__c,
Channel_Interaction_Status_vod__c,
Channel_Interactions_Earned_vod__c,
Channel_Interactions_Goal_vod__c,
Cycle_vod__c,
Days_Remaining_vod__c,
Days_Total_vod__c,
Description_vod__c,
End_Date_vod__c,
External_Id_vod__c,
Last_Calculated_vod__c,
Lock_vod__c,
Percent_Cycle_Completed_vod__c,
Product_Interaction_Attainment_vod__c,
Product_Interaction_Status_vod__c,
Product_Interactions_Earned_vod__c,
Product_Interactions_Goal_vod__c,
Start_Date_vod__c,
Status_vod__c,
Territory_vod__c,
VExternal_Id_vod__c,
Team_Channel_Attainment_vod__c,
Team_Channel_Interactions_Earned_vod__c,
Team_Channel_Interactions_Goal_vod__c,
Team_Channel_Status_vod__c,
Team_Product_Attainment_vod__c,
Team_Product_Interactions_Earned_vod__c,
Team_Product_Interactions_Goal_vod__c,
Team_Product_Status_vod__c,
Goal_Edit_Status_vod__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c,
JJ_Goal_Edit_Approved__c,
JJ_Manager_Email__c,
JJ_Owner_WWID__c
FROM
    MC_Cycle_Plan_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27103,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27104,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27105,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27106,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27107,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27108,2217,'HCP_OSEA_Ingestion_MC_Cycle_Plan','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PLAN;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27109,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27110,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27111,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','landing_file_name','OSEA_MC_CYCLE_PLAN_CHANNEL',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27112,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','target_table','SDL_HCP_OSEA_MC_CYCLE_PLAN_CHANNEL',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27113,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27114,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','ms_query','SELECT 
	Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_Plan_Target_vod__c,
Channel_Activity_Actual_vod__c,
Channel_Activity_Goal_vod__c,
Channel_Activity_Max_vod__c,
Channel_Activity_Remaining_vod__c,
Channel_Attainment_vod__c,
Channel_Interactions_Actual_vod__c,
Channel_Interactions_Earned__c,
Channel_Interactions_Goal_vod__c,
Channel_vod__c,
Cycle_Channel_vod__c,
External_Id_vod__c,
Last_Calculated_vod__c,
Product_Attainment_vod__c,
Product_Interactions_Earned_vod__c,
Product_Interactions_Goal_vod__c,
VExternal_Id_vod__c,
Channel_Status_vod__c,
Product_Status_vod__c,
Team_Channel_Activity_Actual_vod__c,
Team_Channel_Activity_Goal_vod__c,
Team_Channel_Activity_Max_vod__c,
Team_Channel_Activity_Remaining_vod__c,
Team_Channel_Attainment_vod__c,
Team_Channel_Interactions_Actual_vod__c,
Team_Channel_Interactions_Earned_vod__c,
Team_Channel_Interactions_Goal_vod__c,
Team_Channel_Status_vod__c,
Team_Product_Attainment_vod__c,
Team_Product_Interactions_Earned_vod__c,
Team_Product_Interactions_Goal_vod__c,
Team_Product_Status_vod__c,
Activity_Goal_Edit_vod__c,
Cycle_Plan_vod__c,
Team_Activity_Goal_Edit_vod__c,
Last_Activity_Date_vod__c,
Last_Activity_Datetime_vod__c,
Team_Last_Activity_Date_vod__c,
Team_Last_Activity_Datetime_vod__c,
zvod_Last_Activity_Date_vod__c,
zvod_Team_Last_Activity_Date_vod__c,
JJ_RDO_Is_Call_Channel__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c,
JJ_Actual_Goal__c,
JJ_Channel_Activity__c,
JJ_Channel_Actual_Achievement__c,
JJ_Historical_Channel_Value__c,
JJ_MC_Cycle_Plan_Channel_ID_18__c,
JJ_Weight__c
FROM
    MC_Cycle_Plan_Channel_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27115,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27116,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27117,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27118,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27119,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27120,2218,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Channel','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PLAN_CHANNEL;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27121,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27122,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27123,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','landing_file_name','OSEA_MC_CYCLE_PLAN_PRODUCT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27124,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','target_table','SDL_HCP_OSEA_MC_CYCLE_PLAN_PRODUCT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27125,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27126,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','ms_query','SELECT 
	Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_Plan_Channel_vod__c,
Channel_vod__c,
Cycle_Product_vod__c,
External_Id_vod__c,
Last_Calculated_vod__c,
Product_Activity_Goal_vod__c,
Product_Activity_Max_vod__c,
Product_Activity_Remaining_vod__c,
Product_Actual_Activity_vod__c,
Product_Attainment_vod__c,
Product_Interactions_Actual_vod__c,
Product_Interactions_Earned_vod__c,
Product_Interactions_Goal_vod__c,
Product_Name_vod__c,
VExternal_Id_vod__c,
Detail_Priority_vod__c,
Product_Status_vod__c,
Team_Product_Activity_Goal_vod__c,
Team_Product_Activity_Max_vod__c,
Team_Product_Activity_Remaining_vod__c,
Team_Product_Actual_Activity_vod__c,
Team_Product_Attainment_vod__c,
Team_Product_Interactions_Actual_vod__c,
Team_Product_Interactions_Earned_vod__c,
Team_Product_Interactions_Goal_vod__c,
Team_Product_Status_vod__c,
Activity_Goal_Edit_vod__c,
Cycle_Plan_vod__c,
Detail_Group_Name_vod__c,
Team_Activity_Goal_Edit_vod__c,
Last_Activity_Date_vod__c,
Last_Activity_Datetime_vod__c,
Team_Last_Activity_Date_vod__c,
Team_Last_Activity_Datetime_vod__c,
zvod_Last_Activity_Date_vod__c,
zvod_Team_Last_Activity_Date_vod__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c,
JJ_Product_ID18__c,
zvod_PM_JJ_Classification__c,
zvod_PM_JJ_MY_Adoption_ladder__c
FROM
    MC_Cycle_Plan_Product_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27127,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27128,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27129,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27130,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27131,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27132,2219,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Product','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PLAN_PRODUCT;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27133,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27134,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27135,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','landing_file_name','OSEA_MC_CYCLE_PLAN_SUMMARY',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27136,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','target_table','SDL_HCP_OSEA_MC_CYCLE_PLAN_SUMMARY',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27137,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27138,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','ms_query','SELECT 
	Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_Plan_vod__c,
Attainment_vod__c,
Cycle_Channel_vod__c,
Interactions_Earned_vod__c,
Interactions_Goal_vod__c,
Last_Calculated_vod__c,
Percent_All_Goals_vod__c,
Product_vod__c,
Summary_For_vod__c,
Veeva_External_Id_vod__c,
Detail_Group_vod__c,
Status_vod__c,
Team_Attainment_vod__c,
Team_Interactions_Earned_vod__c,
Team_Interactions_Goal_vod__c,
Team_Status_vod__c,
JJLegacyID__c,
JJ_IN_Actual_Call__c
FROM
    MC_Cycle_Plan_Summary_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27139,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27140,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27141,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27142,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27143,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27144,2220,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Summary','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PLAN_SUMMARY;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27145,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27146,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27147,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','landing_file_name','OSEA_MC_CYCLE_PLAN_TARGET',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27148,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','target_table','SDL_HCP_OSEA_MC_CYCLE_PLAN_TARGET',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27149,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27150,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','ms_query','SELECT 
	Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_Plan_vod__c,
Channel_Attainment_vod__c,
Channel_Interactions_Actual_vod__c,
Channel_Interactions_Earned_vod__c,
Channel_Interactions_Goal_vod__c,
Channel_Interactions_Max_vod__c,
Channel_Interactions_Remaining_vod__c,
Channel_Status_vod__c,
External_Id_vod__c,
Last_Calculated_vod__c,
Product_Attainment_vod__c,
Product_Interactions_Earned_vod__c,
Product_Interactions_Goal_vod__c,
Product_Status_vod__c,
Status_vod__c,
Target_vod__c,
VExternal_Id_vod__c,
Team_Channel_Attainment_vod__c,
Team_Channel_Interactions_Actual_vod__c,
Team_Channel_Interactions_Earned_vod__c,
Team_Channel_Interactions_Goal_vod__c,
Team_Channel_Interactions_Max_vod__c,
Team_Channel_Interactions_Remaining_vod__c,
Team_Channel_Status_vod__c,
Team_Product_Attainment_vod__c,
Team_Product_Interactions_Earned_vod__c,
Team_Product_Interactions_Goal_vod__c,
Team_Product_Status_vod__c,
Goals_Edited_vod__c,
Child_Account_vod__c,
Furigana_vod__c,
Location_vod__c,
Parent_Child_Name_vod__c,
JJ_RDO_Last_Cycle_Progress_Generated__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c,
JJ_Channel_Actual_Achievement__c,
JJ_MC_Cycle_Plan_ID_18__c,
JJ_MC_Cycle_Plan_Target_ID_18__c,
JJ_Owner_Manager__c,
JJ_Target_ID18__c,
zvod_ACCOUNT_JJ_Primary_Parent_Name__c,
zvod_ACCOUNT_Specialty_1_vod__c,
zvod_ADDRESS_City_vod__c,
JJ_New_Channel_Goals__c,
JJ_New_Product_Interaction_Goals__c
FROM
    MC_Cycle_Plan_Target_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27151,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27152,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27153,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27154,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27155,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27156,2221,'HCP_OSEA_Ingestion_MC_Cycle_Plan_Target','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PLAN_TARGET;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27157,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27158,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27159,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','landing_file_name','OSEA_MC_CYCLE_PRODUCT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27160,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','target_table','SDL_HCP_OSEA_MC_CYCLE_PRODUCT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27161,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27162,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','ms_query','SELECT 
Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Cycle_Channel_vod__c,
Channel_Label_vod__c,
Cycle_vod__c,
Detail_Group_vod__c,
External_Id_vod__c,
Product_Weight_vod__c,
Product_vod__c,
VExternal_Id_vod__c,
Applicable_Product_Metrics_vod__c,
Master_Align_Id_vod__c,
Country_Code__c,
JJLegacyID__c
FROM
    MC_Cycle_Product_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27163,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27164,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27165,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27166,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27167,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27168,2222,'HCP_OSEA_Ingestion_MC_Cycle_Product','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_MC_CYCLE_PRODUCT;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27169,2223,'HCP_OSEA_Ingestion_Sample_Lot','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27170,2223,'HCP_OSEA_Ingestion_Sample_Lot','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27171,2223,'HCP_OSEA_Ingestion_Sample_Lot','landing_file_name','OSEA_SAMPLE_LOT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27172,2223,'HCP_OSEA_Ingestion_Sample_Lot','target_table','SDL_HCP_OSEA_SAMPLE_LOT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27173,2223,'HCP_OSEA_Ingestion_Sample_Lot','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27174,2223,'HCP_OSEA_Ingestion_Sample_Lot','ms_query','SELECT 
Id,
OwnerId,
IsDeleted,
Name,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Sample_Lot_Id_vod__c,
Active_vod__c,
Sample_vod__c,
U_M_vod__c,
Calculated_Quantity_vod__c,
Expiration_Date_vod__c,
Allocated_Quantity_vod__c,
Product_vod__c,
Suppress_Lot_vod__c,
JJ_Core_Country__c,
Batch_Lot_Id_vod__c,
JJ_LegacyID__c
FROM
    Sample_Lot_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27175,2223,'HCP_OSEA_Ingestion_Sample_Lot','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27176,2223,'HCP_OSEA_Ingestion_Sample_Lot','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27177,2223,'HCP_OSEA_Ingestion_Sample_Lot','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27178,2223,'HCP_OSEA_Ingestion_Sample_Lot','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27179,2223,'HCP_OSEA_Ingestion_Sample_Lot','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27180,2223,'HCP_OSEA_Ingestion_Sample_Lot','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SAMPLE_LOT;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27181,2224,'HCP_OSEA_Ingestion_Sample_Receipt','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27182,2224,'HCP_OSEA_Ingestion_Sample_Receipt','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27183,2224,'HCP_OSEA_Ingestion_Sample_Receipt','landing_file_name','OSEA_SAMPLE_RECEIPT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27184,2224,'HCP_OSEA_Ingestion_Sample_Receipt','target_table','SDL_HCP_OSEA_SAMPLE_RECEIPT',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27185,2224,'HCP_OSEA_Ingestion_Sample_Receipt','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27186,2224,'HCP_OSEA_Ingestion_Sample_Receipt','ms_query','SELECT 
Id,
IsDeleted,
Name,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Shipment_Id_vod__c,
Transferred_From_vod__c,
Transferred_From_Name_vod__c,
Transferred_Date_vod__c,
Quantity_vod__c,
Receipt_Comments_vod__c,
Lot_Name_vod__c,
U_M_vod__c,
Ref_Transaction_Id_vod__c,
Comments_vod__c,
Confirmed_Quantity_vod__c,
Lot_vod__c,
Sample_vod__c,
Received_vod__c,
JJ_LegacyID__c
FROM
    Sample_Receipt_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27187,2224,'HCP_OSEA_Ingestion_Sample_Receipt','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27188,2224,'HCP_OSEA_Ingestion_Sample_Receipt','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27189,2224,'HCP_OSEA_Ingestion_Sample_Receipt','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27190,2224,'HCP_OSEA_Ingestion_Sample_Receipt','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27191,2224,'HCP_OSEA_Ingestion_Sample_Receipt','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27192,2224,'HCP_OSEA_Ingestion_Sample_Receipt','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SAMPLE_RECEIPT;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27193,2225,'HCP_OSEA_Ingestion_Sample_Transaction','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27194,2225,'HCP_OSEA_Ingestion_Sample_Transaction','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27195,2225,'HCP_OSEA_Ingestion_Sample_Transaction','landing_file_name','OSEA_SAMPLE_TRANSACTION',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27196,2225,'HCP_OSEA_Ingestion_Sample_Transaction','target_table','SDL_HCP_OSEA_SAMPLE_TRANSACTION',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27197,2225,'HCP_OSEA_Ingestion_Sample_Transaction','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27198,2225,'HCP_OSEA_Ingestion_Sample_Transaction','ms_query','SELECT 
Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Inventory_Impact_Quantity_vod__c,
Lot_vod__c,
Discrepancy_vod__c,
Adjust_For_vod__c,
Transfer_To_Name_vod__c,
Signature_vod__c,
Received_vod__c,
Signature_Date_vod__c,
Transferred_From_vod__c,
Call_Name_vod__c,
Receipt_Comments_vod__c,
Transferred_Date_vod__c,
Submitted_Date_vod__c,
Transfer_To_vod__c,
Shipment_ID_vod__c,
Address_Line_1_vod__c,
Zip_vod__c,
Status_vod__c,
City_vod__c,
Adjusted_Date_vod__c,
Confirmed_Quantity_vod__c,
U_M_vod__c,
Disclaimer_vod__c,
Disbursed_To_vod__c,
Ref_Transaction_Id_vod__c,
Comments_vod__c,
Sample_vod__c,
Unlock_vod__c,
Quantity_vod__c,
Transferred_From_Name_vod__c,
Type_vod__c,
Lot_Name_vod__c,
Reason_vod__c,
Group_Transaction_Id_vod__c,
zvod_Sample_Lines_vod__c,
Address_Line_2_vod__c,
State_vod__c,
Return_To_vod__c,
Sample_Card_vod__c,
ASSMCA_vod__c,
Account_vod__c,
Call_Date_vod__c,
Call_Datetime_vod__c,
DEA_Expiration_Date_vod__c,
DEA_vod__c,
Sample_Card_Reason_vod__c,
Zip_4_vod__c,
License_vod__c,
Request_Receipt_vod__c,
Group_Identifier_vod__c,
Credentials_vod__c,
Salutation_vod__c,
Manufacturer_vod__c,
Distributor_vod__c,
JJ_Core_Country__c,
JJ_LegacyID__c
FROM
    Sample_Transaction_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27199,2225,'HCP_OSEA_Ingestion_Sample_Transaction','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27200,2225,'HCP_OSEA_Ingestion_Sample_Transaction','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27201,2225,'HCP_OSEA_Ingestion_Sample_Transaction','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27202,2225,'HCP_OSEA_Ingestion_Sample_Transaction','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27203,2225,'HCP_OSEA_Ingestion_Sample_Transaction','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27204,2225,'HCP_OSEA_Ingestion_Sample_Transaction','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SAMPLE_TRANSACTION;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27205,2226,'HCP_OSEA_Ingestion_Survey','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27206,2226,'HCP_OSEA_Ingestion_Survey','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27207,2226,'HCP_OSEA_Ingestion_Survey','landing_file_name','OSEA_SURVEY',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27208,2226,'HCP_OSEA_Ingestion_Survey','target_table','SDL_HCP_OSEA_SURVEY',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27209,2226,'HCP_OSEA_Ingestion_Survey','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27210,2226,'HCP_OSEA_Ingestion_Survey','ms_query','SELECT 
Id,
OwnerId,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Assignment_Type_vod__c,
Channels_vod__c,
End_Date_vod__c,
Expired_vod__c,
External_ID_vod__c,
Language_vod__c,
Lock_vod__c,
Open_vod__c,
Product_vod__c,
Region_vod__c,
Segment_vod__c,
Start_Date_vod__c,
Status_vod__c,
Territory_vod__c,
zvod_Questions_vod__c,
zvod_Segments_vod__c,
zvod_Targets_vod__c,
Max_Score_vod__c,
Min_Score_vod__c,
Account_Types_vod__c,
Autotarget_vod__c,
Territories_vod__c,
Country__c,
Detail_Group_vod__c,
Profile_Name_vod__c,
Share_Team_vod__c,
zvod_Advanced_Share_Team_vod__c,
iFrame_LandingPage_URL_vod__c,
Score_Display_vod__c,
JJ_Survey_Results_Sharing_Scope__c,
Enable_Employee_Comment_vod__c,
Target_Type_vod__c,
JJ_Survey_Type__c,
jj_Mindset_Indicator__c,
jj_Mindset_Product__c,
jj_Mindset_Segmentation_Model__c,
JJ_Metric_Considered__c,
Allowed_Back_Days__c,
JJ_Allow_Email_Reminders__c,
JJ_Allowed_back_days_to_acknowledge__c,
JJ_LegacyID__c
FROM
   Survey_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27211,2226,'HCP_OSEA_Ingestion_Survey','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27212,2226,'HCP_OSEA_Ingestion_Survey','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27213,2226,'HCP_OSEA_Ingestion_Survey','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27214,2226,'HCP_OSEA_Ingestion_Survey','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27215,2226,'HCP_OSEA_Ingestion_Survey','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27216,2226,'HCP_OSEA_Ingestion_Survey','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SURVEY;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27217,2227,'HCP_OSEA_Ingestion_Survey_Question','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27218,2227,'HCP_OSEA_Ingestion_Survey_Question','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27219,2227,'HCP_OSEA_Ingestion_Survey_Question','landing_file_name','OSEA_SURVEY_QUESTION',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27220,2227,'HCP_OSEA_Ingestion_Survey_Question','target_table','SDL_HCP_OSEA_SURVEY_QUESTION',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27221,2227,'HCP_OSEA_Ingestion_Survey_Question','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27222,2227,'HCP_OSEA_Ingestion_Survey_Question','ms_query','SELECT 
Id,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
Survey_vod__c,
Answer_Choice_vod__c,
External_ID_vod__c,
Max_Score_vod__c,
Min_Score_vod__c,
Order_vod__c,
Question_vod__c,
Required_vod__c,
Text_vod__c,
Question_Number_vod__c,
Condition_vod__c,
Source_ID_vod__c,
JJ_LegacyID__c
FROM
   Survey_Question_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27223,2227,'HCP_OSEA_Ingestion_Survey_Question','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27224,2227,'HCP_OSEA_Ingestion_Survey_Question','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27225,2227,'HCP_OSEA_Ingestion_Survey_Question','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27226,2227,'HCP_OSEA_Ingestion_Survey_Question','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27227,2227,'HCP_OSEA_Ingestion_Survey_Question','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27228,2227,'HCP_OSEA_Ingestion_Survey_Question','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SURVEY_QUESTION;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27229,2228,'HCP_OSEA_Ingestion_Survey_Target','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27230,2228,'HCP_OSEA_Ingestion_Survey_Target','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27231,2228,'HCP_OSEA_Ingestion_Survey_Target','landing_file_name','OSEA_SURVEY_TARGET',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27232,2228,'HCP_OSEA_Ingestion_Survey_Target','target_table','SDL_HCP_OSEA_SURVEY_TARGET',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27233,2228,'HCP_OSEA_Ingestion_Survey_Target','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27234,2228,'HCP_OSEA_Ingestion_Survey_Target','ms_query','SELECT 
Id,
OwnerId,
IsDeleted,
Name,
RecordTypeId,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Account_Display_Name_vod__c,
Account_vod__c,
Channels_vod__c,
End_Date_vod__c,
Entity_Reference_Id_vod__c,
External_ID_vod__c,
Language_vod__c,
Lock_vod__c,
Mobile_ID_vod__c,
No_Autoassign_vod__c,
Not_Completed_vod__c,
Region_vod__c,
Segment_vod__c,
Start_Date_vod__c,
Status_vod__c,
Survey_vod__c,
Territory_vod__c,
zvod_Address_vod__c,
zvod_Specialty_vod__c,
Score_vod__c,
Account_Types_vod__c,
Territories_vod__c,
User_vod__c,
Coach_vod__c,
Completed_Datetime_vod__c,
Detail_Group_vod__c,
Employee_vod__c,
Product_vod__c,
Profile_Name_vod__c,
Recalled_Datetime_vod__c,
Report_Status_vod__c,
Review_Date_vod__c,
Sent_To_Employee_Datetime_vod__c,
Share_Team_vod__c,
zvod_Coaching_Questions_vod__c,
JJ_SIMP_Primary_Parent__c,
Sent_Email_vod__c,
EM_Attendee_vod__c,
EM_Event_Speaker_vod__c,
EM_Event_vod__c,
zvod_Questions_vod__c,
Suggestion_vod__c,
Submitted_DateTime_vod__c,
JJ_Account_Specialty__c,
JJ_Survey_Results_Sharing_Scope__c,
Employee_Comment_vod__c,
Enable_Employee_Comment_vod__c,
JJ_Rep_Manager__c,
JJ_Rep_Department__c,
JJ_Rep_Division__c,
JJ_Account_ID18__c,
Child_Account_vod__c,
Location_Entity_Reference_Id_vod__c,
Location_vod__c,
Target_Type_vod__c,
JJ_Account_Data_Privacy_Requested__c,
JJ_Survey_Target_Type__c,
jj_Survey_Mindset_Product_Brand_Name__c,
jj_Survey_Parent_Product_Id__c,
jj_Survey_Product_Id__c,
jj_Survey_Product_Name__c,
JJ_Country_Code__c,
JJ_Segment_Metric_Updated_Flag__c,
JJ_Level2_Manager__c,
Content_vod__c,
Call2_Id_vod__c,
Call2_vod__c,
JJ_Employee_Email__c,
JJ_Hyperlink_for_Record__c,
JJ_LegacyID__c,
JJ_Primary_Parent_ID18__c,
JJ_Allow_email_alerts_from_Survey__c,
JJ_Allowed_Back_days_from_Survey__c,
JJ_Allowed_backdays_to_ack__c
FROM
   Survey_Target_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27235,2228,'HCP_OSEA_Ingestion_Survey_Target','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27236,2228,'HCP_OSEA_Ingestion_Survey_Target','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27237,2228,'HCP_OSEA_Ingestion_Survey_Target','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27238,2228,'HCP_OSEA_Ingestion_Survey_Target','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27239,2228,'HCP_OSEA_Ingestion_Survey_Target','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27240,2228,'HCP_OSEA_Ingestion_Survey_Target','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_SURVEY_TARGET;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27241,2229,'HCP_OSEA_Ingestion_Group','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27242,2229,'HCP_OSEA_Ingestion_Group','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27243,2229,'HCP_OSEA_Ingestion_Group','landing_file_name','OSEA_GROUP',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27244,2229,'HCP_OSEA_Ingestion_Group','target_table','SDL_HCP_OSEA_GROUP',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27245,2229,'HCP_OSEA_Ingestion_Group','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27246,2229,'HCP_OSEA_Ingestion_Group','ms_query','SELECT 
Id,
Name,
DeveloperName,
RelatedId,
Type,
Email,
OwnerId,
DoesSendEmailToMembers,
DoesIncludeBosses,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp
FROM
   Group',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27247,2229,'HCP_OSEA_Ingestion_Group','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27248,2229,'HCP_OSEA_Ingestion_Group','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27249,2229,'HCP_OSEA_Ingestion_Group','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27250,2229,'HCP_OSEA_Ingestion_Group','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27251,2229,'HCP_OSEA_Ingestion_Group','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27252,2229,'HCP_OSEA_Ingestion_Group','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_GROUP;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27253,2230,'HCP_OSEA_Ingestion_Group_Member','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27254,2230,'HCP_OSEA_Ingestion_Group_Member','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27255,2230,'HCP_OSEA_Ingestion_Group_Member','landing_file_name','OSEA_GROUP_MEMBER',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27256,2230,'HCP_OSEA_Ingestion_Group_Member','target_table','SDL_HCP_OSEA_GROUP_MEMBER',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27257,2230,'HCP_OSEA_Ingestion_Group_Member','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27258,2230,'HCP_OSEA_Ingestion_Group_Member','ms_query','SELECT 
Id,
GroupId,
UserOrGroupId,
SystemModstamp
FROM
   GroupMember',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27259,2230,'HCP_OSEA_Ingestion_Group_Member','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27260,2230,'HCP_OSEA_Ingestion_Group_Member','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27261,2230,'HCP_OSEA_Ingestion_Group_Member','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27262,2230,'HCP_OSEA_Ingestion_Group_Member','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27263,2230,'HCP_OSEA_Ingestion_Group_Member','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (27264,2230,'HCP_OSEA_Ingestion_Group_Member','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_GROUP_MEMBER;',FALSE,TRUE);
