create table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_DETAILINGDATA_backup_21_11_2024 
as select * from PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_DETAILINGDATA;



alter table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_DETAILINGDATA alter column P3_DTL type VARCHAR (100);
alter table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_DETAILINGDATA alter column P4_DTL type VARCHAR (100);
commit