create or replace TABLE PROD_DNA_LOAD.INDSDL_RAW.ITG_PILOT_NUP_TARGET_tmp (
	RTRUNIQUECODE VARCHAR(50),
	NUP_TARGET NUMBER(18,0),
	MTH_MM NUMBER(18,0)
);

COPY INTO PROD_DNA_LOAD.INDSDL_RAW.ITG_PILOT_NUP_TARGET_tmp
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.INDSDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('prd/SKURecom_Monthly_Targets/Target_Dec24.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT;