Drop table PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS;
Drop table PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE;
 
 
-----------AMS
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_HB (
	ORDER_TIME VARCHAR(50),
	ORDER_ID VARCHAR(100),
	ORDER_COMPLETED_TIME VARCHAR(50),
	VERIFIED_STATUS VARCHAR(50),
	CONVERSION_COMPLETED_TIME VARCHAR(50),
	BRAND_COMMISSION NUMBER(20,4),
	ITEM_ID VARCHAR(50),
	ITEM_NAME VARCHAR(500),
	MODEL_ID VARCHAR(50),
	PRICE NUMBER(20,4),
	PROMOTION_ID VARCHAR(100),
	QTY NUMBER(38,0),
	PURCHASE_VALUE NUMBER(20,4),
	L1_GLOBAL_CATEGORY VARCHAR(100),
	L2_GLOBAL_CATEGORY VARCHAR(255),
	L3_GLOBAL_CATEGORY VARCHAR(255),
	ATTRI_COMMI_ID VARCHAR(100),
	CHANNEL VARCHAR(100),
	COMMI_RATE VARCHAR(100),
	EXPENSE VARCHAR(100),
	DEDUCTION_STATUS VARCHAR(100),
	DEDUCTION_METHOD VARCHAR(100),
	DEDUCTION_TIME VARCHAR(100),
	SHOP_NAME VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
 
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_JB (
	ORDER_TIME VARCHAR(50),
	ORDER_ID VARCHAR(100),
	ORDER_COMPLETED_TIME VARCHAR(50),
	VERIFIED_STATUS VARCHAR(50),
	CONVERSION_COMPLETED_TIME VARCHAR(50),
	BRAND_COMMISSION NUMBER(20,4),
	ITEM_ID VARCHAR(50),
	ITEM_NAME VARCHAR(500),
	MODEL_ID VARCHAR(50),
	PRICE NUMBER(20,4),
	PROMOTION_ID VARCHAR(100),
	QTY NUMBER(38,0),
	PURCHASE_VALUE NUMBER(20,4),
	L1_GLOBAL_CATEGORY VARCHAR(100),
	L2_GLOBAL_CATEGORY VARCHAR(255),
	L3_GLOBAL_CATEGORY VARCHAR(255),
	ATTRI_COMMI_ID VARCHAR(100),
	CHANNEL VARCHAR(100),
	COMMI_RATE VARCHAR(100),
	EXPENSE VARCHAR(100),
	DEDUCTION_STATUS VARCHAR(100),
	DEDUCTION_METHOD VARCHAR(100),
	DEDUCTION_TIME VARCHAR(100),
	SHOP_NAME VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_LTR (
	ORDER_TIME VARCHAR(50),
	ORDER_ID VARCHAR(100),
	ORDER_COMPLETED_TIME VARCHAR(50),
	VERIFIED_STATUS VARCHAR(50),
	CONVERSION_COMPLETED_TIME VARCHAR(50),
	BRAND_COMMISSION NUMBER(20,4),
	ITEM_ID VARCHAR(50),
	ITEM_NAME VARCHAR(500),
	MODEL_ID VARCHAR(50),
	PRICE NUMBER(20,4),
	PROMOTION_ID VARCHAR(100),
	QTY NUMBER(38,0),
	PURCHASE_VALUE NUMBER(20,4),
	L1_GLOBAL_CATEGORY VARCHAR(100),
	L2_GLOBAL_CATEGORY VARCHAR(255),
	L3_GLOBAL_CATEGORY VARCHAR(255),
	ATTRI_COMMI_ID VARCHAR(100),
	CHANNEL VARCHAR(100),
	COMMI_RATE VARCHAR(100),
	EXPENSE VARCHAR(100),
	DEDUCTION_STATUS VARCHAR(100),
	DEDUCTION_METHOD VARCHAR(100),
	DEDUCTION_TIME VARCHAR(100),
	SHOP_NAME VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
 
--------SHOPEE
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_HB (
	PRODUCT_NAME VARCHAR(400),
	PRODUCT_ID VARCHAR(255),
	GROSS_SALES NUMBER(20,4),
	GROSS_SALES_GROWTH NUMBER(20,4),
	GROSS_ORDERS NUMBER(20,4),
	GROSS_ORDERS_GROWTH NUMBER(20,4),
	GROSS_UNITS_SOLD NUMBER(20,4),
	GROSS_UNITS_SOLD_GROWTH NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE_GROWTH NUMBER(20,4),
	GROSS_ITEM_PER_ORDER NUMBER(20,4),
	GROSS_ITEM_PER_ORDER_GROWTH NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE_GROWTH NUMBER(20,4),
	PRODUCT_VIEWS NUMBER(20,4),
	PRODUCT_VIEWS_GROWTH NUMBER(20,4),
	PRODUCT_VISITORS NUMBER(20,4),
	PRODUCT_VISITORS_GROWTH NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE_GROWTH NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE_GROWTH NUMBER(20,4),
	DATE VARCHAR(50),
	PLATFORM VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_JB (
	PRODUCT_NAME VARCHAR(400),
	PRODUCT_ID VARCHAR(255),
	GROSS_SALES NUMBER(20,4),
	GROSS_SALES_GROWTH NUMBER(20,4),
	GROSS_ORDERS NUMBER(20,4),
	GROSS_ORDERS_GROWTH NUMBER(20,4),
	GROSS_UNITS_SOLD NUMBER(20,4),
	GROSS_UNITS_SOLD_GROWTH NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE_GROWTH NUMBER(20,4),
	GROSS_ITEM_PER_ORDER NUMBER(20,4),
	GROSS_ITEM_PER_ORDER_GROWTH NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE_GROWTH NUMBER(20,4),
	PRODUCT_VIEWS NUMBER(20,4),
	PRODUCT_VIEWS_GROWTH NUMBER(20,4),
	PRODUCT_VISITORS NUMBER(20,4),
	PRODUCT_VISITORS_GROWTH NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE_GROWTH NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE_GROWTH NUMBER(20,4),
	DATE VARCHAR(50),
	PLATFORM VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
 
create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_LTR (
	PRODUCT_NAME VARCHAR(400),
	PRODUCT_ID VARCHAR(255),
	GROSS_SALES NUMBER(20,4),
	GROSS_SALES_GROWTH NUMBER(20,4),
	GROSS_ORDERS NUMBER(20,4),
	GROSS_ORDERS_GROWTH NUMBER(20,4),
	GROSS_UNITS_SOLD NUMBER(20,4),
	GROSS_UNITS_SOLD_GROWTH NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE NUMBER(20,4),
	GROSS_AVG_BASKET_SIZE_GROWTH NUMBER(20,4),
	GROSS_ITEM_PER_ORDER NUMBER(20,4),
	GROSS_ITEM_PER_ORDER_GROWTH NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE NUMBER(20,4),
	GROSS_AVG_SELLING_PRICE_GROWTH NUMBER(20,4),
	PRODUCT_VIEWS NUMBER(20,4),
	PRODUCT_VIEWS_GROWTH NUMBER(20,4),
	PRODUCT_VISITORS NUMBER(20,4),
	PRODUCT_VISITORS_GROWTH NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE NUMBER(20,4),
	GROSS_ORDER_CONVERSION_RATE_GROWTH NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE NUMBER(20,4),
	GROSS_ITEM_CONVERSION_RATE_GROWTH NUMBER(20,4),
	DATE VARCHAR(50),
	PLATFORM VARCHAR(50),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILENAME VARCHAR(255)
);
 
 

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_HB
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/AMS_HB.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
 

COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_JB
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/AMS_JB.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
 
 
COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_AMS_LTR
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/AMS_LTR.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
 
 
COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_HB
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/SHOPEE_HB.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
 
COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_JB
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/SHOPEE_JB.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
 
COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_ECOM_GMV_SHOPEE_LTR
  FROM @PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS/prd/eCOM_Data/transaction/Shopee_Compensation/SHOPEE_LTR.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
