DROP TABLE NTASDL_RAW.SDL_TW_SFMC_INVOICE_DATA;

create or replace TABLE NTASDL_RAW.SDL_TW_SFMC_INVOICE_DATA (
	PURCHASE_DATE TIMESTAMP_NTZ(9),
	CHANNEL VARCHAR(200),
	PRODUCT VARCHAR(200),
	STATUS VARCHAR(50),
	CREATED_DATE TIMESTAMP_NTZ(9),
	COMPLETED_DATE TIMESTAMP_NTZ(9),
	SUBSCRIBER_KEY VARCHAR(100),
	POINTS NUMBER(18,0),
	SHOW_RECORD VARCHAR(20),
	QTY NUMBER(20,4),
	INVOICE_TYPE VARCHAR(200),
	SELLER_NM VARCHAR(255),
	PRODUCT_CATEGORY VARCHAR(200),
	WEBSITE_UNIQUE_ID VARCHAR(150),
	INVOICE_NUM VARCHAR(50),
	EPSILON_PRICE_PER_UNIT NUMBER(20,4),
	EPSILON_AMOUNT NUMBER(20,4),
	EPSILON_TOTAL_AMOUNT NUMBER(20,4),
	FILE_NAME VARCHAR(255),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);
