DELETE FROM PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_AMART_PURCHASE;
DELETE FROM PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_AMART_INVENTORY;

COPY INTO PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_AMART_PURCHASE
  FROM @PROD_DNA_LOAD.NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN/prd/pos/transaction/amart_purchase.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_AMART_INVENTORY
  FROM @PROD_DNA_LOAD.NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN/prd/pos/transaction/amart_inventory.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
