CREATE OR REPLACE TABLE PROD_DNA_LOAD.META_RAW.USECASE_BKP112724 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.USECASE;
CREATE OR REPLACE TABLE PROD_DNA_LOAD.META_RAW.PROCESS_BKP112724 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PROCESS;
CREATE OR REPLACE TABLE PROD_DNA_LOAD.META_RAW.PARAMETERS_BKP112724 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PARAMETERS;

INSERT INTO PROD_DNA_LOAD.META_RAW.USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (549,'In_Sales_Cube_Weekly_Archival','In_Sales_Cube_Weekly_Archival','In_Sales_Cube_Weekly_Archival ','TRUE',1);
INSERT INTO PROD_DNA_LOAD.META_RAW.USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (550,'In_Scheme_vs_Sales_cube','In_Scheme_vs_Sales_cube','In_Scheme_vs_Sales_cube','TRUE',1);

INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (3014,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans',3014,1,1,FALSE,TRUE,549,NULL,2,NULL,'','','','','','','');
INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (3015,3015,'In_Scheme_vs_Sales_cube_dbt_trans',3015,1,1,FALSE,TRUE,550,NULL,2,NULL,'','','','','','','');

INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28344,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','accountId','99',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28345,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','waitTime','20',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28346,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','tempId','0',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28346,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','transformationType','transformation',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28347,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','container','ind',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28348,3014,'In_Sales_Cube_Weekly_Archival_dbt_trans','jobId','31416',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28349,3015,'In_Scheme_vs_Sales_cube_dbt_trans','accountId','99',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28350,3015,'In_Scheme_vs_Sales_cube_dbt_trans','waitTime','20',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28351,3015,'In_Scheme_vs_Sales_cube_dbt_trans','tempId','0',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28352,3015,'In_Scheme_vs_Sales_cube_dbt_trans','transformationType','transformation',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28353,3015,'In_Scheme_vs_Sales_cube_dbt_trans','container','ind',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28354,3015,'In_Scheme_vs_Sales_cube_dbt_trans','jobId','31417',FALSE,TRUE);