COPY INTO PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_COSMED_STORE_INVENTORY
  FROM @PROD_DNA_LOAD.NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN/prd/pos/transaction/cosmed_store.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );

COPY INTO TABLE PROD_DNA_LOAD.NTASDL_RAW.SDL_TW_POS_COSMED_DC_INVENTORY
  FROM @PROD_DNA_LOAD.NTASDL_RAW.PROD_LOAD_STAGE_ADLS_TWN/prd/pos/transaction/cosmed_dc.csv
FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ','  SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '\"' );
