CREATE OR REPLACE TABLE PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_RAW(
	TEAM VARCHAR(50),
	MONTH VARCHAR(20),
	RBM VARCHAR(100),
	ZBM VARCHAR(100),
	FBM VARCHAR(100),
	MSR VARCHAR(100),
	HQ_CODE VARCHAR(100),
	MSR_NAME VARCHAR(100),
	DSG VARCHAR(50),
	CUSTOMER_NAME VARCHAR(100),
	CID VARCHAR(50),
	SPECIALITY VARCHAR(50),
	CUSTOMER_TYPE VARCHAR(50),
	ACTIVE VARCHAR(10),
	DCR_DATE DATE,
	VA_NAME VARCHAR(100),
	PAGE_NAME VARCHAR(100),
	PAGE_START_TIME TIMESTAMP_NTZ(9),
	PAGE_END_TIME TIMESTAMP_NTZ(9),
	SECONDS VARCHAR(10),
	CAPPED_SECONDS VARCHAR(10),
	AS_ON TIMESTAMP_NTZ(9),
    UPLOAD_DATE DATE,
    CRT_DTTM TIMESTAMP_NTZ(9),
    FILE_NAME VARCHAR(100),
    RUN_ID VARCHAR(50)
);


INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES 
(3037,3037,'In_Ventasys_EM_Edetailing_Ing',3037,1,1,FALSE,TRUE,289,1,1,NULL,'','','','HCPSDL_RAW.DEV_LOAD_STAGE_ADLS','','','');
INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES 
(3038,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing',3038,1,1,FALSE,TRUE,289,NULL,2,NULL,'','','','','','','');


INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28432,3037,'In_Ventasys_EM_Edetailing_Ing','business_mail_trigger','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28433,3037,'In_Ventasys_EM_Edetailing_Ing','container','hcp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28434,3037,'In_Ventasys_EM_Edetailing_Ing','file_header_row_num','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28435,3037,'In_Ventasys_EM_Edetailing_Ing','file_spec','12_eDetailingData',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28436,3037,'In_Ventasys_EM_Edetailing_Ing','folder_path','ventasys/transaction/eDetailingData',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28437,3037,'In_Ventasys_EM_Edetailing_Ing','index','last',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28438,3037,'In_Ventasys_EM_Edetailing_Ing','is_truncate','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28439,3037,'In_Ventasys_EM_Edetailing_Ing','load_method','sp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28440,3037,'In_Ventasys_EM_Edetailing_Ing','sheet_index','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28441,3037,'In_Ventasys_EM_Edetailing_Ing','source_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28442,3037,'In_Ventasys_EM_Edetailing_Ing','sp_name','HCPSDL_RAW.HCP360_IN_VENTASYS_EDETAILING_PREPROCESSING',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28443,3037,'In_Ventasys_EM_Edetailing_Ing','start_Range','A1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28444,3037,'In_Ventasys_EM_Edetailing_Ing','target_schema','HCPSDL_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28445,3037,'In_Ventasys_EM_Edetailing_Ing','target_table','SDL_HCP360_IN_VENTASYS_EDETAILING_RAW',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28446,3037,'In_Ventasys_EM_Edetailing_Ing','trigger_mail','Y',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28447,3037,'In_Ventasys_EM_Edetailing_Ing','val_file_extn','xlsx',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28448,3037,'In_Ventasys_EM_Edetailing_Ing','val_file_header','TEAM|MONTH|RBM|ZBM|FBM|MSR|HQ_CODE|MSR_NAME|DSG|CUSTOMER_NAME|CID|SPECIALITY|CUSTOMER_TYPE|ACTIVE|DCR_DATE|VA_NAME|PAGE_NAME|PAGE_START_TIME|PAGE_END_TIME|SECONDS|CAPPED_SECONDS|AS_ON|UPLOAD_DATE|CRT_DTTM|FILE_NAME|RUN_ID',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28449,3037,'In_Ventasys_EM_Edetailing_Ing','val_file_name','12_eDetailingData',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28450,3037,'In_Ventasys_EM_Edetailing_Ing','validation','1-1-1',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28451,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','accountId','99',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28452,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','waitTime','20',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28453,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','tempId','0',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28454,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','transformationType','transformation',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28455,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','container','hcp',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28456,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing','jobId','',FALSE,TRUE);


