CREATE OR REPLACE TABLE PROD_DNA_LOAD.META_RAW.PROCESS_BKP_12_2_24 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PROCESS;

DELETE FROM PROD_DNA_LOAD.META_RAW.PROCESS WHERE PROCESS_ID IN(3037,3038);

INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES 
(3037,3037,'In_Ventasys_EM_Edetailing_Ing',3037,1,1,FALSE,TRUE,289,1,1,NULL,'','','','HCPSDL_RAW.DEV_LOAD_STAGE_ADLS','','','');
INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES 
(3038,3038,'In_Ventasys_EM_Edetailing_Dbt_Ing',3038,1,1,FALSE,TRUE,289,NULL,2,NULL,'','','','','','','');