INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28727,3046,'HCP_OSEA_Ingestion_Call_Sample','container','ose',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28728,3046,'HCP_OSEA_Ingestion_Call_Sample','landing_file_path','salesforce/',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28729,3046,'HCP_OSEA_Ingestion_Call_Sample','landing_file_name','OSEA_CALL_SAMPLE',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28730,3046,'HCP_OSEA_Ingestion_Call_Sample','target_table','SDL_HCP_OSEA_CALL_SAMPLE',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28731,3046,'HCP_OSEA_Ingestion_Call_Sample','target_schema','HCPOSESDL_RAW',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28732,3046,'HCP_OSEA_Ingestion_Call_Sample','ms_query','SELECT 
	Id,
IsDeleted,
Name,
CreatedDate,
CreatedById,
LastModifiedDate,
LastModifiedById,
SystemModstamp,
LastActivityDate,
MayEdit,
IsLocked,
LastViewedDate,
LastReferencedDate,
Account_vod__c,
Call_Date_vod__c,
Is_Parent_Call_vod__c,
Quantity_vod__c,
Lot_vod__c,
Mobile_ID_vod__c,
Call2_vod__c,
Product_vod__c,
Override_Lock_vod__c,
Distributor_vod__c,
Attendee_Type_vod__c,
Entity_Reference_Id_vod__c,
Delivery_Status_vod__c,
Apply_Limit_vod__c,
Limit_Applied_vod__c,
Manufacturer_vod__c,
Call2_Mobile_ID_vod__c,
Amount_vod__c,
Product_Value_vod__c,
Cold_Chain_Status_vod__c,
Custom_Text_vod__c,
Tag_Alert_Number_vod__c,
Barcode_Scan_vod__c,
JJLegacyID__c,
JJ_Account_Email__c,
JJ_Address__c 
FROM
call2_sample_vod__c',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28733,3046,'HCP_OSEA_Ingestion_Call_Sample','truncate_and_load','Y',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28734,3046,'HCP_OSEA_Ingestion_Call_Sample','decide_source','salesforce_db',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28735,3046,'HCP_OSEA_Ingestion_Call_Sample','incremental_filter',' where LastModifiedDate>={WATERMARK_VALUE}',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28736,3046,'HCP_OSEA_Ingestion_Call_Sample','load_method','sp',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28737,3046,'HCP_OSEA_Ingestion_Call_Sample','sp_name','HCPOSESDL_RAW.HCP_OSEA_SALESFORCE_LOAD_PREPROCESSING',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (28738,3046,'HCP_OSEA_Ingestion_Call_Sample','next_incremental_value','query:SELECT TO_VARCHAR(DATEADD(DAY, -2, MAX(LAST_MODIFIED_DATE)),''YYYY-MM-DD"T"HH24:MI:SSZ'') AS NEXT_VALUE FROM HCPOSESDL_RAW.SDL_HCP_OSEA_CALL_SAMPLE;',FALSE,TRUE);
INSERT INTO PROD_DNA_LOAD.META_RAW.PROCESS VALUES (3046,3046,'HCP_OSEA_Ingestion_Call_Sample',3046,1,1,TRUE,TRUE,306,5,1,NULL,'','','','HCPOSESDL_RAW.DEV_LOAD_STAGE_ADLS','','','');


create or replace TABLE PROD_DNA_LOAD.HCPOSESDL_RAW.SDL_HCP_OSEA_CALL_SAMPLE (
	CALL_SAMPLE_ID VARCHAR(40),
	IS_DELETED VARCHAR(5),
	CALL_SAMPLE_NAME VARCHAR(80),
	CREATED_DATE TIMESTAMP_NTZ(9),
	CREATED_BY_ID VARCHAR(18),
	LAST_MODIFIED_DATE TIMESTAMP_NTZ(9),
	LAST_MODIFIED_BY_ID VARCHAR(18),
	SYSTEM_MODSTAMP TIMESTAMP_NTZ(9),
	LAST_ACTIVITY_DATE DATE,
	MAY_EDIT VARCHAR(10),
	IS_LOCKED VARCHAR(10),
	LAST_VIEWED_DATE TIMESTAMP_NTZ(9),
	LAST_REFERENCE_DATE TIMESTAMP_NTZ(9),
	ACCOUNT VARCHAR(50),
	DATE DATE,
	IS_PARENT_CALL NUMBER(6,0),
	QUANTITY NUMBER(18,1),
	LOT_NO VARCHAR(80),
	MOBILE_ID VARCHAR(100),
	CALL VARCHAR(50),
	PRODUCT VARCHAR(50),
	OVERRIDE_LOCK VARCHAR(50),
	DISTRIBUTOR VARCHAR(255),
	ATTENDEE_TYPE VARCHAR(100),
	ENTITY_REFERENCE_ID VARCHAR(100),
	DELIVERY_STATUS VARCHAR(100),
	APPLY_LIMIT VARCHAR(100),
	LIMIT_APPLIED VARCHAR(100),
	MANUFACTURER VARCHAR(255),
	CALL_MOBILE_ID VARCHAR(100),
	AMOUNT VARCHAR(100),
	PRODUCT_VALUE VARCHAR(40),
	COLD_CHAIN_STATUS VARCHAR(100),
	CUSTOM_TEXT VARCHAR(80),
	TAG_ALERT_NUMBER VARCHAR(80),
	BARCODE_SCAN VARCHAR(100),
	LEGACY_ID VARCHAR(255),
	ACCOUNT_EMAIL VARCHAR(200),
	ADDRESS VARCHAR(1300),
	CRT_DTTM TIMESTAMP_NTZ(9),
	FILENAME VARCHAR(100),
	RUN_ID VARCHAR(14)
);
