DROP TABLE PROD_DNA_LOAD.INDSDL_RAW.SDL_VA_PAGE_CLASS;

alter table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_VA_PAGE_RAW add column TEAM_NAME VARCHAR(50);

TRUNCATE TABLE PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_VA_PAGE_RAW;

COPY INTO PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_VA_PAGE_RAW
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.HCPSDL_RAW.DEV_LOAD_STAGE_ADLS'
)
FILES = ('prod/ventasys/transaction/eDetailingData/VA Page Classifications v3.0.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT ;