

COPY INTO PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_VA_PAGE_RAW
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.HCPSDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('prod/ventasys/transaction/eDetailingData/VA Page Classifications v3.0.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT ;