create or replace TABLE PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_PRTY_GRD_RAW (
	FRANCHISE VARCHAR(50),
	REGION VARCHAR(50),
	SPECIALTY VARCHAR(50),
	P1 VARCHAR(50),
	P2 VARCHAR(50),
	P3 VARCHAR(100),
	P4 VARCHAR(50),
	P5 VARCHAR(50),
	P6 VARCHAR(50)
);

COPY INTO PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_EDETAILING_PRTY_GRD_RAW
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.HCPSDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('prd/ventasys/transaction/eDetailingData/Detailing Priority Grid 2024 v1.0.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT;