update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'sql_server/MDS_Reverse_Sync/MDS_Adhoc_PARAMETERS'
WHERE PARAMETER_ID = 27008;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'PARAMETERS'
WHERE PARAMETER_ID = 27009;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'dbo.MDS_PARAMETERS'
WHERE PARAMETER_ID = 27010;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'META_RAW.PARAMETERS'
WHERE PARAMETER_ID = 27011;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'SELECT PARAMETER_ID, PARAMETER_GROUP_ID, PARAMETER_GROUP_NAME, PARAMETER_NAME, PARAMETER_VALUE, IS_SENSITIVE, IS_ACTIVE FROM META_RAW.PARAMETERS'
WHERE PARAMETER_ID = 27012;

update META_RAW.PARAMETERS
SET PARAMETER_VALUE = 'dna_load'
WHERE PARAMETER_ID = 27014;
