UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='sql_server/MDS/SDL_MDS_IN_HCP_SpecialtyCare'
WHERE PARAMETER_VALUE='sql_server/MDS/MDS_Adhoc_IN_HCP_Targets';
UPDATE META_RAW.PARAMETERS SET PARAMETER_VALUE='sql_server/MDS/SDL_MDS_IN_HCP_SpecialtyCare'
WHERE PARAMETER_VALUE='sql_server/MDS/MDS_Adhoc_IN_HCP_Targets';
