create table PROD_DNA_LOAD.META_RAW.PROCESS_bkp_04122024 as select * from PROD_DNA_LOAD.META_RAW.PROCESS;

update PROD_DNA_LOAD.META_RAW.PROCESS
set IS_ACTIVE='FALSE'
where USECASE_ID='208'
and PARAMETER_GROUP_ID = '1604'
AND PROCESS_ID = '1604' ;

commit;