create table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_HCP_MASTER_backup_05_12_2024 
as select * from PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_HCP_MASTER;


alter table PROD_DNA_LOAD.HCPSDL_RAW.SDL_HCP360_IN_VENTASYS_HCP_MASTER alter column CUST_NAME type VARCHAR (150);
commit
