create or replace table PROD_DNA_LOAD.META_RAW.PROCESS_BKP_120924 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PROCESS;

UPDATE PROD_DNA_LOAD.META_RAW.PROCESS SET IS_ACTIVE='TRUE' WHERE PROCESS_ID =3037;