create or replace table PROD_DNA_LOAD.META_RAW.PROCESS_BKP_121024 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PROCESS;

UPDATE PROD_DNA_LOAD.META_RAW.PROCESS SET SNOWFLAKE_STAGE='HCPSDL_RAW.PROD_LOAD_STAGE_ADLS' WHERE PROCESS_ID =3037;