create or replace table PROD_DNA_LOAD.META_RAW.PARAMETERS_BKP_121024 AS SELECT * FROM PROD_DNA_LOAD.META_RAW.PARAMETERS;

update PROD_DNA_LOAD.META_RAW.PARAMETERS set 
PARAMETER_VALUE='TEAM|MONTH|RBM|ZBM|FBM|MSR|HQ_CODE|MSR_NAME|DSG|CUSTOMER_NAME|CID|SPECIALITY|CUSTOMER_TYPE|ACTIVE|DCR_DATE|VA_NAME|PAGE_NAME|PAGE_START_TIME|PAGE_END_TIME|SECONDS|CAPPED_SECONDS|AS_ON'
where PARAMETER_ID=28448;