create or replace TABLE PROD_DNA_LOAD.THASDL_RAW.SDL_TH_MT_WATSONS_POS_1210_UAT (
	BU_NAME VARCHAR(100),
	SUPPLIER VARCHAR(100),
	BRAND_NAME VARCHAR(200),
	PRODUCT_ID VARCHAR(100),
	PRODUCT_NAME VARCHAR(500),
	CATEGORY_1 VARCHAR(200),
	CATEGORY_2 VARCHAR(200),
	CATEGORY_3 VARCHAR(200),
	CATEGORY_4 VARCHAR(200),
	YEAR VARCHAR(50),
	YEAR_MONTH VARCHAR(50),
	YEAR_WEEK VARCHAR(50),
	TRANSACTION_DATE VARCHAR(50),
	ONLINE_OFFLINE VARCHAR(50),
	STORE_FORMAT VARCHAR(200),
	STORE_SEGMENT VARCHAR(200),
	GROSS_SALES VARCHAR(200),
	NET_SALES VARCHAR(200),
	SALES_QTY VARCHAR(200),
	BARCODE VARCHAR(200),
	CRTD_DTTM TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_NTZ(9)),
	FILE_NAME VARCHAR(255),
	RUN_ID VARCHAR(200)
);

insert into PROD_DNA_LOAD.THASDL_RAW.SDL_TH_MT_WATSONS_POS_1210_UAT select * from DEV_DNA_LOAD.THASDL_RAW.SDL_TH_MT_WATSONS_POS;
