drop table THASDL_RAW.SDL_POP6_TH_RIR_DATA_TEST;

create or replace TABLE THASDL_RAW.SDL_POP6_TH_RIR_DATA_TEST (
	VISIT_ID VARCHAR(255),
	PHOTO VARCHAR(500),
	RELATED_ATTRIBUTE VARCHAR(255),
	SKU_ID VARCHAR(255),
	SKU VARCHAR(255),
	LAYER NUMBER(18,0),
	TOTAL_LAYER NUMBER(18,0),
	FACING_OF_THIS_LAYER NUMBER(18,0),
	SKU_LENGTH NUMBER(18,4),
	FILE_NAME VARCHAR(100),
	RUN_ID NUMBER(14,0),
	CRTD_DTTM TIMESTAMP_NTZ(9)
);
