COPY INTO PROD_DNA_LOAD.THASDL_RAW.SDL_TH_MT_WATSONS_POS_1210_UAT
FROM (
	SELECT *
	FROM '@PROD_DNA_LOAD.THASDL_RAW.PROD_LOAD_STAGE_ADLS'
)
FILES = ('dev/TH_MT/transaction/WATSONS_POS/10.Oct_Weekly_Offtake_as_of_22_Oct_wk3_.csv') 
file_format= (TYPE=CSV SKIP_HEADER = 1)
ON_ERROR=ABORT_STATEMENT ;
