INSERT INTO PHASE (PHASE_ID, PHASE_NAME,PHASE_DESCRIPTION) VALUES (1,'Ingestion','Parent Ingestion Orchestration Pipeline');
INSERT INTO PHASE (PHASE_ID, PHASE_NAME,PHASE_DESCRIPTION) VALUES (2,'Transformation','Parent Transformation Orchestration Pipeline');
INSERT INTO PHASE (PHASE_ID, PHASE_NAME,PHASE_DESCRIPTION) VALUES (3,'Consumption','Parent Consumption Orchestration Pipeline');

INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (412,30,'Perfect_Store_Tableau_Refresh','contentUrl','ADB',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (413,30,'Perfect_Store_Tableau_Refresh','tableauSourceName','Perfect Store',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (414,30,'Perfect_Store_Tableau_Refresh','waitTime','30',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (415,30,'Perfect_Store_Tableau_Refresh','refreshType','datasource',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (416,31,'Customer_360_Tableau_refresh','contentUrl','ADB',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (417,31,'Customer_360_Tableau_refresh','tableauSourceName','Customer 360',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (418,31,'Customer_360_Tableau_refresh','waitTime','30',FALSE,TRUE);
INSERT INTO PARAMETERS (PARAMETER_ID, PARAMETER_GROUP_ID,PARAMETER_GROUP_NAME,PARAMETER_NAME,PARAMETER_VALUE,IS_SENSITIVE,IS_ACTIVE) VALUES (419,31,'Customer_360_Tableau_refresh','refreshType','datasource',FALSE,TRUE);

INSERT INTO USECASE (USECASE_ID, USECASE_NAME,CATEGORY,USECASE_DESCRIPTION,IS_ACTIVE,SEQUENCE_ID) VALUES (13,'POP6_CUSTOMER360_refresh','POP6_CUSTOMER360_refresh','Tableau Refresh Adhoc FOR POP6 AND CUSTOMER360','TRUE',1);

INSERT INTO PROCESS VALUES (30,30,'Perfect_Store_Tableau_Refresh',30,1,1,FALSE,TRUE,13,null,3,null,'','','','','','Tableau');
INSERT INTO PROCESS VALUES (31,31,'Customer_360_Tableau_refresh',31,1,1,FALSE,TRUE,13,null,3,null,'','','','','','Tableau');
